### ISSUE TITLE
UI for OAuth providers

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1]
- [ ] ~~Windowslive~~ Microsoft 
- [x] Spotify
- [x] Apple

**Comment by adithyaakrishna** [comment]
@elitan So Should I just develop the UI? If so will work on this and fix it ASAP :)

**Comment by elitan** [comment]
This is for internal tracking. If you're looking for issues here are some good repos:

https://github.com/nhost/hasura-backend-plus
https://github.com/nhost/docs
https://github.com/nhost/nhost-js-sdk

**Comment by adithyaakrishna** [comment]
Okay Sure, Thanks 😊

**Comment by MarcelloTheArcane** [comment]
@elitan Could you add Auth0 support?  It looks like vanilla Hasura supports it: https://hasura.io/docs/latest/graphql/core/guides/integrations/auth0-jwt.html

**Comment by elitan** [comment]
> @elitan Could you add Auth0 support? It looks like vanilla Hasura supports it: https://hasura.io/docs/latest/graphql/core/guides/integrations/auth0-jwt.html

Any specific reason for wanting to use Auth0?

**Comment by MarcelloTheArcane** [comment]
@elitan Sorry, I think I've made an [XY problem](https://en.wikipedia.org/wiki/XY_problem)!

What I actually want is Microsoft 365 authentication, I think I was getting confused with oauth and auth0.

Hopefully these links will be helpful?

- https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
- https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-app-types

**Comment by elitan** [comment]
I'm closing this. Might open a nother issue specifically for Microsoft in the future.

**Comment by plmercereau** [comment]
what about Twitter? ;)
