### ISSUE TITLE
Hasura explorer tab is not visible in 100% screen size

### ISSUE THREAD

**Issue by Amyx000** [nhost/nhost#1021]
For 100% chrome size the explorer tab is not visible only little portion is visible
![image](https://user-images.githubusercontent.com/104687128/195135345-c53ca569-4524-4f8a-ab5f-8064037ab893.png)

When I decrease the size of the chrome it is getting visible
This is under 75% size of chrome
![image](https://user-images.githubusercontent.com/104687128/195135975-16b787f7-d11d-490c-b63d-e8ebb106bd44.png)

**Comment by pkreipke** [comment]
This has a fix in a recent Hasura GraphQL Engine release but I don't think NHost  running it yet.

Getting that update would be great! Especially since I've never found a way to reset this problem and it persists across tabs and browser windows despite clearing all website data. Sigh.

**Comment by Amyx000** [comment]
Ok

**Comment by Amyx000** [comment]
Yup, it is fixed now @nunopato
