### ISSUE TITLE
Explain how `config.yaml` and environment variables work when using the CLI

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#1024]
I couldn't find anything, but it could be of some help to users, in particular:
- how to configure the application with `nhost/config.yaml`
- the fact that `nhost/config.yaml` is not used when deploying to the cloud
- the fact that dot env files are injected in every services, but prefixed `AUTH_`, `HASURA_` and `STORAGE_` names are reserved
- how the `.env` and `.env.development` override the `nhost/config.yaml`

For reference: https://github.com/nhost/cli/issues/159

@elitan where would we put it in the menu?

**Comment by sayantandasgupta** [comment]
Hi, may I work on this issue? It would also help if I could be guided on a starting point in understanding the project further

**Comment by dbarrosop** [comment]
This is no longer relevant as the new CLI won't use that config file.
