### ISSUE TITLE
Cannot create deployments, claims no github app installed even though there is

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1040]
I connect to github ok, it installs the hnost app in my account: 

<img width="708" alt="image" src="https://user-images.githubusercontent.com/260221/196011617-ec17ed6b-06bc-4a5b-bb5a-6675e855db2b.png">

But the "Connect to github" button doesn't change, even when I refresh everything, wait, and do it again. Repeat the cycle, no change.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/260221/196011645-2b8ec29d-7ff5-424d-b09b-c7fe7d9b9892.png">

So I cannot create new deployments. 

Is there anything else I could check or something I may have missed?

Thank you!

**Comment by ambidexterich** [comment]
I'm having the same problem
<img width="677" alt="image" src="https://user-images.githubusercontent.com/675222/196042013-f377529a-d595-4f66-bc91-3a6217d684e5.png">
And will just keep asking even though it is installed and I gave it access to all my repositories

**Comment by guicurcio** [comment]
Try to completely remove the app installation from your GitHub account and go to the entire flow again. If that doesn't work feel free to email me at guido@nhost.io with the subdomain of your app, and I will connect the repos manually. We're reworking this part of the dashboard to make it much more robust, as the way it's now set up is prone to bugs.

**Comment by ambidexterich** [comment]
> Try to completely remove the app installation from your GitHub account and go to the entire flow again. If that doesn't work feel free to email me at [guido@nhost.io](mailto:guido@nhost.io) with the subdomain of your app, and I will connect the repos manually. We're reworking this part of the dashboard to make it much more robust, as the way it's now set up is prone to bugs.

I was able to connect my repos again, thanks

**Comment by dionjwa** [comment]
@guicurcio yes, that worked, uninstalling then reinstalling the github app removed this blocked, thank you 👍🏻
