### ISSUE TITLE
https://console.nhost.io/ exists, somehow I ended up there, it's confusing

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1041]
This site is maybe an old deployment? It's confusing to users, I don't remember how I ended up there, but it doesn't contain my current account state.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/260221/196012074-39eb06ca-d121-4b1f-a15f-658061fce8ab.png">

**Comment by szilarddoro** [comment]
Hey @dionjwa! This console is for users who are still using v1. You can find the latest version of our dashboard on the https://app.nhost.io URL.
