### ISSUE TITLE
nhost webhook secret

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1048]
We're using `nhost-webhook-secret` in our example here: https://docs.nhost.io/platform/database/event-triggers#security

But `x-nhost-webhook-secret` (with `x-` in the beginning) here: https://github.com/nhost/nhost/tree/main/packages/stripe-graphql-js#quick-start

We should use the same header everywhere.

The question is, which one should we use?

`nhost-webhook-secret` or `x-nhost-webhook-secret`?

**Comment by plmercereau** [comment]
`X-` headers are [deprecated since 2012](https://www.rfc-editor.org/rfc/rfc6648) so I would keep the syntax of our example and correct the Stripe package
