### ISSUE TITLE
nhost python client

### ISSUE THREAD

**Issue by Aashish-Upadhyay-101** [nhost/nhost#1049]
Need a way to integrate nhost with python.

**Comment by nunopato** [comment]
@Aashish-Upadhyay-101 we would be more than happy to help you build a community package for python. Would you be interested?

**Comment by Aashish-Upadhyay-101** [comment]
Yes, @nunopato, I will love to contribute, but I'm new to Open Source and haven't contributed on a large scale. So I might need a lot of help.

**Comment by floer32** [comment]
By the way, this would be useful at my workplace (https://myxt.com). We're not blocked without it, it would be an optimization — so it's not urgent to us. If this effort gets started though, I'd be happy to chip in.
