### ISSUE TITLE
Deployments when multiple apps are connected to the same repo+branch

### ISSUE THREAD

**Issue by beepsoft** [nhost/nhost#105]
It seems that if multiple apps are connected to the same github repo+branch then when pushing a new commit to that branch only one of those apps will be deployed and this app is randomly selected by nhost.

I had 2 apps (app1, app2) connected to the same repo+branch (just because testing various things here and there), and I just realized that the deployments I tried to make on  happened on the older one (app1). Now I created yet another app (app3) with the same  repo+branch and the new deployment happened on not the new one but one of the old ones (app2 in my case).

Probably this is an edge case, but If connecting multiple apps to the same repo+branch is not supported then the UI should warn about it or not allow it at all.

**Comment by elitan** [comment]
Good catch. I think we should allow for connecting the same repository to multiple apps. It could be that you have multiple apps for different branches of your repo, right?

**Comment by beepsoft** [comment]
Yes, I think in the long run I would use 3 apps per project: one for dev, one staging and one for prod and mapped to their respective branches, eg.

```
app-dev ---> repo/dev
app-staging ---> repo/staging
app-prod ---> repo/main
```
I don't think that it is necessary to have more than 1 app to connect to the same repo/branch unless there would be some deployment configuration options per app in the future, like the version of Hasura to use. In this case I would use the following set of apps and repo/branch connections to test my app against both Hasura 2.0 and Hasura 2.1, for example:

```
app-dev-hasura2.0 (configured to use Hasura 2.0) ---> repo/dev
app-dev-hasura2.1 (configured to use Hasura 2.1) ---> repo/dev
```

**Comment by elephant3** [comment]
The fix has been implemented and merged. Soon will be rolled on production, I'll notify once it's there

**Comment by elephant3** [comment]
It's deployed on production!
