### ISSUE TITLE
@nhost/react-urql package

### ISSUE THREAD

**Issue by akhil-naidu** [nhost/nhost#1050]
Can we expect a package similar to `@nhost/react-apollo` for URQL?

I've seen this [repository](https://github.com/nhost/react-urql), but the `README.md` is not what I expect. But in fact, most of the configuration for the `@nost/react-urql` was ready.

**Comment by akhil-naidu** [comment]
#271

**Comment by plmercereau** [comment]
yes, duplicate of the above. closing
