### ISSUE TITLE
NhostClient signup ECONNREFUSED

### ISSUE THREAD

**Issue by adamo97** [nhost/nhost#1055]
------------------------------------------------------------------------------------
Original post at https://discordapp.com/channels/552499021260914688/1031757604764012624
------------------------------------------------------------------------------------
I am using a js serverless function to mimic the front end NhostClient connection to test some DB permissions.  Note, this was working before I updated to `Nhost CLI v0.8.3 for linux-amd64`

Anyways, when this was run:
```
        const nhost = new NhostClient({
            subdomain: "localhost",
            region: ""
        });

        let signup = await nhost.auth.signUp({
            email: "email@example.com",
            password: "password"
        });
```
I got the response: 
```
signup {
   session: null,
   error: {
     message: 'connect ECONNREFUSED 127.0.0.1:1337',
     status: 0,
     error: 'network'
   }
}
```
After following the threads I changed the code to:
```
        const nhost = new NhostClient({
            backendUrl: process.env.NHOST_BACKEND_URL,
        });
```
Then I got:
```
signup {
  session: null,
  error: {
     message: 'Request failed with status code 500',
     status: 500,
     error: 'network'
   }
}
```
I thought this meant the sign up failed.  But running it again said the email was already in use.  I checked the DB and the user was created even though I got the status code 500 error.

I have read several threads from the end of September that mentioned this issue.  It was stated that using backendUrl was a temporary work around for dev and it sounded like the nhost team expected to fix this problem in a couple of days.
I am creating this post to bring attention to this issue since I have experienced it still with `Nhost CLI v0.8.5 for linux-amd64` and `"@nhost/nhost-js": "1.5.0"`,

Nhost team, do we have a status update on this issue?

Refrenced threads: 
https://discordapp.com/channels/552499021260914688/1024256454422708245/1024662120127799368
https://discordapp.com/channels/552499021260914688/1024030556536709150/1024357062022533180

**Comment by plmercereau** [comment]
Hello, you can set a Nhost client in a function like this:
```ts
const nhost = new NhostClient({
  backendUrl: process.env. NHOST_BACKEND_URL
})
```
We are working on making the `NhostClient` more consistent when using functions.

**Comment by elitan** [comment]
With the latest updates from this PR (https://github.com/nhost/nhost/pull/1051) the issue should be fixed.

This is how the NhostClient should be initialized in a Serverless Function:

```js
const localClient = createClient({
  subdomain: 'localhost',
})
```

Documented here: https://docs.nhost.io/cli#subdomain-and-region
