### ISSUE TITLE
feature request - full user registration lock

### ISSUE THREAD

**Issue by c-nv-s** [nhost/nhost#1056]
at present the combination of options for limiting user registration do not fully prevent new users from being created.
users can be still be created but their status is just set to disabled.
It would be useful to have an option the fully prevents any user registration from happening unless a new user is manually added by the administrator.

original discussion:
https://discord.com/channels/552499021260914688/1032407749658693672

**Comment by nunopato** [comment]
closing in favor of https://github.com/nhost/hasura-auth/issues/85.
