### ISSUE TITLE
nextjs example README incorrect

### ISSUE THREAD

**Issue by phishy** [nhost/nhost#1061]
The NextJS example README instructs the user to host `nhost dev`, however upon first clone and `pnpm i` , it does not install `nhost` and therefore user receives `command not found`

**Comment by plmercereau** [comment]
Hello,
You need to install the [Nhost CLI](https://docs.nhost.io/platform/overview/get-started-with-nhost-cli) to run the backend locally.

@elitan you may want to take this into account in [your PR](https://github.com/nhost/nhost/pull/1069)
