### ISSUE TITLE
Cannot add credit card payment method to upgrade plan

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1067]
I click here to add a credit card to upgrade my plan:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/260221/197410018-da64ae95-7ff8-4c4d-9f97-89fea8033560.png">

Add details:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/260221/197409996-cceb6135-e07e-4382-b267-9b1e772944d3.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/260221/197410007-78013c6c-229a-45bd-b259-e4b7a3c177ce.png">

But then get this error:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/260221/197410056-6809bcac-8234-4d0d-a9a7-0bbd5755a0cb.png">

**Comment by dionjwa** [comment]
Hmm I can add a payment method in the main workspace with my username but I cannot add a payment method to other workspaces.

Update: I created a new workspace, then it worked.

But I want to use the original workspace because it has the api path that matches my app, not this one I tested with:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/260221/197410273-2bbbe0cc-f0d7-4192-981c-e5e66e0f6ef3.png">

**Comment by elitan** [comment]
We had some issues a few days ago with our event triggers that caused some workspaces to not get a stripe customer id internally.

It should have been fixed now.

Can you try again?

**Comment by guicurcio** [comment]
@dionjwa 

Were you able to retry? If you did do so, and encountered the same problem feel free to email me at [guido@nhost.io](mailto:guido@nhost.io) so we can manually update your plan and follow up on the problem.

**Comment by nunopato** [comment]
This issue should be fixed so I am closing it. @dionjwa feel free to re-open it if necessary.
