### ISSUE TITLE
"postgres" is unhealthy

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1075]
`nhost up` on a fresh nhost app starts ok.

Maybe I didn't `nhost down`, maybe I did, but when I come back and `nhost -d up` I see this:

```
nhost down && nhost -d up

> No running instance found

> Initializing Hasura client
> start timeout is set to 10m0s
> Stopping docker compose
> Starting docker compose
> Starting functions
> Starting postgres, graphql-engine containers...
> Start took 1.720818195s


> [exit status 1
Container app-mtpg-io-suspicious_jackson-postgres-1  Creating
Container app-mtpg-io-suspicious_jackson-postgres-1  Created
Container app-mtpg-io-suspicious_jackson-graphql-engine-1  Creating
Container app-mtpg-io-suspicious_jackson-graphql-engine-1  Created
Container app-mtpg-io-suspicious_jackson-postgres-1  Starting
Container app-mtpg-io-suspicious_jackson-postgres-1  Started
Container app-mtpg-io-suspicious_jackson-postgres-1  Waiting
container for service "postgres" is unhealthy
] Failed to start services
> Stopping docker compose
```

I have run a lot of very similar stacks with postgres+hasura etc, and mounting the postgres db from the host is rarely problematic. 

There's not much to go on, but the workaround is to:

```
rm -rf .nhost/data/nhost.io/db
```

then it starts ok, but of course, I've lost my local db state, so that's not ideal.

OS: 
```
uname -a

Darwin USM3C22FB9BD8FB 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

docker -v

Docker version 20.10.17, build 100c701
```

**Comment by elitan** [comment]
Can you check the logs using `nhost logs -f` and see if there are any clues?

**Comment by dionjwa** [comment]
When I `cd` into the `.nhost` directory, and run `docker-compose -f docker-compose.json up` I see these logs:

```
nhost-postgres-1        |
nhost-postgres-1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
nhost-postgres-1        |
nhost-postgres-1        | 2022-10-28 01:10:55.033 UTC () [8] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
nhost-postgres-1        | 2022-10-28 01:10:55.033 UTC () [8] HINT:  The server must be started by the user that owns the data directory.
nhost-minio-1           | MinIO Object Storage Server
nhost-minio-1           | Copyright: 2015-2022 MinIO, Inc.
nhost-minio-1           | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
nhost-minio-1           | Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/amd64)
nhost-minio-1           |
nhost-minio-1           | Status:         1 Online, 0 Offline.
nhost-minio-1           | API: http://0.0.0.0:9000
nhost-minio-1           | Console: http://0.0.0.0:8484
nhost-minio-1           |
nhost-minio-1           | Documentation: https://docs.min.io
nhost-postgres-1 exited with code 1
nhost-postgres-1        |
nhost-postgres-1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
nhost-postgres-1        |
nhost-postgres-1        | 2022-10-28 01:10:55.892 UTC () [8] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
nhost-postgres-1        | 2022-10-28 01:10:55.892 UTC () [8] HINT:  The server must be started by the user that owns the data directory.
```

I'm not sure but this smells like a mac+docker issue, since macs use a virtual machine to run docker. 

But it's the same user (me) running this in both cases. Is there a `sudo` appended somewhere where there shouldn't be? (ie not on a mac since docker on mac doesn't require sudo)

**Comment by dionjwa** [comment]
I always use docker volumes to avoid this issue, rather than host volume mounts, because of this exact issue, since host permissions are always a huge PITA.

**Comment by dionjwa** [comment]
I think I found a cause: 
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/260221/198837243-1460540c-58bd-443d-a6d1-672912620f28.png">


If "Enable VirtioFS accelerated directory sharing" is selected, then I see the problem. It uses some kind of host->VM copy mechanism, and likely causes permissions problems. With it disabled, docker restarted, cleared `nhost` caches and db files, nhost restarted, I don't see this issue anymore.

**Comment by nunopato** [comment]
@dionjwa good you were able to fix it. Closing this now.
