### ISSUE TITLE
createApolloClient, SSR, and providing HttpLink to Apollo Client

### ISSUE THREAD

**Issue by jasonkolb** [nhost/nhost#1077]
I am using Vue 3.0 and SSR (via Quasar and Vite), and I am running into a problem where because SSR must be rendered on both the client and server, there is no global fetch instance defined, and I'm getting the following error:

```
Invariant Violation: 
"fetch" has not been found globally and no fetcher has been configured. To fix this, install a fetch package (like https://www.npmjs.com/package/cross-fetch), instantiate the fetcher, and pass it into your HttpLink constructor. For example:

import fetch from 'cross-fetch';
import { ApolloClient, HttpLink } from '@apollo/client';
const client = new ApolloClient({
  link: new HttpLink({ uri: '/graphql', fetch })
});
```

I am using the nhost methods to create these clients and I've tried using generateNhostApolloClient:

`    const apolloClient = generateNhostApolloClient({ gqlEndpoint: "https://hasura-your_hasura_endpoint.nhost.app/v1/graphql%22%7D).client;`

as well as createApolloClient:

`    const apolloClient = createApolloClient({ nhost });
`
When creating an ApolloClient directly the solution suggested by the error is possible, but it doesn't appear that there's a way to provide a custom HttpLink instance when using nhost.

This seems like a showstopper for using SSR, and it seems like the solution would be to pass a custom HttpLink into either generateNhostApolloClient or createApolloClient. Is there another option that I'm missing?

As an aside, I see example of using both generateNhostApolloClient and createApolloClient. Is one of these preferred over the other?

Thanks in advance for the help!!

**Comment by guicurcio** [comment]
Notice that the Apollo package is but a wrapper of Apollo and the headers from the user of your application, so you can achieve the same by importing base apollo and including the headers (token.) Does that help? I'm not sure that you currently can send a special `fetch` to the provider itself 🤔
