### ISSUE TITLE
feat: Nhost account connected to repos of different github accounts

### ISSUE THREAD

**Issue by beepsoft** [nhost/nhost#1079]
When I develop an application I would like to test it under my Nhost account connected to a repo under my github account. 
When I'm finished developing I would like to connect my Nhost project repo to the nhost account of my client I developed the application for.

Currently this is not possible: one github account (and its repos) can only be connected to one Nhost account. It would be great if we could connect different github accounts and repos to the same Nhost account.

**Comment by guicurcio** [comment]
You would like to keep your repository under your GitHub account in private, but a separate Nhost application connected to it? For this, you can create a separate workspace, create an app under that workspace, connect the repo and invite any members to the workspace when you finish working on that repo, does that help?

**Comment by beepsoft** [comment]
It may work with a separate workspace under the same Nhost account, but I would like to access/connect the same github repo from 2 different NHost accounts.

While I develop my app, I deploy it to my Nhost account, say, with a free subscription. Then, when I'm finished, I want to deploy it to the Nhost account of my client, where they have a paid Nhost subscription. As my client doesn't have a github account I want to provide the code from my github account but deploy it this time to my client's Nhost account. It could be a different github repo than the one I use for development, but nevertheless Nhost needs a separate github accounts per Nhost account not a different repo in any github account, this is my problem.
