### ISSUE TITLE
Recommended way to integrate services into the local nhost stack

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1088]
## Problem

I want to add an additional service to my stack, e.g. like [typesense](https://typesense.org/). Basically a single docker container, that the browser client will point to. 

Right now, I start the `nhost` stack with `nhost dev` and then I have to run the other service in another terminal window. I would like to start them all together. 

But how to e.g. connect the lambda functions to the other service is unclear.

Or, is it recommended to just copy and modify an existing docker-compose stack like this? https://github.com/nhost/nhost/blob/main/examples/docker-compose/docker-compose.yaml

## Random ideas

- maybe modify the autogenerated `docker-compose` file the `nhost` cli creates.
- have the ability to start the `nhost` stack deamonized, and if you run `nhost dev` with an already running stack, it just "plugs into" that one. With the deamonized `nhost` stack, then my startup script can start my custom services.
  -  I guess I can just background the `nhost dev` process? 
  - But this doesn't solve the problem of how to automatically configure my lambda functions to connect to another service.

So maybe this is a case of user-defined tooling, but curious if anyone else encounters this requirement, and what solutions others have come up with.

**Comment by nunopato** [comment]
@dionjwa we don't support "bring your own container" right now but it is something we have under our radar. Your workaround seems about right. 

Is this something you want to have available only during development? Would love to know more about what you are doing.

**Comment by dionjwa** [comment]
@nunopato happy to clarify

I am adding [typesense](https://typesense.org/) to my app. `typesense` provides a really nice API for fast, indexed search, it's open source, and they have a very reasonable paid cloud option.

The data flow is:
1. User creates/updates/deletes a document in the db
2. Hasura event fires, calling an `nhost` lambda with the payload
3. `nhost` lambda then inserts/updates/deletes the `typesense` document corresponding to the db document. 
4. This is all very nice and tidy, and provides a fantastic real-time search on the front end.

The browser client had the address of the `typesense` service, so it doesn't need to be heavily integrated into nhost.

As I have iterated on this, I am not using my above solution exactly, tying it in tightly to the local `nhost` stack is no longer needed, as it's a separate service.

**Comment by nunopato** [comment]
Thank you both for your input. I don't think we will be doing anything specific to the CLI to support this as your solution @dionjwa is a valid workaround. 

If you want to start a discussion on a solution/feature to properly support this, I would suggest starting a discussion instead.

I am closing this issue for now.
