### ISSUE TITLE
Example with Remix

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#109]

**Comment by st3phan** [comment]
Now that auth has SSR support a Remix example/starter kit would be awesome! ;-)

**Comment by plmercereau** [comment]
Interesting [feedback from Discord](https://discord.com/channels/552499021260914688/552499021260914691/967393554819334165)

**Comment by dohomi** [comment]
I'd love seeing this too!

**Comment by dohomi** [comment]
After dipping a bit deeper into the codebase I think certain SSR functionality of NextJS should be excluded and made available for other SSR frameworks like Remix. That would be a great addition as Remix is raising in popularity.

**Comment by st3phan** [comment]
Any update on a Remix example? 🙏

**Comment by elitan** [comment]
We're not actively working on a Remix example internally. If anyone from the community is interested in doing a Remix example with Nhost we're open to help out.

**Comment by st3phan** [comment]
Any update on this one?
