### ISSUE TITLE
Can't reset postres password if a permission variable is set

### ISSUE THREAD

**Issue by bcdrme** [nhost/nhost#1093]
Found a bug when trying to reset the postgres password.
I get an error : `Error trying to change database password for ...` if I have a permission variable set.

`struct field for "Org-Id" doesn't exist in any of 1 places to unmarshal`

![image](https://user-images.githubusercontent.com/54471255/199954557-0be93bf5-99fc-455c-970a-0dc72ad3a4d2.png)

After removing the permission variable it works as expected.

**Comment by nunopato** [comment]
@bcdrme thanks for reporting. We will look into this soon.

**Comment by nunopato** [comment]
@bcdrme this has been fixed. Please let me know if you still experience issues. Closing the issue now, feel free to re-open it if necessary.
