### ISSUE TITLE
nhost-js client incorrectly blocks uploads above ~10MB 

### ISSUE THREAD

**Issue by spakanati** [nhost/nhost#1103]
Attempting to upload a larger file (e.g. 14MB) with nhost-js fails with `Error Request body larger than maxBodyLength limit`, which appears to be an Axios error. There are several issues on the Axios repository that suggest the default may be 10MB and to accept larger files, `maxBodyLength` needs to be set to either Infinity or a very high number (possibly [here](https://github.com/nhost/nhost/blob/6ea9ed69ce73b9e0c426d40f20ee42814b21d7cb/packages/hasura-storage-js/src/hasura-storage-api.ts#L28)). 

The bucket I am attempting to upload to has a default 50 MB limit, and the same file is able to be uploaded by the Dart client, confirming that this is a JS client issue.

This bug is a pretty big blocker since it breaks a lot of Storage functionality for those using the JS SDK.

**Comment by elitan** [comment]
@spakanati I've created a test in `hasura-storage-js` for a large file, and I'm not able to reproduce this issue: https://github.com/nhost/nhost/pull/1150

If you look at the PR, is there anything we can change to reproduce your issue?
