### ISSUE TITLE
Display production variables values on nhost dashboard console

### ISSUE THREAD

**Issue by seyaobey-dev** [nhost/nhost#111]
This is more a feature request than a bug: make production variables values visible in dashboard console.
This will greatly improve debugging: I often need to check which value has been assigned, whether it is correct.

See this discord discussion:
https://discord.com/channels/552499021260914688/929545312593383495/929678596631568414

**Comment by elitan** [comment]
It's now possible to see the system environment variables in the Nhost dashboard:

![CleanShot 2022-02-23 at 11 21 08@2x](https://user-images.githubusercontent.com/331818/155300604-d5965d82-a665-4c74-b980-ed57d7945d06.png)
