### ISSUE TITLE
Unable to access project database directly

### ISSUE THREAD

**Issue by makinde** [nhost/nhost#1126]
I am using the Postico postgres client. Copying the connection string and password from my nhost dashboard, I get the following error from my client:

`connection to server at "bcmuovdfucswecjgggrc.db.us-east-1.nhost.run" (52.3.182.89), port 5432 failed: FATAL:  SASL authentication failed`

This happens on multiple free projects that I have at nhost

**Comment by nunopato** [comment]
@makinde I would be curious to see what values are you using (or the connection string) to configure your connection to the postgres instance. Would you mind sharing those with me at nuno@nhost.io or on discord?

**Comment by vinyll** [comment]
I meet the same issue here for running a `pg_dump` and copying locally my database.

```
error: connection to server at "xxxmyserver.nhost.run" (35.157.190.xxx), port 5432 failed: FATAL:  SASL authentication failed
```

Anything to setup for accessing?

**Comment by dbarrosop** [comment]
> Are you aware of anything to setup before accessing?

no, make sure you have the connection string is correct and that you have the correct password. If you are unsure about the password don't hesitate to use the reset password functionality

**Comment by vinyll** [comment]
You are correct.
I had clicked to generated a random password at `https://app.nhost.io/<myprofile>/<myproject>/settings/database` but I didn't hit the red _Reset_ button at the bottom 🤷 

Thanks for you confirmation and prompt reply! 🙏
