### ISSUE TITLE
Missing `azuread` as provider in @nhost/core package

### ISSUE THREAD

**Issue by dipakparmar** [nhost/nhost#1128]
https://github.com/nhost/nhost/blob/4240ad5e84315fa9aee1a01b8f60c7190680cb2e/packages/core/src/types.ts#LL153-L167C1

It seems to be missed addition with this pr https://github.com/nhost/hasura-auth/pull/248

**Comment by plmercereau** [comment]
you're right - thanks for this

**Comment by dipakparmar** [comment]
Thank you for taking care of it quickly.

**Comment by plmercereau** [comment]
Hello,
Unfortunately it won't make it available in the dashboard, as we will need to adapt it.
I created [this issue](https://github.com/nhost/nhost/issues/1130) so we keep that on our radar

**Comment by dipakparmar** [comment]
Thanks for letting me know, I'll watch for it or might also submit a pr.
