### ISSUE TITLE
feat: User provided containers

### ISSUE THREAD

**Issue by beepsoft** [nhost/nhost#1131]
It would be a great addition to the nhost stack if users could provide their own container, which could connect to the other nhost services. 

This would allow running processes, which cannot be implemented with event triggers or cron jobs. For examples, some processing, which requires a specific binary, like ffmpeg. Or if the processing takes more time than is allowed for an nhost function. Something similar to Google Cloud Run / AWS App Runner would be great to have.

**Comment by beepsoft** [comment]
According to some discord chat this may come soon, right?

**Comment by dbarrosop** [comment]
We recently released https://nhost.io/product/run which should cover this use cases.
