### ISSUE TITLE
Replace nhost js GraphQL Client with a third party GraphQL Client

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1177]
The current GraphQL Client in our js SDK (`nhost.grapqhl`) is our custom-built client with minimal features.

We should consider replacing it with a third-party GraphQL client with support for more features and better maintenance.

Some alternatives are:

- `graphql-request`: https://github.com/prisma-labs/graphql-request
- `urql`: https://formidable.com/open-source/urql/docs/basics/core/
- `apollo/client`: https://www.apollographql.com/docs/react/api/core/ApolloClient

**Comment by maximilian-schwarz** [comment]
If you do a request with the built-in client of Nhost JS SDK:

```ts
const QUERY_GET_ALL_USER = gql
  query QueryGetAllUser {
    users {
      email
      displayName
      id
      emailVerified
      createdAt
      roles {
        role
      }
    }
  }

const { data, error } = await client.graphql.request(QUERY_GET_ALL_USER)
```

And got the following error:
`Error: incorrect response data from GraphQL server`

Seems that the default accept-encoding header that Axios uses in a node environment causes issues. If you add "accept-encoding: null" to headers everything is working like expected.

```ts
const { data, error } = await client.graphql.request(QUERY_GET_ALL_USER, {}, {
  headers: {
    'accept-encoding': null
  }
})
```

If think the best solution is to use "apollo/client" as third party client for GraphQL.

**Comment by st3phan** [comment]
> @elitan If you do a request with the built-in client of Nhost JS SDK:
> 
> ```ts
> const QUERY_GET_ALL_USER = gql
>   query QueryGetAllUser {
>     users {
>       email
>       displayName
>       id
>       emailVerified
>       createdAt
>       roles {
>         role
>       }
>     }
>   }
> 
> const { data, error } = await client.graphql.request(QUERY_GET_ALL_USER)
> ```
> 
> And got the following error: `Error: incorrect response data from GraphQL server`
> 
> Seems that the default accept-encoding header that Axios uses in a node environment causes issues. If you add "accept-encoding: null" to headers everything is working like expected.
> 
> ```ts
> const { data, error } = await client.graphql.request(QUERY_GET_ALL_USER, {}, {
>   headers: {
>     'accept-encoding': null
>   }
> })
> ```
> 
> If think the best solution is to use "apollo/client" as third party client for GraphQL.

I can confirm this issue. The fix also works.

**Comment by elitan** [comment]
Thanks for the info. It will help us prioritize this issue.

I think we should use `graphql-request` instead of `urql` or `@apollo/client` because we want a minimal and thin client with no advanced features.

**Comment by maximilian-schwarz** [comment]
Looks good 👍🏻 any plans for the release? 🤗

**Comment by plmercereau** [comment]
A small comparison:

| Library           | Bundle size                                                     | [Npm weekly downloads](https://npmtrends.com/apollo-client-vs-graphql-request-vs-relay-vs-urql) | Easy to begin with | [Codegen](https://the-guild.dev/graphql/codegen/plugins/typescript)                                               |
| ----------------- | :-------------------------------------------------------------: | :------------------: | :----------------: | ----------------------------------------------------- |
| `graphql-request` | [7.9kB](https://bundlephobia.com/package/graphql-request@5.0.0) | 2,447K               | +                  | Vanilla                                               |
| `@apollo/client`  | [42.6kB](https://bundlephobia.com/package/@apollo/client@3.7.1) | 767K                 | -                  | Vanilla, React, Vue, Angular, Stencil, Svelte, Nextjs |
| `urql`            | [8kB](https://bundlephobia.com/package/urql@3.0.3)              | 142K                 | +                  | React, Vue                                            |

I feel `urql` is a bit too react-driven and not as generic as `graphql-request`. I would go for `graphql-request` too.
Moreover:
- we already have a generic `@nhost/apollo` client
- as we are working on a `@nhost/react-urql` library, we could consider adding a `@nhost/urql` library at a later stage so the client can be reused with other frameworks

**Comment by fungilation** [comment]
For a base, graphql-request is good for thinnest possible.

Urql I'm looking at using for my future projects. Apollo cache and its complexity (too smart for its own good with normalization) has annoyed me enough, besides being a fat chunky package. Urql is much lighter and does caching in minimal and predictable ways. +1 to `@nhost/react-urql` being actively maintained

**Comment by SymonRod** [comment]
Hi, for vue 2/3 did you condiser the library [vue-apollo](https://v4.apollo.vuejs.org/)? Its really nice to work with and its supports "new" composition API.

**Comment by elitan** [comment]
We've decided not to do this for now.
