### ISSUE TITLE
Console permission dialog does not accept valid paths

### ISSUE THREAD

**Issue by L3K0V** [nhost/nhost#1198]
The create permission dialog on the console does not accept valid paths.

## Expected behaviour

When enter for path values:

- `user.organization.id`
- `user.organizations[].id`

To be accepted by the field.

## Actual behaviour

The path field does not allow dots `.` or brackets `[]` just dash `-`

### Description

Looks like the regex for the path field is restricted or wrong. [Reference](https://github.com/nhost/nhost/blob/main/dashboard/src/components/applications/users/permissions/modal/CreatePermissionVariableModalBase.tsx#L142)

### Workaround

Use copy-paste from another editor/ide

**Comment by szilarddoro** [comment]
Thanks for your detailed bug report @L3K0V!

We're working on a brand new Roles and Permissions settings page (https://github.com/nhost/nhost/pull/1206). I'll extend the RegExp with `.`, `[`, and `]` in that PR.
