### ISSUE TITLE
nhost success/failure URL settings

### ISSUE THREAD

**Issue by diegonc** [nhost/nhost#1202]
Where should I configure the following URLs from the OAuth example?

    /// Success redirect URL: `nhost-example://oauth.login.success`.
    /// Failure redirect URL: `nhost-example://oauth.login.failure`

On GitHub I filled the following form:

![image](https://user-images.githubusercontent.com/261458/203593322-6d76e696-84bc-420a-bd5a-0931861749fd.png)

there's only one URL to set (the Homepage URL)

And on NHost I am asked for URLs in the `Settings -> Authentication` page shown below:

![image](https://user-images.githubusercontent.com/261458/203593907-3bbbd5ef-25b7-48bd-b2b6-c64ff011318c.png)

The GitHub configuration doesn't show any URL other than the callback that I set on GitHub's settings

![image](https://user-images.githubusercontent.com/261458/203594367-ab6a4ca3-d18a-4b30-8ed8-52f9e271e7ce.png)

**Comment by elitan** [comment]
You can't set URLs for success/failure. Instead, Auth will always redirect the user to either the Client URL or an allowed redirect URL.

If there is an issue during the sign-in process, there will be parameters in the URL describing the error.

I can't see the OAuth URLs changing. They have always included `signin/`.

Some steps we can take to avoid confusion in the future:

- Document how Client URL, Allowed URLs, and Redirect URL works.
- Document what happens on success/failure during the OAuth sign-in process.

**Comment by diegonc** [comment]
> 
> I can't see the OAuth URLs changing. They have always included `signin/`.
> 

I took the URL from the Oauth example in nhost-dart:

https://github.com/nhost/nhost-dart/blob/main/packages/nhost_flutter_auth/example/lib/oauth_providers_example.dart

as well as the instructions to setup urls

**Comment by diegonc** [comment]
> Oh, I see. Would you mind creating a separate issue for that specifically? And we can keep this issue here for documentation.

Done. https://github.com/nhost/nhost-dart/issues/93
