### ISSUE TITLE
add support for maskedErrors: false for the Stripe GraphQL API

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1218]
Right now, it's impossible to get any underlying error from the GraphQL API.

We should allow setting `maksedErrors` when creating the server.

https://the-guild.dev/graphql/yoga-server/v2/features/error-masking#disabling-error-masking

**Comment by rohan-kulkarni-25** [comment]
Hey !! @elitan 
I will like to work on this. It will be great if you can guide me in getting started

**Comment by elitan** [comment]
Sure, what have you tried already? Where are you stuck?

**Comment by chandhuDev** [comment]
hey elitan , is it disabling the maskedErrors only for the stripe or to google-translation , serverless functions also

**Comment by chandhuDev** [comment]
@elitan can you guide me over this
