### ISSUE TITLE
Connection lost in open page after waking up computer from sleep mode

### ISSUE THREAD

**Issue by Godefroy** [nhost/nhost#1225]
Hi,

My webapp uses Nhost Auth and some graphql susbscriptions.
I always let some pages open in my browser, I expect them to maintain their connections to the server to keep data displayed and updated.
When I wake up my computer after sleep mode, auth and subscriptions are lost, data becomes empty.

In production, no error is displayed.
In dev mode, I get:

```
Socket closed with event 4400 {"server_error_msg":"4400: Connection initialization failed: Could not verify JWT: JWTExpired"}
```

How could I make it work?

**Comment by elitan** [comment]
What GraphQL client do you use?

How is it configured? Do you use any of our npm packages? e.g. `@nhost/react-apollo`?

**Comment by Godefroy** [comment]
Hi @elitan!

I'm using `@apollo/client` with codegen.
Should I configure codegen to use `@nhost/react-apollo` instead?

The code of my webapp is here: https://github.com/lonestone/rolebase.io

**Comment by elitan** [comment]
Looks like you're using our packages: https://github.com/lonestone/rolebase.io/blob/main/src/components/App.tsx#L2-L3

Would you mind trying to upgrade these packages to the latest version and see if that solves the issue? 

https://github.com/lonestone/rolebase.io/blob/main/package.json#L34-L35

**Comment by Godefroy** [comment]
I upgraded the package and did some tests, but I still have the same issue in local and prod.

<img width="759" alt="Capture d’écran 2023-01-02 à 18 52 44" src="https://user-images.githubusercontent.com/148421/210265102-297aefb4-9d6f-4072-91bf-5c01af630053.png">

I kept the network tab open to observe what happens.
The token is refreshed multiple times and the websocket restarts usually well.

But sometimes, the websocket doesn't accept the new token. I get an error and there is no retry.
Token continue to refresh periodically after that, but the websocket doesn't restart.

`isAuthenticated` from `useAuthenticationStatus` stays true.

**Comment by Godefroy** [comment]
Hi @elitan, do you have some news about this issue?
It's really blocking for our users.

**Comment by Godefroy** [comment]
I just had the bug on Nhost dashboard: I kept the page open for a long time, and after waking my pc from sleep, I got the message "No Deployments". If I reload, my deployments appear correctly.

![Capture d’écran 2023-02-20 à 22 32 10](https://user-images.githubusercontent.com/148421/220201704-18a56def-89e3-4067-9444-b19f37b052fe.png)

**Comment by jmparsons** [comment]
I'm noticing this as well. It's preventing me from using websockets entirely. The websockets don't reconnect.

**Comment by szilarddoro** [comment]
Have you tried using the `onTokenChanged` function to reconnect to the WebSocket when the token is updated?

**Comment by jmparsons** [comment]
@szilarddoro I figured it automatically would do that under the hood

https://github.com/nhost/nhost/blob/ee154d4ecaa48b2e455be8f9bb488a12da940d09/packages/nhost-js/src/clients/nhost.ts#L64

**Comment by jmparsons** [comment]
@Godefroy were you ever able to figure it out?

**Comment by Godefroy** [comment]
The latest release fixed it, thanks!
