### ISSUE TITLE
Cloud functions failing "couldn't create lambda code for /functionName"

### ISSUE THREAD

**Issue by sachinvnagane** [nhost/nhost#1226]
I'm having issue hosting cloud tried with the solution you gave @elitan  to remove lock file and having latest cli,  everything works fine in local but in cloud its failing **couldn't create lambda code for /functionName**. I have created function in JS, do I need to convert them in TS.

{
  "dependencies": {
    "@sendgrid/mail": "^7.7.0",
    "api": "^5.0.1",
    "cashfree-sdk": "^0.1.1",
    "express": "^4.18.2",
    "firebase-admin": "^11.2.1",
    "jsonwebtoken": "^8.5.1",
    "node-fetch": "^3.2.10",
    "uuid": "^9.0.0"
  }
}

**Comment by elitan** [comment]
Are you able to share the function here too?

**Comment by sachinvnagane** [comment]
function logic ?

**Comment by elitan** [comment]
Yea, the code for the function that is causing this issue. Can you share it here?

**Comment by sachinvnagane** [comment]
const sendgrid = require('@sendgrid/mail');
import fetch from 'node-fetch';

export default async (req, res) => {
    try {

        if (token === SERVER_KEY) {
            const url = process.env.URL;
            const query = `query getOrderDetailsUsingProductId($productId: uuid!, $addressId: uuid!) {
    products_by_pk(productId: $productId) {
      business {
        businessName
        prodConfig(path: "header.logoUrl")
      }
    }
    address_by_pk(addressId: $addressId) {
      name
      emailId
    }
  }`;
            const {
                event: { op, data },
                table: { schema, name },
            } = req.body;
            if (
                (op === 'INSERT' || op === 'UPDATE') &&
                name === 'orders' &&
                schema === 'public' &&
                data.new.orderStatus === 'Placed'
            ) {
                let productId = '';
                let addressId = '';
                productId = data.new.productId;
                addressId = data.new.addressId;
                try {
                    const variables = {
                        productId: productId,
                        addressId: addressId,
                    };
                    await fetch(url, {
                        method: 'post',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({ query, variables }),
                    })
                        .then((response) => response.json())
                        .then((data1) => {
                            const queryResponse = data1;
                            if (queryResponse != null) {
                                const ShopName =
                                    queryResponse.data.products_by_pk.business.businessName;
                                const ShopLogoUrl =
                                    queryResponse.data.products_by_pk.business.prodConfig;
                                const CustomerName = queryResponse.data.address_by_pk.name;
                                const EmailId = queryResponse.data.address_by_pk.emailId;
                                const OrderId = data.new.orderId;
                                try {
                                    const msg = {
                                        to: EmailId,
                                        from: 'emailID',
                                        subject:
                                            'Your Order',
                                        html: ``,
                                    };
                                    sendgrid
                                        .send(msg)
                                        .then((resp) => {
                                            console.log('Email sent\n', resp);
                                            res.status(200).json({
                                                status: true,
                                                payload: {
                                                    message: 'Sucess',
                                                },
                                            });
                                        })
                                        .catch((error) => {
                                            console.error(error);
                                            throw error;
                                        });
                                } catch (error) {
                                    console.log('Error sending message1:', error);
                                    res.status(500).json({
                                        status: false,
                                        payload: {
                                            message: error.message,
                                        },
                                    });
                                }
                            }
                        })
                        .catch((e) => {
                            console.log('Error sending message2:', e);
                            res.status(500).json({
                                status: false,
                                payload: {
                                    message: e.message,
                                },
                            });
                        });
                } catch (error) {
                    console.log('Error sending message3:', error);
                    res.status(500).json({
                        status: false,
                        payload: {
                            message: error.message,
                        },
                    });
                }
            } else {
                res.status(500).json({
                    status: false,
                    payload: {
                        message: 'Auth Failed',
                    },
                });
            }
        } else {
            throw new Error('Server Auth Key Failure');
        }
    } catch (error) {
        console.log(error);
        res.status(401).json({
            status: false,
            payload: {
                message: 'Server Auth failed',
            },
        });
    }
}

**Comment by szilarddoro** [comment]
Hey @sachinvnagane! I updated your comment to make the code block more readable.

```ts
   if (token === SERVER_KEY) {
```

I don't know if the above code is the same as your production code or if it's altered for demonstration purposes, but neither `token` nor `SERVER_KEY` are available in the code. That seems to be the issue to me.

**Comment by sachinvnagane** [comment]
It’s altered for demonstration, all the variables are declared in production code @szilarddoro

**Comment by sachinvnagane** [comment]
is there any way I can check what is causing the creation issue @elitan on dashboard or any other place

**Comment by sachinvnagane** [comment]
`import sendgrid from '@sendgrid/mail';
import fetch from 'node-fetch';

const [SERVER_KEY] = [process.env.SERVER_KEY]; 

export default async (req, res) => {
    try {
        const token = req.headers.key;
        if (token === SERVER_KEY) {
            res.status(200).json({
                status: false,
                payload: {
                    message: 'Server Auth Success',
                },
            });
        } else {
            res.status(401).json({
                status: false,
                payload: {
                    message: 'Server Auth failed',
                },
            });
        }
    } catch(error) {
        res.status(500).json({
            status: false,
            payload: {
                message: error.message,
            },
        });
    }
}`

I tried with even this simple one it failed

**Comment by sachinvnagane** [comment]
```ts
import sendgrid from '@sendgrid/mail';
import fetch from 'node-fetch';

const [SERVER_KEY] = [process.env.SERVER_KEY]; 

export default async (req, res) => {
    try {
        const token = req.headers.key;
        if (token === SERVER_KEY) {
            res.status(200).json({
                status: false,
                payload: {
                    message: 'Server Auth Success',
                },
            });
        } else {
            res.status(401).json({
                status: false,
                payload: {
                    message: 'Server Auth failed',
                },
            });
        }
    } catch(error) {
        res.status(500).json({
            status: false,
            payload: {
                message: error.message,
            },
        });
    }
}
```

I tried with this simple one it failed with same error
