### ISSUE TITLE
nhost production does not have role "me" in "default_allowed_roles" by default

### ISSUE THREAD

**Issue by sangdth** [nhost/nhost#123]
Look like the `default_allowed_roles` missing "me" value on production.

Read more details from [this Discord thread.](https://discord.com/channels/552499021260914688/615892613081333794/934008471802744933)

**Comment by elitan** [comment]
New apps now have "user,me". 

Existing apps still only have "user" so we'll need to upgrade them.

**Comment by sangdth** [comment]
fixed on my old app, so I close this.
