### ISSUE TITLE
@nhost/apollo should use new `graphql-ws` package

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1230]
Apollo no longer recommends using `WebSocketLink` or `subscriptions-transport-ws`. Reference: https://www.apollographql.com/docs/react/api/link/apollo-link-ws/

Instead, they recommend using `grpahql-ws`. Reference: https://www.apollographql.com/docs/react/api/link/apollo-link-subscriptions

**Comment by plmercereau** [comment]
We already use `graphql-ws` - see the [graphql-ws apollo example](https://github.com/enisdenjo/graphql-ws#apollo-client) and [our code](https://github.com/nhost/nhost/blob/main/packages/apollo/src/index.ts#L80)
