### ISSUE TITLE
Hard coded Hasura admin secret key in dashboard source code

### ISSUE THREAD

**Issue by tienpvse1** [nhost/nhost#1241]
currently, dashboard only accept "nhost-admin-secret" as hasura's admin secret key
**
![image](https://user-images.githubusercontent.com/86212960/204511727-9d8a113b-2625-4fda-8711-ce203f15cfeb.png)
**

**Comment by elitan** [comment]
@tienpvse1 What is the specific issue, and how do you suggest the issue is fixed?

**Comment by tienpvse1** [comment]
@elitan when I try to deploy Nhost, my hasura admin secret must be "nhost-admin-secret", otherwise, Nhost's dashboard component won't work correctly.
Can we move that admin secret to environment variable , so when I build docker image, I can pass that variable dynamically?

**Comment by dbarrosop** [comment]
This is fixed in the new CLI we are planning to release today.
