### ISSUE TITLE
Issue Templates ⚠

### ISSUE THREAD

**Issue by ItsRoy69** [nhost/nhost#1243]
### Issue Templates are awesome to have

- Since there are alot of folks contributing to this Opensource project i would suggest we have `ISSUE TEMPLATES`
- That way we can categorize the issues more and manage it more decently.
- I can work on this issue

### Here's how the templates looks :

![image](https://user-images.githubusercontent.com/78967360/204546493-e32ef6f1-32e0-4dc6-8085-5a7da29131e0.png)

Here's how the forms looks :

![image](https://user-images.githubusercontent.com/78967360/204546591-df36d099-e655-43ca-aec4-59fa7c327386.png)

**Comment by szilarddoro** [comment]
Thanks for the suggestion @ItsRoy69. I'll add the default issue templates to the repo. Feel free to open a PR if you'd like to improve them.
