### ISSUE TITLE
I renamed my git repo, now it won't connect

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1251]
Steps:

1. Connect git repo, and deploy 👍🏻 
2. Rename source git repo name for reasons
3. No more deployment
4. Disconnect git repo
5. New git repo name not in list

<img width="724" alt="image" src="https://user-images.githubusercontent.com/260221/204728403-27f4cbfc-b5ab-41c7-bb81-4d372ff7a287.png">

How do I update the list of available git repos?

**Comment by dionjwa** [comment]
I remember the previous issue, and the solution works the same:

1. Uninstall the `nhost` app in github
2. Reinstall `nhost` app
3. Reconnect repository, now the list of names is current, and the deployments work again 👍🏻

**Comment by elitan** [comment]
Yes, this is on our roadmap. We didn't prioritize it yet, though. Thanks for reporting 🙏
