### ISSUE TITLE
How does a user verify their account?

### ISSUE THREAD

**Issue by thev3ritas** [nhost/nhost#126]
I can create a user auth, but I need to be able to configure user's verifying their accounts.
Additionally, would I be able to generate an auth URL dynamically and point it to my own mail service which can send auth emails to the user?

**Comment by elitan** [comment]
You can configure if a user has to verify their email address or not to be able to sign in.

![image](https://user-images.githubusercontent.com/331818/150926216-8e1ff80d-9c0b-4ebf-9f84-86d8e53f93d7.png)

If this setting is checked (meaning only users with a verified email can sign in) Nhost will automatically send a verification email to the user with a link. When the user clicks the link the following happens:

1. The user's `email_verified` column is set to `true`.
2. The user is redirected to your app and is automatically signed in.

Right no there's no way of using your own email service. This is something we might add in the future.
