### ISSUE TITLE
[beta] Hasura 2.1.0 console showing null for some populated columns in auth.users, storage.files, and more...

### ISSUE THREAD

**Issue by shyndman** [nhost/nhost#133]
<img width="993" alt="Screen Shot 2022-01-28 at 1 54 51 AM" src="https://user-images.githubusercontent.com/42326/151501714-f731d7d7-f6fe-4edf-a007-e5ccb7577aae.png">

This is a bug in Hasura, and has been filed: https://github.com/hasura/graphql-engine/issues/8074

Just wanted to report this so others could avoid having to investigate if they notice it.

**Comment by shyndman** [comment]
(Also, should this be here, or in hasura-backend-plus?)

**Comment by elitan** [comment]
This is a bug in Hasura 2.1.x.

https://github.com/hasura/graphql-engine/issues/8020

**Comment by shyndman** [comment]
I realize. I linked the bug.

**Comment by shyndman** [comment]
I realize...isn't that a bug for you too?

**Comment by elitan** [comment]
Oh, sorry. I was reading too quickly. 🙏

**Comment by plmercereau** [comment]
Hello,
Yes, the solution is to use Hasura v2.2.0
Nhost now uses Hasura v2.2.0, this problem won't occur anymore in our cloud either.
Thanks for this issue, Scott!
