### ISSUE TITLE
Add documentation describing how to setup OAuth providers for Flutter Android/iOS

### ISSUE THREAD

**Issue by shyndman** [nhost/nhost#134]
This is potentially confusing process at the moment, and it'd be nice if someone could follow a checklist.

**Comment by sarkartanmay393** [comment]
Is this issue still open ? I would like to contribute to it.

**Comment by szilarddoro** [comment]
Your contribution is more than welcome @sarkartanmay393.

**Comment by eleijonmarck** [comment]
Anyone could help me setup OAuth providers? https://discord.com/channels/552499021260914688/1094351619719692319/1094351619719692319
