### ISSUE TITLE
Safer deployments

### ISSUE THREAD

**Issue by kratam** [nhost/nhost#1349]
It would be great to have safer deployments, i.e. follow these steps:
- clone the DB
- apply the migrations/metadata to the cloned DB
- try to rebuild the functions
- If there was no error, apply the migrations/metadata to the prod DB and replace the functions immediately

This would eliminate most of the risks of the deployment process. Right now if anything fails after the "applying migrations" step, there's a chance that the app is left in a non-working stance (i.e. an old function might try to access a dropped column).

**Comment by elitan** [comment]
I think this could be an amazing addon for power users and enterprise users.

**Comment by dbarrosop** [comment]
You can do something similar by having a staging project. Use one branch to deploy to the staging project and another branch to deploy to production. The only difference with the suggested workflow is that there would be no automatic cloning of data but that shouldn't really have an influence on the deployment. We are also planning to add the possibility to download backups so pro apps should be able to periodically download their production data and dump it into their staging app.
