### ISSUE TITLE
Hide OAuth secrets in UI

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1350]
Hide the following secrets in the UI so that it's safe to browse the page without anyone seeing all credentials. Useful if you're sharing your screen, streaming, or sitting at a public place.

We should only hide the client secrets.

It would be great if it was possible to toggle the secret to see the value.

![CleanShot 2022-12-06 at 21 47 41@2x](https://user-images.githubusercontent.com/331818/206019882-0b5d0bbd-910d-4c6d-9cc8-84f2a90a56f8.png)

**Comment by chandhuDev** [comment]
hello @elitan  , correct me if I am wrong , user should have the toggle option to hide the keys . Provide me with more details

**Comment by elitan** [comment]
> hello @elitan , correct me if I am wrong , user should have the toggle option to hide the keys . Provide me with more details

That's correct.

What more details do you want?

**Comment by chandhuDev** [comment]
actually it is my first time open source interaction . can you guide me on  work flow of the application for  this issue and necessary code section I should have to go through ?

**Comment by chandhuDev** [comment]
actually it is my first time open source interaction . can you guide me on  work flow of the application for  this issue and necessary code section I should have to go through ?

**Comment by elitan** [comment]
If it's your first time contributing, I'd suggest a simpler issue like this one: https://github.com/nhost/nhost/issues/1218

**Comment by chandhuDev** [comment]
Hey elitan , I am working on this issue , can you guide me on this one . When I started reading the code , going down deep into the code to understand every single thing . At the end of the day neither contributing not understanding the codebase well. So it would be great if you guide me on getting know the actual file where I have make this feature live . I figured out that BaseProviderSettings component is providing that client id and client secret inputs .  I was in the Input component of v2 folder.Any kind of guidance would be appreciated

**Comment by dbarrosop** [comment]
Closing in favor of #2107
