### ISSUE TITLE
Social logins with options.redirectTo broken

### ISSUE THREAD

**Issue by fungilation** [nhost/nhost#1353]
**Describe the bug**
On our staging: https://vsm-nft-fe.vercel.app/deadrop-login

Any of the 3 social logins should on oauth login, redirect to /deadrop?scrollto=snapshots. But instead, redirect goes to / instead.

The social login buttons have onClick running this:
```js
let redirectTo = window.location.origin + '/deadrop?scrollto=snapshots'

const handleSocialLogin = (provider) => async () => {
  await nhost.auth.signIn({
    provider,
    options: {
      redirectTo,
    },
  })
}
```

Note that email (passwordless) login is unaffected, it correctly lands on intended route of redirectTo.

**To Reproduce**
1. Go to https://vsm-nft-fe.vercel.app/deadrop-login
2. Click on the Twitch login button
3. Accept twitch oauth
4. See landing back on https://vsm-nft-fe.vercel.app/, instead of intended path in redirectTo

**Expected behavior**
On our production app https://midnightsociety.com/deadrop-login, login at would successfully redirect to https://midnightsociety.com/deadrop?scrollto=snapshots

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 108.0.5359.94

**Additional context**

On staging, ex. redirect after twitch oauth:
`https://id.twitch.tv/oauth2/authorize?client_id=ynj9jl8p7i32qkjhaiamvgmtbs3ccj&response_type=code&redirect_uri=https%3A%2F%2Fvvfatfhruxzgfdfaefic.nhost.run%2Fv1%2Fauth%2Fsignin%2Fprovider%2Ftwitch%2Fcallback&scope=user%3Aread%`

On production, ex.:
`https://id.twitch.tv/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fppxtxntdrtesvpkcvxgh.nhost.run%2Fv1%2Fauth%2Fsignin%2Fprovider%2Ftwitch%2Fcallback&scope=user%3Aread%3Aemail&state=b7e26975-063e-42d3-aa0a-2ee0affcc891&client_id=4dbzpvs4xjzoahdgkvqz2p56949hlq`

**Comment by plmercereau** [comment]
Hello Gary,
Thanks for your issue. This bug should be solved very soon.

**Comment by plmercereau** [comment]
reopening until this is effectively fixed in the Nhost cloud

**Comment by fungilation** [comment]
Tested again on https://vsm-nft-fe.vercel.app/deadrop-login. Issue is fixed for our staging app, with latest hasura-auth (0.17?) deployed
