### ISSUE TITLE
 Expo url setup for nhost-cli local development and production use cases

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost#136]
For anyone coming after me, even on MacOS Docker actually exposes the ports correctly and if Mac Firewall is off the services are accessible from the local network (i.e. so that Expo Go can point to the local dev environment from a physical device).

For Expo, you can set the URLs as below, this makes the production builds point to the nhost cloud (you need to insert your URL here), the physical devices using Expo Go point to the IP of the machine running the Metro Bundler and the simulators run on the machine point to localhost. 

TLDR: In Expo, to make development use the dev environment and production use production, see code below:

```
export const auth_url =
  Constants.manifest.packagerOpts.dev && !Constants.isDevice
    ? "http://localhost:9001"
    : typeof manifest.packagerOpts === `object` && manifest.packagerOpts.dev
    ? `http://${manifest.debuggerHost.split(`:`).shift().concat(`:9001`)}`
    : "nhost.io cloud url";
```

I created a proposed PR nhost/docs#35 to include this in the docs under the `nhost dev` section.

**Comment by plmercereau** [comment]
PR has been merged, will close the issue for now.
Thanks for the contribution!
