### ISSUE TITLE
Todos example with is_completed and completed

### ISSUE THREAD

**Issue by arnaudbzn** [nhost/nhost#138]
In the Todos documentation [example](https://docs.nhost.io/quick-start/todos-table), the table is created with the field `is_completed` but later in the documentation `completed` is used:
- permissions / insert screenshot
- permissions / select screenshot
- authentication / `App.js` code snippet in the `subscription` query
- authentication / permission /  insert screenshot
- authentication / permission /  select screenshot

**Comment by elitan** [comment]
Documentation has been updated and fixed: https://docs.nhost.io/get-started/quick-start
