### ISSUE TITLE
Nhost Web UI shows "not found in type query_root" error

### ISSUE THREAD

**Issue by calvinlang** [nhost/nhost#1385]
**Describe the bug**

Nhost graphQL, Auth, Storage show errors

```
graphql: field 'createdAt' not found in type: 'users_order_by'
auth/users: field 'displayName' not found in type: 'users_bool_exp'
storage: field 'files' not found in type: 'query_root'
```

Had to reset the metadata in GraphQL many times but didn't touch the auth schema.

This project was started a little over 24 hours ago

**To Reproduce**
1. Start an NHost Project
2. Just migration scripts
3. Navigate to auth in Nhost Project

I think it was because I added a role in a permissions section of a table in Hasura?

**Expected behavior**
When entering the users section at `project/user` there should be a lit of users. "Add User" should be able to add a user

**Screenshots**

![image](https://user-images.githubusercontent.com/14323034/207682679-e77df65a-91ea-4a7f-9f04-0ff6f3080871.png)

![image](https://user-images.githubusercontent.com/14323034/207682502-1a4c5e19-7617-4c3d-b191-6398d724c900.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 12.5.1 
 - Browser: Edge
 - Version 108.0.1462.46 (Official build) (arm64)

**Additional context**
New to Hasura. There is a lot of public data in my project so there was a lot of dumping and restoring. Had a lot of trouble understanding how the migrations worked in

**Comment by elitan** [comment]
Can you share some details about your migration script? The issue might be related to that one.

**Comment by calvinlang** [comment]
Not much to say. All the migrations had nothing to do in Auth or Storage. Only public. Lots of tables and foreign keys.

Is there anyway to reset my entire project?

**Comment by calvinlang** [comment]
In the NHost logs I get this output. (IP X'ed out)

`{"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"10.XXX.XXX.XXX","method":"POST","status":200,"url":"/v1/graphql"},"operation":{"error":{"code":"validation-failed","error":"field 'displayName' not found in type: 'users_bool_exp'","path":"$.selectionSet.users.args.where._or[0].displayName"},"request_id":"63d0157f2f26b355ba1d4187ee9bdeb7","request_mode":"error","response_size":154,"uncompressed_response_size":154,"user_vars":{"x-hasura-role":"admin"}},"request_id":"63d0157f2f26b355ba1d4187ee9bdeb7"},"level":"error","timestamp":"2022-12-15T03:27:03.021+0000","type":"http-log"}`

**Comment by elitan** [comment]
It seems like the GraphQL root queries or fields were modified for auth and storage.

If that happens, Auth and Storage will stop working.

If you start a new project and **don't** run your migration script, does it work?

If yes, then it's highly likely that your migration script is causing this issue.

It's not possible to reset a project. But you can delete the current project and create a new one to get a new fresh project.
