### ISSUE TITLE
Social Auth redirects user to Hasura console and doesn't sign in

### ISSUE THREAD

**Issue by jamesward1** [nhost/nhost#1386]
Opened in hasura-auth but opening here if this is more appropriate. Feel free to close whichever one is in incorrect place.

I'm running into a weird issue in my development environment. I let a project sit for a while, and it went to sleep. Yesterday I dusted it off and re-activated the nhost side of things, and now when I attempt to auth with Google, it redirects me to the Hasura console rather than the app. Is this a known issue with a fix? Happy to provide more information to help diagnose.

Thanks.

**Comment by elitan** [comment]
Do you think your issue can be related to this: https://github.com/nhost/nhost/discussions/1319 ?

**Comment by nunopato** [comment]
@jamesward1 can you provide us with the subdomain of your project? feel free to share it on discord.

**Comment by iangabrielsanchez** [comment]
Experiencing this as well

**Comment by iangabrielsanchez** [comment]
also opened an issue about the redirect uri https://github.com/nhost/nhost/issues/1388

**Comment by plmercereau** [comment]
Closing this for now as @iangabrielsanchez's solution seems to have solved the problem.
If it didn't, please reply to this issue with some context and we'll reopen.
