### ISSUE TITLE
Correct git edit link on overview

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1389]
The following link should go to `/settings/git` instead of opening a dialog.

![CleanShot 2022-12-15 at 09 25 49](https://user-images.githubusercontent.com/331818/207809976-c0d31dbc-9fd6-49f4-bda3-f27f8ea001e1.png)

**Comment by Aashish-Upadhyay-101** [comment]
hey I want to work on this issue 😀

**Comment by Aashish-Upadhyay-101** [comment]
I set up everything locally but when the dashboard loads I can't see the "OverviewRepository" component on the dashboard. why is this ??

**Comment by szilarddoro** [comment]
This has been fixed in a past release.

@Aashish-Upadhyay-101: The reason why you didn't see that component is that it's not available locally. We only allow Git-related features in the cloud.
