### ISSUE TITLE
Better error message when `<NhostProvider />` is absent.

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1391]
**Describe the bug**
We're showing a non-helpful error message when the `<NhostProvier />` is not added correctly.

**To Reproduce**

Use our react/nextjs SDK without any `<NhostProvider />`.

Example:

<img width="1032" alt="CleanShot 2022-12-16 at 15 04 16@2x" src="https://user-images.githubusercontent.com/331818/208115611-f3981bd0-6a46-400c-92ea-b049a97b7963.png">

I think we should return a helpful error message saying that the `<NhostProvier />` is not configured correctly.

**Comment by plmercereau** [comment]
I do not get the same error when I don't wrap the application in `NhostProvider`.
This does the trick from my side, though: https://github.com/nhost/nhost/pull/1452
