### ISSUE TITLE
nhost.auth.signIn throws error "the state machine is not yet ready after 15 seconds" in expo react native android

### ISSUE THREAD

**Issue by seyaobey-dev** [nhost/nhost#1404]
**Describe the bug**
In my Expo React Native app (android production, apk file), calling

`nhost.auth.signIn({
    phoneNumber: '__phone_number__'
  })`
  
throws the error "**the state machine is not yet ready after 15 seconds**"

**To Reproduce**
It is not strait-forward to reproduce the error. This is an app in production since 1 year. It has been working fine until a few days ago.

**Expected behavior**
Calling `nhost.auth.signIn(phoneNumber)` should initiate phone login.

**Desktop (please complete the following information):**
 - OS: Android
 - Version: Android 12

**Smartphone (please complete the following information):**
 - Device: Android Samsung A12
 - OS: Android 12
 - Expo React Native

**Additional context**
expo: 47
react-native: 0.70.5
@nhost/core": ^0.9.4,
@nhost/nhost-js": ^1.7.0,

**Comment by seyaobey-dev** [comment]
I wipeout my android phone and reinstalled everything. Seems to have fixed the issue, not sure why. So I'll just close this issue.

**Comment by Svarto** [comment]
Same issue just popped up for me after installing `react-native-view-shot`, will do more debugging but it is very weird. The Nhost SDK just stops functioning, nothing is sent out from the `signIn` function. Seems to be that xstate just gets stuck somewhere and doesn't initialize properly. FYI @elitan

**Comment by Svarto** [comment]
For those coming after and have this issue, I did what @seyaobey-dev said, clean simulator (my problem was on iOS) and rebuild my app. BUT, I also had to restart the Nhost dockers / CLI. Somehow the postgres container had gotten stuck and refused to shut down, so had to force kill it and delete it.

After that and a computer restart, it worked again. Guess I have been coding for too long :)
