### ISSUE TITLE
Visual bug on app overview (Nhost Dashboard)

### ISSUE THREAD

**Issue by MichalNemec** [nhost/nhost#1445]
Hello, free plan and on iphone it shows this:
![image](https://user-images.githubusercontent.com/5663019/209712567-2b980893-96d4-40ca-8aff-b2a8d3c239ad.png)

**Comment by chandhuDev** [comment]
Does it mean increasing the border or decreasing the font size of Settings word ?

**Comment by chandhuDev** [comment]
If so , does not it make any gap in between ?

**Comment by bennett1412** [comment]
is somebody working on this? if not can i try fixing it?

**Comment by thetejasmagade** [comment]
Hey, @elitan ! should I work on this? 🔥

**Comment by szilarddoro** [comment]
This issue has been fixed already.
