### ISSUE TITLE
Can't add security key

### ISSUE THREAD

**Issue by sberney** [nhost/nhost#1446]
**Describe the bug**

I am attempting to add _sign in with a security key_ to my app as per [this](https://docs.nhost.io/authentication/sign-in-with-security-keys) and [this](https://nhost.io/blog/webauthn-sign-in-method). I am not self-hosting. When I attempt to add a key to my account, I get the message "Invalid WebAuthn security key". This is an electron app.

**To Reproduce**
1. Create an electron project using the [ERB seed project](https://electron-react-boilerplate.js.org/docs/installation)
2. Follow the [nhost react quickstart](https://docs.nhost.io/quickstarts/react)
3. You can now sign up, sign in, and sign out using email + password
4. In the nhost control panel, go to Settings -> Sign in methods
5. Enable security keys
6. Create a react component that adds a security key for the signed in user as per docs linked previously
7. Run app
8. Click add security key
9. Windows hello pops up and says "Making sure it's you / Set up Windows Hello to sign in to localhost as [my name according to Windows]. / This request comes from [path to project\node_modules\electron\dist\electron.exe], which is an unverified app."
10. Enter your pin number (presumably, this is for window hello, but I have my security key connected and I didn't get to choose it)
11. The app makes a call to register the security key using the nhost library functions
12. Attempt fails, see below:

**Actual behavior**
Error message is returned by the nhost API:

```
Error: Invalid WebAuthn security key
    at http://localhost:1212/renderer.dev.js:139621:19
    at async Object.onClick (http://localhost:1212/renderer.dev.js:138396:13)
```

**Expected behavior**
API call to nhost is successful, and adds security key for logged in user.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Electron
 - Version 20

**Additional context**
Here is what the component looks like that invokes the API functions:

```javascript
import { useAddSecurityKey } from '@nhost/react';
import { useCallback, useMemo } from 'react';

import CoreCrudDialog from './CoreCrudDialog';
import FormTextField from './form/FormTextField';


export type SecurityKeyCreateDataType = Readonly<{
  nickname: string;
}>;

export type Props = {
  hidden?: boolean;
  onDismiss: () => void;
};

export default function SecurityKeyCreateDialog({
  hidden,
  onDismiss,
}: Props) {

  const securityKey = useAddSecurityKey();

  const initialValue = useMemo(() => ({
    nickname: '',
  }), []);

  const handlePrimary = useCallback(async (value: SecurityKeyCreateDataType) => {
    if (value == null) {
      throw new Error('value is null in SecurityKeyCreate!');
    }
    const result = await securityKey.add(value.nickname);
    if (result.isError) {
      throw new Error(result.error?.message ?? 'unknown error');
    }
  }, [securityKey]);

  return (
    <CoreCrudDialog
      hidden={hidden}
      onDismiss={onDismiss}
      onPrimary={handlePrimary}
      title="Add a security key"
      message="This will allow you to sign in without your password."
      primaryButtonText="Add"
      initialValue={initialValue}
    >
      <FormTextField dataKey="nickname" label="Nickname" required />
    </CoreCrudDialog>
  );
}
```

It's pretty straight forward. Clicking a button is calling `securityKey.add('test')`.

**Comment by plmercereau** [comment]
Hello @sberney,
I could not reproduce the exact same error, but couldn't make WebAuthn work on Electron either.
It seems related to [this issue](https://github.com/electron/electron/issues/24573). I'm afraid there's not much we can do until it is resolved, unless someone comes up with a bright idea.
