### ISSUE TITLE
Serverless functions not picking up process.env variables - despite them being added to the variables inside Nhost console

### ISSUE THREAD

**Issue by founderpad** [nhost/nhost#146]
I've added several variables into the Nhost console but they are always undefined in functions.

**Comment by guicurcio** [comment]
Hey Jamie, I've just tested this and it's working correctly. Remember that you need to [trigger a redeploy after adding an environment variable](https://docs.nhost.io/platform/nhost/environment-variables#:~:text=When%20an%20environment%20variable%20is%20changed%2C%20you%20must%20deploy%20your%20app%20again%20for%20the%20changes%20to%20take%20effect.).

**Comment by plmercereau** [comment]
Couldn't reproduce, and issue raised 4 months ago. Closing
