### ISSUE TITLE
Cannot connect to Github from separate nhost accounts.

### ISSUE THREAD

**Issue by Shinlun** [nhost/nhost#1460]
Hello 🙂
I'm having trouble connecting my nhost project to a github repository. The NHost app is already installed on github and several repositories are already linked to other NHost workspaces on different accounts. 
As shown on the screenshots, I can only "Connect to Github", then "Configure the app".
3 repositories are supposed to be accessible, but none is available when back on my dashboard.

Thanks for the help 🙂

<img width="1304" alt="Screenshot_2023-01-02_at_17 00 34" src="https://user-images.githubusercontent.com/612809/210344685-1a7ac4e6-a000-4e71-88db-35d6673d6524.png">
<img width="599" alt="Screenshot_2023-01-02_at_17 00 49" src="https://user-images.githubusercontent.com/612809/210344694-9acd72b5-2634-47e4-90c8-49036ec5ad1e.png">
<img width="599" alt="Screenshot_2023-01-02_at_17 03 04" src="https://user-images.githubusercontent.com/612809/210344696-cd9d2421-c6d3-46fe-a475-6e555906b192.png">

**Comment by mortenhillbom** [comment]
Is the repos you're connecting in a github organization?
I have experienced a similar issue, and it seems to work fine one repos owned by individual accounts, but not orgs

**Comment by Shinlun** [comment]
Yes it is indeed in a github org. However, the same workflow works on 2 different nhost accounts, linked repos in the same organization :/

**Comment by guicurcio** [comment]
Yes, this is currently a permission issue that we're tracking internally. Would you mind sending me an email to the email attached to [`guido@nhost.io`](mailto:guido@nhost.io) I can add the repo manually (include the subdomain and the full name of the repo e.g. org/name-of-the-repo)

**Comment by Godefroy** [comment]
This issue is blocking for us. We want to use Nhost for multiple projects for our clients (maybe dozens in the future) but it's currently not possible because of that.
