### ISSUE TITLE
signUpEmailPassword function is deprecated?

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1465]
### Discussed in https://github.com/nhost/nhost/discussions/1464

<div type='discussions-op-text'>

<sup>Originally posted by **ankur1163** January  3, 2023</sup>
In vs code, i see strike through on signupemailpassword. Is this deprecated or its something else?

https://prnt.sc/2CYzqW8P4G48</div>

**Comment by plmercereau** [comment]
Reproduction link: https://codesandbox.io/s/vite-react-ts-forked-e888yh?file=/src/App.tsx
it happens when `email` is of `unknown` type. `email` should be `string` - and then the deprecation disappears

**Comment by plmercereau** [comment]
Will be solved when we will release https://github.com/nhost/nhost/pull/1348

**Comment by szilarddoro** [comment]
This issue has been fixed already.
