### ISSUE TITLE
make a user authenticate with phone also

### ISSUE THREAD

**Issue by chandhuDev** [nhost/nhost#1466]
It is a feature request :
When a new user is asked to verify the email after signing up in local mode via mobile not with laptop , redirects to the localhost error.

Sol'n I would like to have  :
As user authentication is being tested locally , he should be able to verify email via mobile and would be redirected to a page acknowledgement about the verification.

**Comment by chandhuDev** [comment]
@elitan If you find this is an needed feature , then would like to ask you any better solution , please provide it might help anyone to contribute .

**Comment by elitan** [comment]
is it possible to solve this using something like this?

```js
nhost.auth.signUp({
  email: 'joe@example.com',
  password: 'secret-password',
  options: {
    redirectTo: '<some-url>/verification-successful`
  }
})
```

**Comment by chandhuDev** [comment]
can I know the documentation part of it , I have again gone through docs for signup section but could not able to find the redirectTo options ?

**Comment by elitan** [comment]
I don't think it's properly documented yet.
