### ISSUE TITLE
Show error message if delete user fails

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1473]
## Problem

Sometimes deleting a user fails because of FK constraints, however, the error message only shows a generic message.

![CleanShot 2023-01-05 at 08 33 40](https://user-images.githubusercontent.com/331818/210726048-ca1b758f-84e0-419f-a146-940ba2c34053.png)

## Solution

Show the error message from GraphQL to make it easier for the user to understand why the deletion failed and how to fix it.

E.g:

```
Foreign key violation. update or delete on table \"users\" violates foreign key constraint \"profile_id_fkey\" on table \"profile\"
```

**Comment by guicurcio** [comment]
I think what we could do is that if we run into a `Foreign key violation` we should warn our users that removing their users would result in a cascade delete of their attached tables, say, with an alert. wdyt?

**Comment by elitan** [comment]
> wdyt?
Not needed (and not possible, I think, because if the FK is set to Cascade Delete you won't see the `FK violation` error when deleting).
