### ISSUE TITLE
when we can have Self hosted document like HBP docker-compose model include both Auth and Storage ?

### ISSUE THREAD

**Issue by msalehy** [nhost/nhost#148]

**Comment by plmercereau** [comment]
Hello @msalehy,
We just added a docker-compose example:
https://github.com/nhost/nhost/tree/main/examples/docker-compose

**Comment by plmercereau** [comment]
Hello,
No, but this is something we are considering to do in the future. There is no official hasura helm chart, but you can see what's available in [artifacthub](https://artifacthub.io/).

**Comment by AdZoAi** [comment]
Many thanks, 
For the record, for hasura i'm using https://charts.platy.plus chart 1.1.6 and works perfect!.

**Comment by plmercereau** [comment]
I wonder who created it ;)
