### ISSUE TITLE
updating nhost-js.umd.js fails with error: NhostClient is not a constructor

### ISSUE THREAD

**Issue by c-nv-s** [nhost/nhost#1480]
I think at some point a breaking change occurred because when trying to update to the latest version using the below script tag import method I receive the error ``NhostClient is not a constructor`` when using  client = new NhostClient({...}). 
Was working fine in 1.1.14

```
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/@nhost/nhost-js@latest/umd/nhost-js.umd.js"></script>
</head>
<body>
    <script>
        const { NhostClient } = window['@nhost/nhost-js']
        const nhost = new NhostClient({  subdomain: '<your-subdomain>',  region: '<your-region>'})
        console.log(nhost)
    </script>
</body>
</html>
```

**Comment by c-nv-s** [comment]
Please could someone give an indication of whether this is a big task, or whether it will be an abandoned option, so that people who can't use nhost with a build step can decide on the next actions they need to take.
Thanks

**Comment by c-nv-s** [comment]
...please?

**Comment by szilarddoro** [comment]
We had a [conversation](https://discord.com/channels/552499021260914688/1058956005448351834) about this on Discord. We'll need to find some bandwidth to fix this issue.

In the meantime, using an older version can be an option:
`<script src="https://cdn.jsdelivr.net/npm/@nhost/nhost-js@1.5.0/umd/nhost-js.umd.js"></script>`

**Comment by iamkhalidbashir** [comment]
cannot import nhost lib on appsmith due to this issue

**Comment by szilarddoro** [comment]
@iamkhalidbashir - Have you tried using an older version as per my suggestion?

> In the meantime, using an older version can be an option: `<script src="https://cdn.jsdelivr.net/npm/@nhost/nhost-js@1.5.0/umd/nhost-js.umd.js"></script>`

**Comment by iamkhalidbashir** [comment]
The older version works on a normal html/js based site but not appsmith
as it needs a error-free UMD script and feeding it the new or old fails

**Comment by szilarddoro** [comment]
What do you mean by "error-free"?

**Comment by iamkhalidbashir** [comment]
Not sure, I try to debug why it was failing on appsmith as appsmith gives a generic error that it cannot load this script.
There were 2 possibilities:-
1. This is not a valid UMD script
2. The script has some syntax based bugs of some sort

Given it looks like a UMD script, the logical possibility is no2

**Comment by c-nv-s** [comment]
It would be great to get an understanding of if we need to wait weeks or months more for this to be updated?

**Comment by szilarddoro** [comment]
Sorry @c-nv-s but we have other priorities at the moment. Can you use the older version in the meantime that still works? We don’t have an ETA on this one. We are open for contributions though so feel free to open a PR if you have some spare time.

**Comment by c-nv-s** [comment]
ok no worries, I'll abandon this for now but you can obviously keep the ticket open for anyone else
