### ISSUE TITLE
Can't update an already uploaded file in NHost Storage

### ISSUE THREAD

**Issue by bcdrme** [nhost/nhost#1483]
I was trying to update the content of a file I already uploaded, `fileId` is known:
```
const { upload } = useFileUpload()
...
await upload({ id: fileId, file })
```

This doesn't work, it throws 400, duplicate key, this file already exists.

Apparently Hasura Storage allows it, it would be great if it was integrated in the JS SDK as well (and @nhost/react @nhost/nextjs ofc)

> Johan Eliasson
> I think it's supported to update an existing file in Hasura Storage: https://editor.swagger.io/?url=https://raw.githubusercontent.com/nhost/hasura-storage/main/controller/openapi.yaml#:~:text=Replace%20an%20existing%20file%20with%20a%20new%20one (check the PUT operation).
> Maybe we can re-use nhost.storage.upload() and, as you did, require the user to specify a file id and also specify an optional { update: true } or something

**Comment by plmercereau** [comment]
Which version of the sdk are you using? This should have been fixed in [1.12.1](https://github.com/nhost/nhost/blob/main/packages/react/CHANGELOG.md#1121)

**Comment by bcdrme** [comment]
I can confirm this works using fetch :

```
const formData = new FormData()
formData.append('file', file)
await fetch(`/api/files/${fileId}`, {
    method: "PUT",
    body: formData,
    headers: {
        'Authorization': `Bearer ${token}`,
    }
})
```

**Comment by elitan** [comment]
Yea, we have the support in Storage but we don't have a method for it in our SDK.

**Comment by mainstreetmark** [comment]
I would also like to update an existing file.

My use case is downloading word docs, making some changes and reuploading them.  I have the file_id, but useFileUpload provides no "overwrite" mechanism.
