### ISSUE TITLE
Feature to change user's name

### ISSUE THREAD

**Issue by KMohZaid** [nhost/nhost#1489]
**Is your feature request related to a problem? Please describe.**
The problem is i created account with github and so my email coming up in name place, i want to change my name

**Describe the solution you'd like**
A feature to change user name

**Comment by chandhuDev** [comment]
can you describe more about this in detail ?

**Comment by elitan** [comment]
Do you mean in the Nhost Dashboard or in your own app built with Nhost?

**Comment by KMohZaid** [comment]
> Do you mean in the Nhost Dashboard or in your own app built with Nhost?

In dashboard, if you are workspace member list you can see your email address as name when you create nhost account with Github

**Comment by KMohZaid** [comment]
> can you describe more about this in detail ?

When i create my account with github, it only request read email address permission for github not other eg. Username
And after that nhost didn't ask for entering name and put my name as email

**Comment by KMohZaid** [comment]
![image](https://github.com/nhost/nhost/assets/68484509/d4adfadb-9b4f-44ff-b0f9-4ca557a51799)
i signup from github and nhost  put my email as name instead of github name
there  is no change option there
