### ISSUE TITLE
Is is possible to debug local functions & use vs code breakpoints

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost#1499]

**Comment by plmercereau** [comment]
Hi, no, but that would be a nice to have

**Comment by mayconht** [comment]
Hi!
There is any plan to make it work?
It would be great to have vscode breakpoints working.

**Comment by pkreipke** [comment]
@mayconht I see your pull request here https://github.com/nhost/cli/pull/570.

That'd be super exciting and super useful! Does it work locally for you? Is there a way for me to try it locally by modifying files in my `.nhost` folder or elsewhere?

**Comment by mayconht** [comment]
Hi, @pkreipke  I am able to attach the debugger through vscode, but for some reason, the breakpoint is not binding properly. 
I still working on it, probably something with the sourceMap on tsconfig or something like that.


But answering your question:

Download this forked CLI: https://github.com/mayconht/cli
it contains the debug port + docker image with the --inspect command on it.

you'll need to have the go compiler installed, after that run the command:

```go build -o cli```

it will generate a cli file that you will move with the following command

```sudo mv ./cli /usr/local/bin/nhost```

just execute nhost dev -d on your project folder and it should run with the debugger mode activated.

On the laucher.json I am using the following:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Docker: Attach to Node",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "address": "localhost",
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/",
            "protocol": "inspector"
        }
    ]
}
 ```
 
 The problems I spotted so far:
 
>  the CLI is not able to identify that the functions are finally running so it keeps the ¨Processing...¨ message.
>  I can attach the debugger but not bind the breakpoint, probably because the server changes a bit the layout of the functions folder.

I still working on it, but a hand or two will be welcome, this is my first contribution to an open-source initiative, so if something is wrong please let me know.

**Comment by mayconht** [comment]
![image](https://user-images.githubusercontent.com/18490169/216482977-8ad0507d-c8c0-4e51-bd68-d69cfd6d06b3.png)

**Comment by pkreipke** [comment]
I'm not sure I'd be much help (don't know Go nor Docker internals) but I'll try to find time in the next 3-4 workdays to try it as you outlined.

I had been wondering after looking to the code commit you made whether the Functions are being served by Go or by node. And whether in development it's _not_ running like a true serverless lambda where each invocation launches a new JS/node instance. E.g. could that why the debugger might attach then detach or never attach because the instance hasn't been spun up by the HTTP server (which is presumably in Go).

**Comment by mayconht** [comment]
Yeah, I am not sure either, it is my first experience with Go.
as I can tell Go takes care of folder management, docker, ports, and other configs related to docker-compose, Hasura, database, and so on.
Node is an express server that "joins" our serverless application into a single docker container with each function being a new route. (if one of them fails, all of them will fail)

**Comment by mayconht** [comment]
Also, my solution might not be the best one.
It would be better to have a flag/arg on the nhost cli E.g. ```nhost dev -debugger``` so we can expose the port only when needed.
Why: we expose the debugger port and allow it to be accessed from any IP (0.0.0.0) so it should not be the most secure approach to have it enabled by default.
