### ISSUE TITLE
changing url of endpoint (localhost:1337)

### ISSUE THREAD

**Issue by Vanillabacke** [nhost/nhost#1514]
Hi,

I have installed the project via the docker-compose example and have no problem running it on localhost.
My problem is, as soon as i expose the project on my domain, it will always try to get the endpoint from localhost:1337 (`http://localhost:1337/v1/auth/healthz`)

I have changed the proxy successfully to work on my subdomain `https://nhostapi.mydomain.com/v1/auth/healthz`, but as soon as I go to the dashboard page, it will always request on `http://localhost/v1/....`. It looks like, that this url is hardcoded or is there any ENV-variable for the endpoint? I tried to edit it in the `config.yaml`, but it has no effect.

thanks for any help and for your work on that project!

**Comment by hugomn** [comment]
May I ask how did you expose the project on your domain? Did you self-host Nhost in your own cloud? I'm also exploring how to make nhost-js work with self-hosted versions.

**Comment by Vanillabacke** [comment]
i used the docker example (link below) and slightly modified it to use my existing minio and mailhog container. 
[https://github.com/nhost/nhost/tree/main/examples/docker-compose](https://github.com/nhost/nhost/tree/main/examples/docker-compose)

locally it is working fine, but the dashboard kinda has some hardcoded url for the v1 api.
but i couldn't figured it out yet, where the value came from of `client.auth.url` and i get some
`Error Connecting ` on my public url.

**Comment by szilarddoro** [comment]
We have [had a discussion](https://discord.com/channels/552499021260914688/1063419881531383849/1063440905727660062) about this on Discord. Our dashboard (and SDK) has a limitation at the moment. It only allows `localhost` to be used as a subdomain (without a region), therefore it's hardcoded.

There is an open PR (https://github.com/nhost/nhost/pull/1467) that allows custom subdomain configuration in the dashboard, but the SDK would still have the restriction to a valid `subdomain` and `region` pair (what you'd get if your app is hosted by us) or `localhost` / `localdev`.

I hope we can make a decision about this during the week and make the necessary changes to both the dashboard and the SDK very soon. We'll keep you posted.

**Comment by Vanillabacke** [comment]
thanks a lot for the update and your effort!

**Comment by szilarddoro** [comment]
Hey folks! Just letting you know that the individual URLs are supported by the dashboard. You can use [this README](https://github.com/nhost/nhost/blob/main/dashboard/README.md#enable-local-development) as a reference. Let me know if you need any help with the setup.

I also think that this issue is related to https://github.com/nhost/nhost/issues/1701.
