### ISSUE TITLE
Adding sender name to SMTP settings

### ISSUE THREAD

**Issue by anelad** [nhost/nhost#1524]
It would be great to have an option set a sender name to Nhost emails, like "Website Admin", but they are shown as plain mail address.

**Comment by guicurcio** [comment]
The Nhost cloud understands `auth_smtp_sender` to be just the email name. We are in the same situation as the case with adding new providers: adding a new input to the SMTP page is trivial, but we need changes both to our remote database, and then coordinate with infra to re-deploy the app with new env variable e.g. 'auth_smtp_name'.  

Alternatives would be to send to hasura auth the `auth_smtp_sender` as something like `smtp.provider;website admin," while showing two inputs in the front-end, but it may be prone to errors. Another one which I think was the idea from the beginning was to add either the app name or the workspace name as the from. (both of needs would not need infra changes)

**Comment by kelkes** [comment]
Would be nice to have this implemented. I got some complains from clients thinking that the mails are spam because there is no sender name

**Comment by dbarrosop** [comment]
Oh, for the record, this always worked. Just set `Name <name@company.com>`.
