### ISSUE TITLE
Improve project import process

### ISSUE THREAD

**Issue by nirvdrum** [nhost/nhost#1549]
**Is your feature request related to a problem? Please describe.**

I've attempted to import an existing Hasura project into Nhost. I already had Hasura metadata and migrations in my project that I needed to apply in Nhost, but Nhost prepopulates a project's Hasura instance with its own metatadata and DB tables. Hasura does not merge the changes when applying the metadata from my application, which effectively deletes the Nhost resources such as users and storage.

**Describe the solution you'd like**

It'd be nice if importing an existing project was simpler. I think ideally Nhost's project resources would be managed separately from the app's to avoid conflicts such as this. Barring that, there should be an easier way to fetch the existing Hasura configuration to merge it.

**Describe alternatives you've considered**

After realizing that applying my app's metadata destroyed Nhost's, I created a new Nhost project and used the Hasura CLI to export the metadata created by Nhost. I then manually merged it with my app's metadata. This required some manual changing of values per #1232. It works, but if Nhost expects to make future changes to the app's Hasura metadata, I'll have to work out the process again. Also, my app's configuration now includes Nhost's service-specific resources, which I'd prefer to avoid.

**Comment by elitan** [comment]
Good suggestion. We should write a guide on how to do this. It's relatively simple when using the Nhost CLI. I've made a note internally to write a blog post about this.

**Comment by dohomi** [comment]
I'm very much interested in this. I have 2 projects which both run on on Hasura v1 with self hosted DigitalOcean and I'd love to move the projects to Nhost. Currently I am not sure how to start as the projects hare not even v2 of Hasura.

**Comment by elitan** [comment]
Thanks for your comment, @dohomi. We'll prioritize this.

**Comment by nirvdrum** [comment]
I'm sorry, I was traveling when the stalebot notification came in. Has there been any movement on this issue?

**Comment by dbarrosop** [comment]
No, but I am afraid I don't understand the issue. Metadata is managed independently by each individual service and re-applied every time the CLI is started so the following process should simply work:

1. Start CLI
2. Import postgres data and metadata from existing project
3. Restart CLI

**Comment by nirvdrum** [comment]
Can you elaborate on the CLI option when you get a chance? I applied the migrations and metadata via the Hasura console. Since Nhost manages the storage and auth systems inside the same Hasura instance as the application, applying my application's metadata effectively deleted the auth and storage services. The database tables still exist, but Hasura doesn't know anything about them.

My solution was to export the auth and storage metadata from Hasura first and then manually merge with my application's metadata. While that works, it's difficult to keep in sync, and this issue is about finding a way to avoid some of the bumpy paths to getting it all working.

**Comment by dbarrosop** [comment]
There is no option, just restart the CLI, metadata is always re-applied on boot to avoid issues like the one you are describing. Nhost's metadata is managed by nhost services and they will always attempt to make sure it is correct during the boot process.
