### ISSUE TITLE
Update "Allowed Roles" to "Default Allowed Roles"

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1561]
"Allowed Roles" should be named "Default Allowed Roles" to make it clear that these are default values being applied to new users on sign-up.

Adding "default" also matches the env var in Hasura Auth: https://github.com/nhost/hasura-auth/blob/main/.env.example#L45

**Comment by losahlmann** [comment]
https://github.com/nhost/nhost/issues/1736

**Comment by kuluruvineeth** [comment]
@elitan I have created pull request  which fixes this issue, would you please review and let me know if still any changes to be made thanks : https://github.com/nhost/nhost/pull/1864
