### ISSUE TITLE
Extending useUserData()

### ISSUE THREAD

**Issue by anelad** [nhost/nhost#1564]
I like to add additional information linked to user.

For example, in my accounting application users have different `id`s than my nhost users, so I have a table to link user id's to each other.  Something like this:

```
table AccountingIds {
  accounting_id: string (PK)
  user_id: UUID (unique)
}
```
And I add an object relationship between `public.AccountingIds.user_id = auth.users.id`

Of course, `useUserData()` hook does not return the accounting id linked to it.

Adding a feature like `useUserData({ additionalData: <PartialGrapql> })` to return custom relationships alongside with default ones might be useful.

(I don't want to use metadata for this, since while updating metadata it's easy to overwrite exiting data)

**Comment by mainstreetmark** [comment]
I wrote my own `useUser()` which points at my own public/users table.  That table has a relationship to the auth/users table.  My useUser uses nhost's useUser to provide `isAuthenticated` and all the normal stuff.
