### ISSUE TITLE
nhost type is not capable with NhostApolloProvider

### ISSUE THREAD

**Issue by Meir-p** [nhost/nhost#1565]
**Describe the bug**
nhost type is not compatible with NhostApolloProvider.

<img width="940" alt="צילום מסך 2023-01-31 ב-18 37 03" src="https://user-images.githubusercontent.com/100231666/215830297-ad0f6b27-0087-4427-83bc-212dadf6cc57.png">

**Comment by szilarddoro** [comment]
Could you please share some  details about the versions you are using?

You can also try to remove the `node_modules` folder and reinstall the dependencies.

**Comment by elitan** [comment]
This is most probably because of old versions. Try to upgrade all `@nhost/*` packages and you should be OK.

I'm closing this, but feel free to write here again if it didn't solve the issue.
