### ISSUE TITLE
Make it possible to manage roles

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1575]
**Describe the bug**
It's currently not possible to manage roles in the dashboard. We're locking the `storage.roles` table and it's only possible to manage default allowed roles under settings -> roles and permissions.

**Expected behavior**
Make it possible to manage roles.

**Comment by szilarddoro** [comment]
Is this and #1562 related @elitan ?

**Comment by elitan** [comment]
Yes. This is a duplicate.
