### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by Bijit-Mondal** [nhost/nhost#1576]
**404 on self hosting**
I went through the documentation and use `docker-compose.yml` to install nhost on my cloud setup, but when ever I go to the public IP 404 page is coming as response. how to resolve

**Comment by Samsonov0** [comment]
+

**Comment by Bijit-Mondal** [comment]
Hey,have you set the .env variables

**Comment by Samsonov0** [comment]
yes, I did cp .env.example .end and cp env.example .env.development, I tried to change the host address directly in docker-compose, climbed in dashboard configurations and everything like that. as I noticed, only dashboard doesn't start.  functions, for example, work fine

**Comment by ngi** [comment]
maybe you should remove the "localhost" parts in traefik.http.routers.functions.rule in your docker-compose.yaml

**Comment by Bijit-Mondal** [comment]
> maybe you should remove the "localhost" parts in traefik.http.routers.functions.rule in your docker-compose.yaml
have you succeed to install nhost
please help me out

**Comment by zuohuadong** [comment]
+1

**Comment by chaitugsk07** [comment]
+1

**Comment by chaitugsk07** [comment]
+1

**Comment by zuohuadong** [comment]
Has it made any progress?

**Comment by dbarrosop** [comment]
Looking at the [example](https://github.com/nhost/nhost/tree/main/examples/docker-compose) and following the instructions in the `README.md` everything seems to work without any problem. Keep in mind, this is an example on how to run it on your own without using our cli, it will most likely need to be adapted for your existing setup. As you can imagine, we can't support every possible way users may want to deploy this as there are infinite possibilities here. If you are facing issues self-hosting it I'd suggest you contact your network administator or devops person so they can help you in your environment.

I am closing this issue as the example works, if someone has problems following the example to the letter feel free to open a new issue.
