### ISSUE TITLE
Serverless functions not working with Hasura remote schema

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#1577]
**Describe the bug**
Serverless function examples that utilize graphql and are schema stitched using Hasura remote schema do not work when deployed to app.nhost.io. 

**To Reproduce**
Using one of the example serverless functions:
- [Nhost Pothos Example](https://github.com/nhost/nhost/blob/main/examples/serverless-functions/functions/graphql-pothos/index.ts)
- [Nhost Yoga Example](https://github.com/nhost/nhost/blob/main/examples/serverless-functions/functions/graphql-yoga/index.ts)

1. In the same project, locally configure both a serverless function and Hasura to use the serverless function as a remote schema.
2. Restart the local stack and observe Hasura remote schema is functioning.
3. Deploy to app.nhost.io and observe failed deploy status.
4. Open deployed hasura instance and see the serverless functions are no longer listed under remote schema.

**Expected behavior**
Deployed stack should not deploy with errors and the remote schema in Hasura should be shown and working.

**Comment by jovermier** [comment]
The deployment order prevents graphql serverless functions to work with Hasura remote schema. The startup sequence needs to be changed to first start the serverless function then once complete start Hasura.

Current Order:
```
Starting deployment
Cloning repo ...
Applying database migrations
Database migrations applied successfuly
Applying metadata
Metadata applied successfully
Deploying functions
Functions deployment completed
Skipping custom email templates. Not available on 'Starter' plan
Deployment completed with status DEPLOYED
```

Proposed Order:
```
Starting deployment
Cloning repo ...
Deploying functions
Functions deployment completed
Applying database migrations
Database migrations applied successfully
Applying metadata
Metadata applied successfully
Skipping custom email templates. Not available on 'Starter' plan
Deployment completed with status DEPLOYED
```

What are your thoughts @elitan?

**Comment by elitan** [comment]
I think we should try to simply add a Hasura Metadata Reload.

In the deployment, we can add it as a final step after functions have been deployed.
In the CLI, we can also add it as a final step before everything starts.
