### ISSUE TITLE
Creating new GitHub Labels for our monorepo

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#158]
Now that we have a monorepo we should have labels for various parts of the repo such as:

- docs
- each individual js SDK

This will make it easier to sort and categorize GitHub issues for this repo.

**Comment by plmercereau** [comment]
let's start with a `doc` and a `sdk` label, then we'll split the `sdk` label when it's getting crowded

**Comment by elitan** [comment]
![CleanShot 2022-02-11 at 08 20 58@2x](https://user-images.githubusercontent.com/331818/153551713-159625ae-7b1b-4e11-87e6-c52c34bf5943.png)

Done.
