### ISSUE TITLE
Does nhost apollo attach correct header?

### ISSUE THREAD

**Issue by ankur1163** [nhost/nhost#1580]
```
<NhostProvider nhost={nhost}>
      <NhostApolloProvider nhost={nhost}>
        <RouterProvider router={router}>
          <MantineProvider withGlobalStyles withNormalizeCSS>
            <Signup />
          </MantineProvider>
        </RouterProvider>
      </NhostApolloProvider>
    </NhostProvider>
```
```
 const { loading, error2, data } = useQuery(gql`
  query MyQuery {
    user(id: "95a8ec60-a163-46b6-855f-09fe6e3d045c") {
      avatarUrl
      createdAt
    }
  }
`);

if (loading) {
  console.log("loading", loading);
}
if (error2) {
  console.log("error2", error2);
}

if (data) {
  console.log("data query", data);
}
```
This doesnt attach correct  jwt. I assume through documentation, it should attach correct jwt inheader itself. 
https://prnt.sc/7DPkUF-DtP6D
Am i missing some steps here or this is a bug?
update --- now magically i can see jwt in my header. 
https://prnt.sc/JDcogbZhdKKm
this is strange

**Comment by elitan** [comment]
Does this happen after a reload of the page?

If it does, it could be that you're sending the GraphQL request before the user is authenticated.

You can use `<SignedIn />` to make sure the user is signed in before you render anything: https://docs.nhost.io/reference/react/signed-in

**Comment by elitan** [comment]
I'm closing this issue for now since I'm 99.9% sure this is the issue. Let me know if the issue persists, and we can always reopen it.
