### ISSUE TITLE
Upgrade account

### ISSUE THREAD

**Issue by pedromontanes** [nhost/nhost#1592]
when I try to upgrade the account return me an error:

Error adding a payment method: Foreign key violation. insert or update on table "workspaces" violates foreign key constraint "workspaces_billing_address_country_code_fkey"

I try to do it from SPAIN

**Comment by elitan** [comment]
@pedromontanes Can you send me an email: johan@nhost.io and we'll sort it out.

**Comment by iangabrielsanchez** [comment]
Hi @elitan I am also getting this exact error.

**Comment by elitan** [comment]
I'm working on it right now. 

For now, you should be able to open the Stripe Customer portal and manage your payment methods there.

You find the customer portal by clicking on your workspace and then the Stripe Customer Portal button under Invoices. Then you can manage your payment methods there.

I'm right now working on making this the default behavior across Nhost, so we don't have to manage the payment methods UI ourselves.

![CleanShot 2023-02-08 at 09 23 41@2x](https://user-images.githubusercontent.com/331818/217474387-e0669f3c-d433-443f-9fb6-c7610c2bede6.png)

![CleanShot 2023-02-08 at 09 24 01@2x](https://user-images.githubusercontent.com/331818/217474463-ed9ca011-6769-4def-841b-438f5e5b8464.png)

![CleanShot 2023-02-08 at 09 24 42@2x](https://user-images.githubusercontent.com/331818/217474605-79c60224-c73d-4ee8-bada-45365a56fa94.png)

**Comment by elitan** [comment]
Please let me know here if this approach worked for you 🙏 or if there are any other bumps you encountered.

I'm planning to have all of this tested and ready during the day today.

**Comment by pedromontanes** [comment]
i can upgrade then plan !!!!
Pedro Montañés Albertí
***@***.***
+34 606 326 612
motivales.com

**Comment by pedromontanes** [comment]
I can not upgrade the plan !!!
Pedro Montañés Albertí
***@***.***
+34 606 326 612
motivales.com

**Comment by elitan** [comment]
We're rolling out a fix now. Please test in the next 10-20 minutes and things should work.
