### ISSUE TITLE
Send Email Feature for use in serverless functions

### ISSUE THREAD

**Issue by tehpsalmist** [nhost/nhost#1596]
**Is your feature request related to a problem? Please describe.**
I need to send emails and nhost already has and is using my smtp creds.

**Describe the solution you'd like**
I'd love to be able to leverage a simple function in my serverless functions that would send an email using the functionality already present in nhost.

```js
import { sendEmail } from '@nhost/email'

const err = await sendEmail({
  to: 'newuser@gmail.com',
  subject: 'Welcome',
  body: '<p>welcome...</p>',
  ...otherPropsAsNecessary
})
```

**Describe alternatives you've considered**
re-building the email capability myself (again....). I've done this in a few projects already and I'm just tired of it lol...

**Additional context**
I'm assuming this feature wouldn't be that hard, since emails are already being sent from nhost using the credentials we've already provided to them. Of course, we'd only want to expose this api in a server-side context...

**Comment by elitan** [comment]
We could expose the SMTP credentials as environment variables for functions.

Then you can send emails via SMTP. Here's an example: https://github.com/nhost/nhost/blob/main/examples/serverless-functions/functions/send-email/index.ts

**Comment by pkreipke** [comment]
@elitan Is this now possible? It's be pretty awesome to use small projects for transactional emails.

For example, I feel like sending the magic link email this way would be useful. There's a hook in the API named `useSigninEmailPasswordless` which seems like it's for handling the magic link. I can't find (or misunderstand) whether I can generate the magic link from a function/backend. Let's say I want to invite someone to join a team for example.

**Comment by dbarrosop** [comment]
We don't expose SMTP credentials automatically and we don't have plans for it. However, as this is a feature that would only work with users with custom SMTP settings, you should be able to add them as environment variables yourself and follow the example provided previously.

I am closing this issue as I don't think there is anything that needs to be done here but feel free to reopen if you feel otherwise.
