### ISSUE TITLE
React Native Expo for ios/web fails with 'Module parse failed' when using @nhost/nhost-js 1.13.2

### ISSUE THREAD

**Issue by beepsoft** [nhost/nhost#1607]
Here's a repo to reproduce the error:

https://github.com/beepsoft/nhost-js-expo-web-problem2

When using the `@nhost/nhost-js` (1.13.2) in vanilla React Native Expo 46 or above for web  starting the app fails with an error like this in the web console:

```
wrapNativeSuper.js:31 Uncaught Error: Module parse failed: Unexpected token (285:143)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
| }
> const G = typeof window < "u", K = /* @__PURE__ */ new Map(), Pe = (s) => G && typeof localStorage < "u" ? localStorage.getItem(s) : K.get(s) ?? null, Ce = (s, e) => {
|   G && typeof localStorage < "u" ? e ? localStorage.setItem(s, e) : localStorage.removeItem(s) : e ? K.set(s, e) : K.has(s) && K.delete(s);
| }, Ne = (s, e) => {
    at ./node_modules/@nhost/hasura-auth-js/dist/index.esm.js (wrapNativeSuper.js:31:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at Module.<anonymous> (index.esm.js:1:1)
    at ./node_modules/@nhost/nhost-js/dist/index.esm.js (index.esm.js:250:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (App.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
./node_modules/@nhost/hasura-auth-js/dist/index.esm.js	@	wrapNativeSuper.js:31
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
(anonymous)	@	index.esm.js:1
./node_modules/@nhost/nhost-js/dist/index.esm.js	@	index.esm.js:250
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
./App.tsx	@	App.tsx:1
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
./node_modules/expo/AppEntry.js	@	AppEntry.js:1
__webpack_require__	@	bootstrap:789
fn	@	bootstrap:100
1	@	log.js:59
__webpack_require__	@	bootstrap:789
(anonymous)	@	bootstrap:856
(anonymous)	@	bootstrap:856
```

To reproduce the error:

```
1. yarn
2. yarn web
```

App startup fails with the error above displayed in the browser's console.

It also fails with `yarn ios`, so nhost is pretty much not usable in Expo at all.

When using 

```
    "expo": "45.0.8",
```

it works, starting from expo 46 it does not. 

This error looks similar to this older one, which has been fixed and worked so far: https://github.com/nhost/nhost/issues/275

**Comment by pkreipke** [comment]
This may not help since I'm still using expo v44 and @nhost/react v0.12.0 for a bit longer before tackling upgrades. I looked at your repo quickly and just have these thoughts. YMMV.... 

- I'm not sure from the snippet you posted that `window` is the issue but I whenhad a problem with the `window` global I found this workaround from somewhere online worked for me:

```
const prevWindow = window
window = undefined;

export const nhost = new NhostClient({
	subdomain: <your-subdomain>,
	region: 'us-east-1',
	// ... clientStorage etc
})

window = prevWindow

```

- just making sure: are you expecting the new Hermes engine to be on or off? Maybe be explicit in `app.json` to eliminate possible compatibility problem?

- you're testing a React app but using `@nhost/nhost-js` and not `@nhost/react`. I wonder if switching to the React version would help.

**Comment by beepsoft** [comment]
@pkreipke, thanks for the tips!

I also used v44 and it worked all right, but `@nhost/nhost-js` doesn't work with newer versions.

The window thing didn't help. I wonder how it fixed for you, what could be the connection with this problem, which seems to be some packaging or transpilation problem.

I also don't think the issue is related to Hermes as it also happens when running expo web. When Hermes is turned off, the error still happens. It is different from the web one, though:

```
 ERROR  TypeError: Ge.create is not a function. (In 'Ge.create({
        baseURL: s
      })', 'Ge.create' is undefined)
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

And yes, I use `@nhost/nhost-js` client directly in my app.

@plmercereau do you have any idea what could be the problem here?

**Comment by beepsoft** [comment]
I just checked that under `"expo": "~47.0.12"` the last working `nhost-js` version is

```
    "@nhost/nhost-js": "1.7.0",
```

and it starts to break with

```
    "@nhost/nhost-js": "1.12.0",
```

**Comment by beepsoft** [comment]
It might be related to this expo bug: https://github.com/expo/expo/issues/19677

**Comment by beepsoft** [comment]
Based on the tip in https://github.com/expo/expo/issues/19677#issue-1421754824 a good workaround is to add a `webpack.config.js` to the project like this:

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: [
          "@nhost/hasura-storage-js",
          "@nhost/hasura-auth-js"
        ],
      },
    },
    argv
  );
  return config;
};
```

This will cause the offending nhost libs to get it transpiled just like any other source code in the expo project itself.

This may worth be added to the nhost documentation.

I guess we can consider it a bug of expo, so I close this issue for now.
