### ISSUE TITLE
[Feature Request] Add information about presignedUrls and image transformations

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#1619]
**Is your feature request related to a problem? Please describe.**
Currently the https://docs.nhost.io/storage#image-transformation covers how to resize public URLs. How do users deal with image-transformations and presigned URLs?

**Describe the solution you'd like**
I'd love to resize user images which are in need of presigned URLs

**Describe alternatives you've considered**
I use the presigned URL but after resizing the image error messages show up similar like
```
{"error":{"message":"signature already expired"}}
```

**Comment by viktorfa** [comment]
Presigned urls don't support resizing or image transformations at the moment. 

https://github.com/nhost/nhost/issues/1430
https://github.com/nhost/hasura-storage/issues/104

**Comment by dbarrosop** [comment]
this is now supported, if someone wants me to update their cloud version DM me or drop me an email with your subdomain
