### ISSUE TITLE
trying working locally

### ISSUE THREAD

**Issue by morandalex** [nhost/nhost#1633]
Hello guys, I installed nhost locally and I have a question. When you run the dashboard there are some sections disabled. How to activate them ?
![image](https://user-images.githubusercontent.com/9484568/219797771-3f391dfc-17f1-4848-99cc-c2a4bf7f4a11.png)

**Comment by elitan** [comment]
Those sections are not available in the local version.

- Functions: This has been replaced by Logs. Maybe you're running an old version?
- Deployments: Handled by the Nhost Cloud infrastructure.
- Backups: Handled by the Nhost Cloud infrastructure.
- Logs: Use `nhost logs -f` locally.
- Settings: Use `nhost/config.yaml` locally.

**Comment by bigzhu** [comment]
is authentication work in local version? @elitan
