### ISSUE TITLE
[deployment] 502 Bad Gateway

### ISSUE THREAD

**Issue by doooooooooots** [nhost/nhost#1636]
**Describe the bug**
<img width="750" alt="Capture d’écran 2023-02-19 à 08 22 22" src="https://user-images.githubusercontent.com/91453739/219934946-e344e67c-698a-4225-bad7-8764309a0e3d.png">

<img width="750" alt="Capture d’écran 2023-02-19 à 08 29 19" src="https://user-images.githubusercontent.com/91453739/219935009-9d79749a-d452-4ad2-866c-ebf25e7ad5c3.png">

I'm having some random 502 Bad Gateway errors on deployments, even if it works perfectly locally.
I can't figure where it's coming from.

Big problem with screenshot #1 is that Hasura schema is up to date with the errored deployment.

**To Reproduce**
1. I don't know

**Expected behavior**
Not having error | Having a much comprehensive message

**Screenshots**
See above

**Desktop (please complete the following information):**
It's working locally

**Smartphone (please complete the following information):**
--

**Additional context**
--

**Comment by elitan** [comment]
My theory is that you have a lot of migrations and metadata that consume too much memory when they are applied, which causes Hasura to get [OOM killed](https://neo4j.com/developer/kb/linux-out-of-memory-killer/).

Do you see anything in the logs, specifically Hasura logs, while deploying?

**Comment by doooooooooots** [comment]
Yes, I get OOM killed.
Like Hasura logs says "Killed"  😅

What I don't understand is why does this happens during the step "reloading metadata", and not during first apply.

Also, when Hasura respawns about 10s after, migration & metadata are well applied.
At the end, nhost deployment has failed (and is marked as failed in the dashboard), but my database schema and GQL APi are updated, resulting in a very fuzzy state where nhost and Hasura are not agreeing 😶‍🌫️ .

I patched the problem with a creaky process where I: 
1. Export local metadata in JSON format using Hasura Metadata API
2. Delete public metadata in nhost folder
3. Push to github / deploy with nhost action
4. Send JSON metadata to Hasura using Metadata API
... which is terrible.

I also thought to chop my database and use federation, but it seems that in production, you set HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS to true, as permission on remote schema are enable even if Hasura says it is disabled by default.

> ENABLE REMOTE SCHEMA PERMISSIONS
Remote Schema permissions are not enabled by default.
>
>To enable them, you will have to run the GraphQL Engine either with the server flag --enable-remote-schema-permissions or environment variable HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS set to true.
>
>When Remote Schema permissions are not enabled, all Remote Schemas are considered to be public entities, i.e. all roles will have unrestricted access to the Remote Schemas. Once enabled, access to Remote Schemas will be restricted for all roles (other than admin) unless explicit permissions for the Remote Schema fields are granted to the roles.
https://hasura.io/docs/latest/remote-schemas/auth/remote-schema-permissions/

Maybe here is not the right place to ask this question, but does the paid plan allows more memory?

**Comment by doooooooooots** [comment]
![Capture d’écran 2023-02-23 à 09 10 37](https://user-images.githubusercontent.com/91453739/220852925-8c5f6b88-c202-4309-a17e-3c71f7528b4b.png)

**Comment by elitan** [comment]
Yes, you get more memory (and CPU) on the Pro plan. We're also working on custom resource allocation plans.

**Comment by elitan** [comment]
If you need more resources that what's on the Pro plan, then you can reach out to us via [Discord](https://nhost.io/discord) or email: johan@nhost.io and we'll help you with a bigger plan until we have this feature in our dashboard.

**Comment by doooooooooots** [comment]
I can confirm you that migrations are ok with pro plan. 
We are starting to migrate more tables, so I won't hesitate to reach out to you soon.
Thanks for this amazing work.

**Comment by elitan** [comment]
Perfect!
