### ISSUE TITLE
how to develop on personal smtp mail server?

### ISSUE THREAD

**Issue by morandalex** [nhost/nhost#1654]
the local deployment is using mailhog and it works fine. But I would like to use mailgun for testing purposes.
What  should  I  do in order to config correctly?

**Comment by elitan** [comment]
It's not something that's documented, but you should see SMTP settings in your `nhost/config.yaml` file:

![CleanShot 2023-02-22 at 18 31 50](https://user-images.githubusercontent.com/331818/220708797-cad5adcf-16b6-46e6-993c-b46cc57d514e.png)


We're working on a new configuration setup that will make this much easier in the future: https://github.com/nhost/cli/pull/597
