### ISSUE TITLE
[Error] Local development uploading image through dashboard not working

### ISSUE THREAD

**Issue by abarcod** [nhost/nhost#1657]
**Describe the bug**
Local development uploading file through dashboard ist not working.
Getting a 403 error.

**To Reproduce**
1. Setup local enviroment
2. go to storage
3. upload image

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/96572110/220857912-e3bff111-6416-4e7a-8c5c-a8ff84a0755b.PNG)

**Additional context**
CLI: v0.8.23

**Workaround**
Downgrade CLI to v0.8.21

**Comment by szilarddoro** [comment]
Hello @abarcod! The issue has been fixed. Please give it a shot now.

**Comment by abarcod** [comment]
Hello @szilarddoro works great thanks but the cli needs a update to use the new version
