### ISSUE TITLE
unable to run nhost project locally in windows 10 

### ISSUE THREAD

**Issue by chandhuDev** [nhost/nhost#1682]
**Describe the bug**
When I try to run the nhost website locally with the command "nhost up" for development , getting an error while starting the functions .

**To Reproduce**
1. Clone the forked nhost repo locally 
2. Install nhost cli and login
3. Install the desired nhost project and navigate to that project directory
4. Run the command nhost up (installed git and docker running succesfully)

**Expected behavior**
Expected to run the selected nhost project run locally without any error

**Screenshots**

![Screenshot (207)](https://user-images.githubusercontent.com/106800538/221844316-47339805-6e61-49a1-ba42-33e17c618bd2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser : Brave
 - nhost cli version : v0.8.23 for linux-amd64
 - docker version :version 20.10.22, build 3a2c30b

**Comment by yibum** [comment]
Was it running inside WSL?
