### ISSUE TITLE
Ordered lists appear as unordered lists

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#169]
Even when numbered lists used in the documentation, there is no numbering used for the rendered lists. The HTML gets the right tag (ol) but the wrong list-style is set for ol and/or li in CSS.

![image](https://user-images.githubusercontent.com/331818/153859388-78274e83-0df8-4952-a565-255d6b312ad7.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @elitan Can I fix this please?

**Comment by elitan** [comment]
> Hey @elitan Can I fix this please?

Sure!
