### ISSUE TITLE
Unable to start React app based on babel error from nhost/hasura localstorage

### ISSUE THREAD

**Issue by wollerman** [nhost/nhost#1696]
**Describe the bug**
Previously had a running React app with expo. After adding `nhost` dependencies and running `yarn web` I'm now seeing a failure related to babel loader and localstorage.

**To Reproduce**
1. create an expo template (e.g. `npx create-expo-app --template bare-minimum`
2. `yarn add @nhost/react graphql`
3. `yarn`
4. `yarn web`

**Expected behavior**
The app starts and loads nhost correctly.

**Screenshots**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/1610241/222433200-a48f72af-dddc-4c69-86ea-8002e5a03a58.png">

**Desktop (please complete the following information):**
 - OS: mac OS Monterey
 - Browser: Chrome

**Additional context**
I may just need a babel plugin, but I can't seem to pick the right magic combination to allow webpack to parse hasura-auth-js correctly. Copy of the error in text for better searchability:
```
index.esm.js:116 Uncaught Error: Module parse failed: Unexpected token (285:143)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
| }
> const M = typeof window < "u", x = /* @__PURE__ */ new Map(), be = (n) => M && typeof localStorage < "u" ? localStorage.getItem(n) : x.get(n) ?? null, Oe = (n, e) => {
|   M && typeof localStorage < "u" ? e ? localStorage.setItem(n, e) : localStorage.removeItem(n) : e ? x.set(n, e) : x.has(n) && x.delete(n);
| }, Pe = (n, e) => {
    at ./node_modules/@nhost/hasura-auth-js/dist/index.esm.js (index.esm.js:116:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
```

Any help would be greatly appreciated!

**Comment by szilarddoro** [comment]
Hi there! We are aware of this issue. It's unfortunately out of our control.

Please refer to this discussion for further information on how to solve it temporarily:
https://github.com/nhost/nhost/issues/1607

Let me know if that solves your issue.

**Comment by wollerman** [comment]
Ah thanks, I missed that one because it was closed. I can close this and follow those steps and watch the expo thread as well. Thanks!
