### ISSUE TITLE
Typography is inconsistent

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#170]
Lists, tables and paragraphs have different font sizes and font weights.

All article content should use the same default font sizes. Whether body text is inside a table or list, shouldn’t matter.

https://www.figma.com/file/HeY5eaAADnye0P7A7K7PIZ/Nhost-screens%3A-Docs?node-id=0%3A1

<img width="1440" alt="Screenshot 2021-12-07 at 13 30 58" src="https://user-images.githubusercontent.com/331818/153861293-09d0ba0b-ded2-4e00-b56f-fcb8c24a5e0c.png">

**Comment by szilarddoro** [comment]
Table components still suffer from this issue.
