### ISSUE TITLE
Nhost docker-compose Dashboard not working on VPS machine – may be its backend path is not being updated from localhost to server IP

### ISSUE THREAD

**Issue by rizvanhaider** [nhost/nhost#1701]
**Describe the bug**

Nhost docker-compose Dashboard not working on VPS – may be its backend path is not being updated from localhost to server IP

**To Reproduce**

I installed the nhost backend on my VPS by this command. 

```
git clone https://github.com/nhost/nhost
cd nhost/examples/docker-compose
cp .env.example .env
docker-compose up -d

I modified the docker-compose.yaml by replacing localhost with my IP.
```
After all services are up i tried to access the dashboard with http://{{myip]}:3030
but it was not loading properly because in network it was using localhost:1337/v1/auth/healthz calls which were failing.
May be it will work when it will use http://{{myip}}:1337/v1/auth/healtz

I tried opening other endpoints which were working fine

- http://myip:1337/v1/graphql: Hasura GraphQL endpoint

- http://myip:1337/v1/auth: Hasura Auth

- http://myip:1337/v1/storage: Hasura Storage
 
- http://myip:1337/v1/functions: Functions

- http://myip:1337: Hasura Console

- http://myip:8025: Mailhog SMTP testing dashboard

- http://myip:9090: Traefik dashboad

but for when i try to open http://myip:3030 to access Nhost Dashboard its failing.

**Expected behavior**
I expect that dashboard should open as hasura console is also working properly 

**Screenshots**
![image](https://user-images.githubusercontent.com/9403438/222695676-e61978d1-8c88-41d9-845d-b4caf228381e.png)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04
 - Browser: chrome

**Additional context**
I think there should be an environment variable for dashboard in docker-compose file to pass as host for backend.

**Comment by FNG-2002** [comment]
I have the same issue. Did you fix it?

**Comment by szilarddoro** [comment]
Hey there! We have made some changes to the dashboard recently and in an upcoming release, it's going to be possible to configure service URLs through environment variables (such as `NEXT_PUBLIC_NHOST_AUTH_URL`, `NEXT_PUBLIC_NHOST_GRAPHQL_URL`, etc.).

You can take a look at this again once this PR is released:
https://github.com/nhost/nhost/pull/1716

**Comment by FNG-2002** [comment]
Thanks, I will try it later. Will the docker-compose file be updated to the current version of nhost:dashboard too? At the moment the version listet is 0.7.4

**Comment by szilarddoro** [comment]
Oh, that's true. I'll fix it.

**Comment by szilarddoro** [comment]
Actually, we decided to remove it from the docker-compose example for now, because of certain limitations we need to tackle in the future.

It's going to be removed in this PR: https://github.com/nhost/nhost/pull/1703

**Comment by szilarddoro** [comment]
You can use individual URLs for every service. See the detailed list here: https://github.com/nhost/nhost/blob/main/dashboard/README.md#enable-local-development

I'll close this issue but feel free to ping me if you get stuck at some point.

**Comment by FNG-2002** [comment]
Thank you very much @szilarddoro. I tried to get it working but I think you also need to update the docker-compose example inside nhost/examples/docker-compose/. I get the same error still. I tried to copy the envs from https://github.com/nhost/nhost/blob/main/dashboard/README.md#enable-local-development to the .env in the docker example. There are also some files I don't know if I need them. e.g the config.yaml still contains the local endpoint localhost:1337. I would appreciate an updated doc on how to self host out of the box (if that makes sense).

Thanks for all your work ^^

**Comment by szilarddoro** [comment]
Yeah, we don't have too much documentation for self-hosting. We'll talk about this internally and see how we can prioritize things. Thanks for your patience! 🙏🏼

In the meantime, could you please update the Dashboard's version in the docker-compose example you downloaded/forked to `0.13.3`? The environment variable-related changes have been introduced in a more recent version of the Dashboard. As I mentioned, we will most likely remove the Dashboard from the example for a while, because we need to add extra functionality to it to make it truly "self-hostable".

**Comment by zuohuadong** [comment]
@szilarddoro Has it made any progress?

**Comment by R3flector** [comment]
Still not work?

**Comment by szilarddoro** [comment]
Sorry, I somehow missed the recent updates to this issue. Could you please share some info with me where you got stuck with the setup?

**Comment by jpoles1** [comment]
I'm trying to get setup with docker self-hosted myself, but running into the same issues as above!
