### ISSUE TITLE
createServerSideClient still takes backendUrl

### ISSUE THREAD

**Issue by trflagg** [nhost/nhost#1707]
I'm trying to use `createServerSideClient` from the `nhost/nextjs` package, but it still takes `backendUrl` as a string which is no longer supported.

What should I pass in for `backendUrl` since I'm only given `region` and `subdomain`?

**Comment by szilarddoro** [comment]
We need to adjust the implementation of `createServerSideClient` to support additional parameters such as `subdomain`, `region`, or per-service URLs. I don't think there is a workaround for this problem other than creating a function [similar to our `createServerSideClient`](https://github.com/nhost/nhost/blob/99fcc36250b74995157b98c1416800c74a4b152a/packages/nextjs/src/create-server-side-client.ts#L23) that would accept these parameters.
