### ISSUE TITLE
View Invoices in the Stripe Customer Portal not working

### ISSUE THREAD

**Issue by dbj** [nhost/nhost#1715]
**Describe the bug**
When I click on the "View Invoices in the Stripe Customer Portal", a blank window opens.

**To Reproduce**
1. Go to your Nhost dashboard
2. Open a workspace
3. Click on "View Invoices in the Stripe Customer Portal"

An empty window opens with the url `about:blank`.

**Expected behavior**
The stripe customer portal opens.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Device: MacBook Pro
 - OS: Venture 13.2
 - Browser Brave with shields OFF
 - Version 1.48.171

**Smartphone (please complete the following information):**
n/a

**Additional context**
May be related to #1705 ? 
[Also posted in Discord](https://discord.com/channels/552499021260914688/1082352008746520636)

**Comment by szilarddoro** [comment]
Thanks for reporting this issue @dbj! It’ll be fixed in our next SDK release tomorrow.

**Comment by dbj** [comment]
Marvelous!  Thanks. :)
