### ISSUE TITLE
Deprecated backendUrl parameter in getNhostSession function of @nhost/nextjs package should be updated to accept alternative parameters.

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1727]
The `getNhostSession` function in the `@nhost/nextjs` package only accepts the now deprecated `backendUrl`.

I _think_ that the `getNhostSession` should accept either `subdomain`/`region` or individual URLs for each endpoint (graphql / auth / storage / functions).

**Comment by szilarddoro** [comment]
This is related to #1707.
