### ISSUE TITLE
docs: remove deprication notice for axios

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#1728]
We've replaced Axios for Fetch so we should now remove the depreciation notice in our docs here:

![CleanShot 2023-03-10 at 08 08 21](https://user-images.githubusercontent.com/331818/224247564-4ff2850f-358b-4d5f-9a21-09f3b859088e.png)

**Comment by szilarddoro** [comment]
I think we should also remove the `useAxios` property from the SDK. We can release that as a minor bump IMO.
