### ISSUE TITLE
Environment Variables shared between projects?

### ISSUE THREAD

**Issue by simonphughes** [nhost/nhost#1733]
**Describe the bug**
When I create an environment variable in one of my nhost projects (my development project) I set an environment specific value as per the instructions "Environment Variables are key-value pairs configured outside your source code. They are used to store environment-specific values such as API keys." on the page.  When I go into my production project it has the same environment variable defined with the same value. Which means I can't use an environment variable as an environment variable if they are the same across all environments.

**To Reproduce**
Create 2 different nhost projects under the same login.
Add an environment variable to one of the projects
Check the other project and it exists with the same value. 

**Expected behavior**
The second project should not have the environment variable defined in it, they should be able to be different per project.

**Comment by dbarrosop** [comment]
I am afraid I don't understand, environment variables are per project, we don't share them at all between them. I just tried to reproduce myself and couldn't:

<img width="1677" alt="Screenshot 2023-03-13 at 09 06 19" src="https://user-images.githubusercontent.com/6246622/224642293-6def1a9b-4bb8-4cd1-9cf9-7d43483d566f.png">

<img width="1669" alt="Screenshot 2023-03-13 at 09 06 30" src="https://user-images.githubusercontent.com/6246622/224642326-a22a1a8f-e277-45c3-8aad-f989567cb71f.png">

as you can see both projects belong to the same user/workspace and have different env vars.

**Comment by simonphughes** [comment]
Just been trying to replicate and it looks like its actually the browser caching issue. If it hit refresh it does show different values between environments, but was definitely showing the the dev cache version in production .
Thanks
