### ISSUE TITLE
Unable to create workspace and projects in self hosted nhosts

### ISSUE THREAD

**Issue by MercusChan** [nhost/nhost#1734]
**Describe the bug**
We are able to self hosted nhost.
While access http://localhost:3030/
It shows local project and local workspace.
This is unable to create workspace or projects.
![Screenshot 2023-03-12 00:32:21](https://user-images.githubusercontent.com/17057914/224496257-7e755a85-5b06-47f1-8944-479e6148f188.png)

**To Reproduce**
Base on this example
https://github.com/nhost/nhost/tree/main/examples/docker-compose
See steps in **Configuration**

**Expected behavior**
Same as using in nhost cloud. This is freely on create workspace and projects.

**Comment by dbarrosop** [comment]
Workspaces and projects are not part of the nhost stack, they are part of internal systems we built to orchestrate and manage our cloud offering. The nhost stack is comprised of hasura, auth, storage and functions, which you can self-host and orchestrate yourself in any way you want.
