### ISSUE TITLE
Authentication Setting "Disable New Users" can't be changed in Dashboard and setting shows wrong behavior

### ISSUE THREAD

**Issue by losahlmann** [nhost/nhost#1736]
**Describe the bug**
The Authentication setting "Disable New Users" can't be changed in Dashboard, it stays always "on". Moreover, in the "on" position, the setting does not have the expected behavior. New users are not disabled.

**To Reproduce**
1. Go to Dashboard -> Settings -> Authentication
2. Toggle setting for 'Disable New Users'
3. Click 'Save'
4. Refresh page
5. The setting is still "on", toggling and saving had no effect.

**Expected behavior**
The new toggle position should be saved.
When "Disable New Users" is "on", new users should be disabled.

**Nhost Environment:**
This behavior is observed in Nhost.io instances.
Local development instance with the Nhost CLI take the correct setting from config.yaml.

**Comment by szilarddoro** [comment]
Thanks for reporting this issue! It has been introduced recently by a tiny mistake. Should be fixed in our next release.
