### ISSUE TITLE
cannot use hasure's claims_map with NHOST_JWT_SECRET

### ISSUE THREAD

**Issue by xmlking** [nhost/nhost#1738]
I am trying to use setting supported in `HASURA_GRAPHQL_JWT_SECRET` by Hasura like `claims_map` with nHost but I am getting error in the UI

Trying to set this
```json
{
  "type": "HS256",
  "key": "my-secret",
  "claims_map": {
    "x-hasura-allowed-roles": { "path": "$.roles" },
    "x-hasura-default-role": "viewer",
    "x-hasura-user-id": { "path": "$.sub" },
    "x-hasura-org-id":  { "path": "$.org", "default": "public" }
  }
}
```

nHost UI only allow:

```json
{
  "type": "HS256",
  "key": "my-secret"
}
```

**Comment by dbarrosop** [comment]
while the UI doesn't let you set it right now I may be able to set it for you if this is a blocker. Feel free to DM me on discord and I can fix it for you.

**Comment by xmlking** [comment]
@dbarrosop  really appreciate your support. 
just sent you email with JSON I needed for `NHOST_JWT_SECRET` 
it also contain key I am using.
