### ISSUE TITLE
Dead link of blog post about how to approach the building of a multi-tenant application with Nhost

### ISSUE THREAD

**Issue by MercusChan** [nhost/nhost#1739]
NHost have did a great job.

Related to this closed issue:
Unable to create workspace and projects in self hosted nhosts 
https://github.com/nhost/nhost/issues/1734

I found another related issue, this is over 3 years ago.
[nhost/hasura-backend-plus#82 (comment)](https://github.com/nhost/hasura-backend-plus/issues/82#issuecomment-567402385)

May I have the latest link of that blog post for reference?

**Comment by dbarrosop** [comment]
That blog post was lost when we migrating to a new blog system but the accompanying example is here:

https://github.com/nhost/nhost/tree/main/examples/multi-tenant-one-to-many

In any case, multi-tenancy here means sharing one single auth/storage/graphql with many customers, this is not about having many workspaces/projects in self-hosted (like you were asking on the other issue).
