### ISSUE TITLE
Turning off "jit" Postgres extension for better query performance?

### ISSUE THREAD

**Issue by Godefroy** [nhost/nhost#1740]
Hi,
I have been experiencing slow query performances for non-admin users in my Nhost app, even after optimizing indexes. While trying to find a solution, I came across an interesting issue on the Hasura Github page (https://github.com/hasura/graphql-engine/issues/3672) which suggests that turning off the "jit" Postgres extension could help improve query performance.

According to the issue, the "jit" extension (Just-In-Time Compilation) is responsible for dynamically compiling Postgres queries, which could lead to performance degradation for complex queries, especially for non-admin users who may generate more complex queries for permissions.

However, I am not entirely sure if this is the right approach or if there are any potential downsides to turning off this extension.

Therefore, I am writing this issue to gather more thoughts and feedback from the community.
I would appreciate any insights or suggestions on this matter. Thank you 😃

**Comment by dbarrosop** [comment]
This is something we will probably want to allow you to configure in the near future but in the meantime you can connect to postgres and execute `set jit = off;` and see if that helps your case.

**Comment by Godefroy** [comment]
Thank you @dbarrosop 
So I tried `set jit = off;` for a day, but it doesn't seem to help with my performance issue.
I close the issue, feel free to open it if you think it can be useful.

**Comment by dbarrosop** [comment]
@Godefroy feel free to reach out to me via email or dm on discord. I can help you by looking at CPU/Memory metrics.
