### ISSUE TITLE
Creating your app...panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by doooooooooots** [nhost/nhost#1743]
**Describe the bug**
Creating your app...panic: interface conversion: interface {} is nil, not []interface {}
nhost init --remote exit with this error while trying to init a remote project

**To Reproduce**
I simply run nhost init --remote 

**Expected behavior**
App is locally initialized

**Screenshots**
![Capture d’écran 2023-03-16 à 00 08 27](https://user-images.githubusercontent.com/91453739/225463565-915b8a54-7ec9-451f-8012-e687542edf57.png)

**Desktop (please complete the following information):**
 - OS: macOs Monterey 12.3 - MacbookPro M1 2020

**Additional context**

**Comment by phlogios** [comment]
Same bug as https://github.com/nhost/cli/issues/274

**Comment by elephant3** [comment]
Should be fixed in the latest v0.9.1, please upgrade
