### ISSUE TITLE
Functions: ability to apply custom express middleware in dev server

### ISSUE THREAD

**Issue by chrtze** [nhost/nhost#175]
For implementing the stripe webhook (https://stripe.com/docs/webhooks/signatures) that is used to update user payment information in your database, it is required to pass the raw request body to the stripe api.

To achieve this using nhost it would be helpful to have the ability to apply middleware specifically for your serverless functions. This could be done by exposing the `app` object from express for example. Then you could do something like `app.use(bodyParser.raw({type: 'application/json'}))`. 
It could also be specified for the individual route like this:
```app.all('/my-stripe-webhook', bodyParser.raw({type: 'application/json'}), (req, res) => {....})```

In nextjs this is possible with a custom config object: https://nextjs.org/docs/api-routes/api-middlewares#custom-config

I am not sure which implications this would have for the production function which would also need to handle the custom configuration.

https://github.com/nhost/cli/blob/71f080b213b83c5fbfbbd159ee815ef7ff342e5f/functions/functions.go#L78

`app.all('%s', func);` -> `app.all('%s', customMiddleware,func);`

**Comment by elitan** [comment]
I think the solution described here solves this problem: https://github.com/nhost/nhost/discussions/770
