### ISSUE TITLE
Discord's authorization "Redirect URL" setting was wrong 

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#1750]
In setting up the Discord Sign-In method, _app.nhost.io_ offers the following for a Redirect URL as the valid redirect to enter into Discord:

`https://aiknxspnotwfqxepmrqx.auth.us-east-1.nhost.run/v1/signin/provider/discord/callback`

But, in practice, my app called Discord with the following redirect_uri:

`https://aiknxspnotwfqxepmrqx.nhost.run/v1/auth/signin/provider/discord/callback`

I added this second URL to Discord, and the authorization proceeded as expected.  So, I suspect "region" should be removed from the Redirect URL field?

**Comment by nunopato** [comment]
@mainstreetmark you can find more info on the deprecated DNS name here https://github.com/nhost/nhost/discussions/1319. If you haven't, please make sure to follow the instructions there.

**Comment by szilarddoro** [comment]
I assume the issue has already been fixed. Please reopen if the issue persists.
