### ISSUE TITLE
isAuthenticatedAsync throws: "The state machine is not yet ready after 15 seconds." (expo react-native)

### ISSUE THREAD

**Issue by seyaobey-dev** [nhost/nhost#1755]
**Describe the bug**
In expo react-native app, I am using the method `isAuthenticatedAsync` to check user is authenticated. The method hangs and then fails with above error.

**To Reproduce**
Here is a github repo where this behaviour is observed:
https://github.com/paygroup/nhost-app
1. First download and install the "Expo Go" app in a physical mobile device (https://expo.dev/client)
2. git clone this repository
3. yarn install
4. yarn start
5. Observe that the call to `isAuthenticatedAsync` hangs and fails with above behaviour

**Expected behavior**
`isAuthenticatedAsync` should complete quickly and return status

**Screenshots**
![image](https://user-images.githubusercontent.com/83374925/226335780-f9646f6b-c83a-41b2-9c7e-86b93f035804.png)

**Smartphone (please complete the following information):**
 - Device:iPhone 11
 - OS: iOS 16.2

**Additional context**
```
  "dependencies": {
    "@nhost/react": "^2.0.11",
    "@types/react": "~18.0.27",
    "expo": "~48.0.6",
    "expo-constants": "~14.2.1",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.2.2",
    "expo-secure-store": "~12.1.1",
    "expo-status-bar": "~1.4.4",
    "native-base": "^3.4.28",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-web": "~0.18.10",
    "typescript": "^4.9.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
```

**Comment by szilarddoro** [comment]
Could you please try to use the [`useAuthenticationStatus`](https://docs.nhost.io/reference/react/use-authentication-status) hook instead?

**Comment by seyaobey-dev** [comment]
@szilarddoro I used it: same behaviour

**Comment by szilarddoro** [comment]
I tried to run your example and I don't see this error:

<img width="1218" alt="Screenshot 2023-03-20 at 13 34 40" src="https://user-images.githubusercontent.com/310881/226340195-d0a25644-72f4-46c5-940c-febad6af3ceb.png">

I didn't change anything in your implementation, although, your repository contains two lock files (`yarn.lock` and `package-lock.json`). You want to keep only one of them, then try to reinstall the dependencies.

**Comment by seyaobey-dev** [comment]
@szilarddoro At first, in my case, all worked well. The error started appearing after a few restarting the app. This error has also appeared on android app in production

**Comment by seyaobey-dev** [comment]
@szilarddoro I had a look at the `nhost` source code to try to understand why I'm getting this error. In the source code, in the `hasura-auth-client.ts`, the method `waitUntilReady` with `TIMEOUT_IN_SECONS = 15` throws this error when it does not complete. Digging further, it seems that `nhost` hangs when trying the refresh token when starting.
I just want to know what could cause it to hang some times

**Comment by szilarddoro** [comment]
It's hard to tell why it hangs. My two naive guesses would be bad network quality or an issue with the backend services. Have you checked your Nhost project's logs?

**Comment by seyaobey-dev** [comment]
Thanks for the tip. I looked at the log. I'm not sure what this means, but I'm seeing a lot `500` errors:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/83374925/226350159-558fdea1-6cd9-4e01-92c1-71a6634abae7.png">

My network is fine. All other calls work just fine. Only the `nhost` authentication...

**Comment by dbarrosop** [comment]
@seyaobey-dev can you correlate those 500 with `hasura` logs? If you see some `refresh_token_hash` error, could you update your local `cli`, start the project with `nhost dev` and push to git the changes introduced by the nhost cli?

**Comment by seyaobey-dev** [comment]
@dbarrosop How do I "correlate" these errors with `hasura` logs? I'll try to update the local `cli`.
(FWIW I would like to mention that this error is observed also in production, so it may just not be an issue with `nhost dev`)

**Comment by seyaobey-dev** [comment]
@dbarrosop I'm not observing this error when running locally with `nhost dev` (it works fine locally). I'm facing this problem only when I'm connect to my remote repository. (Nevertheless, I'll still try to update my local `cli`)

**Comment by seyaobey-dev** [comment]
Printing here additional logs errors:

```
{"latencyInNs":13000000,"level":"error","message":"POST /token 500 13ms","method":"POST","statusCode":500,"url":"/token"}

{"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"10.110.17.37","method":"POST","status":200,"url":"/v1/graphql"},"operation":{"error":{"code":"validation-failed","error":"field 'refreshTokenHash' not found in type: 'authRefreshTokens_bool_exp'","path":"$.selectionSet.authRefreshTokens.args.where._and[0].refreshTokenHash"},"request_id":"d8815574-5a6f-4b24-b774-cc5a0c9dbc07","request_mode":"error","response_size":189,"uncompressed_response_size":189,"user_vars":{"x-hasura-role":"admin"}},"request_id":"d8815574-5a6f-4b24-b774-cc5a0c9dbc07"},"level":"error","timestamp":"2023-03-20T11:45:39.148+0000","type":"http-log"}
```

**Comment by dbarrosop** [comment]
That make sense, could you do what I suggested?

1. update your nhost cli
2. start it with `nhost dev`
3. At this point you will see some changes to the metadata, commit and push them to github
4. wait for the deployment and try again

**Comment by seyaobey-dev** [comment]
@dbarrosop I upgraded the `nhost cli` and ran `nhost dev` as you suggested. This, indeed, changed the metadata which I then push to github (which triggered a new production deployment). Unfortunately, I'm observing the same behaviour: I'm getting the same error: `The state machine is not yet ready after 15 seconds.` when I run the `isAuthenticatedAsync` method (same error even when I use the hook version)

**Comment by dbarrosop** [comment]
what do the logs say? are you still seeing `500` errors in hasura-auth service? what about hasura logs, any errors there?

**Comment by seyaobey-dev** [comment]
I'm not seeing the `500` errors any more in the `hasura-auth` logs. 
But I'm still getting this error with above method in production with android device. I'm generating a new production build and see if there were some messed up updates...

**Comment by seyaobey-dev** [comment]
Unfortunately, the error is still observed with the new build...

**Comment by szilarddoro** [comment]
I have tested it on an old Android device (via Expo Go) and it's working fine there too with your example.

<img width="1114" alt="Screenshot 2023-03-21 at 13 05 05" src="https://user-images.githubusercontent.com/310881/226600858-3695116a-cf6f-4dc4-a9d6-f4d06c2ae791.png">

Is there anything else you can share about your application?

**Comment by seyaobey-dev** [comment]
Here is my `Sentry` output. [Sentry](https://docs.sentry.io/) is a platform to track bugs on mobile devices at runtime:

![image](https://user-images.githubusercontent.com/83374925/226614983-b9e4d84f-c5a0-41d7-bf55-c47dbdcf9fe0.png)
