### ISSUE TITLE
Questions about examples/docker-compose

### ISSUE THREAD

**Issue by perfalle** [nhost/nhost#1767]
Hi,
I was looking at the docker-compose.yaml (main branch) and I wonder:

- Do lines 24-25 imply, that postgres database can be accessed publicly via port 5432?
This is not mentioned in the README and I guess it should be secured by tls, or in this case just opened internally, e.g. with the expose keyword.
- What are these traefik middlewares?
strip-auth@docker in line 70
strip-suffix@docker in line 99
strip-functions@docker in line 107
They are not mentioned in the traefik docs, where do they come from?
https://doc.traefik.io/traefik/middlewares/http/overview/
The internet does only know these names from this repo, apparently.

**Comment by dbarrosop** [comment]
> Do lines 24-25 imply, that postgres database can be accessed publicly via port 5432?

No, it means it will be accessible from the host machine. Whether that means that it is also public or not it will depend on your network configuration.

Re TLS, agreed. If you are planning on self-hosting you should do that. If you are planning to use our cloud version that is already in place.

> What are these traefik middlewares?

The lines you are referring only assign middleware configuration to the endpoint. The actual middlewares are a couple of lines above. For instance:

```traefik.http.middlewares.strip-auth.stripprefix.prefixes=/v1/auth```
https://doc.traefik.io/traefik/middlewares/http/stripprefix/

Keep in mind this is just an example for you to get started, nothing else. You are free to scrap it and do you own or change at will or even use a different orchestration system other than docker-compose.

**Comment by dbarrosop** [comment]
Closing as there isn't any actionable item here but feel free to comment/ask if you have more doubts.
