### ISSUE TITLE
jwt is attached to uselazyquery but not with usequery

### ISSUE THREAD

**Issue by ankur1163** [nhost/nhost#1776]
**Describe the bug**
I have very strange error. I am using apollo. On component load, i use usequery to fetch orders. It fails and gives me this error 

```
{
  "errors": [
    {
      "extensions": {
        "code": "validation-failed",
        "path": "$.selectionSet.order"
      },
      "message": "field 'order' not found in type: 'query_root'"
    }
  ]
}
```
Then i tied it to a button and used same query with uselazyquery. This time it worked and i got results. 
this is my query 
```
const GET_ORDERS = gql`
  query getorders {
    order(limit: 10, order_by: { createdAt: desc }) {
      id
      clientMobileNumber
      status
      price
      displayName
    }
  }
`;
```

On checking, i found out that jwt is not attached with usequery queries, but jwt is attached with uselazyquery. 
https://prnt.sc/-lCo7MyTKcvg

https://prnt.sc/2u451ie2P2o-
**To Reproduce**
what sort of bug is this?

**Comment by szilarddoro** [comment]
Could you please share a few details about your app so I can reproduce the issue you're experiencing?
