### ISSUE TITLE
`nhost init --remote` does not pull down settings set in nhost console/dashboard

### ISSUE THREAD

**Issue by darrow97** [nhost/nhost#1791]
**Describe the bug**
The `nhost/config.yaml` file does not reflect the settings set via the nhost console/dashboard.
For example, if I have `Require Verified Emails` unchecked (aka, set to False), the `config.yaml` file will indicate that setting as being set to True.

**To Reproduce**
1. In an nhost project dashboard, go to Settings -> Sign-In Methods -> Email and Password
2. Make sure `Require Verified Emails` is unchecked
3. Open a terminal from the directory where the local instance/development of the project altered in Step 1 is kept
4. Make sure `nhost/` and `.nhost/` directories have been removed from the project directory
5. Run `nhost init --remote`
6. Select the nhost project that was altered in Step 1
7. Check the new `nhost/config.yaml` file
     1.  `signin_email_verified_required` will be set to True instead of the expected False

**Expected behavior**
`nhost init --remote` produces a `config.yaml` file that reflects the state of the nhost dashboard

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave
 - Version 1.45.127

**Smartphone (please complete the following information):**
N/A

**Additional context**
nhost cli information : Nhost CLI v0.9.4 for linux-amd64

**Comment by dbarrosop** [comment]
This isn't currently supported but [good timing] we will be announcing something related to this very soon.

**Comment by dbarrosop** [comment]
Sorry for the late response but this is already supported.
