### ISSUE TITLE
Local stack browser auth uses non-existant URL

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1809]
**Describe the bug**

I am attempting to help someone get set up with their nhost app, but am having trouble getting their local host app running on my machine.

Both of us have the latest `nost` cli (version: `Nhost CLI v0.9.4`)

**To Reproduce**
1. Friend has created the nhost app
2. I copy their repo, `nhost link` the app
3. Attempt to start the local stack `nhost dev`

```
URLs:
- Postgres:		postgres://postgres:postgres@local.db.nhost.run:5432/postgres
- Hasura:		https://local.hasura.nhost.run
- GraphQL:		https://local.graphql.nhost.run/v1
- Auth:			https://local.auth.nhost.run/v1
- Storage:		https://local.storage.nhost.run/v1
- Functions:		https://local.functions.nhost.run/v1
```

So these URLs have changed since I last used it, and I cannot find any documentation about it. But the nhost stack starts up.

But when the local browser app is setup, with the latest `@nhost/nhost-js` module, signing up doesn't work. Client `nhost` config:

```js
export const nhost = new NhostClient({
    subdomain: "localhost",
  })
```

The signup call is:

```js
await nhost.auth.signUp({
      email,
      password,
    })

```

However, the auth call is going elsewhere:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/260221/229605120-bf868f2f-a464-4f5e-9fcf-fbc20659aae9.png">

The URL does not match the above nhost URLs. Setting them directly in the client (e.g. with `authUrl` does not change the URL for the auth call).

So I am confused as to why the local browser nhost client wants to talk to a URL that does not match the local stack URLs

**Expected behavior**

Sign up with the example stack works locally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac and linux

**Comment by viktorfa** [comment]
I couldn't make the switch from using `subdomain: "localhost"` to `subdomain: "local"`, but it works for me after upgrading the cli to version `Nhost CLI v0.9.6 for linux-amd64`.

**Comment by dbarrosop** [comment]
To use `local` make sure you are running latest sdk version, if that doesn't work create a new issue, please.

As @viktorfa suggested, 0.9.6 has backwards compatibility so both the old domains and new ones should work. However, I'd suggest making sure you migrate to the new behavior as we will remove support for the old ones eventually.

**Comment by dionjwa** [comment]
Ok, got it. Upgrading the CLI seemed to work now 👍🏻 thank you

**Comment by szilarddoro** [comment]
I'll close this issue because the original problem seems to have been resolved. We will add a short migration guide to the docs to avoid issues like this in the future. Feel free to leave a comment if something is still wrong with the CLI or the SDK.
