### ISSUE TITLE
Console admin

### ISSUE THREAD

**Issue by pedromontanes** [nhost/nhost#1814]
I want to create users in my front, if I use the function useSignUpEmailPassword it doesn´t allow me because I am singin.

I there any function to do it??

**Comment by szilarddoro** [comment]
You were trying to use the correct function to sign up users.

Based on the hook you mentioned, I presume you're using the React or Vue library. Have you tried looking at the [Tutorials](https://docs.nhost.io/quickstarts/react) we have? If yes, then please share more details about the issue you experienced (console errors, etc.).

**Comment by pedromontanes** [comment]
Hi Szilárd,
We use signUpEmailPassword()
We are using vue and the problem is that we want to manage users in our
front, for create a user the error is :
User is already signed in
Status 20
we need to be signed in to make new users... because we are inside an admin
user crud.

Pedro Montañés Albertí
***@***.***
+34 606 326 612
motivales.com

**Comment by szilarddoro** [comment]
Sorry, I didn't understand how you wanted to register users at first, but I think I get it now. So you are building an admin portal where you want to register users into your application, is that correct?

Managing users should be done via GraphQL instead. As an administrator, you have access to mutations such as `insertUser` / `updateUser` and `deleteUser`.

`useSignIn...` and `useSignUp...` hooks should be used for single users only.

```ts
import { gql, useMutation } from '@apollo/client'

const INSERT_USER = gql`
  mutation insertUser($user: users_insert_input!) {
    insertUser(object: $user) {
      id
    }
  }
`

function UsersPage() {
  const [insertUser] = useMutation(INSERT_USER)
  
  async function addUser() {
    await insertUser({
      variables: { user: {...} }
    })
  }
  
  return <div>...</div>
}

```
