### ISSUE TITLE
Non compiled code in releases.

### ISSUE THREAD

**Issue by rikardwissing** [nhost/nhost#1828]
**Is your feature request related to a problem? Please describe.**
Can't fix issues easily.

**Describe the solution you'd like**
Ship your modules with non compiled code. No reason not to, let your users compile the code in the way they want to.

**Describe alternatives you've considered**
Fix the issues in your source. Submit a PR etc etc. But I just want a quick fix for a specific Issue I am facing.

**Additional context**
For instance I want to add a RetryLink to your NhostApolloProvider. This is not easily possible as far as I can tell with your current implementation.

**Comment by rikardwissing** [comment]
Yeah, wasn't sure what you intended with that customLink.

Might I suggest a getLinks function instead that allows you to append  or prepend whatever you wish to your links array instead? Then you can probably just remove customLink and onError.

I could make a PR if you want?

**Comment by rikardwissing** [comment]
I still feel that modules should have non compiled code though. You want to be able to review the code you run.

**Comment by szilarddoro** [comment]
We highly appreciate pull requests, and I'd be happy to review yours if you open one.

As for the non-compiled modules discussion, I'm not sure I follow. What is the difference between reviewing the code on a platform like GitHub vs. reviewing them while it's packaged together with "compiled" (transpiled + minified) code? Could you please give me a few other examples where having the raw source code would help you? I'm happy to convert this part of the issue to a GitHub discussion.

**Comment by rikardwissing** [comment]
If I want to make sure the code isn't doing something malicious for example. Even if the source on github looks good, the release might have code that does malicious things. I'm sure there's been many examples of malicious npm modules over the recent years.

Our project isn't sensitive in any case, so I'm not too bothered by it in this case though. But I do feel it is a real concern.

Another case would be for debugging. I recently had issues with subscriptions losing connections etc that I remember fixing in the old nhost repo. But now there were changes that reintroduced the bug and stuff like that is impossible to debug with a release that has been minified. (It seems you fixed it again recently though)

What's the case for shipping modules minified anyways?

**Comment by szilarddoro** [comment]
I see your point about security, but in my opinion, the "real concern" label applies to the whole NPM ecosystem. You'd still need to verify that the transpiled code is the same as the source code, whether they are being shipped together or not.

It's not necessary to minify them at all, that is something we should change as it makes more sense only if people want to use the UMD bundle.

**Comment by rikardwissing** [comment]
Fair enough.
Btw, is there an easy way to include the `pnpm dev` generated modules in my project for testing purposes?

**Comment by szilarddoro** [comment]
There are a few ways to test development builds:
- You can use the example projects inside the monorepo
- You can publish the packages to a locally running Verdaccio instance
- You can create a symlink to the dist folder in your project which wants to use the dependencies
- You can just copy-paste the output folders

I'd say the last two points are suboptimal but are pretty efficient ways to test small changes quickly.
