### ISSUE TITLE
Custom email templates from the Nhost console rather than CLI

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#1842]
**Is your feature request related to a problem? Please describe.**
It would be great if in the settings section of the Nhost console email templates can be manipulated and updated.

**Describe alternatives you've considered**
The CLI approach bends the functionality to the developer, while updating email messages is not really developer centric. In larger projects the project manager itself would like to make updates himself.

**Comment by dbarrosop** [comment]
Could you elaborate a bit more? Why can't the PM use the cli? What are the expectations here?

**Comment by dohomi** [comment]
The client is non tech, even I'd mention CLI they won't know how to install it. The expectation is similar to update things like SMTP server and all the social media details - it would be great if email responses would be handled inside the settings as well.

**Comment by dbarrosop** [comment]
ok, but if the client is non tech, are you expecting some form of WYSIWG editor? Because if that's the case that's a whole different request IMO. Adding the templates as a setting in the dashboard is one thing, having a fully fledged "no code" solution might be another.

**Comment by dohomi** [comment]
not WYSIWYG on Nhost side. Just a text input where the client can copy paste the email structure either as plain text or html. Most of the time what I've seen on other backend solutions two different textarea fields, one for HTML and one for TEXT for each message.

**Comment by dbarrosop** [comment]
ok, thanks for the clarification
