### ISSUE TITLE
HasuraAuthClient (JavaScript) should have a method to close it

### ISSUE THREAD

**Issue by markelm1** [nhost/nhost#1846]
**Is your feature request related to a problem? Please describe.**
I'm using the JavaScript hasura-auth client in a node-js testing environment. I would want to close it after doing some operations so it doesn't leave the server process hanging but I couldn't find any documented way of doing that.

**Describe the solution you'd like**
A close() method or similar to stop any ongoing connection or process from the client.

**Comment by szilarddoro** [comment]
The Hasura Auth client doesn't maintain any active connection between the client and the backend. It just sends network requests to your backend. Likely, one of the network requests takes a long time to run, so you see that the server process is hanging.

I'm closing this issue now, but feel free to reopen it if you have more details to share.
