### ISSUE TITLE
Allow to switch between nhost clients on runtime.

### ISSUE THREAD

**Issue by hidalgofdz** [nhost/nhost#185]
This might be out of the scope of this package but I noticed that with the current implementation there is no easy way of changing nhost clients on runtime. This might be an edge case but I think it could be useful if someone builds a panel to access all of its nhost applications. Currently, the only way of changing nhost clients is by unmounting and mounting again `NhostAuthProvider`.

If you think this could be useful I could create a PR to address it. 🤔 

PD: I think the same is happening on https://github.com/nhost/react-apollo

**Comment by elitan** [comment]
I'm closing this issue for onw due to inactivity.
