### ISSUE TITLE
No getting progress value when uploading a file using vuejs

### ISSUE THREAD

**Issue by argenisleon** [nhost/nhost#1854]
**Describe the bug**
Even though I can upload a file, I am NOT getting info from the upload status.

**To Reproduce**
```
const { nhost } = useNhostClient();
const { upload, isUploading, isError, progress } = useFileUpload();
watchEffect(() => {
  console.log(progress, isUploading, isError);
});
```

it prints 
`false null false`
Anything I could be missing?

**Expected behavior**
receive a number representing the upload progress

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 112.0.5615.87

**Comment by onehassan** [comment]
@argenisleon I've tested this with our [`vue-apollo`](https://github.com/nhost/nhost/blob/main/examples/vue-apollo/src/pages/StoragePage.vue) example project, and it works as expected. I recommend following the example project for guidance. Additionally, if you can provide a complete snippet or sample code, we'll be able to assist you more effectively.

I'm going to close this for now but feel free to re-open if you still having issues with the sdk.
