### ISSUE TITLE
Slight UI bug with status red/green indicator

### ISSUE THREAD

**Issue by ArieJones** [nhost/nhost#1858]
Just a small bug in the UI for the portal when I log in my dev/qa instance always shows red even though the unerlying deployments are fine 

![image](https://user-images.githubusercontent.com/14859781/233648643-5877253b-4d60-4e53-a664-2d1b65a46938.png)

**_underlying deployments_** 

![image](https://user-images.githubusercontent.com/14859781/233648800-498b80c5-393a-41a1-b3d3-78383a5b4ada.png)

**Comment by szilarddoro** [comment]
We fixed this in the latest release. If the issue persists, don't hesitate to let us know.
