### ISSUE TITLE
`isLoading` is true, even when no loading has started

### ISSUE THREAD

**Issue by niieani** [nhost/nhost#186]
The `const { isLoading } = useNhostAuth()` variable is not returning accurate information. 

It's `true`, when no authentication has even been attempted, which initially caused my app to run a spinner indefinitely on the login screen (had to stop depending on it). Technically, nothing is loading at that time, so I would expect isLoading to flip to `true` only once the first authentication attempt has started.

**Comment by plmercereau** [comment]
Solved with the release of the new [@nhost/react package](https://github.com/nhost/nhost/releases/tag/%40nhost%2Freact%400.2.0).

See also 
https://docs.nhost.io/reference/react
