### ISSUE TITLE
isAuthenticated not work in nextjs middleware

### ISSUE THREAD

**Issue by 5no0p** [nhost/nhost#1870]
I'm trying to use nhost.auth.isAuthenticated() in nextjs middleware but it always returns false.

```ts
import { NextResponse } from "next/server"
import type { NextRequest } from 'next/server'
import { nhost } from "@/lib/nhost"

export default async function middleware(req: NextRequest) {
  const isAuthenticated = nhost.auth.isAuthenticated();
  console.log("🚀 ~ file: middleware.ts:8 ~ middleware ~ isAuthenticated:", isAuthenticated)

  const isAuthPage =
    req.nextUrl.pathname.startsWith("/login") ||
    req.nextUrl.pathname.startsWith("/register")

  if (isAuthPage) {
    if (isAuthenticated) {
      return NextResponse.redirect(new URL("/dashboard", req.url))
    }

    return null
  }
  if (!isAuthenticated) {
    let from = req.nextUrl.pathname;
    if (req.nextUrl.search) {
      from += req.nextUrl.search;
    }

    return NextResponse.redirect(
      new URL(`/login?from=${encodeURIComponent(from)}`, req.url)
    );
  }
}

export const config = {
  matcher: ["/dashboard/:path*", "/login", "/register"],
}
```

and my nhost client:

```ts
import { NhostClient } from '@nhost/react'

export const nhost = new NhostClient({
  subdomain: process.env.NEXT_PUBLIC_NHOST_SUBDOMAIN!,
  region: process.env.NEXT_PUBLIC_NHOST_REGION!
})
```

.env file:

```
NEXT_PUBLIC_NHOST_SUBDOMAIN=localhost
NEXT_PUBLIC_NHOST_REGION=
```

NhostWrapper.tsx file

```ts
"use client";

import { NhostProvider } from "@nhost/react";
import { nhost } from "@/lib/nhost";

export function NhostWarpper({ children }: { children: React.ReactNode }) {
  return <NhostProvider nhost={nhost}>{children}</NhostProvider>;
}
```

app layout.tsx

```ts
import ReactQueryWrapper from "@/hoc/ReactQueryWrapper";
import { NhostWarpper } from "@/hoc/NhostWarpper";
import MuiWrapper from "@/hoc/MuiWrapper";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryWrapper>
          <NhostWarpper>
            <MuiWrapper>{children}</MuiWrapper>
          </NhostWarpper>
        </ReactQueryWrapper>
      </body>
    </html>
  );
}

```

**Comment by szilarddoro** [comment]
Based on the code you shared it seems to me that the `NhostClient` has no information at all about any session you might have.

Could you share more code that you use to authenticate the user? I guess it happens somewhere else.

**Comment by 5no0p** [comment]
@szilarddoro I edit my issue to show more files.

this is my code on the dashboard page: 

```ts
"use client";

import Link from "next/link";
import { nhost } from "@/lib/nhost";

export default function Dashboard() {
  const isAuthenticated = nhost.auth.isAuthenticated();
  return (
    <div className="flex min-h-screen flex-col items-center justify-between p-24">
      <div>
        {isAuthenticated ? (
          <Link href={"/logout"}>sign out</Link>
        ) : (
          <Link href={"/login"}>sign in</Link>
        )}
      </div>
      <div>{"dashboard"}</div>
    </div>
  );
}

```

and it is work fine...it gives me the authentication status...but the authentication from middleware always gives me false.

and this is my wrapper...I used it before trying to switch to the middlewar:

```ts
"use client";

import { useEffect } from "react";
import { useRouter, useSearchParams} from "next/navigation";
import { useAuthenticationStatus } from "@nhost/react";
import Loader from "@/components/loader";

export default function SignedOutWrapper({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isAuthenticated, isLoading } = useAuthenticationStatus();
  const router = useRouter();
  const searchParams = useSearchParams();

  useEffect(() => {
    if (isAuthenticated) {
      const redirectUrl = searchParams.get("redirectUrl");
      router.push(redirectUrl ? `${redirectUrl}` : "/");
    }
  }, [isAuthenticated, router, searchParams]);


  return (
    <>{!isAuthenticated && !isLoading ? children : <Loader />}</>
  );
}
```

and it is work too.

I looked to try getNhostSession but it use GetServerSidePropsContext not NextRequest.

**Comment by szilarddoro** [comment]
Could you tell me a bit more about your use case? Why is it necessary to route the authentication through the middleware? It's probably a totally valid use case. I just want to understand the problem better.

**Comment by szilarddoro** [comment]
For the middleware to work, we'll need to create some helper functions that helps you populate the `NhostClient` with some information about your session.

At the moment, this is practically what's happening in the middleware:
1. Client is initialized with the correct `subdomain`.
2. `nhost.auth.isAuthenticated()` is being called but the client doesn't know if there is a user available or not because it has just been initialized. Naturally, it will return `false`.

Instead of this, what we should do is the following:
1. Initialize the client with the cookies that are available in the `NextRequest`.
2. Call and await `nhost.auth.isAuthenticatedAsync()`. It should now return `true` if the session was valid.

The problem is indeed related to the lack of `NextRequest` support in the `getNhostSession` function. I'll change the label of this issue to an enhancement instead of a bug report. You can add support for this on your end by copying and changing the functionality of `createServerSideClient` + `getNhostSession` but I understand that this is far from ideal.

**Comment by onehassan** [comment]
@5no0p you can take a look at a [recent example](https://github.com/nhost/nhost/tree/main/examples/quickstarts/nextjs-server-components) we've added that demonstrates how to use the NhostClient in a middleware. If you have any questions let me know, happy to help!
