### ISSUE TITLE
需要自定义电话登录逻辑，以及自定义电话字段格式

### ISSUE THREAD

**Issue by jijkbird** [nhost/nhost#1877]
需要自定义电话登录逻辑，以及自定义电话字段格式

**Comment by dbarrosop** [comment]
The nhost team speaks many languages but I am afraid Chinese isn't amongst them. Would you mind explaining your issue in english?

Thanks!

**Comment by jijkbird** [comment]
I have some questions, such as how to customize the SMS login logic, I want to implement my own SMS verification code, and customize the phone number format. How to use third-party storage systems, such as Alibaba Cloud OSS. How to add interceptors for dynamically modifying logic, such as temporarily adding a keyword filtering system to filter keywords in advance when posting comments.
@dbarrosop

**Comment by jijkbird** [comment]
And how to monitor data changes, such as how to inform users when someone comments.
@dbarrosop

**Comment by dbarrosop** [comment]
If you have questions I'd suggest opening different topics under [discussions](https://github.com/nhost/nhost/discussions), preferably one per question so it's easier to deal with. Issues are mostly for bug reports.

I am closing this issue as this is not a bug report but, please, start discussions with your questions so we can discuss them.
