### ISSUE TITLE
Passwordless Auth working locally, but getting a "This Endpoint Is Disabled" when I push to production. 

### ISSUE THREAD

**Issue by lkfuel** [nhost/nhost#1884]
- Using the Nextjs Stripe Starter project.
- Deployed the front end using Vercel 
- Added the environment variables to the Vercel app 
- Everything works fine when deployed on localhost, but getting these errors when I try passwordless auth: 

![Screenshot 2023-04-28 at 1 39 07 PM](https://user-images.githubusercontent.com/132064134/235216975-2d214355-64da-42dd-bc7d-3720c7d3b326.png)

![image](https://user-images.githubusercontent.com/132064134/235217082-6c9a8777-5353-4191-ab17-04b295da60c8.png)

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/132064134/235217231-17de7833-4332-4703-9d4d-272e39ba1a9c.png">

I followed the tutorial that was included with the project, but I am a little lost as to what to do next. Anything helps!

**Comment by dbarrosop** [comment]
did you enable Magic Link under settings?
