### ISSUE TITLE
"isLoading" inside the useNhostAuth() is not resolving 

### ISSUE THREAD

**Issue by penumatv** [nhost/nhost#189]
Hi Team,

I would like to bring a bug to your notice, when we are working with `@nhost/react-auth` package the destructured `isLoading` is getting hung in true status indefinitely causing a bad user experience. so I have to refresh the page then the `isLoading `is properly getting resolved to false

`const { isLoading, isAuthenticated } = useNhostAuth()`

Thanks
Venk

**Comment by anelad** [comment]
@plmercereau any update on this? Should I worry about it or just leave it and continue to do other works because it will gonna be fixed soon?

**Comment by dohomi** [comment]
I noticed this especially working with NextJS `next/link` and client side redirects.

**Comment by plmercereau** [comment]
Solved with the new [@nhost/react package](https://github.com/nhost/nhost/releases/tag/%40nhost%2Freact%400.2.0)
See
https://docs.nhost.io/reference/react
