### ISSUE TITLE
I do not know how to make "forget password" work

### ISSUE THREAD

**Issue by ankur1163** [nhost/nhost#1898]
I am trying to find docs, how to make forget password work. I guess i have to set up smtp credentials. But where ? Can someone tell me steps involved in this? I will love to see docs on this particular issue. Here's the doc link for reset password 
https://docs.nhost.io/reference/vue/use-reset-password

It gives the impression that if i use this function, my user will get reset password link. Offcourse, this is not the case, as smtp settings are required. So, i request to update docs. There should be one step by step example on how to set up SMTP for gmail. So, we can use it to apply sendgrid or other mail providers. Thanks

**Comment by dbarrosop** [comment]
SMTP settings come already configured in the CLI and in the cloud projects so you shouldn't need to worry about that.

If you are self-hosting, you can refer to hasura-auth documentation:

https://github.com/nhost/hasura-auth

**Comment by ankur1163** [comment]
```
export default function ResetPassword({ style, ...props }) {
  const [email, setEmail] = useState('')
  const { resetPassword, isLoading, isSent, isError, error } = useResetPassword(
    {
      redirectTo: 'http://localhost:3000/login'
    }
  )
 
  const handleOnSubmit = async e => {
    e.preventDefault()
    console.log('email', email)
    await resetPassword(email)
  }

  return (
    <Flex
      h={'100vh'}
      bg="white"
      gap="md"
      justify="center"
      align="center"
      direction="column"
      wrap="wrap"
    >
      <>
        <Title order={3}>Reset Password</Title>

        <TextInput
          w={'25%'}
          placeholder="Your Email id"
          label="Email"
          required="true"
          value={email}
          onChange={event => setEmail(event.currentTarget.value)}
        />

        <Button onClick={e => handleOnSubmit(e)} variant="filled">
          Reset Password
        </Button>
        <p> Check Your email after clicking reset password button</p>

        <Link to={`/login`}>Log in</Link>
      </>
    </Flex>
  )
}
```

https://prnt.sc/qc2dIPiFPUG9
when i click on reset password button. I see "reset" two times in network tab. first it gives me 204 no content and secondly , 400 bad request
https://prnt.sc/mw5BB08ePp0U

**Comment by ankur1163** [comment]
https://prnt.sc/45JeTuEWVLLc

**Comment by ankur1163** [comment]
ok, i dig more. I removed redirectTo  from react component. My code looks like this now 
```
const { resetPassword, isLoading, isSent, isError, error } =
    useResetPassword()

```
in nhost authentication, i have set it to 
https://prnt.sc/AVAT6buYGIOC

I did get an email. So thats a progress. But when i click on the link, i go to home page. I was thinking, I will get reset password screen? Do I have to code reset password screen myself?

**Comment by ankur1163** [comment]
The url is 
http://localhost:3000/?error=invalid-ticket&errorDescription=Invalid+or+expired+verification+ticket

**Comment by ankur1163** [comment]
i checked table and email verified is false. I hope that is not causing the issue

**Comment by ankur1163** [comment]
i went to the auth table and turned emailVerified to true. Now , when i reset password, i got the email. when i open it, it goes to home page. I am still confused, I need to code one more page where i have to create and set new password or nhost has premade page, where user can set the password?

**Comment by ankur1163** [comment]
It should be included in docs that resetpassword link will not work, if email is not verified. Because, i was allowing users to login without verifying as its for internal team only. But, if this is the case, I will make sure everyone verifies their email before they login

**Comment by ankur1163** [comment]
anyone here who can solve my issue?

**Comment by szilarddoro** [comment]
> i went to the auth table and turned emailVerified to true. Now , when i reset password, i got the email. when i open it, it goes to home page. I am still confused, I need to code one more page where i have to create and set new password or nhost has premade page, where user can set the password?

Yes, you need to create your own reset password page, we don't offer one. The error you received indicates that the ticket that was sent in the reset password email is invalid or expired. It doesn't seem to be related to the email not being verified.

Did you immediately open the link in the email you received?

**Comment by ankur1163** [comment]
Thanks for the reply. It means I have to use this 
https://docs.nhost.io/reference/javascript/nhost-js/auth/change-password
1) I have to create new form which will have new password 
2) then i have to use function from above link, provide newPassword and ticket property 

It will update the password then, correct?

**Comment by dbarrosop** [comment]
Hello, take a look here:

https://docs.nhost.io/reference/javascript/auth/reset-password

in particular the `options` argument:

https://docs.nhost.io/reference/docgen/javascript/auth/types/reset-password-params
