### ISSUE TITLE
Feature: Preserve authentication from client to server

### ISSUE THREAD

**Issue by EvHaus** [nhost/nhost#192]
I'm using nhost on a Next.js app. I've got authentication working well on the client side using `@nhost/react-auth`. However, I would like authentication to also be done on the server side, so that I can create a Next.js middleware that validates the user is authenticated prior to server returning the page.

I would be happy to help write some documentation for this, but need some guidance. What is the best way to do this? Store the client-side JWT in a cookie and then read that on the server? Or has the nhost team already considered this scenario and have a more elegant solution in mind?

**Comment by plmercereau** [comment]
Hello Ev,
Thanks for this issue.
We're currently working on this, starting with NextJS. The approach that we'll have will most likely be to maintain a cookie between the browser and the SSR server, while the SSR server will update the cookie from `hasura-auth` when the browser will request a page.
The cookie will only set the refresh token, while the browser will get the JWT and user information from the SSR server response, and will be able to rotate the JWT in directly calling `hasura-auth` in the regular way.
It will be hopefully be available in approximately two weeks.

**Comment by EvHaus** [comment]
@plmercereau Thanks for that update! Can you please post an update in this ticket when you have a alpha/beta version of this change? I would be happy to test it on a project I'm working on.

**Comment by plmercereau** [comment]
This is an alpha WIP, you can have a look at [this branch](https://github.com/nhost/nhost/tree/react-next).
I plan to create a pull request tomorrow, not because it's ready to be merged, but to have a vercel documentation snapshot to share with you an the team, and to get peer review.
In a nutshell, yes, reviews and comments are most welcome!

**Comment by plmercereau** [comment]
Hello,
[@nhost/react](https://github.com/nhost/nhost/releases/tag/%40nhost%2Freact%400.2.0) and [@nhost/nextjs](https://github.com/nhost/nhost/releases/tag/%40nhost%2Fnextjs%400.2.0) have been released. Please have a look at the [documentation](https://docs.nhost.io/reference/nextjs) to see the approach that we took
