### ISSUE TITLE
hasura-auth-js Module Parse error on Nuxt 2

### ISSUE THREAD

**Issue by RayZ0rG** [nhost/nhost#1920]
I am migrating from Nhost v1 to v2
When I use yarn build or yarn dev, I get a "Module parse failed" error:

ERROR in ./node_modules/@nhost/hasura-auth-js/dist/index.esm.js 285:143
Module parse failed: Unexpected token (285:143)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   };
| }
> const M = typeof window < "u", x = /* @__PURE__ */ new Map(), be = (n) => M && typeof localStorage < "u" ? localStorage.getItem(n) : x.get(n) ?? null, Oe = (n, e) => {
|   M && typeof localStorage < "u" ? e ? localStorage.setItem(n, e) : localStorage.removeItem(n) : e ? x.set(n, e) : x.has(n) && x.delete(n);
| }, Pe = (n, e) => {

I am running:
- Nuxt version 2.16.3
- @nhost/nhost-js version 2.2.2
- Node 16.18.1

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version 112

This is similar to issue:  #419

**Comment by szilarddoro** [comment]
Hey @RayZ0rG! The reason is that the nullish coalescing operator is most likely unsupported by the bundler you are using. We have experienced issues related to this in the past. I'll try to look into it soon.

**Comment by RayZ0rG** [comment]
Thx. I just figured it out yesterday. I will update the help ticket.

**Comment by szilarddoro** [comment]
I have released a fix for your issue. Please give the new version a try.
