### ISSUE TITLE
Session Argument error in Hasura Console for Custom Function

### ISSUE THREAD

**Issue by RayZ0rG** [nhost/nhost#1928]
I migrated Custom Functions in Hasura Console to Nhost v2 from Nhost v1 (which worked in Nhost v1).   The issue is that when I try to edit and save the "Session Argument" for a custom function as "hasura_session", the save just chokes and there is no value saved.

I seem to get an error in the log:
{"detail":"The following environment variables are deprecated and moved to metadata: HASURA_GRAPHQL_PG_CONNECTIONS, HASURA_GRAPHQL_PG_TIMEOUT, HASURA_GRAPHQL_TX_ISOLATION, HASURA_GRAPHQL_USE_PREPARED_STATEMENTS","level":"warn","timestamp":"2023-05-13T18:57:27.961+0000","type":"unstructured"}

Extra Info:
The custom function I am trying is named "filters_dashboard".  The qraphql api is requiring hasura_session to be manually added instead of automatically added.  See attached image.
![HasuraSessionIssue_2023-05-13](https://github.com/nhost/nhost/assets/33533717/c3fc6937-d3f1-4e82-8f35-900a9b79d7e1)

**Comment by dbarrosop** [comment]
Could you follow the issue template and provide all the information requested? Specially the step-by-step reproduction section. Thanks.
