### ISSUE TITLE
Getting a 404 after creating a Starter Project

### ISSUE THREAD

**Issue by atapas** [nhost/nhost#1938]
**Describe the bug**
Created a project with the starter plan on India region, getting a 404 page.

**To Reproduce**

- Created a workspace
- Filled the details to create project
- After submitting into get a 404 page

**Expected behavior**

**Screenshots**
![image](https://github.com/nhost/nhost/assets/3633137/fabcd684-efec-43a0-a66e-2315e610db31)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Project gets created successfully, though.

**Comment by dbarrosop** [comment]
Did this happen today? Asking, because we fixed a similar issue a few days ago and can't reproduce now.

**Comment by atapas** [comment]
> Did this happen today? Asking, because we fixed a similar issue a few days ago and can't reproduce now.

Yes! About 3 hrs back.

**Comment by dbarrosop** [comment]
Thanks for confirming, we will try to reproduce.

**Comment by szilarddoro** [comment]
We fixed this in the latest release.
