### ISSUE TITLE
Non self serving user management in hasura-auth

### ISSUE THREAD

**Issue by beepsoft** [nhost/nhost#194]
Are there plans to add non self serving user management to hasura-auth? 

Now users can register themselves and then manage their own user data, eg. password. It would be nice if such functionality - registering users with specific roles, changing their password, etc - would be also available to admins (eg. clients with x-hasura-admin-secret) so that they can manage their users.

I can now register new users from my backend via the auth JS SDK and can add roles by using the - what I think is private - API of hasura-auth, namely the Hasura graphql API exposed for the auth tables. Using the same API and looking at hasura-auth sources I could also implement password change for any of my users. However, this smells as I use these private API-s and the password hash function may change in the future.

So instead, it would be great to have an auth API, which can be used when passing x-hasura-admin-secret or similar along with the auth calls and which would allow managing any users under hasura-auth. 

Or if you say that the Hasura exposed hasura-auth graphql API is intended for us developers as well and it will be officially documented, then it is also fine with me.

**Comment by plmercereau** [comment]
Hello @beepsoft,
Better late than never.
From what I see, it is possible to perform some tasks from the GraphQL endpoint when setting a specific set of permissions to a super user role (or when using the hasura secret except):
- trigger emails
- set password
- authenticate (but I don't think this one should be considered)

About the two examples, it would imply adding new columns in the user table (something like `access_token_expires_in` and `mfa_required`). Then, in using the above suggestion, it would be already possible to change these values.

I feel the two examples are bit of an edge case, but feel free to open an issue about each, maybe it will ring a bell to other community members!

**Comment by mrkpatchaa** [comment]
@plmercereau I was actually looking for how to set longer user sessions without having to refresh. 
We're adding offline capability to our application and we would like people to login in the morning, disconnect from internet and then synchronize their work at the end of the day for example.
