### ISSUE TITLE
Unable to set storage URL correctly 

### ISSUE THREAD

**Issue by 333miiko** [nhost/nhost#1946]
**Describe the bug**

```
export const nhost = new NhostClient({
  backendUrl: NEXT_PUBLIC_API_URL
});
```

I am using backendUrl because I am using self hosted for now.

When I try to get the getPresignedUrl, the result is always returned pre-appended with http://localhost:8000/ rather than my `NEXT_PUBLIC_API_URL`

```
const resp = await nhostClient.storage.getPresignedUrl({
        fileId: fileId?.fileId,
      });
```

**Comment by szilarddoro** [comment]
It's recommended to use individual service URLs when using the self-hosted version. Here's an example of how we set it up in our dashboard: https://github.com/nhost/nhost/blob/main/dashboard/src/utils/nhost.ts#L11

**Comment by 333miiko** [comment]
I've done that but it doesn't seem to overwrite the getPresignedUrl. Uploading images works no problems and i can see it hits the storage endpoint to upload the image, and retrieving the image hits the correct endpoint, but the actual hostname received always stays as localhost

**Comment by szilarddoro** [comment]
I just tried using a custom storage service URL, and the request URL was updated for the `getPresignedUrl` function as I expected.

```ts
export const client = new NhostClient({
  authUrl: "https://local.auth.nhost.run/v1",
  storageUrl: "https://local.test.nhost.run/v1",
  graphqlUrl: "https://local.graphql.nhost.run/v1",
  functionsUrl: "https://local.functions.nhost.run/v1",
});
```

When I used a configuration like this, my `getPresignedUrl` requests went to the `local.test.nhost.run` endpoint.

**Comment by 333miiko** [comment]
So apparently this comes from the env variable `PUBLIC_URL` in the hasura-storage image rather than the NhostClient. Setting this solves the issue.
