### ISSUE TITLE
[React Native] auth.isAuthenticated returns false on first start even when logged in

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost#195]
Running the following in App.js (top level) makes auth.isAuthenticated() return false even when use is logged in (the auth.onAuthStateChanged() returns "SIGNED_IN").
```
  useEffect(() => {
    // Initial login run only once
    const logged_in = nhost.auth.isAuthenticated();
    console.log("FIRST TIME", logged_in);


    // Subscription to track login status
    const unsubscriber = nhost.auth.onAuthStateChanged(res => {
      console.log("SUBSCRIBER", res)

      if (res === "SIGNED_IN") {
        setLocalLoggedIn(true);
      } else {
        setLocalLoggedIn(false);
      }
    });

    return unsubscriber;
  }, []);
```
Is this intended and is there a best practice for how to handle authentication for React Native using nhost v2? 

The current setup is that onAuthStateChanged does not consistently run on first app start, which requires the use of auth.isAuthenticated(), however since the auth.isAuthenticated() does not provide the correct logged in status (e.g. it throws back false even when the user is logged in) makes handling authentication very difficult in React Native.

Preference would be to have auth.onAuthStateChanged to run and return when initialized (would mean isAuthenticated() is not needed in normal authentication handling) - however if this is not desirable then auth.isAuthenticated() needs to wait until nhost-js properly initializes instead of throwing back "false" as it breaks consistent authentication handling on app start.

**Comment by plmercereau** [comment]
Hello,
Thanks for this issue. The latest release of the SDK solved the problem.
You'd probably need to use `isAuthenticatedAsync()` in order to wait for the pre-existing refresh token to be used to get the initial access token.
Don't hesitate to reopen the issue if you're still bumping into this problem
