### ISSUE TITLE
My pro project is down, and there is no obvious way to get support

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#1952]
My pro-level project: `mtpg-io/app-mtpg-io` is down. The API endpoint is completely unresponsive:

<img width="677" alt="image" src="https://github.com/nhost/nhost/assets/260221/48228901-a6cc-49a6-8876-cd098268a5d0">

`curl -v https://<xxx>.auth.us-east-1.nhost.run/`:

```
*   Trying 52.3.182.89:443...
* Connected to <xxx>.auth.us-east-1.nhost.run (52.3.182.89) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=nhost.run
*  start date: Apr 28 00:00:00 2023 GMT
*  expire date: May 27 23:59:59 2024 GMT
*  subjectAltName: host "<xxx>.auth.us-east-1.nhost.run" matched cert's "*.auth.us-east-1.nhost.run"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: <xxx>.auth.us-east-1.nhost.run
> User-Agent: curl/8.0.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS alert, close notify (256):
* Empty reply from server
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (52) Empty reply from server
```

So this is not great, but really: who or how to I contact priority support? Having my app be completely unresponsive, with no way to contact any support that could address is frustrating. I can't tell my users anything, and the app is offline. 

I get it, stuff happens, but how do I notify the right channels at `nhost.io`? I cannot find anything in the docs.

Things eventually came back, back I am basically blind as to how this happened, or most importantly: when this is likely fixed, so I can communicate to my downstream users.

Thanks.

**Comment by dbarrosop** [comment]
We will try to write things down somewhere so it's easier to figure out in the future but the "feedback" button (I think you got a response from there), a github issue like these or even discord are the best ways to reach out to us.

**Comment by dionjwa** [comment]
Thanks for the help, and the pointers. I have made a node for future reference. 

I apologize if my email came across wrong. Sometimes when I am a bit stressed I am blind to things right in front of me.
