### ISSUE TITLE
Cookie conflict cause hasura auth errors

### ISSUE THREAD

**Issue by 333miiko** [nhost/nhost#1955]
I have two sites, one at staging.example.com and example.com 

When logged into staging.example.com, my example.com ends up broken with the following error returned from hasura-auth I Assume this is because the cookies are the same for the token. Is there any way to set a cookie name to avoid this conflict? 

```
{"message":"Cannot destructure property 'options' of 'undefined' as it is undefined."}
```

**Comment by dbarrosop** [comment]
Apologies for the late response, you could try with a different [ClientStorageType](https://docs.nhost.io/reference/docgen/javascript/auth/types/client-storage-type) or a [custom](https://docs.nhost.io/reference/docgen/javascript/auth/types/client-storage) one.

Closing as I don't think there is anything to do on or side here but feel free to keep commenting if you need further help or reopen if you think there is something to fix here.
