### ISSUE TITLE
Error: field with name "customer" already exists in table "transactions"

### ISSUE THREAD

**Issue by vinyll** [nhost/nhost#1958]
**Describe the bug**

Error: field with name "customer" already exists in table "transactions"

**To Reproduce**
1. create a table "customers" and a table transactions, both with "id" fields
2. in the "transactions" table create 2 other fields: "from_id" and "to_id"
3. create 2 foreign relations for "transactions": `transactions.from_id -> customers.id` and `transactions.to_id -> customers.id`

**Expected behavior**
We should have 2 relations to the customers table with name such has "from" and "to"

**Additional context**
This error occurs when editing from the GUI on the cloud: https://app.nhost.io/vinyll/my-super-project/database/browser/default/public/transactions

**Comment by vinyll** [comment]
I could bypass the error playing around editing the table.
However I can only retrieve the relation customer matching the `to_id`.
Also setting up permissions to allow retrieving all customers matching the `from_id` and `to_id` is not possible as only 1 `customer` relation actually exists.

**Comment by dbarrosop** [comment]
thanks for reporting this issue. While we fix this you can workaround the issue by editting the `relationships` for the table `transactions` in the hasura console:

<img width="554" alt="Screenshot 2023-05-24 at 07 41 48" src="https://github.com/nhost/nhost/assets/6246622/95cf5254-52f2-4d43-a632-7eac178bf1ad">

<img width="894" alt="Screenshot 2023-05-24 at 07 43 32" src="https://github.com/nhost/nhost/assets/6246622/699275f8-d90c-4da3-89e3-580c3f197dac">

**Comment by vinyll** [comment]
That's great one can fallback manually yet it's clear and simple.
Thanks for the crystal clear work around @dbarrosop!

**Comment by dbarrosop** [comment]
Apologies, forgot to update this issue but this should work now. Otherwise, let us know. Thanks!
