### ISSUE TITLE
nhost-js from CDN

### ISSUE THREAD

**Issue by richcorbs** [nhost/nhost#196]
I want to use nhost in a site that doesn't have a build process. I found nhost-js on jsdelivr but when I include the script tag I get:

```
Uncaught ReferenceError: NhostClient is not defined

// AND

Uncaught ReferenceError: exports is not defined
```

I've tried a few things but nothing seems to work. Maybe I can't do what I'm trying to do?

**Comment by plmercereau** [comment]
Hello,
Our packages are now bundled into both ESM and CommonJS. This code worked:
```html
<script type="module">
    import { NhostClient } from 'https://cdn.skypack.dev/@nhost/nhost-js'
    window.nhost = new NhostClient({
        backendUrl: 'http://localhost:1337',
    })
    console.log(window.nhost)
</script>
```
Also works in using `https://cdn.jsdelivr.net/npm/@nhost/nhost-js@0.3.7/dist/index.es.js`.
Closing this issue for now. Many thanks for your feedback!
