### ISSUE TITLE
auth.signup returning unexpected values

### ISSUE THREAD

**Issue by joshua1** [nhost/nhost#197]
The auth.signUp method (with email and password parameters keeps returning
```
{session:null,mfa:null}
```
 with the user account created successfully. which doesn't make any sense, as one would need the userId returned as part of the session.user object to enable the saving of other user data in public tables. 
This is the case for several accounts created

**Comment by plmercereau** [comment]
Hello Joshua,
This is the normal behaviour when an user registers, but cannot sign in yet as their email needs to be verified.

It is possible to make email verification optional:
- when using Hasura Auth: set the `AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED` environment variable to `false`
- when using Nhost: untick this option in Users -> Loggin settings: <img width="744" alt="image" src="https://user-images.githubusercontent.com/24897252/161037628-2036ceda-41d2-4918-af3d-7eb3179a4766.png">

I agree this is quite confusing, and we are thinking about how to improve the API without introducing a breaking change.

I hope it helps
