### ISSUE TITLE
vue-apollo example: social sign-in broken

### ISSUE THREAD

**Issue by zenflow** [nhost/nhost#1972]
**Describe the bug**
Social sign-in (i.e. /w github/google/facebook) is broken in vue-apollo example and probably others

**To Reproduce**
1. Go to https://vue-apollo.example.nhost.io/signin
2. Click on Continue With Github/Google/Facebook
3. Observe nginx 404 page

**Expected behavior**
Expected to be able to sign in

**Screenshots**
![image](https://github.com/nhost/nhost/assets/3198597/dcaa8695-a9e1-4994-a495-e44dd74b1ce7)

**Comment by szilarddoro** [comment]
Unfortunately, the backend for this example doesn't exist anymore. In fact, we are not deploying new releases to the frontend you mentioned anymore. You can run the Nhost project locally inside `examples/vue-apollo` to test how a Vue project should be structured.
