### ISSUE TITLE
Failed to send test alert.: SMTP not configured, check your grafana.ini config file's [smtp] section

### ISSUE THREAD

**Issue by Ibrahim-Jarada** [nhost/nhost#1975]
**Describe the bug**
Seems to no direct way to configure SMTP

**Expected behavior**
Ability to edit it or at least to use the same smtp settings in nhost dashboard

**Screenshots**

`/alerting/notifications/receivers/grafana-default-email/edit?alertmanager=grafana`

![image](https://github.com/nhost/nhost/assets/48867411/7c0525de-fecd-44e4-ab8a-5b9f461db99e)

`/admin/settings`

![image](https://github.com/nhost/nhost/assets/48867411/d292c1f7-0033-44ff-b698-82fb68328667)

![image](https://github.com/nhost/nhost/assets/48867411/2fb5c920-0c1d-4370-8e16-2d9c075960ac)

**Comment by dbarrosop** [comment]
Thanks for reporting the feature request, we will look into this.

**Comment by dbarrosop** [comment]
This is not supported at this point and we have no immediate plans to support it. If you want to run your own grafana where you can have full control you can leverage [Nhost Run](https://docs.nhost.io/run).
