### ISSUE TITLE
Make the SDK more modular and tree-shakable

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#198]
Hello

currently this SDK is quite a big dependency due to the nature of the imports. I think Firebase v8 => v9 did also the transition to make all of the functions more modular. (https://firebase.google.com/docs/web/modular-upgrade#example_1_refactoring_an_function)

It would be great if Nhost would follow the approach as well, to reduce client side bundles and remove non-used features.

Thanks

**Comment by plmercereau** [comment]
Hello Dominic, thanks for your suggestion. We've made some improvements in the latest release, would you mind taking the time in having a look at the latest release?
We also plan to have a 'core' system that would be loaded in any case, and the rest that would be used by more granular functions, e.g. hooks in React or composables in Vue.

**Comment by dohomi** [comment]
@plmercereau thanks I will. I am looking forward for a more granular approach. My current project will not use the graphql and file implementation and currently its still loaded event though not used.

**Comment by plmercereau** [comment]
Hello, the new [@nhost/react package](https://github.com/nhost/nhost/releases/tag/%40nhost%2Freact%400.2.0) has major improvements on tree-shakability

See also 
https://docs.nhost.io/reference/react
