### ISSUE TITLE
Custom auth and graphql endpoints

### ISSUE THREAD

**Issue by makstr** [nhost/nhost#199]
Hi, the new sdk (nhost-js) accepts only backendUrl string 

```
export const nhost = new NhostClient({ backendUrl })
```
as the base for auth, storage and graphql endpoints:
```
    this.auth = new HasuraAuthClient({
      url: `${backendUrl}/v1/auth`,
      refreshIntervalTime,
      clientStorage,
      clientStorageType,
      autoRefreshToken,
      autoLogin
    })

    this.storage = new HasuraStorageClient({
      url: `${backendUrl}/v1/storage`
    })

    this.functions = new NhostFunctionsClient({
      url: `${backendUrl}/v1/functions`
    })

    this.graphql = new NhostGraphqlClient({
      url: `${backendUrl}/v1/graphql`
    })
```

https://github.com/nhost/nhost-js/blob/5ad91d231a8c9c6a67d8060bb7edae941f5c64ff/packages/nhost/src/core/nhost-client.ts

perhaps we could allow for custom endpoints, as is the case with:

```
import { NhostApolloProvider } from '@nhost/react-apollo'
...
<NhostApolloProvider nhost={nhost} graphqlUrl={graphqlUrl}>
...
```

**Comment by nunopato** [comment]
@makstr could you elaborate a bit on why you think this is useful and what use cases you had in mind?

**Comment by elitan** [comment]
This is now possible: https://github.com/nhost/nhost/pull/1051
