### ISSUE TITLE
Anonymous users?

### ISSUE THREAD

**Issue by curtisshipley** [nhost/nhost#20]
Does nHost support anonymous users? 

If not, is there some way this could be achieve with the existing APIs?

**Comment by elitan** [comment]
Not yet but it's on our road map: https://github.com/nhost/hasura-backend-plus/issues/475

**Comment by dongido001** [comment]
Nice

**Comment by elitan** [comment]
This is actually working now with Nhost v2 but we lack the documentation. Hopefully, we can complete the documentation soon.

**Comment by EvHaus** [comment]
I'm a bit stuck on this as well. [Hasura docs](https://hasura.io/docs/latest/graphql/core/auth/authentication/unauthenticated-access.html) say it can be done via:

> You can configure Hasura GraphQL engine to allow access to unauthenticated users by defining a specific role which will be set for all unauthenticated requests. Once an unauthenticated role is configured, unauthenticated requests will not be rejected and instead the request will be made with the configured role.

But I can't find how to do this in the Hasura tab.

**Comment by EvHaus** [comment]
Thanks @elitan. That worked for me.
