### ISSUE TITLE
Client side routing does not work with Nhost and NextJS

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#200]
Hello,

I use `@nhost/nhost-js` and `@nhost/react-auth` inside of a NextJS app and if I use client side routing with `next/link` the routing breaks. Basically this does not work any longer as expected:
```ts
const { user, isAuthenticated, isLoading } = useNhostAuth() // this never resolves correctly with the use of client side routing
```
The app remains in a `isLoading` loop.

It seems this example will not work using NextJS and `next/link` https://docs.nhost.io/reference/supporting-libraries/react-auth#next-js

**Comment by plmercereau** [comment]
Hello,
We released a dedicated NextJS package that solves the problem. Please have a look at its [documentation](https://docs.nhost.io/reference/nextjs).
You can also find a [small example here](https://github.com/nhost/nhost/tree/main/examples/nextjs), we are planning to flesh it up soon.
