### ISSUE TITLE
Functions do not work

### ISSUE THREAD

**Issue by camillo18tre** [nhost/nhost#2012]
Hei guys,
I'm trying to work with /functions without success.

This is my folder structure.

<img width="340" alt="Screenshot 2023-06-05 alle 21 34 41" src="https://github.com/nhost/nhost/assets/38567269/4d46f8bc-1b21-410c-8d57-0ffbf46e550f">

If I try to run my function with:  
```
curl http://localhost:1337/v1/functions/test
```
```
export default (req, res) => {
  res.status(200).send(`File: /test/index.ts. Endpoint: /test`);
};
```

I get back this response from the server:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /test</pre>
</body>
</html>
```

Am I doing something wrong?
Thank you

**Comment by dbarrosop** [comment]
which CLI version are you using? If you aren't on `1.0.x`, please, upgrade and take a look at [this blog post](https://nhost.io/blog/config)

After the upgrade and starting everything again try:

```
curl -v https://local.functions.nhost.run/v1/test
```
