### ISSUE TITLE
tsconfig.json conflict

### ISSUE THREAD

**Issue by israelidanny** [nhost/nhost#2024]
I have nhost in a folder in a github repo that has an expo project. The expo project has a `tsconfig.json` at the root as well as a `tsconfig.json` in the folder that nhost is using as base.

The funcitons cli while deploying is trying to use the `tsconfig.json` at the root, which is problematic because it has different configuration than what's intended.

The local development workflow works normal as expected.

**Comment by wollerman** [comment]
I had run into something similar on initial setup. My recommendation is to move your expo app into a subdirectory. In fact, I have my monorepo setup with a `backend` directory where nhost lives and a `frontend` directory where the expo app lives. This seems to not cause any problems as long as nhost cloud console is correctly connected to the `backend` repo directory.

**Comment by israelidanny** [comment]
Yup. I tried something like that yesterday and it seems to work fine.
