### ISSUE TITLE
signOut() does not reset the auth state when providing an initial session

### ISSUE THREAD

**Issue by fmanzali** [nhost/nhost#2028]
**Describe the bug**
When passing an `initialSession` to a server-side instance of the NhostClient (as in the [next-js case](https://github.com/nhost/nhost/blob/d91271cce182e44dd41d5e34a1cb2e65dd14579a/packages/nextjs/src/create-server-side-client.ts#L84)), a subsequent call to `nhost.auth.signOut()` does not reset completely the session - for instance `nhost.auth.getAccessToken()` still returns the access token from the `initialSession`.

**To Reproduce**
Minimal code that reproduces the error is provided in this [repo](https://github.com/fmanzali/nhost-initial-session-bug-report).

**Expected behavior**
Calling `nhost.auth.getAccessToken()` after signout should return undefined. 

**Additional context**
I think the issue stems from [here](https://github.com/nhost/nhost/blob/44d460cd01d5398bcf36ea6079d5a49d1be4223d/packages/hasura-auth-js/src/internal-client.ts#L74).

When starting the client, the `machine.context` is initialized to `INITIAL_MACHINE_CONTEXT` ([here](https://github.com/nhost/nhost/blob/44d460cd01d5398bcf36ea6079d5a49d1be4223d/packages/hasura-auth-js/src/machines/authentication/context.ts#L28)). 

Now, since `context` is not performing a deep copy, when setting the `initialSession` we are actually modifying the exported `INITIAL_MACHINE_CONTEXT`, which is a unintended effect. 

Thus, when signing out, the context is reset to `INITIAL_MACHINE_CONTEXT` ([here](https://github.com/nhost/nhost/blob/44d460cd01d5398bcf36ea6079d5a49d1be4223d/packages/hasura-auth-js/src/machines/authentication/machine.ts#L530)), which  however contains the data from the `initialSession`.

**Comment by szilarddoro** [comment]
Thanks for the detailed report @fmanzali! We'll look into this

**Comment by xmlking** [comment]
we still have this same problem with SvelteKit
after signout,  session is null but `nhost.auth.getAccessToken()` still return token
<img width="1439" alt="image" src="https://github.com/nhost/nhost/assets/627951/24ba941a-39f3-451c-bccf-a9808ef28c79">

<img width="946" alt="image" src="https://github.com/nhost/nhost/assets/627951/79710cd6-d306-4f61-8bcf-5f5e746433ab">

**Comment by onehassan** [comment]
This was fixed in this PR https://github.com/nhost/nhost/pull/2736, make sure to update to the latest versions of the sdk

```
@nhost/nhost-js: 3.1.5
@nhost/react: 3.5.2
@nhost/nextjs: 2.1.16
```
