### ISSUE TITLE
Refreshing the page with refresh token in URL can break the session

### ISSUE THREAD

**Issue by jerryjappinen** [nhost/nhost#203]
Repo to replicate (see `App.js`): https://github.com/jerryjappinen/nhost-demo-client

After successfully logging in from a magic link, the refresh token used will remain in the URL. If a user reloads the page with the refresh token still in there, their session might break.

It's a bit hard to debug this and I can't exactly tell what happens in the SDK, and how `isLoading` behaves here.

**Comment by elitan** [comment]
Is this fixed in the latest version of `@nhost/nhost-js`?

cc @jerryjappinen @plmercereau

**Comment by jerryjappinen** [comment]
Did a quick test, seems to be fixed. Updated the demo client.
