### ISSUE TITLE
Enable TLS 1.3 - disable 1.0 and 1.1

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#205]
After conducting a openssl check on my nhostv2 backend url, I noticed that for the v2backend TLS 1.3 is not supported yet and 1.0 and 1.1 is still supported, leading to warnings, bad scores and potential security issues. 
Thus to enhance security, please change it.

fun fact: v1 is set up already like that, scoring better in mytest :-/

**Comment by MaxSchilling** [comment]
Update: here is the score from a v2 test app that I evaluated using: https://www.ssllabs.com/ssltest/
<img width="452" alt="Picture 1" src="https://user-images.githubusercontent.com/65183496/154224613-09472aa4-24ac-4c5c-83c1-0e54097e6b60.png">

**Comment by Pascal-Orthopy** [comment]
and here is the result of **Nhost V1**
<img src="https://user-images.githubusercontent.com/93537945/154228411-4dfc0e5a-fe28-4875-998e-20b5a42db249.png" width="500" />

**Comment by NesManrique** [comment]
I'm closing this issue as our policies were updated and is already fixed.
