### ISSUE TITLE
`nhost.storage.upload` ignores the provided `id` key

### ISSUE THREAD

**Issue by luciodale** [nhost/nhost#2071]
**Describe the bug**
When calling `nhost.storage.upload({ file, id })`, the `id` is not attached to the request, thus it gets generated server side

**To Reproduce**
- Use this version `@nhost/react": "^2.0.23"`
- Call `nhost.storage.upload({ file, id })` with a provided `id`

**Expected behavior**
I'm expecting the response to not give me a random id but to store the file with the provided one

**Comment by luciodale** [comment]
This bug is in since  `v2.0.21`

**Comment by szilarddoro** [comment]
I'm using the latest version of `@nhost/react` and I can't reproduce it.

I used this implementation:

```tsx
export default function App() {
  const { upload } = useFileUpload();

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();

    if (!(event.target instanceof HTMLFormElement)) {
      return;
    }

    const fileInput = event.target.children.namedItem(
      "file"
    ) as HTMLInputElement;

    if (!fileInput.files) {
      return;
    }

    const customId = "6d4686bf-6e6b-4087-b1af-5bcf3578f728";

    const response = await upload({
      file: fileInput.files[0],
      id: customId,
    });

    console.log(response); // { error: null, isError: false, isUploaded: true, id: '6d4686bf-6e6b-4087-b1af-5bcf3578f728', bucketId: '6d4686bf-6e6b-4087-b1af-5bcf3578f728', …}
    console.log(response.id, customId, response.id === customId); // 6d4686bf-6e6b-4087-b1af-5bcf3578f728 6d4686bf-6e6b-4087-b1af-5bcf3578f728 true
  }

  return (
    <form onSubmit={handleSubmit}>
      <input name="file" type="file" />
      <button>Upload</button>
    </form>
  );
}
```

Do you have a reproduction repository I could use to check what could've gone wrong?

**Comment by szilarddoro** [comment]
Oh, I see what you mean now. That's indeed a problem when using the `client.storage.upload` method to upload your files. `id` doesn't get passed properly to the function that uploads the file when using `file` and not `formData`. I'll look into this.

**Comment by szilarddoro** [comment]
The fix for this issue will shortly be released. Thanks for your patience @luciodale!

**Comment by luciodale** [comment]
Thanks! <3
