### ISSUE TITLE
Ingress redirect fails when the redirect URL is too large

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#2089]
**Describe the bug**

My application serves configurable webpages by embedding user code in the URL hash parameters e.g. 

The user navigates to this URL: 

```
https://app.metapage.io/mf?mfk=<key>
```

then my nhost function checks the database for the content for the `<key>` and creates a redirect (`302` HTTP response) with something like (where `<code>` is some base64 encoded string of javascript, and might be e.g. :
```
https://js.mtfm.io/#?js=<code>
```

The size for the example is ~13k. So much larger than typical URLs, but well within limits of modern browsers.

There are various reasons not relevant here why I want to do this (security, user customization). 

There used to be browser limits on the total size of the URL, but now those limits are gone for the supported browsers for the size of content I am embedding.

However, when the nhost function does a redirect, if the redirect URL is too large, I get a `502` response.

I could do some wrangling and app logic to do some complex embedding of the user code into the webpage served: ultimately, the function is going to serve exactly the same data, but as the URL redirect size has a configured limit, I cannot serve these pages via the URL redirect over a certain size.

Failing increasing the limit, it would be good to know the configured limit, so if that cannot be changed, I can work around it.

**To Reproduce**

Create an nhost function that serves a `302` redirect URL increasing in size. At some point, the `302` redirects become `5xx` failures.

**Expected behavior**
That redirects work even if the URL is quite long, because the content is still relatively small for web content.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:macos
 - Browser: Chrome

**Comment by dbarrosop** [comment]
Could you provide a subdomain, function name and a time when this issues was triggered? Feel free to DM me the info on discord if you prefer.
