### ISSUE TITLE
Auto-generate a down migration for adding pg function

### ISSUE THREAD

**Issue by alexander-mart** [nhost/nhost#2091]
**Is your feature request related to a problem? Please describe.**

`down.sql` AS-IS:
```sql

-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION attempt_is_answered(attempt_row attempts) RETURNS BOOLEAN AS $$
-- BEGIN
--     RETURN COALESCE(attempt_row.answer_boolean, attempt_row.answer_integer, attempt_row.answer_text, attempt_row.answer_date);
-- END;
-- $$ LANGUAGE plpgsql STABLE;
```

**Describe the solution you'd like**

`down.sql` TO-BE:
```sql

DROP FUNCTION IF EXISTS <function_name>;
```

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by dbarrosop** [comment]
migrations are managed by hasura so I am afraid this is out of scope here. Feel free to open an issue in [their repo](https://github.com/hasura/graphql-engine/issues)

**Comment by alexander-mart** [comment]
Right! I messed up the repos :)

I moved the issue to Hasura:
https://github.com/hasura/graphql-engine/issues/9751
