### ISSUE TITLE
useFileUpload and useMultipleFilesUpload ignore `bucketId` param

### ISSUE THREAD

**Issue by kelkes** [nhost/nhost#2092]
**Describe the bug**
I've tried to upload files into a different bucket but it keeps adding the files to `default`

**To Reproduce**
1. upload file
```
const res = await upload({
            bucketId: teamId,
            file: selectedFiles[0],
        });
```

I double and triple checked that teamId is not null. Even provided the value hardcoded.

3. check file in hasura
4. it's in the default bucket

**Expected behavior**
Files should have the correct bucketId

**Screenshots**

Payload
![SCR-20230703-lvji](https://github.com/nhost/nhost/assets/204445/eefda84e-93b2-4d8b-b286-bcde1e541903)

Response
![SCR-20230703-lvkf](https://github.com/nhost/nhost/assets/204445/cfa36270-4731-4d37-a3e0-a6dd15cb3518)

**Desktop (please complete the following information):**
 - OS: macOS Venture 13.4.1
 - Browser chrome
 - Version 114.0.5735.198
 - 
**Additional context**
"@nhost/nextjs": "^1.13.33",
"@nhost/react-apollo": "^5.0.31",

**Comment by onehassan** [comment]
Please provide a sample repo where this issue occurs. This will help us understand the issue better and provide you with an appropriate solution or guidance.

**Comment by dbarrosop** [comment]
Hi, yeah, I asked you to open it to properly track it. To the best of our knowledge this issue is fixed and we can't reproduce it anymore. Make sure there is nothing wrong on your end and if you still can't make it work, please, provide us with an example repo so we can reproduce and fix.

**Comment by hk-meko** [comment]
Hi, I have the same Issue.
I tested the following: 
Using Insomnia posting a file as form-data straight to hasura-storage files endpoing (subdomain.storage.region.nhost.run/v1/files) I tried using 'bucketID', 'bucketId', 'bucket-id' as a form field, but the file always ended in the 'default' bucket. Only setting the header 'x-nhost-bucket-id' worked. 
Therefore I assume that the change to [these lines](https://github.com/nhost/nhost/blob/4c67fd23c463d7a3cf96e47c15c88ee2ff9ac9fc/packages/hasura-storage-js/src/utils/upload.ts#L41C1-L43C4) : 
```
  if (bucketId) {
    data.append('bucket-id', bucketId)
  }
```
and not using the header anymore is still causing the issue.
I am using hasura-storage 0.3.5.

**Comment by dbarrosop** [comment]
@hk-meko don't use `x-nhost-bucket-id` as it's been deprecated for more than a year and it will be removed eventually. It is not even documented as part of the openapi spec. The correct way is by adding the field `bucket-id` as the snippet above does. Here is a postman example:

<img width="1305" alt="Screenshot 2023-07-07 at 09 16 51" src="https://github.com/nhost/nhost/assets/6246622/41f35384-d530-4dda-9d50-8f3229a92162">

**Comment by kelkes** [comment]
Here we go:

https://github.com/kelkes/nhost-upload-bucket-bug

The weird thing is. The response from useFileUpload shows some uuid as bucketId but in the network tab it's still in the default bucket.

![SCR-20230707-jahv](https://github.com/nhost/nhost/assets/204445/aa58966c-233a-420a-870b-4cbbf43fcb69)
![SCR-20230707-jahc](https://github.com/nhost/nhost/assets/204445/b00ebd2a-afcb-4997-ac3a-ed32ca56c03e)
![SCR-20230707-jagh](https://github.com/nhost/nhost/assets/204445/17ba13bc-f949-4623-8a29-438fbb9d2c3b)

**Comment by hk-meko** [comment]
@dbarrosop Thank you! Found my mistake: I was using 'file' instead of 'file[]' as a field name...

@kelkes seems in your screenshot, that you use the same wrong field name

**Comment by kelkes** [comment]
I am not using or setting any field name... i am using

```
const { upload } = useFileUpload();
const res = await upload({
        file: e.target.files[0],
        bucketId: "test",
      });
```

**Comment by dbarrosop** [comment]
Ok, I think the issue is [here](https://github.com/nhost/nhost/blob/main/packages/hasura-storage-js/src/machines/file-upload.ts#L121), `file` should be `file[]` like [here](https://github.com/nhost/nhost/blob/main/packages/hasura-storage-js/src/hasura-storage-api.ts#L66).


@kelkes while we fix this your easiest/fastest workaround is to set `x-nhost-bucket-id` as that's how the old mechanism using `file` worked but don't forget to change it to the new method once we fix this.

@onehassan can you take a look at this?

thanks @hk-meko for the help finding the issue

**Comment by kelkes** [comment]
How can i set the header using the hook?

**Comment by onehassan** [comment]
This issue is now fixed in the latest version: `"@nhost/nextjs": "^1.13.34"`

**Comment by kelkes** [comment]
Awesome! Thanks

**Comment by quentin-decre** [comment]
I still have this issue with @nhost/nhost-js 2.2.16.
