### ISSUE TITLE
OAuth is not work

### ISSUE THREAD

**Issue by bigzhu** [nhost/nhost#2096]
1. https://app.nhost.io/bigzhu/entube/settings/sign-in-methods page display the wrong callback url: https://jysijxgffjwavdtqcuir.auth.ap-south-1.nhost.run/v1/signin/provider/github/callback when run real callback url is https://jysijxgffjwavdtqcuir.nhost.run/v1/auth/signin/provider/github/callback
2. When use github OAuth https://jysijxgffjwavdtqcuir.nhost.run/v1/auth/signin/provider/github/callback?code=d142a731ea7f3b991396 redirect to https://jysijxgffjwavdtqcuir.nhost.run/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider then redirect to https://jysijxgffjwavdtqcuir.nhost.run/console, the OAuth can't work now

**Comment by dbarrosop** [comment]
The domain `jysijxgffjwavdtqcuir.nhost.run` isn't correct. You need to use the full domain with the service and the region in it, for instance; `jysijxgffjwavdtqcuir.auth.ap-south-1.nhost.run`.

**Comment by bigzhu** [comment]
when use `jysijxgffjwavdtqcuir.auth.ap-south-1.nhost.run` throw this error: 
`https://jysijxgffjwavdtqcuir.auth.ap-south-1.nhost.run/v1/signin/provider/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch`

so I said the real callback url not match the doc/console display

**Comment by bigzhu** [comment]
Use 
 `https://jysijxgffjwavdtqcuir.nhost.run/v1/auth/signin/provider/github/` 
don't use 
`https://jysijxgffjwavdtqcuir.auth.ap-south-1.nhost.run/v1/signin/provider/github`

Everything is working fine.
I assume your coder intends to add regions in the future but unfortunately introduced some bugs in the process.

**Comment by dbarrosop** [comment]
No, `jysijxgffjwavdtqcuir.nhost.run` has been deprecated for months. Do not use it as we will remove it soon without warning.

**Comment by dbarrosop** [comment]
If the one with the region and the service isn't working you probably have something misconfigured, review your callbacks and settings and make sure everything is correct.

**Comment by bigzhu** [comment]
no，I have nothing misconfigured. 
The the region url can't work with long time. 
Please check your platform find and fix this bug

**Comment by bigzhu** [comment]
@spakanati Their availability is worrisome, never mind, I used a self-host service

**Comment by dbarrosop** [comment]
After some discussion with the user it was discovered the issue was that the user was using deprecated settings:

https://github.com/nhost/nhost/discussions/1319
