### ISSUE TITLE
Feature request: functions with path parameters

### ISSUE THREAD

**Issue by beepsoft** [nhost/nhost#211]
Currently it is impossible to deploy a function in nhost which can get path parameters.

For example, if I create a function `todo` I am unable to call it like this:

`/v1/functions/todo/123`

nhost would look for the function `123` in the directory `todo` and would not execute the function `todo`.

This is could be useful when we want to deploy our REST API in nhost and we previously had routes like 

```
app.get('/api/todo/:id', (req, res) => {
...
})
```

and want to have the same or similar API with path parameters handled by `/v1/funtions/api` or `/v1/functions/api/todo`

**Comment by andr-ec** [comment]
I'd like to see this as well

**Comment by dbarrosop** [comment]
This is not planned. Serverless functions are meant for adding simple RPC-like functionality, webhooks, and such. For building complex APIs with custom routing logic, etc., you can use [Nhost Run](https://docs.nhost.io/run)
