### ISSUE TITLE
Invalid WebAuthn security key when using platform authenticator

### ISSUE THREAD

**Issue by RihanArfan** [nhost/nhost#2128]
**Describe the bug**
When using sign in/sign up via security keys, an error is shown when trying to use a platform authenticator (Windows Hello, Passkeys via 1Password, fingerprint, etc.). Only physical security keys seem to work.

**To Reproduce**
1.
```ts
await nhost.auth.signUp({
      email: "example@example.com,
      securityKey: true
});
```
2. <img width="242" alt="image" src="https://github.com/nhost/nhost/assets/20425781/f9f1c8b5-bbf6-4db4-8bec-b4c5fc1019e9">
3. <img width="329" alt="image" src="https://github.com/nhost/nhost/assets/20425781/431dbc0a-1b92-41a7-aa9b-95b040716b79">

**Expected behavior**
I expect platform authenticators to work. This includes Windows Hello with the on device fingerprint sensor.

**Screenshots**
<img width="112" alt="image" src="https://github.com/nhost/nhost/assets/20425781/26bba749-f302-482f-aca2-20c4873c504e">

**POST** Platform Authenticator https://rwkcqfmmwqmvedyqjohq.auth.eu-west-2.nhost.run/v1/signup/webauthn/verify
Payload:
```json
{
  "credential": {
    "id": "<removed>",
    "rawId": "<removed>",
    "response": { "attestationObject": "<removed>" },
    "type": "public-key",
    "clientExtensionResults": {},
    "authenticatorAttachment": "platform",
    "transports": []
  },
  "options": {}
}
```

Response:
```
{
    "status": 401,
    "message": "Invalid WebAuthn security key",
    "error": "invalid-webauthn-security-key"
}
```

**POST** Physical Security Key https://rwkcqfmmwqmvedyqjohq.auth.eu-west-2.nhost.run/v1/signup/webauthn/verify
Payload:
```json
{
  "credential": {
    "id": "<removed>",
    "rawId": "<removed>",
    "response": {
      "attestationObject": "<removed>",
      "clientDataJSON": "<removed>"
    },
    "type": "public-key",
    "clientExtensionResults": {},
    "authenticatorAttachment": "cross-platform",
    "transports": ["nfc", "usb"]
  },
  "options": {}
}
```

Response:
```
{
  "session": {...}
}
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 114

**Additional context**
Using Nhost Cloud with Auth 0.21.2.

**Comment by RihanArfan** [comment]
Looks like I should have opened this in https://github.com/nhost/hasura-auth, my apologies! I've done some digging to try and find the cause.

The actual logic for handling WebAuthn is handled by [@simplewebauthn/server](https://github.com/MasterKale/SimpleWebAuthn), which seems to be on 5.3.0 despite latest being 7.3.0.
- [package.json](https://github.com/nhost/hasura-auth/blob/main/package.json#L27) 
- [pnpm-lock.yaml](https://github.com/nhost/hasura-auth/blob/main/pnpm-lock.yaml#L2760)

I've found issues relating to Windows Hello:
- ee
- ee

After trying `@simplewebauthn/server`'s example project, I see that fingerprint via Windows Hello on master (7.3.0+) works. https://simplewebauthn.dev/docs/advanced/example-project

**Comment by RihanArfan** [comment]
I'm very new to Nhost and currently limited in time, otherwise I would try running hasura-auth locally and updating dependencies. 

I noticed that nhost/hasura-auth doesn't have any automatic dependency update PRs. [Dependabot now supports pnpm](https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/) and nhost/nhost uses renovate, so either could be setup on that repo.

**Comment by RihanArfan** [comment]
I've ran hasura-auth locally, upgraded `@simplewebauthn/server` to 7.3.1 and changed `attestationType: 'indirect'` to `
`attestationType: 'none',`,. Changes to facilitate this was relatively simple. https://github.com/nhost/hasura-auth/compare/main...RihanArfan:hasura-auth:main

On the frontend, I've used pnpm overrides in package.json:
```json
{
  ...
  "pnpm": {
    "overrides": {
      "@simplewebauthn/browser": "^7.2.0"
    }
  }
}
```

With these changes, sign up using Windows Hello with fingerprint is working. 🥳 

![image](https://github.com/nhost/nhost/assets/20425781/2821509f-1472-498b-8684-d8ddf8af5fc7)
![image](https://github.com/nhost/nhost/assets/20425781/47721e42-872e-4d82-9476-547a7112007a)


Currently, hasura-auth-js uses @simplewebauthn/browser 6.0.0, and I while 7.0.0 renames the types for credentials/body both on client/server, it seems like using v6 browser with v7 server works.

I haven't made a PR yet, but my [changes are commited on my fork](https://github.com/nhost/hasura-auth/compare/main...RihanArfan:hasura-auth:main) (did to main instead of a branch oops). I need to research into the effects of changing to `attestationType: 'indirect'`. Also haven't ran tests so unsure whether they need any changes. I'll be unable to contribute for at least a month but happy if someone else picks this up.

Also for some reason, 1Password's passkeys prompt still shows an error when trying to save, however, that is still in beta and I don't believe it's an issue on Nhost's side.

**Comment by dbarrosop** [comment]
Awesome work and thanks a lot for the detailed explanation.

> I'll be unable to contribute for at least a month but happy if someone else picks this up.

Unless some other user needs this we will probably wait, we don't have windows machines to test this so it is probably better if we wait.

> I'm still unsure why it was previously indirect, and before making this change that would need to be clarified.

I suspect it may have been related to development and/or tests environment.

**Comment by fungilation** [comment]
this is still fresh. Like Hello Fresh
