### ISSUE TITLE
Vue SDK does not return refs for useFileUpload

### ISSUE THREAD

**Issue by RihanArfan** [nhost/nhost#2131]
**Describe the bug**
The Vue SDK does not return refs for useFileUpload(), meaning they cannot be watched or updated after originally being set.

```
const {
  isUploaded,
  isUploading,
  isError,
  progress,
  id,
  bucketId,
  name,
} = useFileUpload();

```

**Expected behavior**
I expect refs to be returned, just like how other composables such as `useUserDisplayName()` do.

**Screenshots**
<img width="167" alt="image" src="https://github.com/nhost/nhost/assets/20425781/28731cb4-686c-4631-b0dc-18ad1cd521a3">

**Comment by onehassan** [comment]
Apologies, it seems this slipped through the cracks. I'll make sure it's on our list.

**Comment by onehassan** [comment]
This issue has already been addressed in this PR https://github.com/nhost/nhost/pull/2333. I'm going to close this for now, but feel free to open a new issue or drop us a comment if you have questions about this.
