### ISSUE TITLE
Cannot use custom URLs with Vue SDK

### ISSUE THREAD

**Issue by RihanArfan** [nhost/nhost#2134]
**Describe the bug**
When trying to specify `authUrl` to `NhostClient`'s Vue SDK, I get the following error.

The docs which suggest this https://docs.nhost.io/reference/vue.

```ts
Argument of type '{ authUrl: string; subdomain: string; region: string; }' is not assignable to parameter of type 'NhostVueClientConstructorParams'.
  Object literal may only specify known properties, and 'authUrl' does not exist in type 'NhostVueClientConstructorParams'.ts(2345)
```

**Expected behavior**
I expect to be able to override each component's URL as suggested by the docs.

**Screenshots**
<img width="471" alt="image" src="https://github.com/nhost/nhost/assets/20425781/e96bc3e6-6a99-492b-b4b2-ee5d216dc40c">

**Additional context**
`@nhost/vue": "^1.13.33"`

It seems like there is a `backendUrl` option, however, it would require all components to be running on the specified URL.

**Comment by dbarrosop** [comment]
Strange, that should work. We will look into it.

Ignore `backendUrl`, that was deprecated long ago and was there for backward compatibility reasons.

In the meantime, if you aren't trying to self-host you can use the nhost cli instead and use the subdomain `local`.

P.S: If you are trying to build your own hasura-auth you can do in hasura-auth repo `docker build -t nhost/hasura-auth:local .` and then set `local` in the `nhost.toml` to use the image you just built.

**Comment by dbarrosop** [comment]
No update at this point, this needs to be fixed but, unfortunately, we are a bit bogged down with other stuff. We will get to this as soon as we can. PRs are also appreciated/welcomed.

**Comment by nunopato** [comment]
@RihanArfan can you share the code you are using to initialize the client?

**Comment by nunopato** [comment]
the following is working for me with `@nhost/vue` `1.14.1`. 

```js
import { NhostClient } from "@nhost/vue";

export const nhost = new NhostClient({
  authUrl: "https://subdomain.auth.eu-central-1.nhost.run/v1",
  graphqlUrl: "https://subdomain.graphql.eu-central-1.nhost.run/v1",
  storageUrl: "https://subdomain.storage.nhost.run/v1",
  functionsUrl: "https://subdomain.functions.nhost.run/v1",
});
```
