### ISSUE TITLE
Users in dashboard are wrongly paginated

### ISSUE THREAD

**Issue by luciodale** [nhost/nhost#2135]
I've currently got 6 users and see 6 pages with 1 user per page. 

To reproduce just visit `/users` of an nhost project.

**Comment by tawsbob** [comment]
Yeah, I have the same issue!

**Comment by tawsbob** [comment]
This line https://github.com/nhost/nhost/blob/7e37570587f5d51bbd5e767daa594b17d9c4cb01/dashboard/src/pages/%5BworkspaceSlug%5D/%5BappSlug%5D/users/index.tsx#L33

**Comment by tawsbob** [comment]
I would have fixed it if I allowed to create a new pull request

**Comment by dbarrosop** [comment]
@tawsbob you are allowed to open a Pull Request

**Comment by tawsbob** [comment]
https://github.com/nhost/nhost/pull/2136

**Comment by dbarrosop** [comment]
Thanks, I will have a colleague review, merge and release first thing tomorrow.


To be clear, anyone can open a PR. No permission needed although for big changes it is usually better to open an issue to discuss them to avoid wasting time (in case it conflicts with something else we may be doing)

**Comment by tawsbob** [comment]
All right David, thanks!

**Comment by dbarrosop** [comment]
This one should be fixed now, thanks for reporting.
