### ISSUE TITLE
Using Apollo with Next.js getServerSideProps

### ISSUE THREAD

**Issue by EvHaus** [nhost/nhost#215]
I'm trying to get `@nhost/react-apollo` working with Next.js's `getServerSideProps` so that I can fetch my data on the server-side and feed it to Apollo on the client to avoid the initial loading state that appears.

Looking at the Next.js Apollo example, I can see this is possible: https://github.com/vercel/next.js/tree/canary/examples/with-apollo

However, from what I can tell, the way they do this seems to be incompatible with `@nhost/react-apollo` because nhost's library doesn't provide any mechanism to access the client (which is needed for `getServerSideProps`).

Is this something the nhost team is aware of and planning to add support for in the future?

**Comment by EvHaus** [comment]
Do you have any examples of how this could be done? I'm having a hard time figuring out this part:

> ...feed it to the client after the request...

**Comment by highdox** [comment]
@EvHaus I just used the nhost client for that (Keep in mind: request will be sent with the "public" role):

```
export async function getServerSideProps() {

    // Get all template locales
    const { data: localesData } = await nhost.graphql.request(
        GET_TEMPLATE_LOCALES
    );

    return {
        props: {
            localesData,
        },
    };
}
```

And then use it in your page component via props:
`const myServerSideFetchedLocales = props.localesData;`

You can read more about the nhost sdk-client in the [docs](https://docs.nhost.io/reference/sdk).
Hope that helps :)

**Comment by plmercereau** [comment]
Hello,
We just released a set of new packages `@nhost/nextjs`, `@nhost/react`, `@nhost/apollo` and updated `@nhost/react-apollo`, they could be used as a basis to load a query in `getServerSideProps`. To sync the Apollo cache between the client and the server and we don't foresee to work on it in the next weeks. However, contributions are most welcome to eventually get a `@nhost/nextjs-apollo`!
You can have a look at the [Rect documentation](https://docs.nhost.io/reference/react) and the [Next.js documentation](https://docs.nhost.io/reference/nextjs)
