### ISSUE TITLE
Possible to connect with websockets to nhost functions?

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#2163]
**Is your feature request related to a problem? Please describe.**
I would like to connect websockets to nhost functions (not hasura) for fast streaming data

**Describe the solution you'd like**

I can connect to an nhost function via websockets

With an example with the express framework used in nhost functions

**Describe alternatives you've considered**

Use a completely different deployment system for handling websockets

**Comment by dbarrosop** [comment]
No, functions are meant to be short-lived cals that completely quickly. If you need long-lived connections via websockets [Nhost Run](https://nhost.io/product/run) is a better fit.

**Comment by WillieJW** [comment]
@dbarrosop A Run service offers four port types: http, tcp, udp and grpc.
Does an http port with publish on upgrade to a WebSocket?
Or do we need a published tcp port and handle TLS ourselves?
Is there a limit on the number of connections, or an idle timeout? 

Can't find anything about this in the docs.
