### ISSUE TITLE
Error when using useLazyQuery from @apollo/client with NhostApolloProvider

### ISSUE THREAD

**Issue by jaquisonsferreira** [nhost/nhost#2172]
### Description:

When using the `{ NhostApolloProvider }` dependency from the `@nhost/react-apollo` package alongside `useLazyQuery` from `@apollo/client` in a NextJS project, a runtime error occurs.

### Steps to Reproduce:

1. **Setting up `NhostApolloProvider`**:

   Import and set up `{ NhostApolloProvider }` from `@nhost/react-apollo` as demonstrated:

   ```jsx
   <NhostProvider nhost={nhost} initial={pageProps.nhostSession}>
     <NhostApolloProvider nhost={nhost}>        
       <Component {...pageProps} />        
     </NhostApolloProvider>    
   </NhostProvider>
   ```

2. **Using `useLazyQuery`**:

   Within the component, utilize `useLazyQuery` from `@apollo/client`:

   ```jsx
   const [fakeQueryFunction, { loading, fakeData }] = useLazyQuery<{ fakeBooleanResult: boolean }>(FAKE_QUERY_NAME, {
       fetchPolicy: 'no-cache',
   });
   ```

3. **Handler Function**:

   Implement the handler function that uses the `fakeQueryFunction` query:

   ```jsx
   const fakeHandlerFunction = async (email: string) => {
       const queryResult = await fakeQueryFunction({
         variables: { email },
       })

       if (queryResult.data?.fakeBooleanResult) {
         await push({ pathname: '/auth/login', query: { email: email } })
       } else {
         await push({ pathname: '/auth/signup', query: { email: email } })
       }
   }
   ```

### Expected Behavior:

The query should execute correctly without any runtime errors.

### Observed Behavior:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'data')

Call Stack:
- InternalState.toQueryResult node_modules/@apollo/client/react/hooks/useQuery.js (286:0)
- Object.complete node_modules/@apollo/client/react/hooks/useQuery.js (79:0)
- ...
- eval node_modules/zen-observable-ts/module.js (70:0)
```

**Comment by onehassan** [comment]
I think the issue with your implementation is that calling the trigger function will probably cause a re-render of the component.

I don't think this is an issue with our SDK. I would suggest that you try to get the results from the [`onCompleted`](https://www.apollographql.com/docs/react/api/react/hooks/#oncompleted) callback function that you can pass to the options of `useLazyQuery`.

I've tried it with our nextjs example project and it works as expected.
