### ISSUE TITLE
Error when linking then starting dev stack

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#2178]
**Describe the bug**

Pulling config results in an error
Nhost subdomain : `bfjkpxyioihrzqavyivm`

**To Reproduce**

nhost version: ` v1.5.2`

```sh
nhost link
nhost config pull
```

then

```sh
nhost up
```

gives:
```
failed to validate config: failed to apply json patches: failed to apply json patches: replace operation does not apply: doc is missing path: /global/environment/0/value: missing value
```

I tried deleting the `.nhost` directory and repeating the steps, but I still see the same problem.

**Expected behavior**

No errors when pulling nhost config

**Comment by dionjwa** [comment]
It might have been because I had a space in the URLs here:
<img width="370" alt="image" src="https://github.com/nhost/nhost/assets/260221/e36fdd9b-1fbf-4031-94f5-85683bfb8840">

**Comment by dbarrosop** [comment]
It seems to be complaining about an overlay, could you verify the overlays are correct or even removing them?

https://docs.nhost.io/cli/overlays
