### ISSUE TITLE
Unable to Start Development Environment on Windows

### ISSUE THREAD

**Issue by Mattlawd** [nhost/nhost#2181]
**Describe the bug**
After running 'wsl -e nhost up', the docker-compose logs shows: _initdb: error: could not change permissions of directory "/var/lib/postgresql/data/pgdata": Operation not permitted_

The nhost CLI ouputs: '_dependency failed to start: container nhost-example-postgres-1 is unhealthy_'

**To Reproduce**
1. Install nhost on WSL Ubuntu 22.04
2. Open powershell, create empty directory and cd.
3. Run 'wsl -e nhost init'
4. Run 'wsl -e nhost up'
5. Check docker-compose logs.

**Expected behavior**

- Run 'wsl -e nhost up' and all containers start-up and are healthy.

**Screenshots**
<img width="1053" alt="image" src="https://github.com/nhost/nhost/assets/116180526/aec20419-1ba7-4ed5-9c33-213692d70003">

**Desktop (please complete the following information):**
 - OS: Windows 11
.

**Comment by dbarrosop** [comment]
That is unfortunately a common issue with postgres under different setups. It could be anything from the filesystem driver your docker for windows is using to permissions of your directory...

**Comment by dbarrosop** [comment]
> I can run the docker-compose example

that's strange... I'd suggest stopping the cli, deleting `.nhost` and trying to start it again. If that doesn't work, it'd be nice to understand why one works and the other doesn't. Not sure how versed you are with docker-compose but you can find the one we generate under `.nhost/docker-compose.yaml` in case you want to try to dig in a bit

>  is is possible to start the development environment locally using this example and take advantage of the nhost CLI for other features like database migrations etc?

No, I am afraid not

**Comment by Mattlawd** [comment]
I have tried using some of the suggested resolutions in mention [here](https://github.com/docker-library/postgres/issues/116).

Any changes made to the docker-compose.yaml file are overwritten when I run 'wsl -e nhost up'.

**Comment by dbarrosop** [comment]
You'd have to run it manually, i.e., `docker compose --project-directory .nhost/ -f ./nhost/docker-compose.yaml up`.

What I have seen in the past working for other windows users is installing docker directly into the VM instead of relying on docker for windows as the latter relies on yet another virtualization layer.

**Comment by Mattlawd** [comment]
> You'd have to run it manually, i.e., `docker compose --project-directory .nhost/ -f ./nhost/docker-compose.yaml up`.
> 
> What I have seen in the past working for other windows users is installing docker directly into the VM instead of relying on docker for windows as the latter relies on yet another virtualization layer.

I managed to run ‘nhost up’ on the WSL after installing docker on it. Could you please advise on how to access  ‘local.dashboard.nhost.run’ on my windows machine?

**Comment by Mattlawd** [comment]
Even if I run ‘curl https://local.auth.nhost.run/v1/version’ in the WSL it returns an error: ‘curl: (6) could not resolve host: local.auth.nhost.run’.

All of the containers are healthy.

**Comment by dbarrosop** [comment]
> Thanks! I managed to run ‘nhost up’ on the WSL after installing docker on it.

Glad to hear

> ‘curl: (6) could not resolve host: local.auth.nhost.run’.

That is a problem with your ISP, some ISPs block domains that return localhost. You have two options:

1. Change your DNS to one that doesn't filter requests on your behalf (i.e. 1.1.1.1 Cloudflare or 8.8.8.8 Google)
2. Add to `/etc/hosts` (I guess you'd need to do it both in WSL and on your host windows machine?) the development domains pointing to 127.0.0.1

**Comment by Mattlawd** [comment]
@dbarrosop 

> 1. Change your DNS to one that doesn't filter requests on your behalf (i.e. 1.1.1.1 Cloudflare or 8.8.8.8 Google)

This solved the issue, thanks a lot for your support bud! Looking forward to taking full advantage of nhost now.
