### ISSUE TITLE
Storage upload in browser does not handle response status code correctly

### ISSUE THREAD

**Issue by dddenis** [nhost/nhost#2189]
**Describe the bug**
Storage upload in browser does not handle response status code correctly on this line:
https://github.com/nhost/nhost/blob/73230eb35a7f435142ec659c06a75aef8b214fcf/packages/hasura-storage-js/src/utils/upload.ts#L90

**To Reproduce**
Upload invalid file from the browser - the error response will be returned in the `fileMetadata` field, as if the upload succeeded.

**Expected behavior**
Upstream error from the storage service is returned in the `error` field.

**Comment by dbarrosop** [comment]
Nice! Thanks for reporting this. I actually created a vague issue a couple of days about this too. Will close as this is more detailed and includes a PR.

Thanks!

**Comment by onehassan** [comment]
@dddenis Thank you for reporting. LGTM!
I'll add a changeset to your PR and merge it

**Comment by onehassan** [comment]
@dddenis Can you please check `Allow edits from maintainers` so I can add the changeset!
