### ISSUE TITLE
CLI issue bringing up functions dependent on nhost/stripe-graphql-js

### ISSUE THREAD

**Issue by darrow97** [nhost/nhost#2209]
**Describe the bug**
The screenshot below includes the error message in the output from `nhost logs functions -f`.

There is some naming issue when referencing nhost/stripe-graphql-js in the `nhost up` process.

**To Reproduce**
1. Follow the steps to set up the Stripe Nhost API (follow [the steps here](https://docs.nhost.io/graphql/remote-schemas/stripe#get-started))
2. run `nhost up`
3. run `nhost logs functions -f`
4. see error causing the hang

**Expected behavior**
`nhost up` does not hang on bringing up functions container and loads the serverless function that is dependent on @nhost/stripe-graphql-js

**Screenshots**
![image](https://github.com/nhost/nhost/assets/46908712/9a53368d-cb9b-4fb8-b6e8-186dcc5d6a8a)

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser chrome
 - Version 13.5.1

**Smartphone (please complete the following information):**
 - N / A

**Additional context**
Nhost CLI version is v1.5.3 for darwin-arm64

**Comment by dbarrosop** [comment]
this doesn't look like a CLI issue, this looks like something in your node_modules. I'd suggest to start by removing the `.nhost` folder and trying again.

**Comment by onehassan** [comment]
I couldn't replicate the issue you're having. Maybe it's worth running:
```
1. nhost down
2. pnpm clean:all && pnpm store prune && pnpm install
3. nhost up
```

**Comment by darrow97** [comment]
@dbarrosop I removed the `.nhost` directory and got the same result. There are no links to local packages.

@onehassan is 'clean:all' a script in some `package.json`? After I installed `pnpm` this morning, I ran the steps you recommended, but it failed on step 2 with error: `ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL Command "clean:all" not found`

**Comment by onehassan** [comment]
@darrow97 You need to be in the root to run step 2

https://github.com/nhost/nhost/blob/main/package.json#L24

**Comment by darrow97** [comment]
Ok... So i need to be in the project root for Nhost... Where do you recommend I look for that? So far, I have the cli downloaded and have `@nhost/nhost-js` and `@nhost/stripe-graqhql-js` add to my project through npm, but I have never knowingly downloaded Nhost proper to my machine

**Comment by onehassan** [comment]
Oh! I though you were testing the example project we have in our repo. Ignore my suggestion then. But you can still try to remove the modules folder `rm -rf node_modules` and then installing all the dependencies again

**Comment by darrow97** [comment]
phew! I was getting nervous lol.
I have removed the `node_modules` folder and reinstalled the dependencies and the issue persisted.

An interesting note: I can bring the project up just fine on my linux machine (CLI version is v1.5.3 for linux-amd64)

**Comment by onehassan** [comment]
Have you tried to restart nhost `nhost down && nhost up` after re-installing the node_modules?

**Comment by darrow97** [comment]
I have tried the restart.

I have yet to identify any noticeable differences. All the version numbers are the same on both machines. I will learn about the npm error `ENOEMPTY` in hopes it can give a lead

**Comment by dbarrosop** [comment]
I'd suggest doing a hard reset on docker in case there is something cached somewhere:

```docker system prune --all --volumes```

Just keep in mind that will delete all the docker data, including images.

**Comment by darrow97** [comment]
running `docker system prune --all --volumes` did the trick! `nhost up` is no longer hanging.
Thanks @dbarrosop for the docker command

**Comment by dbarrosop** [comment]
glad it worked.
