### ISSUE TITLE
Database shouldn't be available publicly //  Opt-in to publicly reveal the database into the internet

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#221]
To enhance security, it would be great if I could select whether my database shall be reachable publicly via the internet or not. 
Standard procedure from others that I saw is, that in standard the database is not reachable publicly and only if you opt-in /want to, the database is exposed. Usually combined with red flags, stating that up from that point that there's no liability in terms of security by the operator any longer and you customers would have to take the risk themselves.

Pretty standard security setting (compared with others), which is pretty important I guess!

```[tasklist]
### Tasks
- [ ] backend
- [ ] https://github.com/nhost/nhost/pull/2707
- [ ] https://github.com/nhost/nhost/pull/2708
- [ ] announce
```

**Comment by dahmc** [comment]
I agree.

If available to the internet, it should be possible to allow only a certain IP range to access it, as it's common in most other services.

**Comment by cd-a** [comment]
Any news on this?

**Comment by dbarrosop** [comment]
Sorry, this one fell through the cracks. Will take a look this month.

**Comment by dbarrosop** [comment]
This one should be done, check the announcement:

https://github.com/nhost/nhost/discussions/2710
