### ISSUE TITLE
Enforce admin-side 2FA/MFA

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#222]
It should be possible to secure the nhost interface by enforcing MFA/2FA. Plain user/password login is not secure enough for enterprise customer.

Github 2FA could be an option, but it should be able to enforce it / deactive the user/password login from admin side to only allow 2FA GitHub accounts / GitHub organization users.

**Comment by plmercereau** [comment]
Hello Max,
Many thanks for the suggestion. Hasura-auth, the authentication service that we're using under the hood, is supporting MFA. We'll make sure to reflect this feature in the console UI and the documentation.
