### ISSUE TITLE
Nhost doesn't sync the metadata from the local database with the remote database for the hasura native queries.

### ISSUE THREAD

**Issue by rihnoo** [nhost/nhost#2223]
### Context for the issue

I have created a few Hasura native queries locally, and local nhost creates the metadata in the nhost/metadata/databases/databases.yaml file. However, Nhost does not create these native queries remotely, even if the deployment is successful. Hasura has announced that native query editing is not supported yet and will be supported in a future version. I thought this might be the reason why Nhost is not creating the native queries. Therefore, I created the native queries manually on the remote. However, Nhost deletes the native queries that are already created whenever a new deployment is done.

**Comment by rihnoo** [comment]
@dbarrosop I confirmed that the issue has been gone. Thank you

**Comment by dbarrosop** [comment]
Thanks for confirming
