### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [nhost/nhost#2228]
**Describe the bug**
The Twitter logo is updated recently and hasn't been updated on the site. I didn't find any issue related to this.

**To Reproduce**
1. Go to Footer section and see twitter old logo

**Expected behavior**
Twitter logo should be changed to X

**Screenshots**

<img width="960" alt="Screenshot 2023-09-07 174553" src="https://github.com/nhost/nhost/assets/91591901/fa72158f-8efa-45be-a0a5-80128fdbef8b">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Won't change anything in the code as such would replace the twitter-logo with a new file. No code will be touched.

@dbarrosop 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by lalitkumawat1m** [comment]
Thanks @dbarrosop will raise a pr soon

**Comment by dbarrosop** [comment]
Thanks for raising the issue but I am not sure if you can fix this issue yourself. Our landing page is in a private repo.

**Comment by lalitkumawat1m** [comment]
So how can I contribute to this project ?

**Comment by dbarrosop** [comment]
The dashboard still has some twitter references:

<img width="1792" alt="Screenshot 2023-09-08 at 12 05 00" src="https://github.com/nhost/nhost/assets/6246622/2f1a206f-cc22-4636-b633-933c04ec59f2">

So you can fix that if you want.

**Comment by lalitkumawat1m** [comment]
I will take a look at this

**Comment by nunopato** [comment]
The website has been updated with the new X logo. We will keep the dashboard as is because their developer portal is still using "twitter".
