### ISSUE TITLE
Nhost should become ISO 270001 certified

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#224]
To become enterprise ready and increase credibility for security, nhost should pursue and receive ISO27001 certification.

This will enable enterprise customers who are/will be ISO certified to still use nhost (plus side - enterprise are happy to pay more for your service ;) )

**Comment by elitan** [comment]
We don't have a roadmap for such ISO certification yet, but we do recognize the importance of such ISO certificates for enterprise customers.

I'm just adding Firebase certification table here for reference: https://firebase.google.com/support/privacy#certifications
