### ISSUE TITLE
"Downloading metadata" is missing the "..."

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#2253]
During `nhost up`, the CLI lists a bunch of actions it's taking, such as "Applying migrations..."

But, when it comes to "Downloading metadata", it doesn't have the ellipsis on the end, like every other step.  It should be "Downloading metadata..."

**Comment by dbarrosop** [comment]
Thanks for reporting, just opened a PR to fix this cosmetic issue.
