### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by jijkbird** [nhost/nhost#2258]
git clone https://github.com/nhost/nhost
cd nhost/examples/docker-compose
cp .env.example .env
docker-compose up -d

Error Connecting
Did you forget to start nhost up? Please refer to the [CLI documentation](https://docs.nhost.io/platform/cli) if you are having trouble starting your project.

Checking status...

**Comment by dbarrosop** [comment]
Please, reopen the issue following the template provided.
