### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by jijkbird** [nhost/nhost#2259]
**Describe the bug**
Starting with Docker Compose up - d, console displays connection error

Error Connecting
Did you forget to start nhost up? Please refer to the CLI documentation if you are having trouble starting your project.

**To Reproduce**

On the server
git clone https://github.com/nhost/nhost
cd nhost/examples/docker-compose
cp .env.example .env
docker-compose up -d
Then access server port 3030

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
debian 12

**Smartphone (please complete the following information):**

**Additional context**
supabase.lure.plus

**Comment by jijkbird** [comment]
It looks like the docker composite dashboard is requesting localhost, but in the configuration file, I have replaced localhost. Port 1337 can be accessed normally.

**Comment by jijkbird** [comment]
![QQ20230921-205652](https://github.com/nhost/nhost/assets/20245625/aa58be38-8e5f-4cd8-a53b-f3a5ea0424fd)
![QQ20230921-205629](https://github.com/nhost/nhost/assets/20245625/4c657581-6f08-4c9f-bcf7-586502a0c356)
![QQ20230921-205550](https://github.com/nhost/nhost/assets/20245625/7d767286-08fa-4de8-aa4e-085b8e923984)

**Comment by jijkbird** [comment]
![QQ20230921-205912](https://github.com/nhost/nhost/assets/20245625/3869df96-47bc-4c12-8646-a93a32966f30)

**Comment by dbarrosop** [comment]
If you are self-hosting you need to configure the services correctly. For instance, check the dashboard README to verify which env vars you may need to tweak and why:

https://github.com/nhost/nhost/blob/main/dashboard/README.md#environment-variables-for-local-development-and-self-hosting

**Comment by jijkbird** [comment]
The document did not mention the configuration information for Docker Compose deployment. I tried to write the dashboard to the environment environment variable, but it was still unsuccessful. Perhaps we should update the following document?
@dbarrosop

**Comment by NelsonArguera12** [comment]
I need help I tried setting the .env bars for nhost-dashboard docker image but is not working, I'm still getting the same error as well....

**Comment by mattyx97** [comment]
Same error here

**Comment by dbarrosop** [comment]
Same error doesn't help. Share your settings and the error returned by the developer console.
