### ISSUE TITLE
Apollo: cached/public queries do not return data after `nhost.auth.signOut()`

### ISSUE THREAD

**Issue by st3phan** [nhost/nhost#2297]
**Describe the bug**
I have this query, with public permissions, that is run (with Apollo's `useQuery`) while not being logged in.
Then after I sign in and then sign out, that query is no longer returning data and hangs in a loading state.

When I disable [this line](https://github.com/nhost/nhost/blob/236996a903fe880e5b1ac8d6f54fe309dfb91940/integrations/apollo/src/index.ts#L204C7-L204C46) in the `@nhost/react-apollo` pacakge, the public query returns data normally after a `signOut()`.
However, queries that require an access token obviously no longer work.

Am I perhaps on the trail of a possible bug? Or is this just an implementation error on my side.

Here's a screen recording that shows the issue in more detail:
https://www.dropbox.com/scl/fi/ii4hke3k9tjqtavpw28z4/2023.10.04-Nhost-apollo-cache-issue.mp4?rlkey=ofdkga3skgvwvb277a52x6nzw&dl=0

**To Reproduce**
1. Make sure you are logged out
2. Do a simple query using useQuery
3. Do a sign in
4. Do a sign out
5. Go to the page with the simple query (from step 2) and see that the query is not returning data.

**Expected behavior**
useQuery should return data after a `nhost.auth.signOut()`.

**Packages information**
* @apollo/client: 3.8.4
* @nhost/nextjs: 13.37
* @nhost/nhost-js: 2.2.16
* @nhost/react: 2.0.31
* @nhost/react-apollo: 5.0.35

**Comment by onehassan** [comment]
@st3phan, thank you for reporting this.

I've created a small prototype on my end, and it appears to be functioning correctly. Could you please provide a link to a repository where I can take a closer look? It's possible that there may be an implementation error that I can help identify.

**Comment by st3phan** [comment]
Here's a repo with the bare minimum, that also has the same issue.
https://github.com/st3phan/nhost-issue-2297

I'm talking to a local nhost instance with `auth` version `0.21.2`.


https://github.com/nhost/nhost/assets/416652/eb6e1ade-dd83-4e76-89f5-f69e84ad972c

**Comment by st3phan** [comment]
I confirm that `@nhost/react-apollo@5.0.38` fixes this issue 👍
