### ISSUE TITLE
SDK: Missing function to delete user?

### ISSUE THREAD

**Issue by chrtze** [nhost/nhost#230]
I want to add a button to my app to allow users to delete their account. Would that be something that could be added to SDK (something like `nhost.auth.deleteUser()`)? Or should this be done manually via the GraphQL api?

Thanks!

**Comment by elitan** [comment]
You can delete users directly from GraphQL or in the database directly.

This is the GraphQL query you would do:

```garphql
mutation {
  deleteUser(id: "<user-id>") {
    id
  }
}
```

In a Nhost Function you can do the following:

```js

const DELETE_USER = `
mutation ($userId: uuid!) {
  deleteUser(id: $userId) {
    id
  }
}
`

const { data, error } = await nhost.graphql.request(
  DELETE_USER,
  {
    userId: "<user-id>",
  },
  {
    headers: {
      "x-hasura-admin-secret": process.env.NHOST_ADMIN_SECRET,
    },
  }
);
```

(untested code)

**Comment by chrtze** [comment]
Thanks @elitan ! Closing the issue.

**Comment by chrtze** [comment]
Just for clarification: The functionality I want to implement is for users to delete their own accounts. Should this really be done with the admin secret in the client code? Or is the above code only to be run in backend services? What would be the recommended way for implementing a "delete your account" feature? Thanks :)

**Comment by guicurcio** [comment]
You should not embed the admin secret in client-side code.

In a function it's safe to do so given that it only runs on the server, it's encrypted, and it's short-lived. Having that said, a user can delete their own account as long as the user requesting account deletion has the same credentials as the account they want to delete (e.g. `x-hasura-user-id` and you figure this out by using Hasura permissions: https://docs.nhost.io/platform/database/permissions)

**Comment by chrtze** [comment]
Thanks @guicurcio!

**Comment by elitan** [comment]
You can also set the GraphQL permissions so that users can delete their own row in the `auth.users` table via GraphQL.
