### ISSUE TITLE
nhost react hook function useChangeEmail function retrun error

### ISSUE THREAD

**Issue by yadudev** [nhost/nhost#2300]
i use react nhost hook function useChangeEmail. in some cases it returns an error THE REQUEST PAYLOAD IS INCORRECT. 
in which case it occurs ?

**Comment by onehassan** [comment]
I'm guessing you did not supply a new email in the payload

This is how you should use it 👇 

```tsx
const { changeEmail } = useChangeEmail();

const handleChangeEmail = async () => {
  await changeEmail({
    email: "new@example.com", // here you must supply a new email
  });
};
```

**Comment by cooperhailey** [comment]
{error: email- already-in-use,
message: The request payload is Incorrect, status: 488}

**Comment by cooperhailey** [comment]
using nhost/react:   "@nhost/react": "2.0.31",
showing this error
{error: email- already-in-use,
message: The request payload is Incorrect, status: 488}

**Comment by cooperhailey** [comment]
when using 
await changeEmail({
      await changeEmail({email:values?.email})  // here you must supply a new email
  });
showing an error  type error Argument of type '{ email: any; }' is not assignable to parameter of type 'string'.ts(2345)

**Comment by dbarrosop** [comment]
@cooperhailey on your first comment, the error is telling you you are trying to sign in with an email that is already in use. I don't understand your second comment due to formatting issues, please, format the message correctly with code snippets so it's easy to understand

**Comment by cooperhailey** [comment]
export const EmailForm = ({
  user,
  emailHandle,
  handleSkip,
  setEditDetails,
}: ProfileFormProps) => {
  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm({
    defaultValues: { email: "'' },
  });

const onSubmit = async (values) => {
    try {
      Keyboard.dismiss();
      await changeEmail(values?.email);

    } catch (err) {
      alertMessageRef.current?.show();
    }
  };  
this is my current on submit

**Comment by dbarrosop** [comment]
https://docs.nhost.io/reference/javascript/auth/change-email
