### ISSUE TITLE
Can't access storage files publicly

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost#2302]
I have recently updated my NHost CLI and migrated to Nhost Config after I deployed to the cloud, I no longer can access files using the public url. 

Here is the file
![image](https://github.com/nhost/nhost/assets/22567094/44779102-d221-4a83-92d7-661827d4199b)

I have set the public select role to only allow access for images:
{"mime_type":{"_in":["image/png","image/jpg","image/jpeg"]}}

Here is the public URL:
https://${NHOST_SUBDOMAIN}.storage.eu-central-1.nhost.run/v1/files/${fileId}

I have even tried to set the select permission without any checks but keep getting
{
    "error": {
        "message": "you are not authorized"
    }
}

**Comment by dbarrosop** [comment]
what do the logs say?

**Comment by vipafattal** [comment]
I disabled the access to metadata since they are always null, after allowing the metadata I can access it already - though it's empty.
