### ISSUE TITLE
Local Dashboard has non-functional "Run"

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#2305]
The locally running dashboard has the new "Run" tab, but the option does not appear functional.
```
Cannot read properties of null (reading 'isFree')
```

It should probably be disabled, like several of the other tabs.

**Comment by dbarrosop** [comment]
that is expected, Nhost Run is a cloud feature.

**Comment by dbarrosop** [comment]
To elaborate a bit further, eventually we may add functionality to start Run services with the CLI too but for now that's not supported.
