### ISSUE TITLE
Session settings are updated funny when switching projects

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#2322]
When setting Session variables via Settings->Authentication across multiple projects, the settings are getting confused or something.

Using two different projects:

1. Open a the first project, go to Settings->Authentication
2. Set the Session variables (Access Token or Refresh Token) to some unique specific number, like 922, and Save it
3. Select a second nhost project
4. Go back to Settings->Authentication for the second project
5. Observe that the Access Token displayed is the unique number from the first project (922).
6. Refresh the page and observe the Access Token changes to the correct access token for this project (probably, 900)

So, it appears that the data from the first project is hanging around when the settings page is loaded for the second project, and is showing the cached data from the first project.

(This is at app.nhost.io, not local)

**Comment by dbarrosop** [comment]
Weird, I couldn't reproduce. Which browser are you using? I tried with Firefox and Safari and both showed the correct values for each project.

Would you mind sharing a loom video or similar to make sure I am following your exact steps? (via DM so you don't end up sharing publicly something sensitive). I tried a combination of things:

1. two tabs and just hitting refresh
2. one tab where I navigate between projects
3. one tab where I just replace the direct link for the settings page for each project

but all cases behaved as expected.

Also, do you have some proxy or anything else that could be caching things?

**Comment by mainstreetmark** [comment]
I did it 3 times yesterday, even following my own steps before I submitted this ticket. 

But I cannot reproduce today.  Probably because I restarted Chrome or something.

I should have checked for errors in the console, i guess.  Sorry.
