### ISSUE TITLE
Use AWS SDK clients within serverless functions

### ISSUE THREAD

**Issue by bbalanza** [nhost/nhost#2337]
**Is your feature request related to a problem? Please describe.**
I am trying to use the Amazon Javascript SDK inside of the serverless functions, but the amazon client keeps using Nhost's AWS profile when making requests.

**Describe the solution you'd like**
Add an option in the nhost.toml to create a custom AWS profile to use with serverless functions.

**Describe alternatives you've considered**
An alternative would be to use the run functionality instead of the serverless functions, but I do not know if it would work.

**Additional context**
N/A

**Comment by dbarrosop** [comment]
We don't have plans to support this for the free and pro projects. If you need to use the AWS SDK you can always provide an access and secret keys.

I am closing the issue but feel free to keep commenting if needed.

**Comment by bbalanza** [comment]
Thank you for your reply! 

The issue is that I am providing an access and secret key, setting them up in the Javascript textract client with environmental variables. So for example:

```
  const awsCredentials: AwsCredentialIdentity = {
    accessKeyId: process.env.AMAZON_ACCESS_KEY_ID,
    secretAccessKey: process.env.AMAZON_SECRET_ACCESS_KEY,
  }

  const textract = new client({
    credentials: fromNodeProviderChain({
      clientConfig: {
        credentials: awsCredentials,
        region: 'us-east-1',
      },
    }),
    region: 'us-east-1'
  })
```

Gives me the following log error:

```
{"log":"AccessDeniedException: User: arn:aws:sts::163582636966:assumed-role/customer_lambda/642351d5414c944c135589993305c80812a068f4d9e2fb3be8448b4cdd7cca34 is not authorized to
 perform: textract:AnalyzeDocument because no identity-based policy allows the textract:AnalyzeDocument action\n at 
ge (/var/task/lambda.js:94:77558)\n at D_e (/var/task/lambda.js:94:46721)\n at process.processTicksAndRejections 
(node:internal/process/task_queues:95:5)\n at async /var/task/lambda.js:77:53176\n at async 
/var/task/lambda.js:77:4960\n at async /var/task/lambda.js:78:22892\n at async /var/task/lambda.js:66:31839\n at async 
yTe (/var/task/lambda.js:97:7734)\n at async _Te (/var/task/lambda.js:97:8577) {\n '$fault': 'client',\n '$metadata': {\n 
httpStatusCode: 400,\n requestId: '9a006746-c2ea-483a-b8d9-29b9d2e25ad2',\n extendedRequestId: undefined,\n cfId: 
undefined,\n attempts: 1,\n totalRetryDelay: 0\n },\n Code: undefined,\n __type: 
'AccessDeniedException'\n}","path":"/resultScan","requestId":"cf6678c3-0653-487b-b7c0-5f6e2c06f39a","level":"INFO"}
```
My guess is that the textract client is using the lambda's SSO role.

**Comment by bbalanza** [comment]
For example. something like [this could be achieved](https://repost.aws/knowledge-center/lambda-function-assume-iam-role).

**Comment by dbarrosop** [comment]
You need to configure the credentials yourself instead of relying on "automated" configuration methods like fromNodeProviderChain or fromEnv as those will automatically try to assume roles and do other things you may not be intending.

> For example, something like [this could be achieved](https://repost.aws/knowledge-center/lambda-function-assume-iam-role).

As mentioned on my previous message, we don't support that or free/pro projects.

**Comment by bbalanza** [comment]
Indeed. I was specifying the AWS credentials AND using an automated credential provider, when I didn't need to use the provider. This worked:

```
  const awsCredentials: AwsCredentialIdentity = {
    accessKeyId: process.env.AMAZON_ACCESS_KEY_ID,
    secretAccessKey: process.env.AMAZON_SECRET_ACCESS_KEY,
  }

  const textract = new TextractClient({
    credentials: awsCredentials,
    region: 'us-east-1'
  })
```

Thank you so much for your time and help!

**Comment by dbarrosop** [comment]
Glad it worked :)
