### ISSUE TITLE
Next JWT token expired when using SSR

### ISSUE THREAD

**Issue by AlexanderMoroz** [nhost/nhost#2348]
So after discussion with @dbarrosop in discord help channel I've decided to open an Issue here

**Describe the bug**
I'm investigation integration next + nhost with SSR enabled (pages router). I've setup our app the same way as in examples - <NhostProvider> + <NhostApolloProvider> + getNhostSession from nhost/nextjs

In general it works really well! Thanks guys for all your work. 

But sometimes (and it's even not clear when and why) I recieve errors about JWT token being expired, both on client and server. Previously we were using next but without getNhostSessions so all auth part was working only on client and it was working flawlessly

error: ApolloError: Could not verify JWT: JWTExpired
**To Reproduce**
1. Go to start page.
2. Wait till refresh token expired

**Expected behavior**
Token updates automatically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.0 (23A344)
 - Browser: Chrome: 118.0.5993.117 
 - Versions: 
   -  "next": "13.3.0",
   -  "@nhost/apollo": "^5.2.19",
   - "@nhost/nextjs": "^1.13.33",
   -  "@nhost/nhost-js": "^2.2.12",
   -  "@nhost/react": "^2.0.27",
   -  "@nhost/react-apollo": "^5.0.36",

**Code**

ApptProvider in `_app.tsx`
```tsx
export const Provider: FC<ProviderProps> = ({
  children,
  nhostSession,
  transitionConfig = {
    type: 'spring',
    bounce: 0.01,
  },
}) => {
  return (
    <NhostProvider nhost={nhost} initial={nhostSession}>
      <ApolloProvider>
        <MotionConfig transition={transitionConfig}>{children}</MotionConfig>
      </ApolloProvider>
    </NhostProvider>
  );
};
```

ApolloProvider used above:
```tsx
import { FC, PropsWithChildren } from 'react';
import { NhostApolloProvider } from '@nhost/react-apollo';
import { nhost } from '@htch/shared-services/nhost';
import { NhostApolloClientOptions } from '@nhost/apollo';

export const ApolloProvider: FC<
  PropsWithChildren<Omit<NhostApolloClientOptions, 'nhost'>>
> = ({ children, ...props }) => {
  return (
    <NhostApolloProvider nhost={nhost} {...props}>
      {children}
    </NhostApolloProvider>
  );
};
```

getNhostSession:
```
import { getNhostSession as fetchNhostSession } from '@nhost/nextjs';
import { REGION, SUBDOMAIN } from '@htch/shared-services/nhost';
import { GetServerSidePropsContext } from 'next';

export const getNhostSession = (context: GetServerSidePropsContext) =>
  fetchNhostSession(
    {
      subdomain: SUBDOMAIN,
      region: REGION,
    },
    context
  );
```

**Screeshoots**

<img width="484" alt="image" src="https://github.com/nhost/nhost/assets/11835202/745288d6-4b40-464d-a8b1-02447fe146f5">

this is console.log from `getNhostSession`
<img width="480" alt="image" src="https://github.com/nhost/nhost/assets/11835202/3ec683d1-4ae3-45c9-a25b-4aa310b99c70">

So session is here, but JWT is expired

Nhost refresh token expired at looks correct
<img width="275" alt="image" src="https://github.com/nhost/nhost/assets/11835202/77df50eb-be1e-4106-9250-f086f46ecc76">
So it expires in a future at the moment of screenshot

Also noticed that If I delete `nhostSession` from cookies and just refersh page - it started to work

Would be glad to get any help with it. Thanks!

**Comment by dbarrosop** [comment]
thanks for the report, we will try to look into this as soon as possible

**Comment by AlexanderMoroz** [comment]
Hi. Thanks a lot.

Sorry for maybe a late response, but we pushed all new SSR-related changes to dev environment and looks like this issue is not reproducible in production mode. I do remember that I've tried production build on my local machine and saw error related to JWT token expiration, but at least on dev env we can't see it. 

So I assume that this might be related to hot-reloading.

**Comment by mmmoli** [comment]
Any updates on this?

**Comment by AlexanderMoroz** [comment]
Update from my side: 

This definitely happens in production mode

**Comment by mmmoli** [comment]
Our users are reporting issues in production too.

Is there anything I can do to help? Repo? Screenshots?

**Comment by AlexanderMoroz** [comment]
Yep, it's quite hard to reproduce. So I've noticed that this happens in dev env (next 13.3 + ssr + page routes) when I have two users simultaneously accessing application. Looks like it's same issue on our dev env with production build.

Yes, we do have subscriptions and we use them quite a lot. For me it looks like token expired and client on server doesn't know how to refresh it and after this things are messed up. The only thing that helps - is to do `signOut` and then sign in back. Just refresh page and trigger new SSR run does not help. 

Maybe I can take a look at some specific logs when we have this error and provide it to you?

**Comment by AlexanderMoroz** [comment]
ok, finally!

We've managed to reproduce this bug in a fresh repo with all new versions of npm packages (not nhost-cli yet).
I've made a loom-video with explanation of what is happening and looking forward to continue discussion. 

https://www.loom.com/share/4620beb23f964c7d9cf7e5192d550aea

**Comment by mmmoli** [comment]
Thanks @AlexanderMoroz

**Comment by AlexanderMoroz** [comment]
https://github.com/HTCH-app/nhost-jwt-token-test 

That's a repo. Unfortunately we don't include our nhost instance in this repo.

**Comment by AlexanderMoroz** [comment]
Thanks for response!

**Comment by mmmoli** [comment]
HNY folks!

Curious: did you get to look at this in Dec?

We see the often over and over again in production.

**Comment by dbarrosop** [comment]
Not yet, unfortunately December turned out to be way too optimistic, specially given our AI week and the holidays. We will most likely start looking into this before the end of the month.

**Comment by mmmoli** [comment]
thanks for the update!

**Comment by mmmoli** [comment]
Don't suppose this has started yet?

**Comment by dbarrosop** [comment]
We just started looking into this so we will hopefully have news soon.

**Comment by dbarrosop** [comment]
As you probably noticed we have a fix already. We will be releasing a new version of the SDKs with it tomorrow. If you upgrade, we'd appreciate if you could confirm the issue is gone. Thanks for your patience.

**Comment by onehassan** [comment]
Hi @mmmoli, can you please try again with the latest versions:

```
@nhost/nhost-js: 3.0.7
@nhost/apollo: 6.0.7
@nhost/nextjs: 2.1.4
@nhost/react: 3.2.2
@nhost/react-apollo: 9.0.2
```

**Comment by AlexanderMoroz** [comment]
@dbarrosop @onehassan does nhost support `next@14` now?. Looks like we start having this issue after upgrading to `next@14.0.4`, downgrading back to `13.5.6` fixed the problem. Could you please check?
