### ISSUE TITLE
Allow setting inherited role as the default

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/nhost#235]
I'm just setting up a repository that will use subscriptions for most requests, and I'm trying to add role-based permission to this.

I've been following the Hasura issue https://github.com/hasura/graphql-engine/issues/877, which indicates I should use inherited roles for this.  The documentation from Hasura is here: https://hasura.io/docs/latest/graphql/core/auth/authorization/inherited-roles.html

![image](https://user-images.githubusercontent.com/21159570/156208190-3b688db5-2dbf-4325-baaf-9677241d8303.png)

This makes roles that are a combination of selected roles.

What I'd really like is for Hasura to automatically join a given users' roles in this way, but since it doesn't work like that, I'd like to set up an inherited role for each user.  Then I can set this inherited role as the default role for each user.

However, when I look at setting the default role in the Nhost console, it doesn't appear to have a list of the inherited roles:

![image](https://user-images.githubusercontent.com/21159570/156208097-0dfc9a44-620b-4595-9de3-ed83ab0cdfe9.png)

Please could you add this to the role list?

**Comment by plmercereau** [comment]
Hello again Marcello,
I guess you tried already to add the roles in the `auth.roles` table?
<img width="860" alt="image" src="https://user-images.githubusercontent.com/24897252/156234507-157e8fb0-3ee6-4dca-9c7a-8a89b6555699.png">

**Comment by MarcelloTheArcane** [comment]
Didn't think of that, thanks!

**Comment by plmercereau** [comment]
Yes, that's a bit annoying - and I couldn't find a simple way to automatically sync the `roles` tables from Hasura metadata.
Hopefully we'll find a way to automate, don't hesitate to subscribe to [this issue](https://github.com/nhost/hasura-auth/issues/103) and to share your thoughts!
