### ISSUE TITLE
Add Next.js 14 support

### ISSUE THREAD

**Issue by atapas** [nhost/nhost#2351]
**Describe the bug**
I have upgraded my app to Next.js 14 and the build fails.

**To Reproduce**
1. Use Next.js 14 with Nhost library for Next. It works well with 13.x

**Expected behavior**
Nhost APIs should work with Next.js 14 as well.

**Screenshots**
![image](https://github.com/nhost/nhost/assets/3633137/d591f649-285c-4f05-a120-64967fb5f1e7)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
None. But happy to chat more about it.

**Comment by dbarrosop** [comment]
Next.js 14 is a major release with many braking changes from [literally] 5 days ago and it isn't currently supported. We will look into this as soon as we can, in the meantime, help from the community is more than welcome.

**Comment by kelkes** [comment]
if you really want to update right away you could use

```"overrides": {
    "next": "^14.0.1"
  }```

it works fine as far as i can tell
