### ISSUE TITLE
can't delete files from storage

### ISSUE THREAD

**Issue by xmaruto** [nhost/nhost#2359]
Hi,
I created a new bucket (documents) where I'm uploading my files and it works just fine. I provided all required permissions for the files folder in hasura.
After that I'm trying to delete files using standard nhost library:
const { error } = await nhost.storage.delete({ fileId: 'uuid' })

Request URL:
https://phxnamxtnvxdsoomforr.storage.eu-central-1.nhost.run/v1/files/7babf278-c76f-4e09-a16a-263cb7068ee7
Request Method:
DELETE
Status Code:
404 Not Found
Remote Address:
151.101.129.91:443
Referrer Policy:
strict-origin-when-cross-origin

I verified files ids I'm sending to delete and it all looks correct. The only suspicious I have right now is that I can delete it because backend is trying to find it in "default" bucket instead of "documents" bucket.

Could you please suggest how I can resolve this issue?
Thanks.

**Comment by dbarrosop** [comment]
Could you please provide more information? A 404 indicates the url you are requesting doesn't exist and the one you provided is correct so there must be something else. If you are running that snippet client side a screenshot of the developer tools -> network tab would be helpful.

Hasura-storage logs may also be useful as you should be able to see which request is returning the 404.

**Comment by xmaruto** [comment]
<img width="1200" alt="Screenshot 2023-11-07 at 08 40 50" src="https://github.com/nhost/nhost/assets/6754548/1dcd74f7-050a-45f6-8cf7-e55c56a202cd">
<img width="1713" alt="Screenshot 2023-11-07 at 08 41 31" src="https://github.com/nhost/nhost/assets/6754548/1b676973-bc1a-493e-a0df-212dba09c538">

**Comment by xmaruto** [comment]
<img width="667" alt="Screenshot 2023-11-07 at 08 56 53" src="https://github.com/nhost/nhost/assets/6754548/d4f00bfb-938f-465e-8c48-c184ead55e3b">

**Comment by xmaruto** [comment]
Ok I found the issue, it's actually was permissions, when I set it Without Checks for Delete everything works just fine. But I want to verify UserId... before I was checking it:
<img width="509" alt="Screenshot 2023-11-07 at 09 04 07" src="https://github.com/nhost/nhost/assets/6754548/f85fe906-ba75-4a9e-9bdd-1945add90538">

And this type of check doesn't seem to work correctly. Or am I missing something?

**Comment by xmaruto** [comment]
Ok the issue is clear now, this attribute is not there, after the file upload.
<img width="247" alt="Screenshot 2023-11-07 at 09 08 34" src="https://github.com/nhost/nhost/assets/6754548/ad94a553-51f2-45cf-9861-5b9d3eeb6196">
can it be fixed somehow?

**Comment by dbarrosop** [comment]
Right now hasura-storage doesn't populate that field automatically, you can do it yourself though when selecting permissions:

<img width="1128" alt="Screenshot 2023-11-27 at 13 34 03" src="https://github.com/nhost/nhost/assets/6246622/bb1146d9-fe4c-464b-bdd3-3cbdb95a992e">
