### ISSUE TITLE
How to fix Hasura inconsistencies?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/nhost#236]
Somehow, I've ended up with an inconsistent state in Hasura.

I've found this comment which shows how to clear it: https://github.com/hasura/graphql-engine/issues/7328#issuecomment-898830011

How would I do that from Nhost? Do I have access to the console?

**Comment by plmercereau** [comment]
Hello Marcello,
Yes, you can. To run the Hasura CLI:
1. install it
2. create a `config.yaml` with the two following key/values:
    - endpoint: https://[app-id].nhost.app
    - admin_secret: <the hasura secret that you can get from the 'Data' tab in the Nhost console>
3. run your hasura command

About your specific problem: I sometimes run into metadata consistency issues. Most of the times, to reload metadata solves the problem
![image](https://user-images.githubusercontent.com/24897252/156232757-f0b83289-7046-402c-ac2a-fffd9cc414d3.png)
