### ISSUE TITLE
Sign In with LinkedIn is deprecated, use Sign In with LinkedIn using OpenID Connect instead

### ISSUE THREAD

**Issue by caudurodev** [nhost/nhost#2364]
**Describe the bug**
Sign In with LinkedIn is deprecated, use Sign In with LinkedIn using OpenID Connect instead. 

Regular signing is deprecated since [August](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin)

**To Reproduce**
follow steps from docs: https://docs.nhost.io/authentication/sign-in-with-linkedin

**Expected behavior**
Update the method to work with the new auth.

[Here](https://github.com/supabase/gotrue/issues/1216) is a relevant discussion where supabase team encountered the same issue

**Screenshots**
<img width="566" alt="image" src="https://github.com/nhost/nhost/assets/60057887/6b1fa942-2cd4-4fbb-a8a9-835ec860b8b4">

**Comment by dbarrosop** [comment]
Thanks for reporting, I suspect this is as simple as just changing the scopes to:

```
   "scopes_supported": [
        "openid",
        "profile",
        "email"
    ],
```

**Comment by caudurodev** [comment]
This is great- how can I get an updated image with the updated code in my nhost cli?

**Comment by caudurodev** [comment]
Nevermind, just saw that I have to manually bum the auth version in the nhost dashboard. Had to dig around to find out though - might be worth highlighting this somewhere !
