### ISSUE TITLE
Request for Compression Support in Nhost AWS Lambda Functions

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#2375]
**Is your feature request related to a problem? Please describe.**
Yes, the problem arises in a serverless function integrated with Hasura's remote schema feature, producing a significant amount of text data. The data compresses well with gzip (achieving a 36 to 1 ratio), but Grafana and Nhost console indicate egress usage corresponding to the uncompressed data size. This situation leads to two main issues:

1. Increased egress costs due to the larger uncompressed data size.
2. Potentially longer execution times as uncompressed data takes longer to transmit.

**Describe the solution you'd like**
I would like Nhost to support data compression within their AWS Lambda functions. This feature would enable the serverless function to compress data before sending it to Hasura, reducing egress usage and improving execution times. Ideally, the implementation would handle the compression transparently, ensuring compatibility with the existing setup and without requiring significant modifications to the serverless function or the way it integrates with Hasura.

**Describe alternatives you've considered**
As an alternative, I attempted to implement compression within the serverless function itself using the compression middleware in an Express application. This approach worked locally, showing significant improvements in size and execution time. However, when deployed on Nhost, it resulted in inconsistencies and errors (e.g., HTTP zlib error: ZlibException (-3)) in the Hasura schema. Modifying the code to conditionally apply compression only partially resolved these issues.

**Additional context**
Supporting compression in AWS Lambda functions would be particularly beneficial for applications dealing with large volumes of data. It would enhance performance and reduce operational costs, making Nhost's serverless solutions more versatile and cost-effective for data-intensive use cases.

**Usage example**
```Typescript
import express, { Request, Response } from 'express';
import { createServer, GraphQLYogaError } from '@graphql-yoga/node';
import SchemaBuilder from '@pothos/core';
import compression from 'compression';

const builder = new SchemaBuilder({
  notStrict: undefined,
});

/* BUSINESS LOGIC ... */

// Create an Express application
const app = express();

const shouldCompress = (req: Request, res: Response) => {
  if (req.headers['x-no-compression']) {
    console.log('No compression', req.headers['x-no-compression']); // Never shows up in logs
    // Don't compress responses if this request header is present
    return false;
  }

  console.log('Compressing', req.headers['accept-encoding']); // Output: Compressing gzip

  // Fallback to standard filter function provided by compression
  return compression.filter(req, res);
};

// Use compression middleware
app.use(compression({ filter: shouldCompress }));

app.use(server.requestListener);

export default app;
```

**Comment by quentin-decre** [comment]
That would be really needed on our end also.

**Comment by quentin-decre** [comment]
To share all the details with you, we must expose an XML feed with all the job offers we manage. This is a constraint from many partners. It must be one URL, non paginated. I checked and we already are at 2MB for this feed. So now I know that in a couple of months it will fail, and it is key in our business.

**Comment by quentin-decre** [comment]
It works like a charm !
