### ISSUE TITLE
Permission variable not showing up in dashboard permission dropdown select

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2387]
### Discussed in https://github.com/nhost/nhost/discussions/2386

<div type='discussions-op-text'>

<sup>Originally posted by **felixhagspiel** November 26, 2023</sup>
hey all,
I am currently trying to setup a permissions variable for my `profile` table as mentioned here: https://docs.nhost.io/graphql/permissions#permission-variables

Here is what I have:

1. I got a profile table that has a column userId, which has a relation to auth.user.id
2. I have added a new permission variable `X-Hasura-profile-id`
3. I pushed everything, ran `nhost config pull` and `nhost up` in my local environment

I checked my users JWT token and it has `x-hasura-profile-id` included in the claims with the correct profile ID. However, I cannot select this in the dropdown when I am trying to setup a new rule, it just does not show up:
<img width="926" alt="Bildschirmfoto 2023-11-26 um 23 27 29" src="https://github.com/nhost/nhost/assets/5927172/f6946823-a845-4b2a-905e-f7e7e43dabf6">

Am I missing something? When I copy & paste `X-Hasura-profile-id` it just gets overwritten with `X-Hasura-user-id`</div>

**Comment by felixhagspiel** [comment]
another issue that might be related to this: I have changed data in hasura in an unrelated table and it created the following update to my `public_friend_view.yaml` file, even though nothing has changed:
<img width="810" alt="image" src="https://github.com/nhost/nhost/assets/5927172/1035a959-831f-4252-9ed2-b2dff07b0e2d">

**Comment by dbarrosop** [comment]
Yeah, this looks related. Thanks!

**Comment by dbarrosop** [comment]
Check https://github.com/nhost/nhost/issues/2815 as it is a duplicate but contains additional information
