### ISSUE TITLE
Allow Specifying roles on User Create UI 

### ISSUE THREAD

**Issue by jmarbutt** [nhost/nhost#24]
When creating a user, it would be great to specify roles in the UI on this screen.
![image](https://user-images.githubusercontent.com/1386587/115963874-144e2b80-a4e7-11eb-92f5-872479213bf7.png)

**Comment by elitan** [comment]
I'll close this as we want the initial user-creat flow to be simple.

Roles can be specified by editing existing users.

![image](https://user-images.githubusercontent.com/331818/162526730-ac1e7e74-b6f4-478a-962e-db87e1547064.png)
