### ISSUE TITLE
Google Auth doesn't work because the app redirects to the wrong uri

### ISSUE THREAD

**Issue by quarkstars** [nhost/nhost#2409]
Hello, I am an early user

I don't know how to change the app to redirect to the proper place via the new updates. Note that I had Google working before.

The wrong redirect uri is here (I see this in the network tab when calling https://accounts.google.com/o/oauth2/v2/auth?client_id=...)
**https://txylhiboesptnuhhtbsq.nhost.run/v1/auth/signin/provider/google/callback**

The correct redirect uri
**https://txylhiboesptnuhhtbsq.auth.us-east-1.nhost.run/v1/signin/provider/google/callback**

I don't know how to make the app call the correct place.

How it's called in the app

`import { useAuthenticationStatus, useSignInEmailPassword, useProviderLink, useNhostClient, useAuthenticated } from '@nhost/nextjs';
`
```
  const nhost = useNhostClient()

                  nhost.auth.signIn({
                    provider: 'google'
                  })
```

All packages are current

```

    "@nhost/nextjs": "^1.13.40",
    "@nhost/nhost-js": "^2.2.18",
    "@nhost/react-apollo": "^6.0.1",

```

**Comment by dbarrosop** [comment]
Probably related to this:

https://github.com/nhost/nhost/discussions/2303

**Comment by quarkstars** [comment]
Ok yes that was it. The blue "I have updated" button didn't read as a button so I totally missed it.
