### ISSUE TITLE
document the use of the `metadata` column and option

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#241]
The feature is available, but invisible in the docs

**Comment by sumitsaurabh927** [comment]
I'd love to work on this! Do I just have to change the docs? If yes, please assign me so that I can get started on this!

**Comment by plmercereau** [comment]
Hello Sumit,
That would be wonderful!
Yes, you only neem to change the docs. You can either use the "Edit this page" link in the doc website, or fork this repo and then start developping locally:
```sh
pnpm install 
cd docs
pnpm start
```
Looking forward!

**Comment by sumitsaurabh927** [comment]
Hey Pilou,
Thanks for replying back and giving me the instructions. Are you going to assign me or shall I start right away?

**Comment by sumitsaurabh927** [comment]
Hey Pilou, I tried running `pnpm install` but it didn't work and the CLI prompt suggested `npm install` so I ran that but even that didn't work. How do I get started with this?

**Comment by sumitsaurabh927** [comment]
> The feature is available, but invisible in the docs

Where can I see this feature?

**Comment by sumitsaurabh927** [comment]
I'll get started on this right!

**Comment by sumitsaurabh927** [comment]
> > The feature is available, but invisible in the docs
> 
> Where can I see this feature? I couldn't find `metadata` column and option #241. Also, do I add it in the root docs page within a section just how _Components_, _Database_ etc have been added?

Still unable to find either the metadata column or the option #241 😞😞

**Comment by elitan** [comment]
Relevant links:

https://github.com/nhost/hasura-auth/blob/main/migrations/00002_custom-user-fields.sql
https://github.com/nhost/hasura-auth/blob/main/src/types.ts#L56
https://github.com/nhost/nhost/blob/main/packages/hasura-auth-js/src/utils/types.ts#L36
https://github.com/nhost/nhost/blob/main/packages/core/src/types.ts#L67

If you want to skip this issue it's fine @sumitsaurabh927. We'll try to add some simpler documentation-related issues in the future.
