### ISSUE TITLE
Typo in info mail

### ISSUE THREAD

**Issue by kelkes** [nhost/nhost#2420]
**Describe the bug**
When a deployment fails, an information mail is sent. The email content has a typo

"You're getting this email **beacuse** you're part of the SunRocks workspace."

**To Reproduce**
1. Failed deployment
2. email received

**Comment by joelnyongesa** [comment]
Hello, @kelkes . Can I work on this issue?

**Comment by dbarrosop** [comment]
Thanks for reporting, this is fixed now.

@joelnyongesa Thanks for the offer, this is an internal template though so nothing you could've fixed yourself.

**Comment by joelnyongesa** [comment]
Thanks for the feedback, @dbarrosop . I'll be on the lookout to make more contributions to the project
