### ISSUE TITLE
all quickstart screenshots result in 403

### ISSUE THREAD

**Issue by polastre** [nhost/nhost#2430]
**Describe the bug**

The nhost docs for the nextjs|vue|react quickstarts have broken images due to a 403 permission denied error

**To Reproduce**
1. Go to [https://docs.nhost.io/guides/quickstarts/nextjs](https://docs.nhost.io/guides/quickstarts/nextjs)
2. Scroll to the screenshots
3. Pick any of the broken images and copy the URL, eg, [https://mintlify.s3-us-west-1.amazonaws.com/nhost/guides/quickstarts/images/guides/quickstarts/react/permissions.png](https://mintlify.s3-us-west-1.amazonaws.com/nhost/guides/quickstarts/images/guides/quickstarts/react/permissions.png)
4. See error:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>DEFW8WFPN3ZKE7F6</RequestId>
    <HostId>NwQULIg/lMhjwG/S9NsIoH2VWocIQT4hPb1Vy9PPNoY2/3poQWs7p/lu9DGNTIY7dYSSsmkuEws7sO2A4PXWgw==</HostId>
</Error>
```

**Expected behavior**
Documentation is rendered with screenshots

**Comment by nunopato** [comment]
@polastre thank you for letting us know. this has been fixed already.
