### ISSUE TITLE
doc: not correct duplicate of `X-Hasura-Admin-Secret` header at `Refresh Oauth Token` method playground

### ISSUE THREAD

**Issue by alexander-mart** [nhost/nhost#2467]
**Describe the bug**
doc: not correct duplicate of `X-Hasura-Admin-Secret` header at `Refresh Oauth Token` method playground

**To Reproduce**
- API doc page: https://docs.nhost.io/reference/auth/refresh-the-oauth-access-tokens-of-a-given-user-you-must-be-an-admin-to-perform-this-operation
- OpenAPI config: https://github.com/nhost/hasura-auth/blob/main/docs/openapi.json#L2814

**Expected behavior**

**Screenshots**
![image](https://github.com/nhost/nhost/assets/14993551/fd281f1b-8b69-444a-b11f-ebc024daab78)

**Desktop (please complete the following information):**
—

**Smartphone (please complete the following information):**
—

**Additional context**
—

**Comment by HelenJonathan** [comment]
Hello @alexander-mart I would like to work on this issue, can you kindly assign it to me?

**Comment by alexander-mart** [comment]
My understanding is that this is not required in this community.
You can simply take the issue and post a PR in response if you know what needs to be fixed in order for the documentation to be correct.

(I'm a regular contributor, I do not have the rights to assign to an issue)

**Comment by alexander-mart** [comment]
@HelenJonathan My understanding is that this is not required in this community.
You can simply take the issue and post a PR in response if you know what needs to be fixed in order for the documentation to be correct.

(I'm a regular contributor, I do not have the rights to assign to an issue)
