### ISSUE TITLE
Improved 404 page for docs

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#247]
Instead of the default Next.js 404 page.

**Comment by szilarddoro** [comment]
Should we use the same design here that we have on https://nhost.io?

![Screenshot 2022-03-04 at 10 04 54](https://user-images.githubusercontent.com/310881/156733281-2bdbc8ee-6d9a-416e-bfdd-902abd0ef0a5.png)

**Comment by elitan** [comment]
Yea I think that would work 👍
