### ISSUE TITLE
User Roles does not appear to work locally

### ISSUE THREAD

**Issue by gpmarkyoung** [nhost/nhost#2472]
When running nhost locally via the CLI, user roles doesn't seem to populate.
![image](https://github.com/nhost/nhost/assets/111084155/29d6d322-83e4-4365-b14e-643597a16017)

However, the same installation online:
![image](https://github.com/nhost/nhost/assets/111084155/abf65c48-05e5-4662-8185-1ace7508419f)

And the local nhost.toml contains:
![image](https://github.com/nhost/nhost/assets/111084155/92aec456-d840-48fb-828b-f1090df274bb)

And the local auth->roles contains:
![image](https://github.com/nhost/nhost/assets/111084155/d90d7f3d-52e7-4276-87b5-76bef98acad5)

The console has no errors in it, and it is sync'd with nhost.io.

**Comment by dbarrosop** [comment]
That is expected as that form is populated from the `nhost.toml` which the dashboard can't read (yet). In the meantime you can manage roles in the database tab:

<img width="1451" alt="Screenshot 2024-01-19 at 07 50 30" src="https://github.com/nhost/nhost/assets/6246622/9ac6f757-8083-4b5c-bddc-bf857bffddb8">

Which should allow you to "mark requests as":

<img width="767" alt="Screenshot 2024-01-19 at 07 51 05" src="https://github.com/nhost/nhost/assets/6246622/5ff7d5ed-8f94-481e-b519-d7207242b73f">

**Comment by dbarrosop** [comment]
🤦 that's a different [bug](https://github.com/nhost/nhost/issues/2476), as a workaround of the workaround you can use the SQL editor:

<img width="1712" alt="Screenshot 2024-01-20 at 13 59 21" src="https://github.com/nhost/nhost/assets/6246622/010d2c87-1432-4a47-aac2-b8fb18cc4eef">

**Comment by felixhagspiel** [comment]
@dbarrosop what is the workflow for adding new roles until this is fixed?
1. Manually a new role on my local dev environment inside the `auth.roles` table & mark it as a migration
2. Push the migration to prod
3. As I understand, in the nhost dashboard the new role will not show in the `auth` tab after the deployment, so I have to manually create a new entry inside `auth.user_roles`

Is this the correct way?

**Comment by dbarrosop** [comment]
You shouldn't create roles in the database directly. For adding new roles you need to add them to settings, either the `toml` under:

```
[auth.user.roles]
default = 'user'
allowed = ['user', 'me', 'some-new-role']
```

or in the dashboard->settings->Roles and permissions.

**Comment by felixhagspiel** [comment]
Can`t believe I have missed that, thanks

**Comment by felixhagspiel** [comment]
Also, the Auth-View does not show roles that he has if they are not in the `allowed` roles config. Is this intended?
So this user has one additional role `staff´ which does not show up in the dashboard -> Auth -> User Details view.
<img width="723" alt="image" src="https://github.com/nhost/nhost/assets/5927172/fd505570-3b8e-4332-b16f-5f448d7a9ca5">

**Comment by dbarrosop** [comment]
Yes, that is correct. Apologies for the confusion. I thought you wanted a new default alowed role. If you just want the role for some users the procedure you described is correct.

**Comment by Denis-NV** [comment]
Are there any updates on this issue? I also can't see user available roles and the default role in local environment, but everything is working fine in the cloud.

**Comment by dbarrosop** [comment]
This work is scheduled for late this week/early next.
