### ISSUE TITLE
Fix docgen script or documentation: remove or replace `X-Hasura-Admin-Secret` if it's not required

### ISSUE THREAD

**Issue by alexander-mart** [nhost/nhost#2474]
**Describe the bug**
Fix docgen script or documentation manually: https://docs.nhost.io/reference/auth/general/veify-jwt-token 

```diff
curl --request POST \
  --url https://local.auth.nhost.run/v1/token/verify \
  --header 'Content-Type: application/json' \
-  --header 'X-Hasura-Admin-Secret: <api-key>' \
  --data '{
  "token": "<token>"
}'
```
or this:
```diff
curl --request POST \
  --url https://local.auth.nhost.run/v1/token/verify \
  --header 'Content-Type: application/json' \
+  --header 'Authorization': `Bearer <token>' \
-  --header 'X-Hasura-Admin-Secret: <api-key>' \
-  --data '{
-    "token": "<token>"
-  }'
```

**To Reproduce**
—

**Expected behavior**
`X-Hasura-Admin-Secret` is not required header for this auth api request.

**Screenshots**
—

**Desktop (please complete the following information):**
—

**Smartphone (please complete the following information):**
—

**Additional context**

> David Barroso — today, at 1:43
> not sure I follow, the description says:
> 
> > If request body is not passed, the autorization header will be used to be verified
> 
> the admin secret is actually not used so it isn't needed, that's most likely an artifact of the docgen that we need to fix

- Conversation: https://discord.com/channels/552499021260914688/1026377069304758334/threads/1196720730025504908

**Comment by alexander-mart** [comment]
@dbarrosop `documentation` label is offered :)

**Comment by dbarrosop** [comment]
This was fixed already but forgot to close this issue, apologies.
