### ISSUE TITLE
github repo linked to apps not visible to other owners

### ISSUE THREAD

**Issue by dikshatekriwal** [nhost/nhost#249]
**Describe the bug**
One of my team member created a workspace and invited me.
I accepted and created a new app and asked him to link the app to GitHub repo because he is the owner.
Now he is seeing the linked repo on nHost dashboard and I ain't. 
I do have have access to repo but as member not owner. 
I should see the linked repo even if I'm not able to link it same as we were doing in the old nhost platform. 

**To Reproduce**
1. Go to [https://app.nhost.io/jebidu/jebidu-dev](url)
2. Click on 'Connect to Github'
3. Link the repo you are owner of
4. The other member of the workspace not able to see the linked repo

**Expected behavior**
 All members should see the linked repo same as we were doing in the old nhost platform. 
 
**Screenshots**
![sameapp](https://user-images.githubusercontent.com/15191000/156723044-34282a5f-a4ec-45f6-a3e7-431626bda27b.png)
![linkedrepo](https://user-images.githubusercontent.com/15191000/156723053-d8ae4b21-5628-4fa3-8fa7-5d30a4586a79.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser chrome
 - Version v0.6.2 for windows-386

**Comment by elitan** [comment]
@dikshatekriwal We've made some updates to permissions. Can you check if you still see this problem on your end?

**Comment by dikshatekriwal** [comment]
@elitan I can see the repo on my side, however when trying to edit (by clicking on Edit button) it throws error
![repoerror](https://user-images.githubusercontent.com/15191000/158117085-1873eef5-e057-41e6-8f6f-e3006122da52.png)
