### ISSUE TITLE
Function, Deployment, Backups, logs, Settings are not available (disabled) self hosted docker

### ISSUE THREAD

**Issue by venkadeshshiva** [nhost/nhost#2499]
**Describe the bug**
new to this community, When I tried NHost with docker compose example,  Function, Deployment, Backups, logs, Settings are disabled. 

**To Reproduce**
```
git clone https://github.com/nhost/nhost
cd nhost/examples/docker-compose
cp .env.example .env
docker-compose up -d
```

**Expected behavior**
menu should be enabled

**Screenshots**
![image](https://github.com/nhost/nhost/assets/40267253/976436ad-787c-4c20-b02d-6f3fa06f6d01)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [Opera]
 - Version []

**Comment by dbarrosop** [comment]
That functionality is provided by our cloud so it isn't available in self-hosted. You need to provide that functionality yourself.
