### ISSUE TITLE
storage-js: get functionality for authenticated files

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2502]
Don't know if we need react components or something too but at least we need to be able to fetch authenticated files.

We need to support image resizing. Also, we need to support range requests: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by dohomi** [comment]
Following this issue as I'd need the functionality for large list of image urls

**Comment by nunopato** [comment]
https://github.com/nhost/nhost/pull/2507

**Comment by dbarrosop** [comment]
This has been released. Thanks!
