### ISSUE TITLE
getHasuraClaims does not work

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#2513]
I am following the Nhost NextJS quickstart example. When calling `nhost.auth.getHasuraClaims()` the runtime error occures:
`TypeError: He is not a function`.

Using `@nhost/nhost-js` 

```typescript
export const getServerNhost = async () => {
  const $cookies = cookies();

  const nhost = new NhostClient({
    subdomain: process.env.NEXT_PUBLIC_NHOST_SUBDOMAIN ?? 'local',
    region: process.env.NEXT_PUBLIC_NHOST_REGION,
    start: false,
  });

  const sessionCookieValue = $cookies.get(NHOST_SESSION_KEY)?.value ?? '';
  const initialSession: NhostSession = JSON.parse(
    atob(sessionCookieValue) || 'null',
  ) as NhostSession;

  nhost.auth.client.start({ initialSession });
  await waitFor(
    nhost.auth.client.interpreter!,
    (state: StateFrom<any>) => !state.hasTag('loading'),
  );

  return nhost;
};
```

Here is the code attempting to get the hasura claims
```typescript
const nhost = await getServerNhost();
const claims = nhost.auth.getHasuraClaim('x-hasura-user-id');
```

**Comment by dbarrosop** [comment]
Could you creaete a branch where you reproduce the issue with the minimum amount of changes in the quickstart?

https://github.com/nhost/nhost/tree/main/examples/quickstarts/nextjs-server-components

Thanks!

**Comment by jovermier** [comment]
I added pages session and claims to the example. The session page works fine but the claims page throws a runtime error.
[claims page]( https://github.com/jovermier/nhost-nextjs-quickstart-claims/blob/main/src/app/protected/claims/page.tsx)
[session page](https://github.com/jovermier/nhost-nextjs-quickstart-claims/blob/main/src/app/protected/session/page.tsx)

**Comment by dbarrosop** [comment]
Thanks! That helps a lot reproducing the issue (which I could), we will look into it as soon as possible.
