### ISSUE TITLE
Error code "Email is not valid" is not defined

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#2514]
When attempting a `signInEmailPassword` and the email is not in `auth.user.emailDomains->allow`, it throws the following error

> Error code "Email is not valid" is not defined, your custom type is missing the correct messages definition

with the following result:
```json
{
    "accessToken": null,
    "error": {
        "message": "Error code \"Email is not valid\" is not defined, your custom type is missing the correct messages definition",
        "status": 400,
        "error": "invalid-request"
    },
    "isError": true,
    "isSuccess": false,
    "needsEmailVerification": false,
    "needsMfaOtp": false,
    "mfa": null,
    "user": null
}
```

I believe this is a nhost error, since there isn't anything to handle the message "Email is not valid", and therefore, it's not throwing the proper error message, such as "Domain not allowed", or something other than "invalid-request".  For example, it sends a specific "invalid-email-password" when the password is wrong.  But this seems to be complaining that the handler itself is failing to provide the proper error message.

To reproduce, set `auth.user.emailDomains` and try to log in with a domain from a different email.

**Comment by dbarrosop** [comment]
Thanks for reporting, should be fixed soon.
