### ISSUE TITLE
nhost.run certificate expired 

### ISSUE THREAD

**Issue by nicholashu** [nhost/nhost#2528]
I am unable to use the local dashboard as the nhost.run certificate has expired.

when starting nhost in docker the graphql-engine fails to start with the error
```
ERRO connecting to graphql-engine server failed   
FATA[0000] making http request failed: Get "https://local.hasura.nhost.run/v1/version": x509: certificate has expired or is not yet valid: current time 2024-02-12T03:03:28Z is after 2024-02-03T23:12:53Z 
```

**Comment by dbarrosop** [comment]
You are using an old CLI version, please, update it. Thanks!
