### ISSUE TITLE
dashboard: default role/allowed roles "disappear" when editing a user

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2529]
When editing a user in the cloud sometimes the default role and allowed roles disappear.

To replicate:

1. Open the dashboard and head to Auth tab
2. Edit a user.
3. Observe if the default role and allowed roles are "gone".
4. If they aren't, reload the page and try editing again. It will eventually happen.

**Comment by onehassan** [comment]
Fixed in https://github.com/nhost/nhost/pull/2532
