### ISSUE TITLE
Unable to upgrade to Nhost Pro

### ISSUE THREAD

**Issue by connectedlife-ro** [nhost/nhost#2530]
Not able to upgrade my project plan.

![image](https://github.com/nhost/nhost/assets/136441841/5786fc1e-b0a8-4920-be6f-7999a9ed9719)

**Comment by dbarrosop** [comment]
Apologies, could you try again?

**Comment by connectedlife-ro** [comment]
Yes, it's working now. Thank you @dbarrosop
