### ISSUE TITLE
@nhost/react 3.2.0 broke compatibility with react-native

### ISSUE THREAD

**Issue by hwangar** [nhost/nhost#2603]
**Describe the bug**
Introduction of jose library in @nhost/graphql-js made all nhost libraries unusable in react-native, breaking with **crypto doesn't exist**

**To Reproduce**
Just try to use @nhost/react last versions (from 3.2.0 on) in a react-native/expo project

**Expected behavior**
It should work

**Screenshots**
![image](https://github.com/nhost/nhost/assets/10528618/96e188f7-d3b8-4ccb-9aa0-151ed91fdcd0)

**Smartphone (please complete the following information):**
 - Device: any
 - OS: in my case just iphone emulator

**Additional context**
This change provoked incompatibility: https://github.com/nhost/nhost/commit/7baee8a9ccc82d89c71a239712ecee83b858d7cb

**Comment by wollerman** [comment]
I am also experiencing this. The only way I've been able to get past this is downgrading explicitly to 
```
"@nhost/hasura-auth-js": "^2.3.0",
"@nhost/nhost-js": "3.0.5", // 3.0.6 bumps hasura-auth-js dep to breaking 2.3.1
"@nhost/react": "^3.2.0", // 3.2.1 bumps @nhost/nhost-js@3.0.6 which is breaking
"@nhost/react-apollo": "9.0.0", // 9.0.1 bumps to react 3.2.1 which is breaking
```

**Comment by wollerman** [comment]
@onehassan any update on this? It's preventing upgrading all nhost packages because of that dependency chain.

**Comment by onehassan** [comment]
We are currently working on supporting react-native. We will make sure to post updates here.

**Comment by ammarfaris** [comment]
OMG, i just encountered the same problem; hopefully the "re-support" for react-native is coming soon... 😢

**Comment by suplere** [comment]
Any news about this issue?

**Comment by onehassan** [comment]
We are currently working on this. We will post updates on here as soon as possible

**Comment by onehassan** [comment]
Good news, we've released a new version of our SDK. We removed `jose` in favor of `jwt-decode`. Make sure to do the following these steps to make sure everything is working properly:

1. Update to the latest versions

```
@nhost/nhost-js: 3.1.3
@nhost/react: 3.5.0,
@nhost/react-apollo: 12.0.0
```

2. In the entry point of your React Native project (index.js file): add a polyfill for base64 decoding. This step is necessary because base64 decoding was removed from [jwt-decode](https://github.com/auth0/jwt-decode?tab=readme-ov-file#polyfilling-atob)

```diff
import 'react-native-gesture-handler';
import {AppRegistry} from 'react-native';
import App from './src/root';
import {name as appName} from './app.json';
+ import {decode as atob} from 'base-64'
+ global.atob = atob
AppRegistry.registerComponent(appName, () => App);
```
