### ISSUE TITLE
Add support for Hasura's stringify-numeric-types (HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES)

### ISSUE THREAD

**Issue by jnv** [nhost/nhost#2606]
**Is your feature request related to a problem? Please describe.**

Using `bigint`, `numeric`, `decimal`, and `double precision` types in Postgres is tricky for JavaScript, because the default number type doesn't support these wide numeric types (it will automatically round them down to the precision supported, resulting in subtle bugs).

Hasura GraphQL engine has a feature toggle to [stringify these numeric types](https://hasura.io/docs/latest/deployment/graphql-engine-flags/reference/#stringify-numeric-types), however there isn't a possibility to enable this feature under Nhost. When I attempt to set the environment variable `HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES`, I get either config validation error, or the dashboard straight-out rejects it (with error `The name can't start with NHOST_, HASURA_, AUTH_, STORAGE_ or POSTGRES_`).

**Describe the solution you'd like**

Per [David's message on Discord](https://discord.com/channels/552499021260914688/1216132053020442726/1216451623744966656), it should be possible to add a configuration option to `nhost.toml`. For example, there could be `enableStringifyNumericTypes` under `hasura.settings`, to enable toggling this option.

**Describe alternatives you've considered**

Per Hasura's docs, one could also use an alternative JSON parser which supports casting `bigint` into JavaScript's `BigInt`. This, however, is less efficient, especially considering Nhost serverless functions context with limited resources.

`bigint` and `bigserial` types are typically used for primary IDs, and thus it's not necessary to perform any numeric operations on them. In case the wide numeric type is used for numeric operations, an appropriate deserialization from string can be handled in application's code.

**Additional context**

Hasura docs:

- https://hasura.io/docs/latest/schema/common-patterns/numeric-types/
- https://hasura.io/docs/latest/deployment/graphql-engine-flags/reference/#stringify-numeric-types

Discord discussion: https://discord.com/channels/552499021260914688/1216132053020442726/1216132053020442726

**Comment by dbarrosop** [comment]
Done, you can use the cli [1.15.2](https://github.com/nhost/cli/releases/tag/v1.15.2)

**Comment by jnv** [comment]
Thanks David, that was fast!
