### ISSUE TITLE
support for `@nhost/nuxt`

### ISSUE THREAD

**Issue by arashsheyda** [nhost/nhost#2607]
**Is your feature request related to a problem? Please describe.**

`@nhost/nuxt` would be helpfull for `nuxt` users; as we need to repeat the same process each time we want to use `nhost` in a `nuxt` project.

**Describe the solution you'd like**

create `@nhost/nuxt`. we add the registering process of `nhost` to a nuxt plugin, with easy configuration so users can setup `nhost` under a minute!

**Describe alternatives you've considered**

if it's not on the roadmap as an official package it's okay.

**Additional context**

I would be happy to work on this an open a PR.

**Comment by arashsheyda** [comment]
I just realized there is already an [existing module](https://github.com/xlanex6/nuxt-nhost) but still it would nice to have it under `@nhost/nuxt`

**Comment by dbarrosop** [comment]
Keep in mind that module isn't provided nor maintained by nhost, that's a third party module.
