### ISSUE TITLE
sendVerificationEmail hook is missing in nhost-react package

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#261]
Hello 

I just migrate my code to all the new changes made to nhost-react and nhost-next. Currently I bump into the issue to invite users via `sendVerificationEmail` on the previous setup.

Could that be added to the nhost-react package or how should this be handled?

Thanks

**Comment by plmercereau** [comment]
Hi Dominic,
[useSendVerificationEmail](https://docs.nhost.io/reference/react/hooks#send-email-verification) is now available, have you tried using it?
Cheers

**Comment by dohomi** [comment]
great! closing this for now
