### ISSUE TITLE
nhost/nextjs example seems not to work with multi-language setup

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#262]
Hello

I tried the newly released `@nhost/next` package. My setup is a multilanguage setup and as soon I switch to non-default the authentication does not work any more

Also, is there an alternative to `getServerSideProps`, maybe making use of `_middleware`?

**Comment by plmercereau** [comment]
Hello,
No news, closing this issue. If the problem still occurs, please let us know and we'll reopen
