### ISSUE TITLE
Typed NhostClient

### ISSUE THREAD

**Issue by janat08** [nhost/nhost#2623]
**Is your feature request related to a problem? Please describe.**
I'm unclear as to how to do codegen to have typed gql requests.

**Describe the solution you'd like**
Prisma lets you generate DB schema and types from schema config files in repo. But by and large I can't be asked to switch gql package with types support because I can't tell how to pass in adminSecret, or what the endpoint looks like, etc. 

**Describe alternatives you've considered**
I considered using graphql-request package instead, and applying some codegen preset thing for my use case (typed gql). The documentation is bad and linked to low-level implementation at first.

**Additional context**
I'm using nhost for server-side, so I just care about types with none of the other bells and whistles.

**Comment by janat08** [comment]
I've now tried apollo with official integration with react that didn't work for me as I  don't use react. I also attempted trying to pass in jwt bearer token and that resulted in jwt error when using apollo directly. I used env variable for hasura endpoint as a link.

`
const httpLink = createHttpLink({
  uri: 'https://ybjelsmfvjhtzjaspgnr.graphql.eu-central-1.nhost.run/v1',
});

const authLink = setContext((_, { headers }) => {
  // Get the authentication token from local storage if it exists
  const token = 'abc';
  // Return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    }
  }
});

const nhost = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache(),
  defaultOptions: {
    query: {
      fetchPolicy: 'no-cache',
    },
    watchQuery: {
      fetchPolicy: 'no-cache',
    },
  },
});
`

**Comment by dbarrosop** [comment]
I guess you could check how we do it in our dashboard:

https://github.com/nhost/nhost/blob/main/dashboard/graphql.config.yaml
https://github.com/nhost/nhost/blob/main/dashboard/package.json#L13

We also wrote a blog post about this topic some time ago:

https://nhost.io/blog/graphql-code-generator-maximizing-graphql-development-typescript

Hopefully this sets you in the right track.

**Comment by janat08** [comment]
I still can't really tell how to use anything but nhost react because the API is undocumented.

**Comment by janat08** [comment]
I take your point, but is there API reference for connecting to nhost with
apollo but without apollo react? I tried passing in hasura and nhost env
variables and it's not working. It's not about authenticating a user, I
want to connect as admin/server. It's a relatively straightforward enough
ask so as not to expect me to go through how you handle connections.
