### ISSUE TITLE
Cannot login with password less in version 3.3.2

### ISSUE THREAD

**Issue by ahmedabdelhafez** [nhost/nhost#2629]
Hello dears,
i create a small login component to test the passwordless and i am using version 3.3.2 as mentioned in te title and after i add email anad click sign in this is the response 

`{
    "status": 500,
    "message": "{\"message\":\"field 'roles' not found in type: 'users': {\\\"response\\\":{\\\"errors\\\":[{\\\"message\\\":\\\"field 'roles' not found in type: 'users'\\\",\\\"extensions\\\":{\\\"path\\\":\\\"$.selectionSet.users.selectionSet.roles\\\",\\\"code\\\":\\\"validation-failed\\\"}}],\\\"status\\\":200,\\\"headers\\\":{}},\\\"request\\\":{\\\"query\\\":\\\"query users($where: users_bool_exp!) {\\\\n  users(where: $where) {\\\\n    ...userFields\\\\n  }\\\\n}\\\\n\\\\nfragment userFields on users {\\\\n  id\\\\n  createdAt\\\\n  disabled\\\\n  displayName\\\\n  avatarUrl\\\\n  email\\\\n  passwordHash\\\\n  emailVerified\\\\n  phoneNumber\\\\n  phoneNumberVerified\\\\n  defaultRole\\\\n  isAnonymous\\\\n  ticket\\\\n  otpHash\\\\n  totpSecret\\\\n  activeMfaType\\\\n  newEmail\\\\n  locale\\\\n  metadata\\\\n  roles {\\\\n    role\\\\n  }\\\\n}\\\",\\\"variables\\\":{\\\"where\\\":{\\\"email\\\":{\\\"_eq\\\":\\\"messi10010@gmail.com\\\"}}}}}\",\"stack\":\"Error: field 'roles' not found in type: 'users': {\\\"response\\\":{\\\"errors\\\":[{\\\"message\\\":\\\"field 'roles' not found in type: 'users'\\\",\\\"extensions\\\":{\\\"path\\\":\\\"$.selectionSet.users.selectionSet.roles\\\",\\\"code\\\":\\\"validation-failed\\\"}}],\\\"status\\\":200,\\\"headers\\\":{}},\\\"request\\\":{\\\"query\\\":\\\"query users($where: users_bool_exp!) {\\\\n  users(where: $where) {\\\\n    ...userFields\\\\n  }\\\\n}\\\\n\\\\nfragment userFields on users {\\\\n  id\\\\n  createdAt\\\\n  disabled\\\\n  displayName\\\\n  avatarUrl\\\\n  email\\\\n  passwordHash\\\\n  emailVerified\\\\n  phoneNumber\\\\n  phoneNumberVerified\\\\n  defaultRole\\\\n  isAnonymous\\\\n  ticket\\\\n  otpHash\\\\n  totpSecret\\\\n  activeMfaType\\\\n  newEmail\\\\n  locale\\\\n  metadata\\\\n  roles {\\\\n    role\\\\n  }\\\\n}\\\",\\\"variables\\\":{\\\"where\\\":{\\\"email\\\":{\\\"_eq\\\":\\\"messi10010@gmail.com\\\"}}}}}\\n    at /app/node_modules/.pnpm/graphql-request@3.7.0_graphql@16.2.0/node_modules/graphql-request/dist/index.js:340:31\\n    at step (/app/node_modules/.pnpm/graphql-request@3.7.0_graphql@16.2.0/node_modules/graphql-request/dist/index.js:63:23)\\n    at Object.next (/app/node_modules/.pnpm/graphql-request@3.7.0_graphql@16.2.0/node_modules/graphql-request/dist/index.js:44:53)\\n    at fulfilled (/app/node_modules/.pnpm/graphql-request@3.7.0_graphql@16.2.0/node_modules/graphql-request/dist/index.js:35:58)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\"}",
    "error": "internal-error"
}`

and here is the my component code:
![image](https://github.com/nhost/nhost/assets/25756993/e75f2690-57dd-478e-bc87-cbb04d8dadf0)

**Comment by dbarrosop** [comment]
This looks like an issue somwhere else. Can you try the following graphql query in the console?

```graphql
{
  users(limit: 1) {
    roles {
      __typename
    }
  }
}
```

**Comment by ahmedabdelhafez** [comment]
@dbarrosop still the same issue

**Comment by dbarrosop** [comment]
If that query doesn't work it means there is something wrong in your project. Are you self-hosting, using the CLI or are you using a project in our cloud?

**Comment by ahmedabdelhafez** [comment]
@dbarrosop the command working and return this issue in console it's status is 200 but here is screenshot:

![image](https://github.com/nhost/nhost/assets/25756993/f4b63a50-5331-47c6-8277-e1e94ee068c5)

**Comment by dbarrosop** [comment]
Yes, that means your project is broken as it's missing tables and/or relationships that should be there. Are you self-hosting, using the CLI or are you using a project in our cloud? Did you modify anything in the auth schema? Have you changed auth's metadata somehow?

**Comment by ahmedabdelhafez** [comment]
i don't do any thing just copy the code from docs to create an example, andi just wake up the app it's created 3 weeks ago and i also update the package to versin 3.3.2 thats all

can you give me instructions to make it work, or should i delete it and start a new one

**Comment by dbarrosop** [comment]
If you can I'd suggest starting over, your project seems to be in a strange state and a clean start is certainly going to be the faster path.
