### ISSUE TITLE
Custom Claim Array always null with auth 0.29.1

### ISSUE THREAD

**Issue by kelkes** [nhost/nhost#2658]
**Describe the bug**
Custom Claim Array always null with auth 0.29.1

I've got a custom Claim configured like this

[[auth.session.accessToken.customClaims]]
key = 'account-ids'
value = 'account_memberships.account.id[]'

After upgrading to auth 0.29.1 its always "null". 

"x-hasura-account-ids": "null",

Downgrading to 0.26.0 (the version i used before) and it works again.

"x-hasura-account-ids": "{\"439cbb31-a2a4-4f01-b87d-1a650f66a797\"}",

Anything changed i am not aware of?

**To Reproduce**
1. Update to auth 0.29.1
2. configure a custom claim (array)
3. value is always null
4. downgrade to 0.26.0
5. value is there

**Comment by dbarrosop** [comment]
Thanks for the report, would you mind describing briefly the structure of your data to make sure we replicate exactly? Thanks again.

**Comment by dbarrosop** [comment]
Would you mind testing `0.29.2-beta1`, please?

**Comment by kelkes** [comment]
> Thanks for the report, would you mind describing briefly the structure of your data to make sure we replicate exactly? Thanks again.

```
users
> account_memberships
 > accounts
```

_tables:_
users
account_members (account_id, user_id)
accounts

**Comment by kelkes** [comment]
> Would you mind testing `0.29.2-beta1`, please?

will do thanks!
