### ISSUE TITLE
Can't Access Auth Endpoint

### ISSUE THREAD

**Issue by osseonews** [nhost/nhost#2682]
We are using Nhost Auth 0.28.1 and now every POST request to our endpoint: https://<SUBDOMAIN>.auth.us-east-1.nhost.run/v1/signin/passwordless/email returns a 500 response. The user is actually inserted into the database, but the endpoint returns a 500 error. There is no other information given. I could have sworn this worked fine the other day. We don't have any special settings or anything. Why are we suddenly getting a 500 error?

**Comment by dbarrosop** [comment]
Already being discussed via support@nhost.io
