### ISSUE TITLE
"options.phoneNumber" is not allowed.

### ISSUE THREAD

**Issue by ttiras** [nhost/nhost#269]
Not possible to insert into phoneNumber in users table.
The error message is below:
Error validating request body. "options.phoneNumber" is not allowed.

**Comment by nunopato** [comment]
@ttiras do you have a code snippet we can look at?

**Comment by ttiras** [comment]
`const { session, error } = await nhost.auth.signUp({
            email: values.email,
            password: values.password,
            options: {
              phoneNumber: values.phone
            }
          })`

**Comment by elitan** [comment]
If we allow setting `phoneNumber` through options during email signup it would make sense to allow setting `email` through options during phone signup.

So the question is: Do we allow to add `phoneNUmber` and `email` as options?

I kind of think we should allow it. If you're trying to sign up using email and password AND your provide an email through options it should give an error. Same with signing up with phone number and providing a phone number through options. It should also give an error.

If all is fine, let's insert the email/phone number. The `emailVerified` / `phonNumberVerifed` is going to default to false anyways so I don't see it as a security issue.

If all is fine, the phone
