### ISSUE TITLE
adding urql package back

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#271]
Hello

I saw that you had a v1 `urql` package, but that hasn't been re-integrated so far in v2. Are there any efforts been made so far? I use `urql` but my approach has some edges especially in dev mode and when the app gets inactive.

Thanks

**Comment by plmercereau** [comment]
Hello Dominic,
Yes, we plan to create either a tutorial or a dedicated package - and I personally love `urql`.
This is however not on the top of our priorities, let's keep the issue open until we have enough bandwidth to work on it!

**Comment by akhil-naidu** [comment]
#1050
