### ISSUE TITLE
Does self hosted solution work?

### ISSUE THREAD

**Issue by DenisOstr** [nhost/nhost#2720]
**Describe the bug**
I cloned the repository, copied the env, changed the keys and ran Docker Compose. At first hasura couldn’t connect to the database, it turns out I don’t need a password. The Hasura tab does not work in the control panel and nothing works at all and gives the error ```invalid x-hasura-admin-secret/x-hasura-access-key```

**To Reproduce**
1. Clone the repository
2. Go to /nhost/examples/docker-compose
3. Copy .env from .env.example
4. Run docker-compose

**Expected behavior**
In theory, everything should start and the control panel should work.

**Screenshots**
![image](https://github.com/nhost/nhost/assets/16721761/0cb397e3-5523-4426-8b8b-eceea5eec0cc)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Browser: Chrome
 - Version: 125.0.6422.60

**Additional context**
-

**Comment by dbarrosop** [comment]
Exact same steps work for me without any issues.

<img width="1436" alt="Screenshot 2024-05-21 at 10 28 41" src="https://github.com/nhost/nhost/assets/6246622/95d17c3b-20df-4798-bd30-3f75023c5fde">

Maybe the network tab can give you more information. In any case, this docker compose file is just a community example. Nhost cloud uses same exact images that are publicly available so there is no reason why self-hosting shouldn't work.

**Comment by bookshiyi** [comment]
Same steps and same issue
<img width="1431" alt="截屏2024-05-23 15 41 43" src="https://github.com/nhost/nhost/assets/14087838/9d28997c-94df-43d7-b2ed-347d85e8454c">

**Comment by dbarrosop** [comment]
@bookshiyi which issue are you seeing? your screenshot looks fine

**Comment by DenisOstr** [comment]
I was able to build and run fine on another device and everything works, but the hasura tab is still not available, and when creating a table and fields through the interface, it gives an error, but when using sql, everything works fine.
