### ISSUE TITLE
Permission Denied for Adding New Public Table

### ISSUE THREAD

**Issue by ronitbatra** [nhost/nhost#2722]
I'm trying to add a new table through Hasura and keep getting an error about not having permission to add a public table. I already added two tables prior to this and am only now facing trouble. I am still using the same account I have been previously and don't know when permissions changed.

**Comment by dbarrosop** [comment]
hi, which environment? Is this the cloud, the cli, self-hosted? if it's the cloud, can you share the subdomain? Thanks

**Comment by ronitbatra** [comment]
I'm using the cloud, and the subdomain is https://app.nhost.io/edtrax/edtrax-test.

**Comment by ronitbatra** [comment]
<img width="1512" alt="Screenshot 2024-05-22 at 2 24 15 PM" src="https://github.com/nhost/nhost/assets/112106439/7efdcb05-38a3-497b-9e60-51c2634c92df">
I don't have permission to create a new table, even though I was able to create two other tables previously.

**Comment by dbarrosop** [comment]
Strange, have you changed any database setting or run any SQL command that might have altered permissions? In any case, try running:

```
SET ROLE postgres;
ALTER SCHEMA hdb_catalog OWNER TO nhost_hasura;
GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO nhost_hasura;
GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO nhost_hasura;
GRANT USAGE ON SCHEMA public TO nhost_hasura;
GRANT ALL ON ALL TABLES IN SCHEMA public TO nhost_hasura;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO nhost_hasura;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO nhost_hasura;
```

**Comment by ronitbatra** [comment]
I haven't changed any settings or run any commands to alter permissions. I tried running the code you gave but it still says permission is denied for public schema.

**Comment by dbarrosop** [comment]
can you try:

```
SET ROLE postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nhost_hasura;
```

and if that doesn't work:

```
SET ROLE postgres;
GRANT CREATE ON SCHEMA public TO nhost_hasura;
```

this is very odd, have you restored a backup with pg_dump or similar? Just wondering how the permissions might have been lost.

**Comment by ronitbatra** [comment]
That worked. Thanks for your help!

**Comment by dbarrosop** [comment]
Perfect, glad to hear. Closing for now. If you have more info on the chain of events that might have led to this issue don't hesitate to let us know. Thanks!

**Comment by dbarrosop** [comment]
This issue has been identified and fix. Thanks to everybody that helped pinpoint the issue.
