### ISSUE TITLE
Question: does nHost support database transactions from client side?

### ISSUE THREAD

**Issue by vakopian** [nhost/nhost#2753]
I could not find an answer to this question in the documentation. And given that not [Supabase](https://github.com/orgs/supabase/discussions/526) nor [PostgREST](https://github.com/PostgREST/postgrest/issues/286) support it, I would like to know if nHost does before diving deeper into this project.

Thanks

**Comment by dbarrosop** [comment]
Yes but with some caveats. Graphql supports sending multiple queries/mutations in a single request and all queries/mutations included in a single request are executed in a single transaction. Multi-request transactions are not supported.

Closing as this isn't an issue. If you have further questions don't hesitate to use [discussions](https://github.com/nhost/nhost/discussions) or join us on [Discord](https://discord.com/invite/9V7Qb2U).
