### ISSUE TITLE
Nhost examples show pnpm lock file

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#2764]
There are Nhost examples showing a pnpm lock file in the functions directory. A recent change breaks the deployment when a npm or yarn lock file is not present. It would be ideal if nhost functions also support pnpm lock files. An alternate solution would be to correct all of the examples.

Statement saying pnpm is not supported: https://discord.com/channels/552499021260914688/1252204096442859581/1252227481671569504

Nhost Examples:
https://github.com/nhost/nhost/tree/main/examples/docker-compose/functions
https://github.com/nhost/nhost/tree/main/examples/quickstarts/nhost-backend/functions
https://github.com/nhost/nhost/tree/main/examples/serverless-functions/functions

There are many more example projects that use pnpm as the overall package manager.

**Comment by dbarrosop** [comment]
Yes, sorry, we were finishing up adding pnpm support which should be supported now. Thanks for the report and your understanding.
