### ISSUE TITLE
expose "refresh" on nextjs package to be able having a client side refresh of the token

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#280]
Hello

the current implementation of the `nextjs` package has some drawbacks. Especially working locally is constantly interrupted due to outdated or invalid jwt data. The main reason in my opinion is, that refetch of the token only happens on initial SSR request. But ideally the refetch also should happen if the browser window is inactive for a while and re-gains focus. Also Graphql clients like `urql` expose client side refetch capabilities on JWT errors. 

After digging deeper I found that the `nextjs` package internally uses `refresh` function. It would be great if this would be exported for API usage. Additionally a utility function would be ideal to get/set the right `refreshToken` to improve the handling of the `accessToken`. Currently I found that `@host/client` exposes `cookieStorageSetter/Getter`, does it make sense to improve this in a utility function?

Thanks

**Comment by plmercereau** [comment]
Have you tried to use `nhost.auth.refreshSession()`?

**Comment by dohomi** [comment]
@plmercereau my plan was moving away from the nhost sdk and using the `@nhost/react`and `@nhost/client` packages. It would be great if `refreshSession()` would be exposed on `@nhost/client`

**Comment by jovermier** [comment]
You can do something like this:
```
import { useNhostClient } from '@nhost/react';
...
const { auth } = useNhostClient();
auth.refreshSession();
```
