### ISSUE TITLE
Git clone impossible on Windows

### ISSUE THREAD

**Issue by JCKodel** [nhost/nhost#2807]
**To Reproduce**

```
>  git clone https://github.com/nhost/nhost
Cloning into 'nhost'...
remote: Enumerating objects: 82498, done.
remote: Counting objects: 100% (4945/4945), done.
remote: Compressing objects: 100% (2247/2247), done.
remote: Total 82498 (delta 3060), reused 4171 (delta 2576), pack-reused 77553
Receiving objects: 100% (82498/82498), 224.29 MiB | 19.21 MiB/s, done.
Resolving deltas: 100% (54274/54274), done.
error: invalid path 'docs/reference/auth/oauth-callback-url-that-will-be-used-by-the-oauth-provider-to-redirect-to-the-client-application-attention:-all-providers-are-using-a-get-operation-except-apple-and-azure-ad-that-use-post.mdx'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

> cd nhost

> dir
Volume in drive C has no label.
 Volume Serial Number is 1E2F-882D

 Directory of C:\Temp\nhost

25/07/2024  19:04    <DIR>          .
25/07/2024  19:04    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  241,072,971,776 bytes free

> git restore --source=HEAD :/
error: invalid path 'docs/reference/auth/oauth-callback-url-that-will-be-used-by-the-oauth-provider-to-redirect-to-the-client-application-attention:-all-providers-are-using-a-get-operation-except-apple-and-azure-ad-that-use-post.mdx'
```

I guess `error: invalid path 'docs/reference/auth/oauth-callback-url-that-will-be-used-by-the-oauth-provider-to-redirect-to-the-client-application-attention:-all-providers-are-using-a-get-operation-except-apple-and-azure-ad-that-use-post.mdx'` is an invalid path for Windows (it has `:`, after all) and the whole git thing fails, leaving an empty folder.

**Comment by dbarrosop** [comment]
Hi,
thanks for the report. Have you tried WSL2? Do you have any issues there?

Regards

**Comment by JCKodel** [comment]
Why I would use WSL2??? I'm on Windows! I don't need a linux shell for anything.

Nevertheless, this whole solution is very anti-native, so, I'm not using it anymore. Maybe it is good for web, but the world isn't resumed to a web environment.

**Comment by dbarrosop** [comment]
I am sorry to hear that. What do you mean with anti native? We support react native and flutter and we have plenty of customers building for mobile. What issue are you having?

**Comment by JCKodel** [comment]
> I am sorry to hear that. What do you mean with anti native? We support react native and flutter and we have plenty of customers building for mobile. What issue are you having?

That's how firebase auth works:

* I call `FirebaseAuth.instance.resetPassword(email: "foo@bar.com");`
* An e-mail is sent with a link to reset password
* The link opens a Firebase Auth page to set up a new password (I don't need to program it).

That's how nhost works:
* I call `client.auth.resetPassword(email: "foo@bar.com")` (or whatever the code is).
* An e-mail is sent with a link to reset password
* That link points to whatever is configurated on nHost settings (default to localhost:3000), so, I have to set up a whole web server to reset a password >.<

Considering I don't want to do that, I could set my redirect url to some custom protocol, such as `my-app://redirect`, so the reset password link is something like `my-app://redirect&ticket=passwordReset:9f4e6dc2-64c4-4c7a-bdb5-2565cf4c9438&type=passwordReset`.

So, grabbing that ticket number and calling the reset password confirmation method: ticket is invalid or expired.

So... not working.

(and, btw, is not possible to register a custom protocol so easily for Linux).


The whole thing appears to be web oriented only. It does NOT work with native credentials ()

**Comment by dbarrosop** [comment]
> The link opens a Firebase Auth page to set up a new password (I don't need to program it).

I am not sure how/why firebase does it but our users want to handle this in their own app/website. Also, a user using your app or website FOO trying to reset the password and being sent to a completely different company (firebase/nhost/whatever) to reset the password might be considered by most a security/privacy issue as users may not have any knowledge of this party and might regard it as an attempt at a phishing attack

> That link points to whatever is configurated on nHost settings (default to localhost:3000), so, I have to set up a whole web server to reset a password >.<

You don't need a webserver, you just need something that responds. It can be a mobile or desktop app.

> (and, btw, is not possible to register a custom protocol so easily for Linux).

You also don't need it. If you are writing a linux desktop app, the same app can open the webserver temporarily during the reset operation. That's how signin in with social works in all terminal and desktop applications as you need a callback in the oauth2 process.

> The whole thing appears to be web oriented only

We fully support dart and react-native and we have very successful mobile only customers, but we are not here to debate this point, you have your reasons to believe that and that's fine. I just want to understand the frustration to see if there is something that can be done and/or needs doing.

> It does NOT work with native credentials

I agree this is a minor shortcoming we need to fix, but there is no loss of functionality so it hasn't been a priority.

>  the whole process is incomplete (I have to implement reset password myself)

see my previous comment about phishing. I understand you may not care about that but the typical customer cares about providing a seamless experience keeping everything in their own website/application and avoid "scaring" their users.

> considering Firebase Auth is 100% free of charge

their pricing page and all of our customers that migrated from firebase disagree with this :) statement but you should use what you think is the best tool for your use case

I just want to say thanks for the feedback, if you have more feel free to reach out
