### ISSUE TITLE
`useAuthenticationStatus` status is not updated when refresh token fails

### ISSUE THREAD

**Issue by felixhagspiel** [nhost/nhost#2817]
**Describe the bug**
when a refreshtoken gets removed in the database, and the auth token expires, the SDK does a call to `/token` to check if the refresh token is valid and to obtain a new auth token. If this request fails, the hook does not update.

**To Reproduce**
1. setup a simple app and redirect the user to `/login` (or just log to console) when he is not authenticated
```
  import { useAuthenticationStatus } from "@nhost/react";
  ...
  const { isAuthenticated, isLoading } = useAuthenticationStatus();
  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.push("/login");
    }
  }, [isAuthenticated, isLoading]);
```
2. Login
3. Delete refresh tokens in database
4. wait until auth token expires
5. you can see the call returning `401` but the hook does not trigger.
<img width="837" alt="image" src="https://github.com/user-attachments/assets/7c1900f1-3867-40b1-9d5c-3f058f3dd3a0">

**Expected behavior**
Hook updates with `isAuthenticated=false`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS m1
 - Browser: Tested in Chrome & Safari
 - Version Chrome 126.0.6478.185 
    "@nhost/react": "^3.5.3",
    "@nhost/react-apollo": "^12.0.3",

**Comment by felixhagspiel** [comment]
where you able to reproduce the issue? this leaves our users currently in a broken state, as we have no way of checking if he is actually signed in or not. as this was working before I would assume that this might be [related to the fix ](https://github.com/nhost/nhost/pull/2790) you have released for the inifinite auth loop?

**Comment by dbarrosop** [comment]
sorry, this was scheduled for this week but, as usual got delayed due to reasons. We should be able to start looking into it today/tomorrow. Thanks for the pointer.
