### ISSUE TITLE
Support docker image pull secrets for nhost Run service

### ISSUE THREAD

**Issue by xmlking** [nhost/nhost#2833]
**Is your feature request related to a problem? Please describe.**
We has robust workflow with GitHub CI and pushing to **Private GHCR** (GitHub Container Registry) Registry with [Artifact Attestations](https://github.blog/news-insights/product-news/introducing-artifact-attestations-now-in-public-beta/)  
Switching  from GHCR is big change for us. We like nhost to be able to pull from **PRIVATE** GHCR with `image pull secrets`  

**Describe the solution you'd like**
**nhost** dashboard should allow storing GHCR `image pull secrets`  in **nhost** secrets and allow configure using that secret to pull `Run's` docker image.

It will simplify avoiding  double publishing steps. 

**Describe alternatives you've considered**
Have workflow to publish both registries but it is more expensive and slow 

**Additional context**
 

```[tasklist]
### Tasks
- [x] backend
- [x] cli
- [ ] https://github.com/nhost/nhost/issues/2855
```

**Comment by dbarrosop** [comment]
This is now supported:

https://docs.nhost.io/guides/run/registry#using-your-own-private-registry

We still need to expose this in the dashboard but it should work fine via the configuration file.

**Comment by xmlking** [comment]
I think it would be helpful to a add docs for other popular registry :  "ghcr.io"
