### ISSUE TITLE
self deploy question

### ISSUE THREAD

**Issue by chenkaiC4** [nhost/nhost#284]
hi, I am using [docker-compose-example](https://github.com/nhost/nhost/blob/main/examples/docker-compose/README.md) to deploy this awesome project at my digitalocean host.

After running docker-compose up, the container status is show below:

![image](https://user-images.githubusercontent.com/7543145/158569723-1e692f84-85fe-403e-a3dc-57e7d5c8fc84.png)

I can use IP:9090 to reach traefik dashborad, but can't reach auth server. also, i can't use hasura graphql console. http://IP:1337

![image](https://user-images.githubusercontent.com/7543145/158570157-21d8fce0-6c58-4bdf-8ee7-9385303f7d0a.png)

the auth container and storage both use 4000 port.

need help to fix this issue, thanks very much.

**Comment by chenkaiC4** [comment]
i try to deploy the [nhost auth](https://github.com/nhost/hasura-auth), and success!

But, the nhost auth api is not prefix with `/v1/auth` which is hard code at nhost js sdk. see below:

https://github.com/nhost/nhost/blob/d2d3ba6eb7274c3191c01cc09b99a26d2fd7fc9f/packages/nhost-js/src/core/nhost-client.ts#L43

**Comment by plmercereau** [comment]
Hello,
I can't reproduce.
The traefik reverse proxy, that redirects the traffic to the right container (hasura, hasura-auth, hasura-storage) works with localhost, not with your public IP.
Have you tried `http://localhost` instead?
