### ISSUE TITLE
[Postgres extension] pg_ivm : incremental view maintenance

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#2875]
**Is your feature request related to a problem? Please describe.**
Postgres materialized view are very costly to refresh

**Describe the solution you'd like**
Incremental View Maintenance (IVM) is a way to make materialized views up-to-date in which only incremental changes are computed and applied on views rather than recomputing the contents from scratch as REFRESH MATERIALIZED VIEW does. IVM can update materialized views more efficiently than recomputation when only small parts of the view are changed.

Would it be possible to enable pg_ivm on nhost ?

https://github.com/sraoss/pg_ivm

**Comment by dbarrosop** [comment]
Done: https://hub.docker.com/repository/docker/nhost/postgres/general
