### ISSUE TITLE
[Feature Request] Custom API Repository Path

### ISSUE THREAD

**Issue by johannesschobel** [nhost/nhost#29]
Dear @elitan ,

in the docs, i read about `Custom APIs` ( https://docs.nhost.io/custom-api ), which would really be an awesome feature.
Prior, i worked a lot with `NestJS` ( https://nestjs.com/ ), which is (at least for me) the go-to backend framework when i need to develop an API. 

For larger project, i always followed a `monorepository` approach (i.e., all of my applications (api, web application, mobile application, admin web application, ...) are stored within the same git repository. In this context, i used `nrwl/nx` to structure / maintain my monorepository. However, `nrwl/nx` has a predefined folder structure. For example, your apps are located within `apps/`!

In this context, the `custom api` would not work, because the api would be stored in `apps/awesome-api` or whatever ;) Could you please make the `api path` within the repository customizable? Somewhere in the `Settings` page or whatever?

All the best,
Johannes

**Comment by elitan** [comment]
Hi @johannesschobel 

Yea I think this make sense. We might not want to change the `api/` folder but we could allow repositories with a Nhost app in a subfolder. Similar to https://vercel.com/blog/monorepos

Could you describe a bit more in detail your preferred folder structure for your monorepo?

**Comment by johannesschobel** [comment]
Dear @elitan ,

thanks for answering to my issue / feature request.
A typical nrwl project is structured as follows:
```
apps\
  todos-www\
  todos-api\
  todos-mobile\
  todos-xyz\
libs\
  // no real defined structure of the libraries, may be feature-specific, or application specific, ...
package.json
```

So basically, all your apps reside in the `apps` folder, whereas the name of the application is customizable (does not need to be named `api` but can also be called `backend-for-todos` or whatever).

Note that `nrwl` follows the `single package.json` approach. i.e., there is only **one single** `package.json` file within the entire repository. Building specific apps (i.e., the api) is done using nrwl-specific command-wrappers, like
```
nx build <NAME>          // i.e., nx build backend-for-todos
```

This command, in turn, builds the project based on the `workspace` definition for this specific application. Furthermore, it finds related packages in the `libs` folder (i.e., `libs/api/auth`) and bundles it all together into one single application. This approach guarantees a highly reusable application structure.

In terms of the `Custom API` feature, I thought about having a `settings` parameter within the `nhost` admin console where the path within the repository may be customized. As a default value, the `/api` value may be provided. However, in my `nrwl/nx` setting, i could change it to `apps/backend-for-todos` ...

However, it is not clear to me, how i would "bundle" my application properly? Because i would need to build the app first to be deployed, right? Do we need to call custom `npm` scripts first?

All the best

**Comment by elitan** [comment]
This is now working: https://docs.nhost.io/platform/github-integration#base-directory
