### ISSUE TITLE
Unable to start nhost locally: invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by stefan-girlich** [nhost/nhost#2920]
**Describe the bug**
I am not able to start nhost locally via `nhost up` due to the following error:
`Error response from daemon: invalid mount config for type "bind": bind source path does not exist: [...omitted]/emails`

**To Reproduce**
1. Install nhost CLI
2. Run `nhost login` and authenticate
3. Run `nhost config pull`
4. Run `nhost up`
5. See error

**Expected behavior**
`nhost up` runs successfully

**Actual behavior**
```
(base) ➜  backend git:(master) ✗ nhost up
Checking versions...
✅ Auth is already on a recommended version: 0.33.0
✅ Storage is already on a recommended version: 0.6.1
✅ PostgreSQL is already on a recommended version: 14.13-20240909-1
✅ Hasura is already on a recommended version: v2.38.0-ce
✅ Nhost CLI v1.24.5 for darwin-arm64 is already on the latest version
Setting up Nhost development environment...
Starting Nhost development environment...
[+] Running 0/7
 ⠙ Network backend_default           Created                                                                              0.1s
 ⠋ Container backend-configserver-1  Created                                                                              0.1s
 ⠋ Container backend-minio-1         Created                                                                              0.1s
 ⠋ Container backend-traefik-1       Created                                                                              0.1s
 ⠋ Container backend-mailhog-1       Created                                                                              0.1s
 ⠋ Container backend-dashboard-1     Created                                                                              0.1s
 ⠋ Container backend-postgres-1      Created                                                                              0.1s
 ⠋ Container backend-graphql-1       Created                                                                              0.0s
 ⠋ Container backend-auth-1          Creating                                                                             0.0s
 ⠋ Container backend-storage-1       Creating                                                                             0.0s
 ⠋ Container backend-console-1       Creating                                                                             0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/myusername/projects/myproject/nhost/emails
failed to start Nhost development environment: failed to start docker compose: exit status 1
- Do you want to stop Nhost's development environment? [y/N] N
```

**Desktop**
 - OS: MacOS 14.5
 - Browser -
 - nhost version v1.24.5
 - Docker version 25.0.3, build 4debf41

**Comment by dbarrosop** [comment]
hello, thanks for your message. Either you are missing important and necessary folders or your docker setup has some issues. Could you run `find nhost -type d` in your project folder and share the output?

**Comment by stefan-girlich** [comment]
Thanks for the very quick answer; here's the output:
<details>
<summary>Output</summary>
nhost
nhost/migrations
nhost/migrations/default
nhost/migrations/default/1729605785775_init
nhost/emails
nhost/emails/test
nhost/emails/test/email-verify
nhost/emails/cs
nhost/emails/cs/email-verify
nhost/emails/cs/email-confirm-change
nhost/emails/cs/signin-passwordless
nhost/emails/cs/password-reset
nhost/emails/cs/signin-passwordless-sms
nhost/emails/generator
nhost/emails/bg
nhost/emails/bg/email-verify
nhost/emails/bg/email-confirm-change
nhost/emails/bg/signin-passwordless
nhost/emails/bg/password-reset
nhost/emails/bg/signin-passwordless-sms
nhost/emails/fr
nhost/emails/fr/email-verify
nhost/emails/fr/email-confirm-change
nhost/emails/fr/signin-passwordless
nhost/emails/fr/password-reset
nhost/emails/fr/signin-passwordless-sms
nhost/emails/es
nhost/emails/es/email-verify
nhost/emails/es/email-confirm-change
nhost/emails/es/signin-passwordless
nhost/emails/es/password-reset
nhost/emails/es/signin-passwordless-sms
nhost/emails/en
nhost/emails/en/email-verify
nhost/emails/en/email-confirm-change
nhost/emails/en/signin-passwordless
nhost/emails/en/password-reset
nhost/emails/en/signin-passwordless-sms
nhost/seeds
nhost/metadata
nhost/metadata/databases
nhost/metadata/databases/default
nhost/metadata/databases/default/tables
</details>

**Comment by stefan-girlich** [comment]
I was able to get the local environment running by stopping and deleting all existing nhost containers, deleting `nhost/` and re-running the steps above with the third step being `nhost init --remote`.
I will let you know if I find more hints concerning the original errors. 

Concerning the `--remote` flag: I found this via Google search, but I could not find actual documentation for this flag. Does it serve the same purpose as `nhost config pull`?

**Comment by dbarrosop** [comment]
Closing this as this isn't an issue.

> Concerning the --remote flag: I found this via Google search, but I could not find actual documentation for this flag. Does it serve the same purpose as nhost config pull?

For up to date information I'd suggest using `--help`:

```
nhost init --help
NAME:
   nhost init - Initialize a new Nhost project

USAGE:
   nhost init [command options]

OPTIONS:
   --remote    Initialize pulling configuration, migrations and metadata from the linked project (default: false) [$NHOST_REMOTE]
   --help, -h  show help
```

As you can see from the help it will download a bunch of things from the remote project. The rest will be initialized with defaults. So, to answer your questions, yes, one of the thing it does is equivalent to `nhost config pull`.

**Comment by caudurodev** [comment]
Getting similar issue - in a new nhost project - I upgraded to the latest postgres, hasura and auth versions (from the dashboard). It worked on the server, but locally, after resetting all images and nhost files:

`Error response from daemon: invalid mount config for type "bind": stat .nhost/data/main/minio: operation not permitted`

I presume there is an incompatibility somewhere for local dev development with the latest versions?

**Comment by dbarrosop** [comment]
That is most likely an issue with your environment. Try:

```
nhost down --volumes
rm -rf .nhost
nhost up
```

If that doesn't fix it the issue might be on your docker setup.
