### ISSUE TITLE
can't find my production Database tables on my local

### ISSUE THREAD

**Issue by Nabinsharma123** [nhost/nhost#2985]
i created some tables on nhost cloud. now when i set up nhost localy my database tables which i created on cloud is not there on my local. i want to sync my local with cloud

**Comment by dbarrosop** [comment]
There is no sync mechanism. You can initiate the local project from an existing cloud project by running `nhost init --remote` but this mechanism isn't meant as a continous syncing tool. The supported workflow is:

1. Make changes locally
2. Commit to git so we deploy the changes in your git repository to your connected projects.

If you haver further questions don't hesitate to let us know.
