### ISSUE TITLE
Provide additional (or useful) details on Project Tiles

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#2995]
The new Projects view on the new dashboard UI shows project tiles.   

<img width="215" alt="image" src="https://github.com/user-attachments/assets/b4ccf999-41be-46c9-aec4-569d18555470">

Right now, it shows a sentence I cannot really even read.  I think it says "deployed xx days ago".  I had to make my window smaller to read it fully.  :)

But, on large screens, it doesn't show much.  For example ,it doesn't show sleep/wake or build status.   Or custom icons.

**Comment by dbarrosop** [comment]
Thanks, good point. Will try to fix as soon as possible.
