### ISSUE TITLE
Each token refresh causes useQuery to rerun the query

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#301]
Verified the issue using Nhost example react-apollo.
![image](https://user-images.githubusercontent.com/7989760/160400447-f2cd5d53-8c22-41d4-8481-6799359727dc.png)
![image](https://user-images.githubusercontent.com/7989760/160400589-b4c676c6-706d-490b-9e6b-b4d796971503.png)

**Comment by szilarddoro** [comment]
Thanks for the issue @jovermier! 

Since `accessToken` is used in `useQuery` as a request header, it makes sense to rerun the query. Changing any state that is not necessary for `useQuery` to work would not rerun it. Please let us know if you have further questions.

**Comment by szilarddoro** [comment]
Thank you for clarifying the issue! I'm going to prepare a PR for this soon.

**Comment by szilarddoro** [comment]
Thanks for the clarification. We'll investigate this issue and get back to you once we have a proper solution.

**Comment by szilarddoro** [comment]
`@nhost/apollo@0.3.1` and `@nhost/react-apollo@4.0.3` should fix the issue @jovermier. Don't hesitate to reopen this issue if you keep experiencing this behaviour.
