### ISSUE TITLE
nhost-js client logs out a user that was logged in with a different nhost-js client instance

### ISSUE THREAD

**Issue by darrow97** [nhost/nhost#3019]
**Describe the bug**

A project relies on two different Nhost databases and connects to each one through separate nhost-js client instances.

Client A refers to the nhost-js client that is instantiated with the subdomain and region of the project's primary Nhost Database.
Client B refers to the nhost-js client that is instantiated with the subdomain and region of the project's secondary Nhost Database and is disconnected from using LocalStorage and does not store anywhere any of the items that would normally be stored in LocalStorage.

When a user logs out with Client B while being logged into Client A, the user is logged out of both Client B and Client A.

**To Reproduce**
1. Create two Nhost projects (for reference, the primary project is A and the secondary is B)
2. In project A, instantiate two nhost-js clients:
     * Project A: instantiate a nhost-js client with the subdomain and region of project A and leave the default storage to LocalStorage (for reference, this is Client A)
     * Project B: instantiate a nnhost-js client with the subdomain and region of project B and set the clientStorageType to `custom`and 'clientStorage' to `{ getItem: (key) => null, setItem: (key_ => null, removeItem: (key) => null }`
4. Generate a user in project A and project B
5. Generate a PAT for the user in project B
6. From project A
     * Sign in with Client A
     * Use the PAT generated in step 5 to sign in with Client B
     * While still signed in with Client A, log out of the secondary project by logging out with Client B
8. At this point, Client B and Client A will have logged out the logged in users

**Expected behavior**
While a user is logged in with Client A, the user can log in to and out of Client B without logging out of Client A

**Screenshots**
N / A

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04.6 LTS
 - Browser: Brave 
 - Version: v1.69.153

**Smartphone (please complete the following information):**
 - N / A

**Additional context**
We encountered this issue while developing project A in a local nhost instance and project B was a deployed Nhost remote instance.

**Comment by dbarrosop** [comment]
can you provide the exact parameters you are passing when instantiating both clients? (no need to share real subdomains)

**Comment by darrow97** [comment]
of course!

The nhost-js clients were initialized as follows:
```js
const clientA = new NhostClient({
    region: "us-east-1",
    subdomain: `${projectA.subdomain}`
});

const clientB = new NhostClient({
    region: "us-east-1",
    subdomain: `${projectB.subdomain}`,
    autoRefreshToken: false,
    clientStorageType: 'custom',
    clientStorage: {
        getItem: (key) => null,
        setItem: (key, value) => null,
        removeItem: (key) => null
    }
});

```

**Comment by dbarrosop** [comment]
Thanks! I will forward the issue to a colleague to take a look. I suspect this might be related with some internal broadcasting we do.
