### ISSUE TITLE
Error on installing nhost - react native package

### ISSUE THREAD

**Issue by pmwangi5** [nhost/nhost#3027]
I wanted to stat setting up a mobile app to utilize my Nhost account. I read through the manual provided here (https://nhost.io/blog/official-support-for-react-native) and ran the installation below using node v18.20.2

npx react-native init myapp --template @nhost/react-native-template

It started installing and ran into the error below:

✔ Downloading template
✔ Copying template
✔ Processing template
⠸ Installing dependencies

error An unexpected error occurred: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-dom@18.3.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0 || ^18.0.0 || >=19.0.0-rc <19.0.0" from @apollo/client@3.11.10
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.10.4" from the root project
npm ERR!     peer @apollo/client@"^3.7.10" from @nhost/react-apollo@12.0.6
npm ERR!     node_modules/@nhost/react-apollo
npm ERR!       @nhost/react-apollo@"^12.0.2" from the root project
npm ERR!     1 more (@nhost/apollo)
npm ERR!   20 more (@nhost/react-apollo, @nhost/react, react-native, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.3.1" from react-dom@18.3.1
npm ERR! node_modules/react-dom
npm ERR!   peerOptional react-dom@"^16.8.0 || ^17.0.0 || ^18.0.0 || >=19.0.0-rc <19.0.0" from @apollo/client@3.11.10
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.10.4" from the root project
npm ERR!     2 more (@nhost/react-apollo, @nhost/apollo)
npm ERR!   peer react-dom@"^17.0.0 || ^18.0.0" from @nhost/react-apollo@12.0.6
npm ERR!   node_modules/@nhost/react-apollo
npm ERR!     @nhost/react-apollo@"^12.0.2" from the root project
npm ERR!   1 more (@nhost/react)
npm ERR!
npm ERR! Conflicting peer dependency: react@18.3.1
npm ERR! node_modules/react
npm ERR!   peer react@"^18.3.1" from react-dom@18.3.1
npm ERR!   node_modules/react-dom
npm ERR!     peerOptional react-dom@"^16.8.0 || ^17.0.0 || ^18.0.0 || >=19.0.0-rc <19.0.0" from @apollo/client@3.11.10
npm ERR!     node_modules/@apollo/client
npm ERR!       @apollo/client@"^3.10.4" from the root project
npm ERR!       2 more (@nhost/react-apollo, @nhost/apollo)
npm ERR!     peer react-dom@"^17.0.0 || ^18.0.0" from @nhost/react-apollo@12.0.6
npm ERR!     node_modules/@nhost/react-apollo
npm ERR!       @nhost/react-apollo@"^12.0.2" from the root project
npm ERR!     1 more (@nhost/react)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:

**Comment by dbarrosop** [comment]
I am closing this issue as #3025 should've fix this but re-open otherwise, please.
