### ISSUE TITLE
Error occurs while sign-up using IdToken (Google One Tab SignIn)

### ISSUE THREAD

**Issue by raja-ilayaperumal** [nhost/nhost#3035]
We are trying to integrate the Google One Tab sign-in using new API(/signin/idtoken).

**It is not working for the new sign-up, it gives the below error,**

{"time":"2024-11-26T11:53:59.922650293Z","level":"ERROR","msg":"error inserting user","trace":{"trace_id":"edef89cb-d553-4345-9daa-83bade2c3d72","span_id":"","parent_span_id":""},"request":{"client_ip":"14.142.183.42","method":"POST","url":"/v1/signin/idtoken"},"error":"error inserting user: ERROR: null value in column "ticket_expires_at" of relation "users" violates not-null constraint (SQLSTATE 23502)"}

**Comment by dbarrosop** [comment]
Hello,
thanks for reporting, can you try using `v0.36.0-beta1` and let us know if the issue is fixed?

Thanks!

**Comment by raja-ilayaperumal** [comment]
Yes, It is working fine. Can I use this version in the production for now?

**Comment by dbarrosop** [comment]
yeah, I will be releasing a new "stable" version soon but it will basically be the same exact build so no need for you to wait

**Comment by raja-ilayaperumal** [comment]
Sure. Thanks for helping us on time.
