### ISSUE TITLE
Email template subject modification (OTP)

### ISSUE THREAD

**Issue by marcusrohden** [nhost/nhost#3045]
Hey everyone,

The OTP feature is working great and, I was thinking, it would be super helpful if we could customize the email template subject.

For example, it’d be amazing if the OTP code could be included right in the subject of the email. This would make it so much easier for users to spot their code at a glance without needing to open the email.

**Comment by dbarrosop** [comment]
Closing as this is supported already, feel free to reopen if you tried and it isn't working though. Also, feel free to keep commenting if you have questions.

As mentioned above, this can be done already, just override the email templates. You can find the supported variables here (the OTP is the ticket): 

https://docs.nhost.io/guides/auth/email-templates#template-variables
