### ISSUE TITLE
Nhost CLI init and login fail with 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by my-nemu** [nhost/nhost#3076]
**Describe the bug**
Since at least 10pm Pacific Time 12/12 I've been getting a 503 error with the nhost CLI when calling nhost init or nhost login.

```
nhost init --remote
Initializing Nhost project
Pulling config from Nhost...
main.go:67: failed to initialize remote project: failed to pull config: failed to get nhost client: failed to load session: failed to login: failed to login: request validation failed: unexpected status code: 503, message: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

```
% nhost --version
nhost version v1.28.0
```

With nhost login I see a webpage with the following text and login does not complete.

```
503 Service Temporarily Unavailable
nginx
```

```
% nhost login    
Select authentication method:
1. PAT                       
2. Email/Password            
3. Github                    
- method: 3
Opening browser to sign-in
Waiting for sign-in to complete
```

**To Reproduce**
1. Run nhost init --remote
You'll see the 403 error in the CLI

or

1. Run nhost login w/ github
You'll see the 503 error within the web browser.

**Expected behavior**
The commands should work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: mac Sanoma 14.6
 - Browser Chrome
 - Version 131.0.6778.109 (Official Build) (arm64)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by dbarrosop** [comment]
You need to update to the latest CLI, if that doesn't fix the issue feel free to reopen it. Thanks!
