### ISSUE TITLE
[Dashboard] Unable to reconnect project to new GitHub organization repository

### ISSUE THREAD

**Issue by chiemerieokorie** [nhost/nhost#3078]
Describe the bug
After moving my repository to a new GitHub organisation, I cannot connect it to my Nhost project. The repository does not appear in the selection list. I tried removing all repositories from my Nhost account and trying to reconfigure, no repositories show up at all. Every time I attempt to reconnect, it redirects me to connect my GitHub account again.

This issue is blocking me from deploying the latest updates to my project.

To Reproduce
	1.	Move a GitHub repository to a new organization.
	2.	Attempt to connect the repository to a project in Nhost via the settings.
	3.	Remove all repositories from the Nhost account to reconfigure.
	4.	Try reconnecting GitHub—no repositories show up, and it repeatedly redirects to connect the GitHub account.

Expected behavior
The repository in the new organization should appear in the selection list, and I should be able to connect it to my Nhost project without being prompted to reconnect my GitHub account repeatedly.

Screenshots
<img width="862" alt="image" src="https://github.com/user-attachments/assets/e79e0602-a5dd-4e02-92ed-1102b9e07e01" />
1. Dashboard shows unconnected Git Repo

<img width="872" alt="image" src="https://github.com/user-attachments/assets/395cc6de-c302-4397-9f54-a888441e5530" />
2. Prompts me to connect to Github Account 

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/acef0825-7e0a-4ac5-abe5-6af04a3afa8b" />
3. Successfully connected Nhost to Githhub Org.

4.  After reloading Dashboard, problem persists as seen in 1  and 2 above.

Desktop and Smartphone
N/A

Additional context
	•	The Nhost app seem to be properly connected on GitHub’s side.
	•	The repository worked before moving it to a new organisation.
	•	This issue is preventing me from deploying the latest updates to my project.

**Comment by dbarrosop** [comment]
Please, open a support ticket. We cannot help you with this via this channel. Thanks!
