### ISSUE TITLE
Calling auth from functions results in error 

### ISSUE THREAD

**Issue by ArieJones** [nhost/nhost#308]
This was working in previously but now after updating things to the nextjs package and using the node-js package for the functions it appears there is an issue in trying to call any of the auth endpoints.... 

Specifically, we were needing to implement a more complicated flow around signup .. so this was implemented in a function endpoint hooked up to a Hasura action ... 

pretty straightforward... 

```         
const creds: SignUpParams = {
                email: params.email,
                password: params.password ?? '',
                options: {
                    displayName: params.display_name,
                    defaultRole: 'user',
                },
            }

            const { error } = await nhost.auth.signUp(creds)

            if (error) {
                console.log('error: an error occurred trying to create the account via normal endpoint')
                return ApiResponses.handleApiError(res, error, error.message)
            }
```

and then afterwards we hookup a bunch of stuff based on the proposed users role.... 

So now after we hit the signUp call it just sits there and spins... and we eventually get this in the backend 

`2022/03/30 17:12:34 http: proxy error: context canceled`

On the same instantiation of the sdk though the graphql endpoint is working .. I dunno.. 

this is the current packages being used.. 

![image](https://user-images.githubusercontent.com/14859781/160944248-5099a27e-9a5e-42d0-a1c5-81cb8ce761af.png)

Thanks!

**Comment by elitan** [comment]
Can you do a console.log of `creds` and paste it here? then I'll test it on my end.

**Comment by ArieJones** [comment]
Here is what is being sent... 

```{
    "email": "julie@example.com",
    "password": "password",
    "options": {
        "displayName": "Julie Jones",
        "defaultRole": "patient",
        "allowedRoles": [
            "me",
            "user",
            "patient"
        ]
    }
}```

**Comment by ArieJones** [comment]
Note: this is happening on the front end now that I have reworked the code in the app to pull those signUp, signIn calls out of the functions....on functions though the call to signUp or signIn ... depending on whether I want the user to have the password preset by the admin or send them in through a magic link and then flow them into setting their password... just dies.. causing the WSL2 console to post the error I stated above 

```2022/03/30 17:12:34 http: proxy error: context canceled```

**Comment by plmercereau** [comment]
I see two problems in one:
- `http: proxy error: context canceled`: the next release with [this PR](https://github.com/nhost/nhost/pull/315) should solve the problem
- `"options.allowedRoles" must be one of ...`: could you tell the auth version you are using? You can get it with `http://localhost:1337/v1/auth/version` (or `https://your-app.nhost.app/v1/auth/version` when using nhost cloud)

**Comment by ArieJones** [comment]
Yeah it is using 

```{"version":"v0.3.2"}```

I tried updating the nhost cli... and removing the local images and then refiring up nhost .. but it pulls down the same version..

**Comment by plmercereau** [comment]
> * `"options.allowedRoles" must be one of ...`: could you tell the auth version you are using? You can get it with `http://localhost:1337/v1/auth/version` (or `https://your-app.nhost.app/v1/auth/version` when using nhost cloud)

It seems you are bumping into [this issue](https://github.com/nhost/hasura-auth/issues/116). It is solved in [Hasura Auth v0.5.0](https://github.com/nhost/hasura-auth/releases/tag/v0.5.0). We are working hard into making it available in Nhost cloud.

In the meantime, here is how you could configure your local `nhost/config.yaml` to choose your Hasura Auth version:
```yaml
services:
  auth:
    version: 0.5.0
```

**Comment by ArieJones** [comment]
Ahh.. okee dokee.

**Comment by elitan** [comment]
Did the version update fix the issue @ArieJones ?

**Comment by ArieJones** [comment]
I seem to be able to do signups again .. so the "options.allowedRoles" error seems to be gone.. 

but trying to call auth from within a function.. like I have a create-new-user function is a no go and still produces the 

```2022/04/01 08:05:04 http: proxy error: context canceled```

I have refactored my code though around this for now to just handle the signup and stuff some data into the metadata field that is then picked up by a triggered event and processed..

**Comment by plmercereau** [comment]
Should be solved on [next release](https://github.com/nhost/nhost/pull/316)
