### ISSUE TITLE
NhostClient constructor error using expo

### ISSUE THREAD

**Issue by fanr870606** [nhost/nhost#309]
Hi, I'm using expo (version 44.0.0) to create an android application and when I tried to create an instance of NhostClient I got the following error:

_undefined is not an object (evaluating 'window.location.origin')_

```
import * as SecureStore from 'expo-secure-store';

const nhost = new NhostClient({
  backendUrl: 'https://gryxhdcysynxvbznyxlp.nhost.run',
  clientStorageType: 'expo-secure-storage',
  clientStorage: SecureStore,
});
```

I think the problem is in the following line:

https://github.com/nhost/nhost/blob/e405b738a62dc4cda7e78cd2edba776d1066e88c/packages/core/src/client.ts#L21

`typeof window` is resolved as an object

Thanks in advance.

**Comment by plmercereau** [comment]
Hello,
Thanks for the issue and for locating the bug!
We'll publish a patch soon
