### ISSUE TITLE
Support Gitmojis on Deployments screen

### ISSUE THREAD

**Issue by jmarbutt** [nhost/nhost#32]
![image](https://user-images.githubusercontent.com/1386587/116262581-49a08680-a73e-11eb-9c7f-4e484a349f7f.png)

On the Deployment screen it would be awesome to support gitmojis. This is a minor suggestion but would line up with github support

**Comment by elitan** [comment]
Hmm, how can we support this? Is there a good react lib?

**Comment by jmarbutt** [comment]
I think this might work https://www.npmjs.com/package/react-emoji but I can validate it
