### ISSUE TITLE
React hook approach (feedback needed)

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#322]
We're currently discussing how we should handle our hooks in React and we would like to get input from the community.

The way I see it we have three options:

## Option 1

_(This is how it's currently working)_

```js
const { signUpEmailPassword, isLoading, isSuccess, needsEmailVerification, isError, error } =
  useSignUpEmailPassword()

// Simplified
const obj = useHook();
```

## Option 2

```js
const [signUpEmailPassword, {isLoading, isSuccess, needsEmailVerification, isError, error }] =
  useSignUpEmailPassword()
  
// Simplified
const [ action, state ] = useHook();
```

## Option 3

```js
const [{isLoading, isSuccess, needsEmailVerification, isError, error }, signUpEmailPassword] =
  useSignUpEmailPassword()
  
// Simplified
const [ state, action ] = useHook();
```

**Comment by sangdth** [comment]
May I ask the reason behind this? What is the problem with option 1?

Option 2 look like the useMutation :D I think our hook works similar with the useMutation so it's OK-ish.

Option 3 look like the useReducer, but I'm not sure how about it. Looks strange and uncomfortable to me.

**Comment by ioss** [comment]
I'd keep Option 1. 
Arrays are mostly good for not having to "destructure-rename" the variables. But in this case, the function is actually one of the names, that rarely need to be changed, opposed to isLoading, error, ... . 

Option 2 will get strange if you ever decide to add another method to what the hook return: `[fun1, { ...values }, fun2, fun3]`

Option 3 would be ok for extending the signature, but so is 1

**Comment by jladuval** [comment]
Option 1 is working fine. If you're looking to change then option 2 would be close to how mutation hooks are defined, so I suppose a minor improvement.

**Comment by szilarddoro** [comment]
I agree with previous comments that Option 1 should be good. @ioss made a good point about the “destructure-rename” feature of arrays, and in our case renaming shouldn’t be a problem. Normally users would have only one hook call. `useState` and similar React hooks use arrays as return values because generally more than one instance is going to be used in components and users of these hooks should rename everything constantly.

I’m voting for Option 1.

**Comment by sangdth** [comment]
One thing I dont like the array is, when I dont want something in smaller index, it looks super ugly

Example:
```javascript
// Array
const [ , , onlyWantThis] = useSomething();

// Object
const { onlyWantThis } = useSomething();
```

**Comment by jovermier** [comment]
Option 1 or Option 2 look good to me. Option 3 is harder to use if state is not needed.

Option 2 looks like the apollo useMutation pattern.

Option 1 is probably the simplest which is how I'm leaning.

**Comment by elitan** [comment]
Thanks for all the feedback. We'll continue with option 1 👍
