### ISSUE TITLE
Large downloadExpiration values will return 500 errors when trying to create a presignedUrl

### ISSUE THREAD

**Issue by jladuval** [nhost/nhost#323]
I haven't got the exact number here but a large value for downloadExpiration can cause the presignedUrl function to return a 500 error,
Setting the downloadExpiration to 2592000 (one month in seconds) returned  500 error. 
Setting it to 604600 (a week) returned a successful response.

**Comment by dbarrosop** [comment]
That is correct, the maximum value supported for presigned URLs is 7 days.

**Comment by elitan** [comment]
@dbarrosop We should probably add a **Postgres check constraint** in Hasura Storage for the `storage.download_expiration` column to make sure the value is between 1 and 604600 (included). 

That way users will never insert an incorrect value and have to debug this 500 error on their side.

What do you think?

**Comment by dbarrosop** [comment]
Make sense, I opened nhost/hasura-storage/pull/54

**Comment by elitan** [comment]
Perfect. I'll wait to close this issue until it's released to Nhost Cloud / CLI.

**Comment by dbarrosop** [comment]
Fixed via https://github.com/nhost/hasura-storage/pull/55

Let me know if you have any questions, comments or concerns.
