### ISSUE TITLE
Module '"@nhost/react"' has no exported member 'NhostReactProvider'

### ISSUE THREAD

**Issue by guven8** [nhost/nhost#324]
I am trying to import NhostReactProvider from @nhost/react 0.4.1 but I'm getting the following error: 

`Module '"@nhost/react"' has no exported member 'NhostReactProvider'`

when I look in node_modules/@nhost/react/src folder, only the index.ts file is present, provider.tsx, helpers.ts, utils.ts and hooks/ are all missing.

Steps to reproduce:

1. create a new react project with create react app
2. `yarn add @nhost/react`
3.  modify src/index.js to match the documentation [configuration](https://docs.nhost.io/reference/react#configuration)

**Comment by elitan** [comment]
That's very strange. I have the following code [here](https://github.com/nhost/nhost/blob/main/examples/react-apollo-crm/src/App.tsx#L2) and that works for me.

Could you double-check the setup and configuration on your side?

**Comment by guven8** [comment]
I didn't change anything my end but seems to be working now, thanks.

**Comment by plmercereau** [comment]
Related to #326 
Glad the problem is solved
