### ISSUE TITLE
useNhostClient produces error 

### ISSUE THREAD

**Issue by ArieJones** [nhost/nhost#327]
When updating to the latest version of the @nhost packages on a Nextjs app it appears that they is an issue with useNhostClient .. 

![image](https://user-images.githubusercontent.com/14859781/161385956-b96a6996-d073-4660-b3af-8222e9d8d01f.png)

it produces the following error 

![image](https://user-images.githubusercontent.com/14859781/161385983-ca70dff5-4ae3-4d96-8ed0-6c00406612c8.png)

when making a simple call 

```
import { FC } from 'react'
import AddressBox from './AddressBox'
import { useNhostClient } from '@nhost/nextjs'


const InvoiceTemplate: FC = () => {
  const client = useNhostClient()
  console.log(client.graphql.getUrl())
```
  
  

even though it does in fact print out the url .... 
  
 
![image](https://user-images.githubusercontent.com/14859781/161386138-55c7a15e-a280-458e-a9d8-c68589fe6022.png)

**Comment by DominikGuzei** [comment]
Having the same issue 👍 downgrading to the previous versions in the diff resolved the issue for me

**Comment by plmercereau** [comment]
Hello,
A patch has been released, please update your dependencies.
Closing the issue for now, don't hesitate to reply to this thread if you still encounter this problem
