### ISSUE TITLE
Stuck at Creating Project

### ISSUE THREAD

**Issue by seyaobey-dev** [nhost/nhost#33]
Hi. I am evaluating this new product. I've just following the getting started guide and tried to create a "todos" app but now the process has been stuck on the "Creating your project..." step (Nhost console) for days now. Even when I pick my answers and move ahead, the process does not complete and stays at this step for hours.

![image](https://user-images.githubusercontent.com/83374925/116600914-25090200-a92a-11eb-95ff-ad8154f92981.png)

**Comment by nunopato** [comment]
@seyaobey-dev Thank you for letting us know. We had a small (~15) number of projects getting stuck because of an issue we had with one of our servers. 

Regarding your project, I deleted it for you, feel free to create another one - I see you have another project running 👍

**Comment by elitan** [comment]
Closing for now. Let us know if this was not solved.
