### ISSUE TITLE
Public API To Create Apps

### ISSUE THREAD

**Issue by jmarbutt** [nhost/nhost#336]
It would be great to have a public API for creating apps. This would allow Saas type products to create unique apps for their customers. For many B2B type customers sometimes it is ideal to create isolated storage, auth and database. Would be amazing to do this through Nhost. 

Questions:

- Allow a way to set deployment from Github?
- Duplicate an existing app? This may make the GitHub deployment and other settings easier.

**Comment by dbarrosop** [comment]
We do have such API, it is basically how our dashboard operates. If you are interested in building an integration feel free to reach out, happy to help out.
