### ISSUE TITLE
Export typescript types

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#337]
Export `User`, `NhostSession`, and `NhostApolloClientOptions`

**Comment by plmercereau** [comment]
You can already import the above types:
```js
import type { NhostApolloClientOptions } from '@nhost/apollo'
import type { User, NhostSession } from '@nhost/core'
```

**Comment by jovermier** [comment]
Great. For some reason my VS code wasn't detecting those import options. I am only installing `@nhost/react` and `@nhost/react-apollo` in the package.json file which might limit vs code from auto-detecting imports from support packages. Thanks
