### ISSUE TITLE
[Blocking] Permission Variables are not in JWT token any more

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#338]
Since this morning, permissions variables are not in the JWT anymore.
This worked well before

![image](https://user-images.githubusercontent.com/1137511/161703776-32a748d3-9592-4c58-9afb-e1cf988fd8dd.png)

![image](https://user-images.githubusercontent.com/1137511/161704212-0af71bf5-5c35-4ce4-ba20-ebd0ffe37a79.png)

I am not the only user with this issue :
![image](https://user-images.githubusercontent.com/1137511/161704319-7c6ea058-9034-47b6-b53d-5f20244f020e.png)

**Comment by plmercereau** [comment]
Hello,
We found the bug and are rolling out the fix right now.
@NesManrique could you close this issue once it's done?

**Comment by quentin-decre** [comment]
This is fix on my side. Thank you.
