### ISSUE TITLE
Allow Disabling Anonymous Registration in Projects

### ISSUE THREAD

**Issue by jmarbutt** [nhost/nhost#35]
It would be great to disable Anonymous registration from so that it cannot be controlled by an account admin. It seems that this could potentially be a security hole for some applications. 

I am not sure if this belongs here or the backend plus.

**Comment by plmercereau** [comment]
Hello,
It is possible to disable anonymous sign-in in [Hasura-auth](https://github.com/nhost/hasura-auth) in setting `AUTH_ANONYMOUS_USERS_ENABLED` to `false`.
Hasura-backend-plus is not actively maintained, but any contribution to set a similar flag in it is welcome!
