### ISSUE TITLE
Versioning of storage rules

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#36]
A versioning of the last saved storage rule settings would be great to "fallback" to the last working version.

Probably someone screwed up his rules and has a struggle right now.. probably that someone is me ...:-|

**Comment by elitan** [comment]
Will be solved by https://github.com/nhost/hasura-backend-plus/discussions/516. All permissions will be part of regular Hasura permissions.

**Comment by elitan** [comment]
Storage rules are now part of Hasura permissions.
