### ISSUE TITLE
Incorrect typing for getNhostSession

### ISSUE THREAD

**Issue by zerosym** [nhost/nhost#371]
I believe `NextPageContext` should be `GetServerSidePropsContext` instead.  

https://github.com/nhost/nhost/blob/744fd6929febe33ed929c190839977117c4b0129/packages/nextjs/src/get-session.ts#L10

**Comment by szilarddoro** [comment]
Hey @zerosym 👋🏼 Could you attach your `package.json` file, so that we can double-check if the correct package version is being used?

**Comment by zerosym** [comment]
I included some of the relevant package versions I'm using below, though I've also tried it with the nextjs example in your repo with the same result.  As I understand it `getNhostSession` is meant to be used in `getServerSideProps` which has a different (though similar) context signature to `NextPage` function components.

```typescript
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const nhostSession = await getNhostSession(BACKEND_URL, context)
  return {...}
}
```

```
Types of parameters 'context' and 'context' are incompatible.
    Type 'GetServerSidePropsContext<ParsedUrlQuery, PreviewData>' is missing the following properties from type 'NextPageContext': pathname, AppTree
```

Packages: 

``` 
"dependencies": {
    "@apollo/client": "^3.5.10",
    "@nhost/nextjs": "^1.0.10",
    "@nhost/react": "^0.5.0",
    "@nhost/react-apollo": "^4.0.10",
    "graphql": "^16.3.0",
    "graphql-tag": "^2.12.6",
    "next": "12.1.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "17.0.23",
    "@types/react": "17.0.43",
    "@types/react-dom": "17.0.14",
    "prop-types": "^15.8.1",
    "typescript": "4.6.3",
  }
```

**Comment by szilarddoro** [comment]
`@nhost/nextjs@1.0.13` should fix this issue. Let us know if you see the same issue happening.
