### ISSUE TITLE
cannot quite workout how to use graphql.request with signed-in user

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#373]
I'm using nhost v2 with Vue3, and it's not quite clear how to use it properly.
After user logged-in I'm keeping nhost session and client in pinia store.
When (after login) there is nhost.graphql.request I see that it lacks authorization header, which obviously gives error (for tables where I've set permissions).
[{"extensions": {"path": "$","code": "validation-failed"},"message": "no mutations exist"}]
looking through methods I see there is setAccessToken, so I've set nhost.graphql.setAccessToken(nhost.auth.getSession().accessToken);
And it worked after that. But there is no token refreshing, so it is stopping working after 15 minutes (default expiration time), 
[{"extensions": {"path": "$","code": "invalid-jwt"},"message": "Could not verify JWT: JWTExpired"}]
it's not clear when and how to refresh token and why SDK doesn't handle it?
What am I missing? I'm reading official docs and I've tried to update to latest SDK
(npm update @nhost/nhost-js "up to date")
could it be error on my side? (could I erase something when saving client/session in Pinia store?)

**Comment by Vincebe** [comment]
I'm not using Pinia but vue 3 composables, and same behaviour.

After a successful `signIn()`, calling `nhost.graphql.request()` is done without auth header and with `"x-hasura-role":"public"`

With `nhost.graphql.setAccessToken`, the request is sent with correct header and role.

**Comment by Vincebe** [comment]
Note that this it's esay to handle with `onTokenChanged` and `onAuthStateChanged` but idk if this is the correct beahvior or not as the SDK doc says 

> [Security](https://docs.nhost.io/reference/sdk#security)
The SDK manages refresh tokens automatically to respect the permission rules of your Nhost apps. Requests will be anonymous by default, and when you use the SDK to log a user in, the permissions for that user will be used for GraphQL, storage and cloud function calls.

**Comment by remoorejr** [comment]
I ran into this today. Spent hours on it. Would be nice if the official docs were in line with the code base.

**Comment by elitan** [comment]
@remoorejr Are you also using Vue or some other framework?

**Comment by remoorejr** [comment]
No framework at all.

**Comment by elitan** [comment]
I can confirm this bug:

Running the following code only works if I set select permissions for the `public` role even if the users is signed in:

```js
import { NhostClient } from '@nhost/nhost-js'

const nhost = new NhostClient({
  backendUrl: 'https://....nhost.run'
});

(async () => {
  // Sign in user
  const signInResponse = await nhost.auth.signIn({
    email: '...',
    password: 'Password123...'
  })

  // Handle sign-in error
  if (signInResponse.error) {
    // throw signInResponse.error
    console.log(signInResponse.error)
    return
  }

  // Get todos
  const todos = await nhost.graphql.request(`
    query {
      todos {
        id
        created_at
        name
        is_completed
      }
    }
  `)

  console.log(JSON.stringify(todos.data, null, 2))
  console.log(todos.error)
})()
```

**Comment by yureckey** [comment]
ugh, 1.0.10 version fixes it only partially - initial call works, but token is not refreshes (or refhreshed but not added to call), so I still got error 'Could not verify JWT: JWTExpired' after 15 minutes

**Comment by Vincebe** [comment]
Idem. And `onTokenChanged` seems not to be triggered.

**Comment by yureckey** [comment]
Yay! It works!
btw, I noted that onTokenChanged fires about every 2 minutes, as that how it suppose to work?
