### ISSUE TITLE
Unexpected behavior regarding authentication with the React SDK - needsEmailVerification

### ISSUE THREAD

**Issue by gdangelo** [nhost/nhost#374]
Hello,

I've stumbled upon an edge case / unexpected behavior regarding authentication with the React SDK.

In a nutshell, the value of the `needsEmailVerification` variable seems to be shared between the `useSignUpEmailPassword` and the `useSignInEmailPassword` React hooks through the context, which does not feel right.

Here's my setup and the workflow that causes the unexpected behavior:

I've two routes in my React app: one to sign-up new users and one to sign-in users.

The `/sign-up` route uses the `useSignUpEmailPassword` React hook. And the `/sign-in` route uses the `useSignInEmailPassword` React hook.

When the user navigates to the `/sign-up` route and enters his email and a new password, I call the `signUpEmailPassword` method. As a result, the `needsEmailVerification` variable is now equal to `true` because the `Only allow login for verified emails.` config in my Nhost project is checked.

But, then, if the user navigates to the `/sign-in` route (without refreshing the page) before verifying his email, the `needsEmailVerification` variable returned by the `useSignInEmailPassword` hook is equal to `true`, even if `useSignInEmailPassword` is called with an empty string for the `email` parameter.

I expect this value to be `false` in that case. Indeed, the user has not yet entered his email address on the sign-in form, and I've not called the `signInEmailPassword` method yet.

What do you think?

Code: https://github.com/AlterClassIO/react-nhost-authentication
Live demo: https://react-nhost.netlify.app/

Thanks,
Greg

**Comment by szilarddoro** [comment]
Thanks for the detailed report! 👍🏼 

Unfortunately I can't access the code. Could you please check if the project visibility is set to public?
