### ISSUE TITLE
URL pattern for "options.redirectTo" in production

### ISSUE THREAD

**Issue by gdangelo** [nhost/nhost#375]
Hello,

I'm using the `options.redirectTo` parameter, from the `useSignUpEmailPassword` React hook, with the value `/`.

```js
const {
  signUpEmailPassword,
  isLoading,
  isSuccess,
  needsEmailVerification,
  isError,
  error,
} = useSignUpEmailPassword({
  displayName: `${firstName} ${lastName}`.trim(),
  metadata: {
    firstName,
    lastName,
  },
  redirectTo: '/',
});
```

In production (app deployed on Netlify), I got the following error:  

> Error validating request body. "options.redirectTo" with value "https://react-nhost.netlify.app/" fails to match the required pattern: /^http:\/\/localhost:3000/.

Nhost expects this parameter to start with `http://localhost:3000` even if my app is in production and not in my local environment anymore.

So, I'm wondering if I'm missing some configuration to match my production environment or if this is a bug.

Thanks for your feedback.

Greg

**Comment by elitan** [comment]
I think you need to do two things to fix this issue:

- Update your production Client URL (Users -> Client URL) to `https://react-nhost.netlify.app/`
- Specify the full URL. E.g. https://react-nhost.netlify.app/. ([Relevant issue](https://github.com/nhost/hasura-auth/issues/53)).

If you don't specify a `redirectTo` value the value is going to be the value of the Client URL by default.

**Comment by gdangelo** [comment]
Thanks, Johan! I've missed that one.

It works like a charm now 👌
