### ISSUE TITLE
Documentation should explain configuration necessary to allow users to upload files.

### ISSUE THREAD

**Issue by aaronblondeau** [nhost/nhost#378]
I had to spend quite a long time figuring out how to allow users to upload files.

First I had to hack on nhost.storage to make it send an auth token.  It was not doing this by default when I was logged in via nhost.auth (nhost js sdk version 1.0.9):

```
nhost.storage.setAccessToken(nhost.auth.getAccessToken())
```
I think most users will expect it to automatically send the token when users are logged in.

Then I had to use the Hasura console to add permissions for the "user" role to create, select, update, and delete permissions on the files table.  This also was not documented anywhere obvious.

I suggest adding documentation about these steps where most users will wind up looking for help : https://docs.nhost.io/reference/sdk/storage#nhost-storage-upload

**Comment by yureckey** [comment]
I think token problem is general - sdk is kinda not working as it should https://github.com/nhost/nhost/issues/373
But your other concerns are actually reflected in the docs:
https://docs.nhost.io/platform/storage

**Comment by elitan** [comment]
This is a bug. If the user is signed in the auth header should be included when doing `nhost.storage.upload()`.

Similar issue here: https://github.com/nhost/nhost/issues/373 (as mentioned above)
