### ISSUE TITLE
Error with sign in with social login when passing options

### ISSUE THREAD

**Issue by alveshelio** [nhost/nhost#386]
I'm signIn a user as follow:
```ts
const login = async () => {
  await auth.signIn({ provider, options: { locale, redirectTo: `/${locale}` } })
}
```
When I click the social login button, I've tested with LinkedIn and Google and they both have the same behaviour, they both return this error:
**Error validating request query. "locale" is not allowed. "redirectTo" is not allowed.**
This is the URL I get: https://my-backendd-url.nhost.run/v1/auth/signin/provider/google?locale=fr-ca&redirectTo=https%3A%2F%2Fmy-site.com%2Ffr-ca

**Comment by plmercereau** [comment]
What's your hasura-auth version?

https://my-backendd-url.nhost.run/v1/auth/version

Options for Oauth providers are introduced in version 0.4.0

**Comment by elitan** [comment]
We have not yet deployed the latest Hasura Auth to Nhost Cloud or CLI. We expect to do that later this month. Once that's done this issue should be fixed.

Sorry for the server/client mismatch. We'll get better at it in the future.

**Comment by alveshelio** [comment]
Thank you, I'll remove the options for now
