### ISSUE TITLE
Typo in React Docs

### ISSUE THREAD

**Issue by quarkstars** [nhost/nhost#389]
[Authentication Hooks](https://docs.nhost.io/reference/react/hooks#authentication-hooks)
[Email and Password Sign-**Un**](https://docs.nhost.io/reference/react/hooks#email-and-password-sign-**un**)

**Comment by szilarddoro** [comment]
Thank you @quarkstars ! We will soon migrate our documentation page where this issue has already been fixed.

I am linking the PR to this issue so it will be closed once we have the new site up and running.
