### ISSUE TITLE
Add the ability to rotate the x-hasura-admin-secret?

### ISSUE THREAD

**Issue by simpson** [nhost/nhost#400]
When working with contractors we have to pass this information on to our development env, it would be nice if we had the ability to rotate this to ensure access is terminated to prevent any issues.

**Comment by elitan** [comment]
I like this suggestion. Another suggestion, somewhat related, is to implement rotation + JWKS: https://github.com/nhost/hasura-auth/issues/123

**Comment by dbarrosop** [comment]
This has been possible for a while actually.
