### ISSUE TITLE
after few hours onTokenChanged stops executing

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#405]
I keep my dev app open all the time.
I noted (twice already) that after a few hours onTokenChanged stops executing, so accees token isn't refreshed, and if user tries any query (that requires authorization) it fails with  'Could not verify JWT: JWTExpired' error.
Also I noted (I added console.log to the event) that onTokenChanged called a bit too often (when it did worked) - period is between one and two minutes

**Comment by yureckey** [comment]
I'm surprised by lack of activity on this bug, as if it's not important. Whereas in real app this bug essentially breaks all functionality related to query from authorised users - users logins, everything good, then couple hours passes, users get back to app, he is still logged, but all queries stops work until user reloads - user annoyed by app and never uses it again. Just like some developers scratching heads now, thinking is it wise to bet on Nhost now and try to build app, hoping that stability will come, some today...

**Comment by kratam** [comment]
I _think_ this happens when the computer goes to sleep mode.
Apollo client should have a retry link which gets a new token when hasura throws a `jwt-expired` error, something like [this](https://github.com/newsiberian/apollo-link-token-refresh).

**Comment by yureckey** [comment]
in my test, it's not due to sleep mode - just regular browser tab opened for a couple hours, even less.
Not sure about apollo stuff, I'm using only nhost client requests

**Comment by plmercereau** [comment]
Hello,
We're currently finding the best way to correct this bug, please be assured this issue is taken seriously.
Kratam, many thanks for the retry-link suggestion, this is definitely an promising safety net to make sure the JWT is refreshed on the first expiration error Apollo may encounter.
But Yuriy is right: this occurs even when not using Apollo - the refresher is not behaving the way it should.
Will keep you posted about the progress to solve this, many thanks for your patience

**Comment by plmercereau** [comment]
Here is the related PR:
https://github.com/nhost/nhost/pull/440

I couldn't reproduce the bug when using it. I started a test application an will run it for a few hours to monitor if the bug disappears in the long run

**Comment by plmercereau** [comment]
5 hours and no bug.
After the PR is reviewed by a team mate we will release the patch.

**Comment by yureckey** [comment]
run a few tests - works good. Thank you!
