### ISSUE TITLE
Add settings for allowed_roles and default_allowed_roles in the V2 console

### ISSUE THREAD

**Issue by st3phan** [nhost/nhost#418]
The settings for `allowed_roles` and `default_alowed_roles` are missing in the V2 console.

Because of it signUp is broken in my production app because I'm not allowed to do this:

```ts
auth.signUp({
  email: formData.email,
  password: formData.password,
  options: {
    defaultRole: 'freelancer',
    allowedRoles: ['freelancer'],
  },
})
```

Response:

```
Error validating request body. "options.defaultRole" must be [user]. "options.allowedRoles" must be [user].
```

In V1 these settings look like this:

![Screenshot 2022-04-15 at 22 05 49](https://user-images.githubusercontent.com/416652/163627366-f9c8b070-3c23-43a0-9347-ce4826f402b3.png)

**Comment by plmercereau** [comment]
Hello Stephan,
Yes, there is definitely room for improvement in roles management in the console.
We are currently on a planning phase and this issue has been put on the table so we can tackle it at some point.
Will keep you posted.
Thanks for your patience

**Comment by alveshelio** [comment]
Hi guys,

Anything on this one? We can't add roles to users on signup.

Thank you

**Comment by rikardkling** [comment]
Yes agree, it would be great to be able to add roles to users on signup like in v1!

**Comment by guicurcio** [comment]
Hey, we're currently working on adding this feature to the console: ETA < 2 weeks to be in prod.

**Comment by plmercereau** [comment]
Hello, this can be now configured from the console. Closing the issue, thanks @guicurcio for the work done!
