### ISSUE TITLE
Package bundling concerns

### ISSUE THREAD

**Issue by zerosym** [nhost/nhost#428]
Using the nextjs example in this repo, the three nhost packages combine to a total of 122KB gzipped in a production build.  Since the entrypoints of each package are preprocessed and minified dist files webpack just includes them as is and fails to dedupe common modules.  This leads to multiple copies of axios code for example in the _app bundle.

**Comment by szilarddoro** [comment]
I'll take a look at how our packages are bundled sometime very soon. Could you please share a sample repo with the app setup you have just in case?
