### ISSUE TITLE
[Feature Request] Hasura Pro Version Option

### ISSUE THREAD

**Issue by henry-huynh-3508** [nhost/nhost#43]
Hi @elitan ,
For hasura's backend, testing and monitoring are almost non-existent right now. Hasura basic console does not offer the features for us to run regression testing and monitor the traffic. Is it possible to include this feature in the near future?
Thanks

**Comment by elitan** [comment]
You can use Nhost together with Hasura Pro/Cloud today, although you would have to manage Hasura Cloud separately.

**Comment by MaxSchilling** [comment]
Any hint how to set this up? Could be interesting for us as well!

**Comment by elitan** [comment]
You can read all about Hasura Cloud here: https://hasura.io/

As soon as we have the [connection string available for databases](https://github.com/nhost/nhost/issues/113) you can connect any service (like Hasura Cloud) to the database.
