### ISSUE TITLE
Cannot seem to make file public. 

### ISSUE THREAD

**Issue by jladuval** [nhost/nhost#434]
Info log can also be found here https://discord.com/channels/552499021260914688/965961261890285649

Here are the select permissions for the file table
![image](https://user-images.githubusercontent.com/1935359/164435633-08f1cf4b-1061-4aa0-a7f7-2e533b0ec756.png)
Here is a file (jpeg) in the bucket named "public"
![image](https://user-images.githubusercontent.com/1935359/164435875-22d4641a-c594-4a6f-bef0-fb17b6bf5495.png)
Is there anything else I need to do to make this link accessible? I've tried allowing all users full access to files, still nothing. 
https://lxbdtagtbpfifdmdpdeb.nhost.run/v1/storage/files/8f5f98c5-0d31-49e3-82b3-c162fc422131

Happy to try anything to debug this, I feel like I've run through every option I can.

**Comment by dbarrosop** [comment]
Let me look into this. As a workaround you can try making the `buckets` public, I think that should do it even though it shouldn't be needed.

**Comment by jladuval** [comment]
Making the bucket public did fix it. I'm fine with this as a workaround for now so no rush.

**Comment by dbarrosop** [comment]
Ok, issue is fixed and will be released soon, I will update you here once it's done

**Comment by elitan** [comment]
@dbarrosop Is this released?

**Comment by dbarrosop** [comment]
Yes, sorry, forgot to update here. Closing as this shouldn't be an issue any longer
