### ISSUE TITLE
React errors are truncated by suppressConsoleMessage

### ISSUE THREAD

**Issue by zerosym** [nhost/nhost#447]
The `suppressConsoleMessage` function is incorrectly implemented and leads to frustratingly opaque error messages from React such as:

`Warning: Did not expect server HTML to contain a <%s> in <%s>.%s`

This is a result of not accounting for variable argument length and assuming that `nativeMessage` is always a single string.

https://github.com/nhost/nhost/blob/744fd6929febe33ed929c190839977117c4b0129/packages/react/src/index.ts#L8
https://github.com/nhost/nhost/blob/0d8afde2c3d18d2f072a8fe079e2a838292024c0/packages/react/src/utils.ts#L1-L8

**See the implementation in Next:**
https://github.com/vercel/next.js/blob/600e0b3e4ef915faa74ce7c814aa3594d7b0d763/packages/next/client/next-dev.js#L12-L29

**Comment by plmercereau** [comment]
Hello @zerosym,
Thanks for raising this up. We will fix this in our next release - this method is not necessary since a previous version bump in our dependency.

**Comment by plmercereau** [comment]
The warning message is still here - reopening

**Comment by plmercereau** [comment]
@szilarddoro my guess is that this bug may be somehow related to how `package.json` is configured or how packages are built - it seems Next picks the umd version, which is not correct.
See #462

**Comment by szilarddoro** [comment]
I couldn't reproduce this issue with #462. I published the packages to a local Verdaccio instance and installed them to your [Stackblitz](https://stackblitz.com/edit/nextjs-6rycjb?file=pages%2F_app.js) project and the error disappeared when running the app in development mode.
