### ISSUE TITLE
Want to use Nhost on Nuxt3 ?

### ISSUE THREAD

**Issue by xlanex6** [nhost/nhost#454]
I want to create a Nuxt3 module base on nhost Js client to use it in Nuxt 3.

User ( session, cookie etc )
Graphql ( query + mutation )
Storage
Functions

I'm not expert, but ready to learn and sweat to do so 
Someone is already work on it ? can I join ? 

@elitan  @plmercereau are you open to this suggestion ?

**Comment by xlanex6** [comment]
Salut @plmercereau 🇧🇪 🇫🇷 

I go the point with cookie refresh on bot side ( client +server ) without using hasura-auth
thanks for use NUXT 3 got `useCookie` , good point for use

I will push you some code and demo when it will be ready, now to much buggy .. 🐛 
I still learning a lot 

Thanks

**Comment by shiftlabs1** [comment]
```One main thing to keep in mind is that hasura-auth does not support cookies, so the cookie will be shared with Nuxt client and server, but not hasura-auth. In the meantime, both client and server should be able to refresh the token, while updating the refresh token as a cookie.```
@plmercereau why is this not on hasura-auth ? And is this still the case in July

**Comment by maximilian-schwarz** [comment]
Hey at all,

here you can find a ready to use Nuxt 3 module: https://github.com/maximilian-schwarz/nhost-nuxt3-plugin
