### ISSUE TITLE
selfhost how-to missing

### ISSUE THREAD

**Issue by chymian** [nhost/nhost#46]
assumption: every OSS app, is written for the people to use.
for that a setup-instruction is a necassary part.

please publish a how-to, docker-compose etc.
TIA

**Comment by c-nv-s** [comment]
I was searching for a docker-compose file too, or wondering if there is a guide for a more production grade install?

**Comment by plmercereau** [comment]
Hello @chymian. sorry for the late reply.
You can find docker-compose example here:
https://github.com/nhost/nhost/tree/main/examples/docker-compose

**Comment by dzcpy** [comment]
Is there any introductions? How to use it after spinning up docker-compose?

**Comment by hotrush** [comment]
Agree, would be good to have some article or blog post with details how to setup nhost stack in the cloud or so
