### ISSUE TITLE
403 error on creating presigned url

### ISSUE THREAD

**Issue by jladuval** [nhost/nhost#463]
More info can be found here https://discord.com/channels/552499021260914688/615892613081333794/968090896237215774

Presigned URL is set to true for bucket, but calling `await nhost.storage.getPresignedUrl({ fileId: fileMetadata.id })` returns a 403 error. The file uploaded successfully; shouldn't the user be able to sign it?

`presignedUrlsEnabled` is set to true for the bucket.

**Comment by elitan** [comment]
Thanks @jladuval for creating an issue here.

The user must also have **SELECT** (read) access to the file (`storage.files`) via GraphQL (in Hasura). So can you please check that the user has permission to read the metadata of the file via GraphQL?

Once the user has select permission, the `presignedUrlsEnabled` must also be set to `true` for the bucket for `nhost.storage.getPresignedUrl()` to work.

But everything starts with select permissions.

**Comment by jladuval** [comment]
![unknown](https://user-images.githubusercontent.com/1935359/165230665-dab129b8-60ec-4070-b3e3-db0d4a21ed49.png)
Permissions look fine and presignedUrlsEnabled is true. I should mention this is with a new project too. The old project

**Comment by elitan** [comment]
Is this all on Nhost Cloud or do you use the CLI?

The permissions do look good. Could you double-check the network tab when you're making the network request for the pre-signed URL? What I want to know is if the `Authorization` header with the access token is sent with the request.

**Comment by jladuval** [comment]
This is with the nhost js SDK. I'm on react native so I'm not actually sure how one gets the network requests! I think the header is being sent though since my other environment works

**Comment by elitan** [comment]
Alright, but is the Nhost running at Nhost (Cloud) or do you run it locally (CLI)?

What packages and versions do you use? You can copy-paste the `@nhost/*` packages from `package.json`.

What you can try to do is to allow **select** for the `public` role without any checks. If the pre-signed URL request works then, we know that the `Authorization` request is not being set correctly.

**Comment by jladuval** [comment]
`    "@nhost/nhost-js": "^1.1.4",
    "@nhost/react": "^0.5.7",
    "@nhost/react-apollo": "^4.0.17",
`
I'm running it on nhost cloud. I just changed the permissions so that the public role has access to all files; still getting 403.

**Comment by jladuval** [comment]
I created a new environment and it's now working. I also noticed that downloadExpiration has changed from seconds to minutes (not sure if bug or feature).
