### ISSUE TITLE
On page reolad Nhost SDK clears the memory 

### ISSUE THREAD

**Issue by dikshatekriwal** [nhost/nhost#466]
I've stumbled upon a scenario in which the isAuthencationStatus becomes 'false' on page reload.
The token also gets vanished from the memory when reloading any page of the portal, however there is no issue when redirecting to pages. 
In my portal I've integrated the social login provider (Google/Facebook) using Nhost however using getAuthenticationStatus() to capture the state of authentication, it is always set to false though in direct login (using email and password) the value of isAuthenticated is 'true'.
@plmercereau Could you please help here to understand that if this is a bug in Nhost SDK or am I doing something wrong?

I've tried to record the issue - [https://www.awesomescreenshot.com/video/8600207?key=e13f93ba40c249895a7363f4314c049c](url)

**Comment by plmercereau** [comment]
Hello Diksha,
From what I can guess in your video, you are using React and Apollo.
I suggest you to use the dedicated [React library](https://docs.nhost.io/reference/react) together with its [Apollo](https://docs.nhost.io/reference/react/apollo)

**Comment by dikshatekriwal** [comment]
Hi Pilou, 
Currently I'm using [@nhost/react](https://docs.nhost.io/reference/react) with [react-apollo](https://www.npmjs.com/package/react-apollo) 
Won't this work? I would need to make changes in the whole project to move to @nhost/react-apollo.

**Comment by plmercereau** [comment]
Hello,
The `react-apollo` hasn't been updated for two years. `@apollo/client` has all the required React hooks included, so I don't think there's a need to use `react-apollo` anymore.

I think you should check if `isLoading` is set to `true`. When loading the page, the client first checks if a refresh token is stored in localStorage, and if it is, uses this refresh token to fetch the access token (JWT). Only then `isAuthenticated` is set to true.

If you could share the code it will be easier for me to help.

In the meantime, you can have a look at this [example](https://github.com/nhost/nhost/tree/main/examples/react-apollo), or [this one](https://github.com/nhost/nhost/tree/main/examples/react-apollo-crm) to get inspiration from

**Comment by dikshatekriwal** [comment]
@plmercereau All other issues got resolved but one is still as is.
The social provider login, I'm still getting 'false' for 'isAuthenticated' when trying to login via Google or Facebook. 
I can share the code to look into over discord.
