### ISSUE TITLE
Nothing rendering when NhostAuthProvider/NhostApolloProvider used

### ISSUE THREAD

**Issue by JavaJamie** [nhost/nhost#47]
I've added these in but nothing is rendered. If I remove them then everything renders as normal. Has anybody seen this?

E.g.

`const App: FC<AppProps> = ({ Component, pageProps }: AppProps) => {
    return (
        <NhostAuthProvider auth={auth}>
            <NhostApolloProvider auth={auth} gqlEndpoint={process.env.GRAPHQL_ENDPOINT}>
                <ChakraProvider>
                    <Component {...pageProps} />
                </ChakraProvider>
            </NhostApolloProvider>
        </NhostAuthProvider>
    );
}`

this just renders a blank page, but if I remove the Nhost providers it works as normal.

**Comment by elitan** [comment]
Any error messages in the console?

Could you set up a separate repository where this bug is reproducable so we can debug and fix it?

**Comment by JavaJamie** [comment]
Hi @elitan 

It turns out I was using this:
`gqlEndpoint={process.env.NHOST_GRAPHQL_ENDPOINT};`

but when I changed to the following it worked fine.

`gqlEndpoint={`${process.env.NHOST_GRAPHQL_ENDPOINT}`}`

The more you know! Everything is working amazingly well. Thank you for this wonderful tool!

**Comment by elitan** [comment]
Hmm 🤔 . That's a bit strange. I would expect `gqlEndpoint={process.env.NHOST_GRAPHQL_ENDPOINT}` to work.

Anyways, glad you got it working.
