### ISSUE TITLE
Unable to logout when signing in with Social Login because #refreshToken in URL

### ISSUE THREAD

**Issue by alveshelio** [nhost/nhost#471]
I'm using `@nhost/nextjs` and when using a social login to sign in, when we gets redirected to the site the refresh token stays on the URL. When I try to sign out, it does signs out but immediately signs the user back because the refreshToken is still in the URL.

**Comment by plmercereau** [comment]
Hello Helio,
We are about to correct this bug: once used or already connected, the `refreshToken` will be removed from the url.
