### ISSUE TITLE
Issues when signing in through social login

### ISSUE THREAD

**Issue by alveshelio** [nhost/nhost#479]
Using `@nhost/nextjs: 1.0.18` and `@nhost/react: 0.5.2`

When signing in through a social login I get a couple of issues.

I have a query to fetch a user's profile and I get an error:
"field \"user\" not found in type: 'query_root'"

This is what I have client side
```ts
const userId = useUserId()

  const { isAuthenticated, isLoading } = useAuthenticationStatus()

  const { data } = useProfileByUserQuery(
    useGraphQLClient(),
    { userId },
    {
      enabled: !!userId,
    }
  )
  

  if (isAuthenticated && !isLoading) {
    if (data?.user?.profile) {
      router.push('/profile')
    } else if (data && data.user && !data.user.profile) {
      router.push('profile-assistant')
    }
  }
...
```
`isAuthenticated` is set to `true`, I do get a userId from `useUserId()` and looking at the request that is made, it has no Authorization Headers.

The other issue and I'm not sure it's related is that in `getServerSideProps` when I do 
```ts
const nhostSession = await getNhostSession(
    process.env.NEXT_PUBLIC_BACKEND_ENDPOINT as string,
    context
  )
```
`nhostSession` is null. I need to refresh the browser to have a cession.

**Comment by ilyozzz** [comment]
I had the same issue. After updating nhost cli I saw that there's no more `users` type in my schema. But GraphiQL suggested me to use `auth_users`. So I temporarily fixed that issue with modifying table name in graphql schema in hasura console


<img width="712" alt="graphiql" src="https://user-images.githubusercontent.com/2750204/165615276-b236f2b6-1ab4-4db6-b166-eb88633d175a.png">

**Comment by plmercereau** [comment]
> The other issue and I'm not sure it's related is that in `getServerSideProps` when I do
> 
> ```ts
> const nhostSession = await getNhostSession(
>     process.env.NEXT_PUBLIC_BACKEND_ENDPOINT as string,
>     context
>   )
> ```
> 
> `nhostSession` is null. I need to refresh the browser to have a cession.

Hello again,
When redirected from hasura-auth, the refresh token is in the hash. While it is accessible in the browser when developing SPA, the hash part of the url is not accessible on the server side.
We are discussing internally about when we will release the patch in hasura-auth, as it will require all clients using the service to be upgraded beforehand.
See [this hasura-auth issue](https://github.com/nhost/hasura-auth/issues/148) and the [description of the patch in the sdk PR](https://github.com/nhost/nhost/pull/459/files#diff-b1f156c82de4360d38c6c93e2ac6ab1652e6a870732ce64230c3a9c92eae6d52).

About the error `"field "user" not found in type: 'query_root'"` my guess is the graphql query has been triggered without the authentication header, you may want to look at the headers or your request.

Many thanks for your patience!
