### ISSUE TITLE
golang client sdk 

### ISSUE THREAD

**Issue by gedw99** [nhost/nhost#483]
I use https://github.com/gioui as do others to build Web, Desktop and Mobile apps.

Can you provide a golang SDK perhaps.

I image it will be a subset of the golang cli perhaps but i have not looked into too deeply. 

The hasura graphql golang client seems to be the main import ?

I think it would be very easy to make an example. Here is a common example basis: https://github.com/gioui/gio-example/tree/main/component

**Comment by elitan** [comment]
Hey @gedw99.

Do you mean a Nhost Golang client/SDK as we have for JavaScript/TypeScript to make it easy to interact with graphql, auth, storage, and functions?

**Comment by gedw99** [comment]
Yes i know you have a JS / TS code lib to interact with the graphql, auth, storage, and functions? 

But i would like a golang equivalent so that i can built web, desktop and mobile apps to work with nhost. 
i would use GIUIO which is a golang GUI framework.

**Comment by beepsoft** [comment]
I started working on a client. It is quite minimal yet:


- NhostClient providing access to Auth, Storage (and later Graphql and Functions) clients
- Auth client
  - Sign in with email/password (`nhostClient.Auth.SignInEmailPassword()`)
  - Sign out (`nhostClient.Auth.SignOut()`
  - Callbacks on token change (`nhostClient.Auth.OnTokenChanged()`) and auth status change (`nhostClientAuth.OnAuthStateChanged()`)
- Storage client
  - Automatic update of access token when Auth refreshes token
  - Get presigned URL for downloading files (nhostClient.Storage.GetPresignedUrl())

https://github.com/beepsoft/nhost-go
