### ISSUE TITLE
Upgrade Node in Nhost functions

### ISSUE THREAD

**Issue by dahmc** [nhost/nhost#493]
Hi,

on https://docs.nhost.io/platform/serverless-functions it states that node 14 is currently supported.

How about bumping that to at least the currently active LTS, 16?

**Comment by elitan** [comment]
We're using AWS Lambda for our serverless functions and AWS lambda currently only support version 12 and 14: https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html

Version 16 is expected to go live later this month: https://github.com/aws/aws-lambda-base-images/issues/14#issuecomment-1108679026 🎉 

We'll probably add the option for customers to specify the Node.js version in our dashboard once we support more versions than 14.

**Comment by elitan** [comment]
AWS Lambda now has support for Node 16: https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/

We plan to support this new versions soon.

**Comment by st3phan** [comment]
Any update on supporting Node 16? 
I upgraded my project to use Node >=16 but now my deployments are failing because of the node version.

**Comment by st3phan** [comment]
Would it be possible to upgrade to Node 16 yet?

**Comment by elitan** [comment]
Not yet, but it's on our roadmap. We need to sync a few things to make this work:

- **CLI / configuration* - so the `functions` container uses node 14/16 depending on the configuration.
- Nhost Dashboard - to set the Node version per project.
- Nhost Deployments - to build and deploy functions with the correct Node version.

For now, we're using Node Version 14.

**Comment by elitan** [comment]
Ok, we've decided to upgrade to Node 16 for all projects without the option to select the Node version. The upgrade will happen in the near future.

**Comment by pkreipke** [comment]
Thanks for the update @elephant3 and the clarification @elitan.

I'm a little skittish about doing a CLI update right now - I'm seeing posts in Discord about the port # and a few other things that I _think_ are in the latest version.

Also, do you expect forcing an update locally to Node v16 to cause any issues with our local dev projects? I've started using `nodenv` to pin node versions to a folder so many projects hopefully won't be affected but some will.

Do you think this change is worth a post in News and Announcements Discord channel with some notes, caveats, etc?
