### ISSUE TITLE
@nhost/react 0.6.1 uses useLayoutEffect which cannot be used in ssr

### ISSUE THREAD

**Issue by cezarneaga** [nhost/nhost#504]
Hi there!

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's 

output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, 

useLayoutEffect should only be used in components that render exclusively on the client. 

See **https://reactjs.org/link/uselayouteffect-ssr** for common fixes.

(node_modules/.pnpm/@nhost+react@0.6.1_a6d34a65eadc87c45754f8a77ed37370/node_modules/@nhost/react/dist/index.umd.js:61:745)
```
i use it the package in nextjs,
cheers,
Cezar

**Comment by plmercereau** [comment]
Hello Cezar,
This warning can be ignored and should disappear once [this PR](https://github.com/nhost/nhost/pull/503) is merged and released.
Please keep an eye on it so you can upgrade to next release

**Comment by plmercereau** [comment]
Hello Cezar,
This should be fixed now. Please upgrade to the latest SDK version.
I'm closing the issue, please let me know if you're still having this problem, and I'll reopen the issue.

**Comment by cezarneaga** [comment]
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
:     at jd (node_modules/.pnpm/@nhost+react@0.7.0_a6d34a65eadc87c45754f8a77ed37370/node_modules/@nhost/react/dist/index.umd.js:66:676)
at MyApp (webpack-internal:///./src/pages/_app.tsx:31:18)

**Comment by plmercereau** [comment]
Hello,
Please try today's release:
https://stackblitz.com/edit/nextjs-6rycjb?file=package.json

Thanks
