### ISSUE TITLE
Document Api Reference if MFA is activated

### ISSUE THREAD

**Issue by masterbater** [nhost/nhost#510]
https://docs.nhost.io/reference/hasura-auth/api-reference
Under Authentication swagger the post /signin/email-password there is no example return field if mfa is activated.

I want to at least know the flow if mfa is activated, does signin will return access toke and refresh token even if they didnt fullfil mfa

**Comment by plmercereau** [comment]
Hello, sorry for the late reply.
There is a `mfa` field in the payload that contains the ticket when MFA is activated, please have a look at the [OpenApi specs](https://editor.swagger.io/?url=https://raw.githubusercontent.com/nhost/hasura-auth/main/docs/openapi.json).
Access and refresh tokens are only returned when the user finished their authentication i.e. when there is no need to complete MFA
