### ISSUE TITLE
Error in deploy function on PROD

### ISSUE THREAD

**Issue by suplere** [nhost/nhost#551]
Hello,

I get this error while I deploy function:
`01:29:13: Starting deployment
01:29:13: Cloning repo github.com/suplere/treninky-dochazka (#15a5e36)
01:29:19: Applying metadata
01:29:21: Metadata applied successfully
01:29:21: Deploying functions
01:29:30: couldn't build lambda for /tmp/2196355423/functions/node_modules/@nhost/core/dist/index.d.ts: ✘ [ERROR] Could not resolve "./client" index.d.ts:2:27: 2 │ export { AuthClient } from './client'; ╵ ~~~~~~~~~~ ✘ [ERROR] Could not resolve "./constants" index.d.ts:3:14: 3 │ export * from './constants'; ╵ ~~~~~~~~~~~~~ ✘ [ERROR] Could not resolve "./cookie-client" index.d.ts:4:48: 4 │ export { AuthClientSSR, AuthCookieClient } from './cookie-client'; ╵ ~~~~~~~~~~~~~~~~~ ✘ [ERROR] Could not resolve "./errors" index.d.ts:5:14: 5 │ export * from './errors'; ╵ ~~~~~~~~~~ ✘ [ERROR] Could not resolve "./machines" index.d.ts:6:14: 6 │ export * from './machines'; ╵ ~~~~~~~~~~~~ ✘ [ERROR] Could not resolve "./storage" index.d.ts:7:14: 7 │ export * from './storage'; ╵ ~~~~~~~~~~~ 6 of 8 errors shown (disable the message limit with --log-limit=0) child_process.js:830 throw err; ^ Error: Command failed: /usr/local/lib/node_modules/esbuild/node_modules/esbuild-linux-arm64/bin/esbuild --bundle --minify --platform=node --outfile=/tmp/2599131909/lambda.js /tmp/2196355423/functions/node_modules/@nhost/core/dist/lambda-605394647632969758.js at checkExecSyncError (child_process.js:790:11) at Object.execFileSync (child_process.js:827:15) at Object.<anonymous> (/usr/local/lib/node_modules/esbuild/bin/esbuild:172:28) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) at internal/main/run_main_module.js:17:47 { status: 1, signal: null, output: [ null, null, null ], pid: 158, stdout: null, stderr: null }
01:29:30: Deployment completed with status FAILED`

On local all works fine.
here is listing source code for function - path function/test/time.ts
```
import { Request, Response } from "express";

export default (req: Request, res: Response) => {
  return res
    .status(200)
    .send(`Ahoj ${req.query.name}! Nyni je: ${new Date().toUTCString()}`);
};
```

**Comment by elitan** [comment]
We just released a new patch, can you check if it works for you now?

**Comment by suplere** [comment]
Hello, not working for me. I must delete whole project, and setup github integration - first deploy works. But when I try new deployment (I add some new function) I get error again:
10:12:50:
couldn't build lambda for /tmp/1368249136/functions/actions/deleteEvent.ts: ✘ [ERROR] Could not resolve "graphql/language/printer" ../node_modules/@nhost/nhost-js/dist/index.es.js:23:22: 23 │ import { print } from "graphql/language/printer"; ╵ ~~~~~~~~~~~~~~~~~~~~~~~~~~ You can mark the path "graphql/language/printer" as external to exclude it from the bundle, which will remove this error. 1 error child_process.js:830 throw err; ^ Error: Command failed: /usr/local/lib/node_modules/esbuild/node_modules/esbuild-linux-arm64/bin/esbuild --bundle --minify --platform=node --outfile=/tmp/342343215/lambda.js /tmp/1368249136/functions/actions/lambda-5577006791947779410.js at checkExecSyncError (child_process.js:790:11) at Object.execFileSync (child_process.js:827:15) at Object.<anonymous> (/usr/local/lib/node_modules/esbuild/bin/esbuild:172:28) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) at internal/main/run_main_module.js:17:47 { status: 1, signal: null, output: [ null, null, null ], pid: 84, stdout: null, stderr: null }
10:12:50:
Deployment completed with status FAILED

**Comment by elitan** [comment]
Can you send your `package.json` file here? Seems like you're missing the `graphql` package? 🤔

**Comment by suplere** [comment]
You are right! Stupid my mistake. Yes now deployment works fine, thanks for the support.

**Comment by elitan** [comment]
Excellent! 👍
