### ISSUE TITLE
Add `nhost.[auth,storage].` to documentation

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#553]
We don't add `nhost.auth` nor `nhost.storage` to our inline documentation and our own documentation.

So instead of showing `nhost.auth.signUp` we show `signUp`. We do this because the auth and storage SDK can be used independently. However, I think most developers use our full JavaScript client, and so I think showing `nhost.[auth,storage].` would be more useful for developers reading our documentation.

![CleanShot 2022-05-13 at 15 07 54@2x](https://user-images.githubusercontent.com/331818/168290163-fcc6082a-3eb2-494b-95d9-b7b205fe16c7.png)

cc @nunopato, @plmercereau, @szilarddoro

**Comment by nunopato** [comment]
@elitan I agree!
