### ISSUE TITLE
Creating users for Admin roles + hierarchy

### ISSUE THREAD

**Issue by mrkpatchaa** [nhost/nhost#574]
Hi, according to the [documentation](https://docs.nhost.io/platform/authentication/user-management#creating-users), We should 
**Never create users directly via GraphQL or database. Never modify the auth.users table. Never modify the GraphQL root queries.**
BTW I'm working on an application where I would need admins to add new users related to them. Let's think it as a manager that is adding new directs.
So I would need to add a column as parent_id and be able to create users via graphql mutation, setting the parent_id automatically.

Do you have any guideline regarding such use case?
Thanks a lot.

**Comment by nunopato** [comment]
@mrkpatchaa We don't allow for changing tables within the `auth` & `storage` schemas so you would have to store `parent_id` differently. You have 2 options atm:

1. use the `metadata` column (in the `users` table) to store the `parent_id`
2. create a new table in the `public` schema with `user_id` and `parent_id` (`parent_id` could be a column preset)

In your use case specifically, do you need to create those users from the client?

**Comment by mrkpatchaa** [comment]
@nunopato for the hierarchy yes I can handle it with a different table.
For the user creation yes I would need to create users from the client (We're building a custom admin dashboard for the application)
So an admin can create users under his organizations instead of allowing everyone to signup. 
The only action for the "normal" users will be the login (And we're planning to not allow email+password login, only paswwordless sms)

**Comment by mrkpatchaa** [comment]
I'll close this as I managed the relationship in another table in the public schema. I am also creating users via graphql. It's working fine.
Thanks
