### ISSUE TITLE
How to know what permissions a user have, through API?

### ISSUE THREAD

**Issue by KrishnaPG** [nhost/nhost#575]
While building the UI, certain parts of UI need to know if user is allowed access or not.

For example, 

- menu links enabled/disabled, 
- buttons enabled/disabled

based on whether user is allowed to perform an action or not.

This requires querying what permissions a user have for the underlying resource/table etc.

Specifically, with the [refine](https://refine.dev/docs/core/providers/accessControl-provider/) front-end to implement the [access control provider](https://refine.dev/docs/core/providers/accessControl-provider/) we need a way to query what permissions a user has for a resource/action.

Documentation specifies [how to **set** the permissions](https://docs.nhost.io/get-started/quick-start/permissions) but does not specify how to **get** the users' existing permissions.

Any example that demonstrates how to achieve this functionality with nHost and Hasura backend permissions would be of great help.

**Comment by elitan** [comment]
I would think about this in terms of roles as you're using roles to set permissions.

You can get a user's default role by getting the whole user object like this:

```js
const user = nhost.auth.getUser()
```

https://docs.nhost.io/reference/javascript/auth/get-user

If you have a more specific use case that would be helpful in giving you a more specific answer.

**Comment by KrishnaPG** [comment]
Thank you @elitan 

The requirement is to know programmatically what a user is allowed to and what not allowed to do.

The goal is to implement access provider function as below:
```js
        accessControlProvider={{
            can: async ({ resource, action, params }) => {
                // find out if user has permission or not from Hasura
                const result = await getUserRolePermissions({ resource, action, params })
                return Promise.resolve({ can: result });
            },
        }}
```
How to implement such function `getUserRolePermissions` with nHost / Hasura?

Please refer the below screenshot (from the nHost documentation [how to set the permissions](https://docs.nhost.io/get-started/quick-start/permissions) ). 

Question is: **After the permissions are set for a role, how to read them back through nHost API?**
----------------------------

![image](https://user-images.githubusercontent.com/4610831/169257396-172e1d48-2dc3-4216-86af-c387bcdc1b2a.png)

**Comment by elitan** [comment]
> After the permissions are set for a role, how to read them back through Nhost API?

Yes, I think it's possible by letting the user do a [GraphQL Introspection](https://graphql.org/learn/introspection/). This way you can see what you're allowed to do through the GraphQL API as that particular user.

But it's not as easy as reading the permissions directly, which I don't think is possible without admin access (server-side).

**Comment by plmercereau** [comment]
You cannot access to permissions from GraphQL introspection as this part of the Hasura metadata is not reflected in the GraphQL schema - it will only determine whether fields and relationships should be in the schema or not, depending on the user's permissions.

There is a workaround to expose permissions: you can create a Postgresql view that exposes the Hasura metadata, and track it in Hasura:
```sql
CREATE VIEW metadata as SELECT * FROM hdb_catalog.hdb_metadata;
```

It will probably require some transformation so you can filter the information that you need

**Comment by nunopato** [comment]
@KrishnaPG Are you using the `access control provider` for client-side conditional rendering of certain components? If we were to expose a function on the SDK to retrieve user permissions, how would that work with complex permission rules? would you assume `can: true` simply because permissions are defined for a role+action? if not, you would have to traverse the permission rule and infer from it.

**Comment by KrishnaPG** [comment]
On a side note, Since Hasura already does this permission check for every read/update etc. action on a resource, it already has the code for the `can` function that we need. 

It would be great if Hasura exposes that functionality as a metadata function, instead of nHost or the end-user App duplicating it again.

**Comment by elitan** [comment]
Sounds like this is an issue more for Hasura than for Nhost. Maybe it's worth creating an issue on [Hasura's repo](https://github.com/hasura/graphql-engine) and seeing what they have to say?

**Comment by KrishnaPG** [comment]
Thank you @elitan opened an issue here: https://github.com/nhost/nhost/issues/575
