### ISSUE TITLE
Nuxt3 gets confused between the CJS and EMS version of dependencies

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#584]
To reproduce:
- use this [stackblitz project](https://stackblitz.com/edit/github-m3qfq4-4grm3j?theme=dark)
- remove `build: { transpile: ['xstate'] }` from `nuxt.config.ts`

Some reading: https://v3.nuxtjs.org/guide/going-further/esm

@szilarddoro I'm curious to get your opinion once you'll be back

**Comment by szilarddoro** [comment]
I don't think that this is something that we can fix on our end. Although we should consider supporting native ESM in the future by creating `.mjs` files for our ESM builds, there is not much we can do about our direct dependencies other than reporting the relevant issues in their repositories.

**Comment by szilarddoro** [comment]
This issue is no longer reproducible with `@nhost/nhost-js@1.2.0`. Can you confirm @plmercereau?
