### ISSUE TITLE
Trouble running react-apollo-crm example

### ISSUE THREAD

**Issue by kubeworkz** [nhost/nhost#605]
I'm having an issue with running Step 4 of the react-apollo-crm example. When I run ```pnpm run dev``` I get the following error:
```
EACCES: permission denied, scandir '/home/osboxes/nhost/examples/react-apollo-crm/.nhost/main/db_data'
```
The permissions for ```/db_data``` on my host machine are ```systemd:coredump``` (translating the permissions of the pg docker) and as a result it's not allowing me to run ```pnpm run dev```.

Also, ```package.json``` contains some entries that throw errors - the ```workspace.*``` entry isn't recognized for @nhost/react and @nhost/react-apollo. 

If anyone has run into any of these issues please let me know how to fix them. Cheers, Dave

**Comment by elitan** [comment]
I'm working on updating the example in a PR here: https://github.com/nhost/nhost/pull/330

I'll try to release a somewhat stable version in the next few days.

**Comment by kubeworkz** [comment]
Sweet - that's quick. Thanks so much.

**Comment by elitan** [comment]
Thanks. 

It's a ragdoll 😅

**Comment by nunopato** [comment]
@elitan should this be closed?

**Comment by elitan** [comment]
The [PR](https://github.com/nhost/nhost/pull/330) was closed, so I suspect this issue remains. I'll have a closer look.

**Comment by elitan** [comment]
We've decided to remove the CRM example and instead focus on the React Apollo example: https://github.com/nhost/nhost/tree/main/examples/react-apollo
