### ISSUE TITLE
[Suggestion] Use ory stack for auth management

### ISSUE THREAD

**Issue by tapkain** [nhost/nhost#62]
Yo guys, what if you will consider for the future to use ory stack for auth Z/N? - https://www.ory.sh
[ory kratos](https://www.ory.sh/kratos/docs/quickstart/) for user management
[ory oathkeeper](https://www.ory.sh/oathkeeper/docs/configure-deploy/) for authorization

- They offer as well an open-source IAM solution and Oauth solution which can be handy for developing your own public APIs.
- No need to maintain own auth solution
- Security issues tracking and hardening can be a hussle

would love to hear from you guys what do you think about this.

**Comment by elitan** [comment]
We're using [Hasura Auth](https://github.com/nhost/hasura-auth) and we don't have any plans of moving to another auth solution.
