### ISSUE TITLE
Next.js SDK fails to get refresh token 

### ISSUE THREAD

**Issue by mjerjawi** [nhost/nhost#622]
I've stumbled upon this problem with my project so i thought I've missed something up, 
so i tried running a fresh app from the  next.js docs example and ended up with the same issue.
At the initial page load i get 3 different  refresh tokens and after 900 secs i start getting 401 with each token refresh request
but sometimes it returns 200!
![initial](https://user-images.githubusercontent.com/68725483/171049316-82ca9cb0-3288-46f8-a90d-44400470d59c.png)
![refresh](https://user-images.githubusercontent.com/68725483/171049332-77c5aa12-bada-4534-ab2b-1eb471520857.png)
![suc](https://user-images.githubusercontent.com/68725483/171049340-a5b4da1f-9a22-4401-bed5-d57eea22ecd3.png)

**Comment by dikshatekriwal** [comment]
I'm also facing the above issue, tried upgrading nhost dependencies but no luck.
Though the token API is failing, the access token generated from last successful /token API call is active and works to get data from DB.

**Comment by plmercereau** [comment]
The patched version of hasura-auth that solves the problem has been deployed. Closing, don't hesitate to reply to this issue if you're still facing the issue and we'll reopen
