### ISSUE TITLE
Disable gravatar and/or set default type setting

### ISSUE THREAD

**Issue by altschuler** [nhost/nhost#625]
It would be nice if the default `avatarUrl` could be configured. Currently it's `https://s.gravatar.com/avatar/<id>?r=g&default=blank`, but I'd like to use `https://s.gravatar.com/avatar/<id>?r=g&default=identicon` (ie. using `identicon` instead of `blank` as fallback).

Edit: I then wanted to disable the default gravatars, but I'm unable to set the `AUTH_GRAVATAR_ENABLED` env var (as documented [here](https://docs.nhost.io/reference/hasura-auth/configuration#gravatar)) because it faisl with "The environment variable name cannot start with a value that is reserved for an internal environment variable."

Edit again: I just found https://github.com/nhost/hasura-auth/blob/main/src/utils/avatar.ts and can see it already is possible to customize this, so the only thing missing is being able to set those env vars in the dashboard (and maybe adding docs for it).

**Comment by elitan** [comment]
We're in the process of releasing these setting options to our dashboard in the next few days.

**Comment by altschuler** [comment]
Awesome, I'll close this then :) thanks!

**Comment by Nabinsharma123** [comment]
i thing the issue is still present

**Comment by elitan** [comment]
This is now possible to configure in the Nhost dashboard.

![Uploading CleanShot 2022-11-20 at 19.49.35@2x.png…]()

**Comment by hadnet** [comment]
I'm using signUpEmailPassword, but I can't set the avatarUrl. When using social OAuth, like Google, the avatarUrl is set automatically. The only way I can think of is to add an avatarUrl in the metadata, but that feels weird. How can I set the avatarUrl using signUpEmailPassword @elitan ?

```tsx
    const response = await signUpEmailPassword(email, password, {
      displayName: username,
      locale: "es",
      // here avatarUrl cannot set avatar with own data 
      // avatarUrl: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
      metadata: {
        agent: "jon",
      },
    });
```

**Comment by dbarrosop** [comment]
You can't set the avatar url per user. You have a few global settings to tweak how the avatar urls is auto-generated.
