### ISSUE TITLE
Accept Any OAuth2 Provider

### ISSUE THREAD

**Issue by PRAJINPRAKASH** [nhost/nhost#63]
Login with Facebook, Google, Twitter, Microsoft, LinkedIn, Apple. etc are necessary.

As per App Store Review Guidelines we must include apple login if we use any third party login otherwise the app will be rejected :
`https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple`

So instead of adding new OAuth2 providers one by one.  I request to create a general UI for any OAuth2 provider to work. By collection additional information.

**Comment by plmercereau** [comment]
Hello, 
Sorry for the late reply.
Google, LinkedIn, Github and Facebook providers are available from now on, and we're about to add missing providers such as Spotify, Apple and Twitter in the upcoming weeks.

We are also considering adding other providers in the future - please track [this hasura-auth issue](https://github.com/nhost/hasura-auth/issues/73).
