### ISSUE TITLE
Next.js quickstart: Cannot find module 'xstate/lib/waitFor'

### ISSUE THREAD

**Issue by chrisfrancis27** [nhost/nhost#636]
I'm working through the [Next.js quickstart guide](https://docs.nhost.io/platform/quickstarts/nextjs) but quickly hit a stumbling block when trying to run the app after importing the client and provider from `@nhost/nextjs`:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/my/project/node_modules/xstate/lib/waitFor' imported from /path/to/my/project/node_modules/@nhost/nextjs/dist/index.mjs
Did you mean to import xstate/lib/waitFor.js?
```

After some digging, it appears this is caused by specifying imports without file extensions from inside `.mjs` files (ES modules). It also appears that a [very recent commit](https://github.com/nhost/nhost/commit/2b2f8e91ae495aff3c4f36a49e4ea1bb1a44aeea) changed some configuration around ESM imports, which has gone out in [`@nhost/nextjs@1.2.9`](https://github.com/nhost/nhost/releases/tag/%40nhost%2Fnextjs%401.2.9). I haven't spotted exactly what has changed and I'm no expert on JS module interop but think this commit is likely related.

Indeed, rolling back to [`@nhost/nextjs@1.2.8`](https://github.com/nhost/nhost/releases/tag/%40nhost%2Fnextjs%401.2.8) fixes the problem for me.

System info:
```
macOS 12.4 (M1 Max)
node v16.13.0
npm 8.11.0
```

**Comment by elitan** [comment]
Thanks for reporting @chrisfrancis27 🙏 

@szilarddoro, could you take a look a this?

**Comment by szilarddoro** [comment]
Sorry for the inconvenience @chrisfrancis27. You are correct, that commit is the reason this happened.

I prepared a fix for this issue: https://github.com/nhost/nhost/pull/640. Please keep using `@nhost/nextjs@1.2.8` for now, we'll release the patch sometime soon.

**Comment by chrisfrancis27** [comment]
Awesome, thanks for jumping on this so quickly @szilarddoro! Of course, happy to use 1.2.8 in the mean time. 🙌

**Comment by elitan** [comment]
I've updated the quickstart template to use React 18 (https://github.com/nhost/quickstart-nextjs/pull/2). Maybe that helps with solving the issue for now too.

**Comment by szilarddoro** [comment]
@chrisfrancis27 could you please bump `@nhost` dependencies to their latest version and check if the issue still persists?
