### ISSUE TITLE
Option to disable remote schema permissions

### ISSUE THREAD

**Issue by thetre97** [nhost/nhost#644]
As per https://discord.com/channels/552499021260914688/981283207083356201/981294504164327434, it would be great to have an option in Nhost to disable certain Hasura features, like remote schema permissions. This would require being able to set currently restricted environment variables, like `HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS`.

**Comment by elitan** [comment]
Right now this value is hardcoded to `true`. We'll work on supporting setting this value.

**Comment by dbarrosop** [comment]
apologies for forgetting about this one but this has been possible since we migrated to the new `config.toml`:


``` toml
[hasura.settings]
enableRemoteSchemaPermissions=false
```
