### ISSUE TITLE
Documentation search bar is not working

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#645]
- ~~when clicking on a search result, it redirects to a 404~~
- ~~the index is maybe not up to date~~
- when clicking to "see all x results", the search page then returns "No results were found"

**Comment by elitan** [comment]
I've fixed the first two issues. The Algolia Crawler is now scheduled to run once per day to update the search index.

> when clicking to "see all x results", the search page then returns "No results were found"

This issue still remains.
