### ISSUE TITLE
Few questions regarding email templates feature

### ISSUE THREAD

**Issue by dikshatekriwal** [nhost/nhost#647]
1. Is it possible to add new variables other than listed in the Nhost documentation? such as 'new email ID' when user requests for changing email.
2. Is there any expiration time defined for the emails sent to customer? If yes, what is it?
3. What should happen when the user uses the link twice sent in the email?

**Comment by elitan** [comment]
1. No it's not possible right now. 

2. Yes.

Magic Link: 1 hour
Verify Email: 30 days
Reset password: 1 hour
Change Email: 1 hour

3. It's only possible to use a link once.
