### ISSUE TITLE
Add labels for inputs when adding user

### ISSUE THREAD

**Issue by outluch** [nhost/nhost#653]
![image](https://user-images.githubusercontent.com/1479468/171404351-3075fcf0-71f3-4f10-84f2-9a5515db5a40.png)

Not that obvious where should I insert email. Because maybe there 2 fields: username and email? 
If password would be hidden, I should enter email in the first field

Labels would solve this

**Comment by elitan** [comment]
Fixed.

![CleanShot 2022-06-21 at 07 55 50](https://user-images.githubusercontent.com/331818/174726443-3695f715-d2b0-4fa4-a0bf-d7dc83170e44.png)
