### ISSUE TITLE
Started getting error  - Can't import the named export 'ApolloProvider' from non EcmaScript module

### ISSUE THREAD

**Issue by dikshatekriwal** [nhost/nhost#654]
I've started getting this error while compiling suddenly when updated the Nhost dependencies

The version for Nhost libraries are - 
		"@nhost/nhost-js": "^1.2.1",
		"@nhost/react": "^0.7.10",
		"@nhost/react-apollo": "^4.2.11",

./node_modules/@nhost/react-apollo/dist/index.esm.mjs
Can't import the named export 'ApolloProvider' from non EcmaScript module (only default export is available)

Tried with downgrading and install the dependencies but the issue is not resolved and now the my portal is broken.
	"@nhost/nhost-js": "^1.1.14",
	"@nhost/react": "^0.7.8",
	"@nhost/react-apollo": "^4.2.9",

**Comment by dikshatekriwal** [comment]
@szilarddoro getting this error now
./node_modules/@nhost/hasura-auth-js/dist/index.esm.mjs
Can't import the named export 'AuthClient' from non EcmaScript module (only default export is available)
Using below versions
		"@nhost/nhost-js": "^1.2.2",
		"@nhost/react": "^0.7.11",
		"@nhost/react-apollo": "^4.2.13",

**Comment by penumatv** [comment]
@dikshatekriwal - Hi, Just now bumped the version to  `@nhost/react-apollo": "^4.2.13`, and seems it's working now. I no longer see the below error

SyntaxError: Named export 'ApolloProvider' not found. The requested module '@apollo/client' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@apollo/client';
const { useQuery, useSubscription, ApolloProvider } = pkg;

**Comment by dikshatekriwal** [comment]
@penumatv which version of @nhost/nhost-js and @nhost/react are you using?

**Comment by penumatv** [comment]
Hi, @dikshatekriwal below are the nhost dependencies in my project at the moment. not using the `@nhost/nhost-js` now

"@nhost/nextjs": "^1.2.11",
"@nhost/react": "^0.7.11",
"@nhost/react-apollo": "^4.2.13",

**Comment by szilarddoro** [comment]
@dikshatekriwal Using the latest version (`1.2.2`) of `@nhost/nhost-js` should not have an impact on your issue. Are you still experiencing problems after upgrading `@nhost/react-apollo` to  `4.2.13`?

**Comment by dikshatekriwal** [comment]
@szilarddoro I'm not saying that the latest version (1.2.2) of @nhost/nhost-js is creating problem.
I'm currently using this set of nhost dependencies with version
"@nhost/nhost-js": "^1.2.2",
"@nhost/react": "^0.7.11",
"@nhost/react-apollo": "^4.2.13"
The previous error seems to be resolved by upgrading @nhost/react-apollo to 4.2.13 however experiencing a new error
./node_modules/@nhost/hasura-auth-js/dist/index.esm.mjs
Can't import the named export 'AuthClient' from non EcmaScript module (only default export is available)

Not sure if this is because of @nhost/react-apollo or @nhost/nhost-js

**Comment by szilarddoro** [comment]
That's weird. Can you share more details about the dependencies you are using?

**Comment by dikshatekriwal** [comment]
@szilarddoro This is the list of dependencies which is getting used
                "@ant-design/icons": "^4.0.2",
		"@apollo/client": "^3.6.2",
		"@nhost/nhost-js": "^1.2.1",
		"@nhost/react": "^0.7.10",
		"@nhost/react-apollo": "^4.2.11",
		"antd": "^4.0.0",
		"axios": "^0.19.2",
		"babel-plugin-import": "^1.13.0",
		"bootstrap": "^4.3.1",
		"customize-cra": "^0.8.0",
		"graphql": "^16.4.0",
		"graphql-tag": "^2.12.6",
		"less-loader": "^5.0.0",
		"lodash": "^4.17.15",
		"md5": "^2.2.1",
		"moment": "^2.24.0",
		"react": "^16.12.0",
		"react-dom": "^16.12.0",
		"react-router-dom": "^6.3.0",
		"react-scripts": "^3.2.0",
		"react-social-login-buttons": "^3.5.0",
		"start": "^5.1.0",
		"yarn": "^1.22.10",
		"zustand": "^4.0.0-rc.1"

**Comment by szilarddoro** [comment]
Could you try upgrading `@apollo/client` to `3.6.6`?

**Comment by dikshatekriwal** [comment]
I've tried that too. Even removed "@nhost/nhost-js", that is also not helping here.
However I've a old yarn.lock file with older version of nhost dependencies with which I'm getting no error.
Could you check if this might help to solve the issue?
[yarn.zip](https://github.com/nhost/nhost/files/8821742/yarn.zip)

**Comment by dikshatekriwal** [comment]
@szilarddoro with this set of version libraries, all works as expected
		"@apollo/client": "^3.6.6",
		"@nhost/nhost-js":"^1.1.14",
		"@nhost/react": "^0.7.8",
		"@nhost/react-apollo": "^4.2.9",

**Comment by szilarddoro** [comment]
I have a feeling that the reason that these errors are thrown are because of the React version your project uses. We are testing our changes with React 17 and 18.

**Comment by dikshatekriwal** [comment]
@szilarddoro I've tried with react 17 version and the issue doesn't resolve.
This is the latest list of dependencies with versions for record that is used - 
	"@ant-design/icons": "^4.0.2",
		"@apollo/client": "^3.6.6",
		"@nhost/react": "^0.7.11",
		"@nhost/react-apollo": "^4.2.13",
		"antd": "^4.0.0",
		"axios": "^0.19.2",
		"babel-plugin-import": "^1.13.0",
		"bootstrap": "^4.3.1",
		"customize-cra": "^0.8.0",
		"graphql": "^16.5.0",
		"graphql-tag": "^2.12.6",
		"less-loader": "^5.0.0",
		"lodash": "^4.17.15",
		"md5": "^2.2.1",
		"moment": "^2.24.0",
		"react": "17.0.0",
		"react-dom": "17.0.0",
		"react-router-dom": "^6.3.0",
		"react-scripts": "^5.0.1",
		"react-social-login-buttons": "^3.5.0",
		"start": "^5.1.0",
		"yarn": "^1.22.10",
		"zustand": "^4.0.0-rc.1"
		
Thanks. 'll wait for the fix.

**Comment by dikshatekriwal** [comment]
@szilarddoro should I create a new issue for the below to follow up for the solution - 
./node_modules/@nhost/hasura-auth-js/dist/index.esm.mjs
Can't import the named export 'AuthClient' from non EcmaScript module (only default export is available)

**Comment by szilarddoro** [comment]
@dikshatekriwal could you please try bumping `@nhost/react` to `0.7.12` and `@nhost/react-apollo` to `4.2.14`?

**Comment by dikshatekriwal** [comment]
@szilarddoro The issue is resolved now with the above versions. Thank you.

**Comment by szilarddoro** [comment]
Awesome! 🎉 Do not hesitate to reopen if the issue re-appears.
