### ISSUE TITLE
Invalid URL when using google provider

### ISSUE THREAD

**Issue by cj** [nhost/nhost#662]
@nhost/react - 0.7.12

``` typescript
import { useProviderLink } from '@nhost/react'

export function AuthMethods(): JSX.Element {
    const { google } = useProviderLink({ redirectTo: '/dashboard' })

  return (
    <>
      <Title>Sign in with</Title>
      <ButtonsWrapper>
        <LinkButton href={google}>
          <GoogleIcon />
        </LinkButton>
      </ButtonsWrapper>
    </>
  )
}

```

Gives the following error:

```
Server Error
TypeError: Invalid URL: 
```

![image](https://user-images.githubusercontent.com/1819/171681529-574c7be8-ea07-4c32-a300-fc5bec0cf527.png)

__Version @nhost/react - 0.6.1 works, it breaks when going into version 0.7.*__

**Comment by cj** [comment]
@plmercereau it needs to be nextjs, sorry I should have mentioned that.

**Comment by plmercereau** [comment]
and try to use  `@nhost/nextjs` instead?
```js
import { useProviderLink } from '@nhost/nextjs'
```

**Comment by cj** [comment]
@plmercereau I made a nextjs repo from scratch https://github.com/cj/nhost-invalid-url-when-using-google-provider just run `yarn install` and `yarn dev`

**Comment by cj** [comment]
@plmercereau and if you change @nhost/react to 0.6.1 in the package.json it will work just fine.

**Comment by plmercereau** [comment]
Many thanks for that, I'll look into it soon!
