### ISSUE TITLE
Subscription watcher in nhost-vue fires on every refresh-token

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#665]
I'm trying new nhost-vue, subscriptions part (on top of my existing code that uses @nhost-js). I have a simple subscription and a watcher for that data.
I'm noticing that each time auth token is refreshing (onTokenChanged, about every 10 minutes) my watcher for this subscription is firing (with no actual data changes). Is this proper behavior?

**Comment by plmercereau** [comment]
Hello Yuriy,
Are we talking about GraphQL subscriptions, set with `@nhost/apollo`?
If so, it is absolutely normal: with Hasuta and most of GraphQL servers, it is not possible to send the authorisation header after the websocket connection started. The only way to send new credentials is to stop the connection and restart it. The Apollo client that we configured does that exactly, so we are sure the access token that is used by Hasura is still valid

**Comment by yureckey** [comment]
ah I see, I thought it looked a bit suboptimal...
ok then, not a bug - a feature!
