### ISSUE TITLE
Is it possible to adapt auth schema to accept only sha256 hashed email address?

### ISSUE THREAD

**Issue by dnk8n** [nhost/nhost#672]
I don't want to store sensitive data of my users. If they want to reset their password, they can supply their email and we can check hashes and send email to the supplied email without ever committing plaintext email string to a database.

**Comment by elitan** [comment]
We will not hash emails.

However, if you need it you can create a fork of [Hasura Auth](https://github.com/nhost/hasura-auth) and implement it.

**Comment by dnk8n** [comment]
Is GDPR not a concern?

I will have to fork. Thank you :)

**Comment by elitan** [comment]
> Is GDPR not a concern?

No. Not from our perspective.

> I will have to fork. Thank you :)

No worries. 👍
