### ISSUE TITLE
Subscriptions don't support x-hasura-role

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#674]
Converting a GraphQL query from `useQuery` to `useSubscription` produces different results when `x-hasura-role` is used. The result of running `useSubscription` returns the same values as the default role value for the authenticated user. I verified `useQuery` passes `x-hasura-role` in the header however `useSubscription` does not pass the `x-hasura-role` neither in the header nor in the message body.

```
const { data } = useQuery(QUERY, {
  context: {
    headers: {
      'x-hasura-role': 'employee',
    },
  },
});
```
vs
```
const { data } = useSubscription(QUERY, {
  context: {
    headers: {
      'x-hasura-role': 'employee',
    },
  },
});
```

**Comment by elitan** [comment]
I think that's because when using the Subscription the role is set when the subscription connection is established with Hasura. This establishment can happen much earlier than the actual subscription.

I think there are two solutions:

1. (easy) Use `useQuery` with [polling](https://www.apollographql.com/docs/react/data/queries/#polling) instead:


```js
const { data } = useQuery(QUERY, {
  pollInterval: 1500,
  context: {
    headers: {
      'x-hasura-role': 'employee',
    },
  },
});
```

2. (hard) Create a new WebSocket connection to Hasura for every new subscription to make sure the `x-hasura-role` header is set correctly. 

This issue is also discussed at Hasura here: https://github.com/hasura/graphql-engine/issues/3566

**Comment by plmercereau** [comment]
That being said, the `headers` option that is given when creating the Apollo client is not reflected in subscriptions, and this is a bug. [This PR](https://github.com/nhost/nhost/pull/677) should help you in your issue.

@elitan well explained the bottleneck of headers and subscriptions over websockets. With this PR, you will however be able to create a second Apollo client with a specific role, for instance:

```jsx
import { useSubscription } from '@apollo/client'
import { createApolloClient } from '@nhost/apollo'

export const MyComponent = () => {
  const [client, setClient] = useState()
  useEffect(() => {
    if (!client) {
      // nhost is your Nhost client created with const nhost = new NhostClient(...)
      setClient(createApolloClient({ nhost, headers: { 'x-hasura-role': 'other-role' } }))
    }
  }, [])
  const { data } = useSubscription(MY_SUBSCRIPTION, { client })
  return (
    <div>
      {JSON.stringify(data)}
    </div>
  )
}
```

It is not an ideal workaround, but I hope this will help

**Comment by jovermier** [comment]
The above approach doesn't work consistently when using `const nhost = useNhostClient();`

It seems to work most of the time when hot loading the component. As soon as I navigate away and return or start on a different page then navigate to the component with the subscription with non-default role then the websocket never starts. I suspect it works if it is the first websocket created but if other websockets are created first then it fails to open a socket.
