### ISSUE TITLE
Nextjs: securing API routes

### ISSUE THREAD

**Issue by ownadi** [nhost/nhost#694]
What's the best way to secure an API route? Currently I'm using an ugly hack:

```ts
export default async (req: NextApiRequest, res: NextApiResponse) => {
  const ctx = {
    req, res, query: req.query
  }

  // @ts-ignore
  const nhost = await createServerSideClient(process.env.NEXT_PUBLIC_NHOST_URL || "", ctx);

  const isAuthenticated = nhost.auth.isAuthenticated()
  if (!isAuthenticated) return res.status(401).json(null);

  // ...
}
```

Isn't there a race condition for refresh token anyway?

**Comment by osseonews** [comment]
Doesn't the JWT get sent to the API endpoint via some sort of cookie? Then you could verify the JWT by getting the cookie and JWT.verify using the secret ENV. But, maybe I'm mistaken how nhost actually receives the JWT and sends it to the server. I'm a bit confused myself by how the JWT is stored and sent.

**Comment by ownadi** [comment]
https://github.com/nhost/nhost/discussions/738
