### ISSUE TITLE
Upgrade Hasura to version 2.9.0

### ISSUE THREAD

**Issue by noverby** [nhost/nhost#695]
Just an issue to track Hasura v2.9.0 upgrade on the nhost platform.

**Comment by elitan** [comment]
Are you a time traveler? 😅  Hasura just released [v2.8.0-beta.1](https://github.com/hasura/graphql-engine/releases/tag/v2.8.0-beta.1) a few hours ago :>

**Comment by noverby** [comment]
Just a really early adopter, I guess 😅

**Comment by plmercereau** [comment]
Hasura 2.10.1 is now live
