### ISSUE TITLE
Changing Gravatar settings causes Hasura crash

### ISSUE THREAD

**Issue by anelad** [nhost/nhost#701]
I've changed `AUTH_GRAVATAR_DEFAULT ` in Nhost Console and Hasura got crashed. Even changing it back to **blank** did not save Hasura and I had to disbale it completely to get everyting work back.

**Comment by plmercereau** [comment]
Can't reproduce, closing for now. If you're still facing this issue, please share a reproduction link, for instance a video recording of the steps that led to the crash
