### ISSUE TITLE
Allowed Redirect URLs with special chars causes Hasura crash

### ISSUE THREAD

**Issue by anelad** [nhost/nhost#702]
Adding URLs like `xxxx-xxxx.vercel.app` (it contains dash char) to the **Allowed Redirect URLs** (and I suspect adding them as the **Client URL** too) causes Hasura crash.

**Comment by plmercereau** [comment]
Hello Arda, I can't reproduce, could you explain the steps to reproduce the error, and what crashes exactly?

**Comment by anelad** [comment]
There is nothing more than I have already said; I just enter my vercel url, which contains dash, crashes Hasura.

Hasura console gives nginx error of 404 and as expected nhost console cannot fetch users or files.

When I delete it, hasura does not reborn until I enter localhost or any other url does not contain special chars. That's why I have changed my vercel url not to contain dash.

I don't know what can I give you more but that's all I have :/

**Comment by anelad** [comment]
Done @guicurcio . Thank you
