### ISSUE TITLE
Types have separate declarations of a private property '_client'

### ISSUE THREAD

**Issue by ManojGaru** [nhost/nhost#712]
import NhostClient from @nhost/nextjs then creating instance with backend url , it is saying nhost issue in NhostNextProvider 

![This is an image](https://i.postimg.cc/RVnTcw6N/Screenshot-from-2022-06-15-13-24-54.png)

**Comment by ManojGaru** [comment]
{
  "name": "delivery-demo-next",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "generate": "graphql-codegen"
  },
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-regular-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@graphql-codegen/typescript": "^2.4.11",
    "@graphql-codegen/typescript-operations": "^2.4.0",
    "@graphql-codegen/typescript-react-apollo": "^3.2.14",
    "@mantine/core": "^4.2.11",
    "@mantine/dates": "^4.2.4",
    "@mantine/hooks": "^4.2.11",
    "@mantine/modals": "^4.2.5",
    "@mantine/next": "^4.2.11",
    "@mantine/notifications": "^4.2.5",
    "@nhost/nextjs": "^1.6.0",
    "@nhost/react": "^0.8.0",
    "@nhost/react-apollo": "^4.6.0",
    "@react-leaflet/core": "^2.0.0",
    "@types/bcrypt": "^3.0.1",
    "@types/leaflet": "^1.7.10",
    "@types/react-slick": "^0.23.8",
    "bcrypt": "^4.0.1",
    "chart.js": "^3.8.0",
    "dayjs": "^1.11.2",
    "faker": "^6.6.6",
    "graphql": "^16.5.0",
    "immutability-helper": "^3.1.1",
    "leaflet": "^1.7.1",
    "leaflet-draw": "^1.0.4",
    "leaflet-geosearch": "^3.6.0",
    "moment": "^2.29.3",
    "next": "12.1.6",
    "react": "^18.1.0",
    "react-chartjs-2": "^4.2.0",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-dom": "^18.1.0",
    "react-error-boundary": "^3.1.4",
    "react-glide": "^4.0.0",
    "react-glider": "^3.1.0",
    "react-leaflet": "^4.0.0",
    "react-leaflet-draw": "^0.19.8",
    "react-slick": "latest",
    "slick-carousel": "^1.8.1",
    "swr": "^1.3.0",
    "tabler-icons-react": "^1.48.0"
  },
  "devDependencies": {
    "@faker-js/faker": "^7.2.0",
    "@graphql-codegen/cli": "^2.6.2",
    "@types/bcryptjs": "^2.4.2",
    "@types/graphql": "^14.5.0",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/leaflet": "^1.7.10",
    "@types/node": "17.0.25",
    "@types/react": "18.0.5",
    "@types/react-dom": "18.0.1",
    "apollo": "^2.34.0",
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.5",
    "typescript": "4.6.3"
  }
}

**Comment by plmercereau** [comment]
Could you try to update `@nhost/react` to `0.11.0`?

**Comment by ManojGaru** [comment]
yes , now it is working by using that @nhost/react version.
