### ISSUE TITLE
Bugs in your NextJs Starter

### ISSUE THREAD

**Issue by osseonews** [nhost/nhost#725]
You have a small bug in your Quickstart NextJs starter package that is in your docs. In the Profile component the submit button is missing an onClick action so the update is never fired. Need to just add: onClick={updateUserProfile} and it works.

**Comment by elitan** [comment]
Would you mind submitting a PR?

https://github.com/nhost/nhost/edit/main/docs/docs/platform/quickstarts/nextjs.mdx

**Comment by elitan** [comment]
Both forms have an `onSubmit` handler that is triggered when the button of type `submit` is clicked, so this should not be an issue.
