### ISSUE TITLE
Cannot build using @nhost/nhost-js with sveltekit

### ISSUE THREAD

**Issue by KTruong008** [nhost/nhost#730]
In accordance with the documentation:

```
import { NhostClient } from '@nhost/nhost-js';

export const createNhostClient = () => {
  return new NhostClient({
    backendUrl: import.meta.env.VITE_NHOST_BACKEND_URL as string
  });
};
```

But when I try to build this error pops up:

`SyntaxError: Named export 'NhostClient' not found. The requested module '@nhost/nhost-js' is a CommonJS module, which may not support all module.exports as named exports.`

**Comment by plmercereau** [comment]
Would you mind sharing a reproduction link? For instance a stackblitz project

**Comment by KTruong008** [comment]
https://stackblitz.com/edit/sveltejs-kit-template-default-breqnl?file=package.json

**Comment by KTruong008** [comment]
The error appears when running `npm run build`, though I was able to work around this issue by reverting back to 1.1.9

**Comment by plmercereau** [comment]
Hello,
Could you add the following configuration piece in `svelte.config.js`?
```js
const config = {
  // ...
  kit: {
    // ...
    vite: {
      ssr: {
        noExternal: ['@nhost/nhost-js'],
      },
    },
  },
}
export default config
```
https://github.com/sveltejs/kit/blob/master/documentation/faq/70-packages.md

**Comment by szilarddoro** [comment]
Considering that our build setup didn't change drastically since `1.1.9` as ESM related changes were reverted, I would say that this must be related to our `exports` field. I'll take a look at this issue soon.
