### ISSUE TITLE
`useAuthenticationStatus` on unstable network

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#752]
From [Discord](https://canary.discord.com/channels/552499021260914688/615892613081333794/988443302783250453).

If `/v1/auth/token` is not accessible, `isLoading` and `isAuthenticated` (from `useAuthenticationStatus`) are both `false`.

This can cause a problem when protecting routes:

```js
import { useAuthenticationStatus } from '@nhost/react'
import { Navigate, useLocation } from 'react-router-dom'

const ProtectedRoute = ({ children }) => {
  const { isAuthenticated, isLoading } = useAuthenticationStatus()
  const location = useLocation()

  if (isLoading) {
    return (
      <div>Loading</div>
    )
  }

  if (!isAuthenticated) {
    return <Navigate to="/sign-in" state={{ from: location }} replace />
  }

  return children
}

export default ProtectedRoute
```

If you're on a mobile phone, and the connection is not stable, it could be that our js SDK tries to sign in the user by making a request to `/v1/auth/token`. The endpoint is not reachable because of the bad connection from the mobile phone. So the SDK sets both `isLoading` and `isAuthenticated` to `false`, which will cause the user to be redirected to `/sign-in`.

Here's what we could do:

1. `isLoading` should only return `false` once the SDK is 100% sure about the `isAuthenticated` state. That means that `isLoading` should only be set to `false` if the SDK gets an actual response from `/v1/auth/token`. Either a `200 OK` or `401 Unauthorize`.
2. If the SDK can't reach `/v1/auth/token` because the network connection is unstable, the SDK should retry the request every 5 seconds until it successfully gets a response.
3. (not sure about this one): We can also introduce a new variable to `useAuthenticationStatus` indicating what's the reason for `isLoading` to be `false`. The reason will always be because the SDK is waiting for a network request, but it could be useful to inform if the network is stable and the SDK is making the first request, or if the network is unstable and the SDK is making the 10th request.

**Comment by plmercereau** [comment]
We could set a retry logic when the auth service cannot be reached, but with the above suggestion, the loading status will remain indefinitely at `true` when the user is offline.
When offline or with a poor connectivity, it is possible to check if a refresh token is present in the local storage:
- If not present, we know the user is not authenticated -> `isLoading` to `false`,  `isAuthenticated` to `false` (current behaviour)
- if present, we know a user _should_ authenticate eventually, unless something goes wrong (for instance invalidated refresh token)

**Comment by plmercereau** [comment]
Please have a look at the above draft PR:
- on startup, it retries to import the token 20 times: the 5 first times every second, then every 5 second
- in the meantime the authentication status is `loading`

We could improve the mechanism
- in adding a `NhostClient` setting that defines a maximum timeout period (default to 3 seconds, in my opinion)
- in adding a boolean `isOffline` to `useAuthenticationStatus` and `nhost.auth.getAuthenticationStatus`

Let me know what you think before I go towards that path.
