### ISSUE TITLE
Access token missing in Graphql request

### ISSUE THREAD

**Issue by nachoaldamav** [nhost/nhost#790]
Since the update that added the CDN (nhost@latest) the Access token was not passed to GraphQl queries from `nhost.graphql.request`.

I had this problem with a nextjs app, but `useAuthQuery` works well.

**Comment by elitan** [comment]
Thanks for reporting.

Can you make sure the user is signed in before sending the request by do a console log like this:

```js
// make sure user is signed in
console.log(nhost.auth.getUser())

// GraphQL request (with missing authorization header)
await nhost.graphql.request(...)
```

**Comment by nachoaldamav** [comment]
Closing this issue as it's not an nhost error.
To avoid this with react, you should wait until the user data is available.

Example:
```jsx
useEffect(() => {
    if (userId) getRoom(room as string);
}, [userId]);
```

**Comment by elitan** [comment]
You can also make use of `isAuthenticatedAsync` to wait and see if the user is signed in or not.

https://docs.nhost.io/reference/javascript/auth/is-authenticated-async

**Comment by oristian** [comment]
I'm having a similar issue, where a user is logged in, but their accessToken is not passed to the graphql request.  Only workaround is to make permissions public on the tables in question.  For instance I have logic on a page that only shows a button if the user isAuthenticated (derived from useAuthenticationStatus).  I check (isAuthenticated and !loading) but when they issue the mutation via a button click, the Auth headers are not passed.  Using @nhost/nextjs version 1.6.1

**Comment by plmercereau** [comment]
Could you please share the arguments you are using when creating the Nhost client?

**Comment by elitan** [comment]
We were able to fix @oristian's issue by:

- Upgrading all `@nhost/*` packages to the latest version
- Removing `@nhost/nhost-js` and `@nhost/react-auth` as dependencies, and only use `@nhost/nextjs`, `@nhost/react` and `@nhost/react-apollo`.
