### ISSUE TITLE
Nhost cloud doesn't create postgres triggers

### ISSUE THREAD

**Issue by heygambo** [nhost/nhost#795]
Hey, I'm using the docker-compose in the example to test my app locally.
I've created a Postgres function and a trigger locally and made it a migration.
Locally everything works fine. But I have trouble on Nhost.
It doesn't want to create the trigger.

```sql
CREATE OR REPLACE FUNCTION "app"."set_next_ingredient_position"() RETURNS TRIGGER AS
$BODY$
DECLARE
  _new record;
  pos integer;
BEGIN
  _new := NEW;
  SELECT count(*) INTO pos FROM "app"."ingredients" WHERE "ingredient_id" = _new."ingredient_id";
  _new."position" = pos + 1;
  RETURN _new;
END;
$BODY$
LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER "set_app_ingredients_position"
BEFORE INSERT ON "app"."ingredients"
FOR EACH ROW
EXECUTE FUNCTION "app"."set_next_ingredient_position"();
```

The function creation works, but the trigger does not.

I'm not sure how to further debug this without being able to look into the Nhost Postgres database.

Postgres error:
```json
{
    "statement": "CREATE OR REPLACE TRIGGER \"set_app_ingredients_position\"\nBEFORE INSERT ON \"app\".\"ingredients\"\nFOR EACH ROW\nEXECUTE FUNCTION \"app\".\"set_next_ingredient_position\"();",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "syntax error at or near \"TRIGGER\"",
        "status_code": "42601",
        "description": null
    },
    "arguments": []
}
```

It executes the trigger code when I change "CREATE OR REPLACE" to "CREATE", but it doesn't run the trigger when inserting data.

**Comment by kratam** [comment]
If I remember correctly, I solved a similar error by creating the function and the trigger in 2 different migrations.
Triggers definitely work on nhost cloud as I use some in production.

**Comment by plmercereau** [comment]
Probably a problem related to [inconsistent Postgres versions between the CLI and the Cloud](https://github.com/nhost/cli/issues/255). the "OR REPLACE" has been introduced in v14, and it feels like v12 (CLI) was permissive about using the clause (although probably ignoring it), whereas v13 fails when using it.
As a workaround, I would rewrite the trigger part of the migration as follows:

```sql
DROP TRIGGER IF EXISTS  "set_app_ingredients_position" ON "app"."ingredients";

CREATE TRIGGER "set_app_ingredients_position" BEFORE INSERT ON "app"."ingredients"
FOR EACH ROW EXECUTE FUNCTION "app"."set_next_ingredient_position"();
```
