### ISSUE TITLE
Error in development when calling Hasura action

### ISSUE THREAD

**Issue by suplere** [nhost/nhost#797]
Hello,
My develop setup:
Windows 11
NHost dev run in WSL (Ubuntu)
Frontend develop is in Windows 11.

I setup action : Webhook (HTTP/S) Handler : {{NHOST_BACKEND_URL}}/v1/functions/actions/updateEvent

when I call mutation I get this error: **http exception when calling webhook**
Whole error log:
`
{"type":"http-log","timestamp":"2022-07-05T11:44:55.804+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin","x-hasura-user-is-anonymous":"false","x-hasura-user-id":"b316dd6a-a298-4224-ba7e-91adbd16bd74"},"error":{"internal":{"error":{"type":"http_exception","message":"Connection failure","request":{"secure":false,"path":"/v1/functions/actions/updateEvent","responseTimeout":"ResponseTimeoutMicro 30000000","queryString":"","method":"POST","requestHeaders":{"Content-Type":"application/json","X-B3-ParentSpanId":"7847561303985693","X-B3-TraceId":"1f89ede19b85438b","X-B3-SpanId":"71191f19368a7692","User-Agent":"hasura-graphql-engine/v2.2.0","nhost-webhook-secret":"nhost-webhook-secret"},"host":"172.17.71.44","port":1337}},"response":null,"request":{"body":{"request_query":"mutation updateEvent($event: UpdateEventInput!, $participants: UpdateEventParticipants!) {\n updateEvent(event: $event, participants: $participants) {\n rows\n __typename\n }\n}","session_variables":{"x-hasura-role":"admin","x-hasura-user-is-anonymous":"false","x-hasura-user-id":"b316dd6a-a298-4224-ba7e-91adbd16bd74"},"input":{"event":{"location":"","end_date_time_utc":"2022-07-28T16:00:00+00:00","event_type":"trenink","start_date_time_utc":"2022-07-28T14:30:00+00:00","teams_id":"92baeaec-ef4c-4f23-9515-6d5fa8552f7d","created_by":null,"id":"c6218c8f-7c69-4e3e-9051-ffc49e95b303","title":"Test Event","description":""},"participants":{"staffs_ids":[],"delete_staff_ids":[],"players_ids":[],"delete_player_ids":[]}},"action":{"name":"updateEvent"}},"transformed_request":null,"url":"http://172.17.71.44:1337/v1/functions/actions/updateEvent","headers":[{"name":"nhost-webhook-secret","value_from_env":"NHOST_WEBHOOK_SECRET"}]}},"path":"$","error":"http exception when calling webhook","code":"unexpected"},"request_id":"36fb6dde-c67e-42ef-b97c-3a26d6ac740f","response_size":1583,"query":{"variables":{"event":{"location":"","end_date_time_utc":"2022-07-28T16:00:00+00:00","event_type":"trenink","start_date_time_utc":"2022-07-28T14:30:00+00:00","teams_id":"92baeaec-ef4c-4f23-9515-6d5fa8552f7d","created_by":null,"id":"c6218c8f-7c69-4e3e-9051-ffc49e95b303","title":"Test Event","description":""},"participants":{"staffs_ids":[],"delete_staff_ids":[],"players_ids":[],"delete_player_ids":[]}},"operationName":"updateEvent","query":"mutation updateEvent($event: UpdateEventInput!, $participants: UpdateEventParticipants!) {\n updateEvent(event: $event, participants: $participants) {\n rows\n __typename\n }\n}"},"request_mode":"error"},"request_id":"36fb6dde-c67e-42ef-b97c-3a26d6ac740f","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"::1","method":"POST","content_encoding":null}}}
`

**In production all works fine.** This issue is on local development.

**Comment by suplere** [comment]
The same error apears while i call event :

"data": {
        "message": "{\"type\":\"http_exception\",\"message\":\"Connection failure\",\"request\":{\"secure\":false,\"path\":\"/v1/functions/events/userCreate\",\"responseTimeout\":\"ResponseTimeoutMicro 60000000\",\"queryString\":\"\",\"method\":\"POST\",\"requestHeaders\":{\"Content-Type\":\"application/json\",\"X-B3-ParentSpanId\":\"7e07410f4eb22845\",\"X-B3-TraceId\":\"16a00f3d0ca9cfae\",\"X-B3-SpanId\":\"bff2e9b25c933bc6\",\"User-Agent\":\"hasura-graphql-engine/v2.2.0\",\"nhost-webhook-secret\":\"nhost-webhook-secret\"},\"host\":\"172.17.66.180\",\"port\":1337}}"
    },
    "version": "2",
    "type": "client_error"

**Comment by elitan** [comment]
Seems like Hasura can not access Functions. We're working on a new structure for the Nhost CLI where Hasura and Functions will be in the same docker network, which will probably fix this issue.

PR is here: https://github.com/nhost/cli/pull/257

**Comment by elitan** [comment]
@suplere This should have been fixed in the latest CLI where the networking between Hasura and Functions has been fixed.

If you still encounter this issue, please let me know, and I'll re-open this issue.
