### ISSUE TITLE
Storage page crashes in Nhost dashboard

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost#798]
I ran into an issue where the Storage page crashes when browsing it with the following error:

![image](https://user-images.githubusercontent.com/24279217/177406949-185a1a35-0936-4c73-9474-e7716600c066.png)

For myself, this started with just one page but now it is every time I navigate to Storage tab. This is my url: https://app.nhost.io/yumee-workspace/yumee/storage

In developer tools on Brave (Chrome based browser), this is the error:

```
framework-79bce4a3a540b080.js:1 TypeError: Cannot read properties of null (reading 'startsWith')
    at E (storage-07274f4815dab91e.js:1:17573)
    at Cell (storage-07274f4815dab91e.js:1:27635)
    at oo (framework-79bce4a3a540b080.js:1:59417)
    at Ku (framework-79bce4a3a540b080.js:1:111717)
    at Li (framework-79bce4a3a540b080.js:1:98958)
    at Ni (framework-79bce4a3a540b080.js:1:98886)
    at Pi (framework-79bce4a3a540b080.js:1:98749)
    at bi (framework-79bce4a3a540b080.js:1:95715)
    at framework-79bce4a3a540b080.js:1:45209
    at t.unstable_runWithPriority (framework-79bce4a3a540b080.js:1:129355)```

**Comment by Svarto** [comment]
I noticed that one row in my Hasura DB had an image_id of NULL and that broke the Nhost dashboard. Not sure how that row got in there, or if it was tied to an image (or which image in that case). Anyway, when I removed that NULL row then the dashboard started working again.

Maybe some checks in storage or the dashboard being able to handle NULL values @elitan @szilarddoro @dbarrosop

**Comment by szilarddoro** [comment]
Thanks for the follow up! 🙏🏼 

Yes, I was going to say, that something must have gone wrong in your database, because `startsWith` is called on a value that shouldn't be null. I was too optimistic there I guess 😃 

The fix is already prepared for this, we'll release it soon.
