### ISSUE TITLE
Apollo Devtools for Chrome and Firefox Not working with NhostApolloProvider

### ISSUE THREAD

**Issue by taylrd** [nhost/nhost#8]
The apollo devtools do not work with nhostapolloprovider. I can interact with the GraphiQl and run queries or mutations but the queries, mutations and cache tabs are empty. I have tested my other GraphQl apps (even ones running with Hasura api) and the browser extension works properly and is stable.

My current working versions for both browsers are: 

Im on a Macbook
Chrome v. 89.0.4389.90
ApolloClient Devtools v. 3.0.2
@nhost/react-apollo 1.0.7

Firefox: latest

**Comment by plmercereau** [comment]
Hello @taylrd,
better late than never.
Here's how to activate Apollo DevTools:
```jsx
 <NhostApolloProvider nhost={nhost} connectToDevTools={true}>
      <App />
    </NhostApolloProvider>
```
You can find an example here:
https://github.com/plmercereau/vitejs-nhost-apollo
