### ISSUE TITLE
Bug - x-hasura-user-id is not accessible in production function

### ISSUE THREAD

**Issue by wontwon** [nhost/nhost#80]
# Description
Currently in local development, I am able to access the x-hasura-user-id in a custom function by forwarding client headers. I access the user id this way below locally and it works.
```
const userId = req.body.session_variables["x-hasura-user-id"];
```

# Problem
In the nhost production function, I am unable to access x-hasura-user-id. This is the error that was pulled from an nhost team member to help me debug:

```Test Event Name
(unsaved) test event

Response
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "TypeError: Cannot read property 'x-hasura-user-id' of undefined",
  "trace": [
    "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'x-hasura-user-id' of undefined",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:400:28)",
    "    at processPromiseRejections (internal/process/promises.js:245:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
  ]
```

# Expectation
I should be able to access the x-hasura-user-id from the session_variables the same way in production as I do in local development

**Comment by elitan** [comment]
Is the function triggered by an Event trigger from Hasura?

If it is, I still don't 100% understand why this is working locally because the variable should be available under `req.body.event.session_variables` (notice the `event`). [Docs reference](https://hasura.io/docs/latest/graphql/core/event-triggers/payload.html)

If the function is **not** triggered by an Event trigger, how do trigger the function?

**Comment by wontwon** [comment]
@elitan The function is triggered by a Hasura action. 

I went ahead and logged out the req.body from my local by adding this line to my function: `console.log("For the Nhost team: ", req.body);`

This is what gets logged out when I run the mutation that is linked to the custom function:

```
For the Nhost team:  {
  session_variables: {
    'x-hasura-role': 'user',
    'x-hasura-user-isanonymous': 'false',
    'x-hasura-user-id': '4a4f1ff9-03ee-4070-a126-593ea69547f3'
  },
  input: {
    object: {
      price_id: 'price_1JMLyLHlpGgmr1VnVnSVA7T4',
      occasion_id: null,
      custom_prompt: '',
      recipient_name: 'Johan',
      is_group: false,
      sender_name: 'Tuan',
      prompt_id: null
    }
  },
  action: { name: 'createAwwdio' }
}
```

I'm wondering if it could be a cache related issue?

**Comment by elitan** [comment]
@wontwon Ok, so it's a Hasura action. If `session_variables` are not set it means you're not logged in when you do the Hasura Action.

Can you double-check the network request headers for the GraphQL request with the Hasura action? Does the network request has the `Authorization` header set?

I would assume that locally when the action works, the `Authorization` header is set. Then, in production, when the action does not work, the `Authorization` header is not set.

**Comment by wontwon** [comment]
@elitan, I just tried again and it looks like the Authorization header is set as expected, but still getting a 500 error. Please see attached screenshot:
![Screen Shot 2021-11-26 at 12 54 23 AM](https://user-images.githubusercontent.com/3239936/143553968-a8b385b9-e5a6-460b-be44-a5db53f2aa5c.png)

**Comment by elitan** [comment]
Sure looks good!

And what if you print out the body for both the local function and the prod function with:

```js
console.log(JSON.stringify(req.body, null, 2));
```

**Comment by nunopato** [comment]
@wontwon the issue seams to be with the content type: if you add `Content-Type: application/json` as a header on your action definition it should fix the issue.

**Comment by wontwon** [comment]
@nunopato the content type is set. I just didn't include that part in the header image, sorry.
![Screen Shot 2021-11-26 at 8 47 45 AM](https://user-images.githubusercontent.com/3239936/143611640-3398c8df-3a23-47d4-98f2-6cfcece65b62.png)

**Comment by elitan** [comment]
We'll try to reproduce this internally. Very strange indeed.

**Comment by nunopato** [comment]
@wontwon Is this still an issue for you?

**Comment by wontwon** [comment]
Issue was resolved on the Nhost end. Thanks team!
