### ISSUE TITLE
SSR codegen examples

### ISSUE THREAD

**Issue by ejkkan** [nhost/nhost#800]
For NextJs it would be great to have examples using SSR with the codegen examples from your [blogpost](https://landing-next-git-blog-codegen-nhost.vercel.app/blog/how-to-use-graphql-code-generator-with-react-and-apollo).

It would be extra neat to have examples with both Apollo(as highlighted in the post) and with React Query.

**Comment by oskery** [comment]
Not sure if it helps, but his is how I currently do it (given the customers-example):

`src/graphql/customers.graphql`:
```grapqhl
query getCustomers($limit: Int) {
  customers(limit: $limit) {
    id
    name
  }
}
```
`pages/customers.tsx`
```react
...
export async function getServerSideProps({ query: { limit } }: GetServerSidePropsContext) {
  const { data, error } = await nhost.graphql.request(GetCustomersDocument, {
    limit,
  });
  if (error) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      ...data,
    },
  };
}
```

**Comment by elitan** [comment]
Here's a live example with Nhost and React Query:

https://matterday-nhost.netlify.app/matters/1c664a23-f0cd-4849-b030-47e901129b81

Repo:

https://github.com/nhost/matterday.netlify.com

Interesting parts:

- https://github.com/nhost/matterday.netlify.com/blob/main/pages/matters/%5Bid%5D.tsx#L12-L25
- https://github.com/nhost/matterday.netlify.com/blob/main/graphql.config.yaml#L6-L19
- https://github.com/nhost/matterday.netlify.com/blob/main/pages/_app.js#L58-L62

I'll write a post about it in the future.


Demo:
