### ISSUE TITLE
Custom Postgres functions' args switched to lowercase somewhere in dev pipeline

### ISSUE THREAD

**Issue by reisupdev** [nhost/nhost#801]
While developing a custom PG function locally I encountered a few gotchas around arg names:

- originally I used snake_case for the function's args because that's what the default was when I set up tables using the Hasura dashboard and thinking the function would have a similar option to rename them to camelCase - however that doesn't exist.

- Because I aliased all the tables, fields etc to camelCase, I then used the SQL tool to drop the function and recreate it with camelCase args. The code saved in the migration file locally includes the args in camelCase correctly.

- when I then went to test in the GQL explorer (after refreshing) the function shows up but it's all lowercase not camelCase

- also note: it was only in the function "signature" that the names were all lower case: once the args were lowercase, the _uses_ of the args in the body were still camelCase.

Original:
`CREATE OR REPLACE FUNCTION public."assign"(source_id_arg uuid, target_id_arg uuid)`

Dropped then added again as:
`CREATE OR REPLACE FUNCTION public."assign"(sourceId uuid, targetId uuid)`

But what I see if I view the function from dashboard (args in lowercase, usage in camelCase):
```
CREATE OR REPLACE FUNCTION public."assign"(sourceid uuid, targetid uuid) RETURNS SETOF targets LANGUAGE sql AS $ function $
UPDATE
  public.targets
SET
  source_id = sourceId
WHERE
  "id" = targetId RETURNING *;
$ function $
```

**Comment by elitan** [comment]
According to the SO link above, dropping the function and creating it again should solve this issue. I'd be happy to re-open this issue if anyone does not get it to work.
