### ISSUE TITLE
UI ERROR: Status email verification Link

### ISSUE THREAD

**Issue by eduardocampo** [nhost/nhost#812]
before
![image](https://user-images.githubusercontent.com/43253539/178179363-ca98f809-1253-435d-876f-d233006aa9ef.png)
After
![nhost issus 1](https://user-images.githubusercontent.com/43253539/178177229-588cc80f-a268-46a6-8bfd-88250ca81958.JPG)
The status is lost, after clicking on the email verification link

**Comment by szilarddoro** [comment]
This should be fixed now @eduardocampo. Please let us know if the issue persists.

**Comment by eduardocampo** [comment]
Solved!! 👌
