### ISSUE TITLE
Invalid or expired refresh token after ~10 minutes of inactive tab in my Next app

### ISSUE THREAD

**Issue by st3phan** [nhost/nhost#813]
I have been receiving `401 Unauthorized` on `/v1/auth/token` when returning to a browser tab after about 10 minutes of inactivity. 
After these 10 minutes everything seems to be working with a new access token but the `401 Unauthorized` keep appearing.

Package versions:
```
"@nhost/nextjs": "^1.6.1",
"@nhost/nhost-js": "^1.4.5",
"@nhost/react": "^0.11.1",
"@nhost/react-apollo": "^4.6.1",
```

Here's a rundown with screenshots of my developer tools console.

1. Last `200 OK` query before leaving the browser tab:

![Screenshot 2022-07-11 at 15 58 18](https://user-images.githubusercontent.com/416652/178281243-9de0e426-9f7d-436d-a3f3-81f61b37e50d.png)

2. Successful request for a new access token (about 10 minutes later):

![Screenshot 2022-07-11 at 15 58 23](https://user-images.githubusercontent.com/416652/178281251-7a5fa0b8-0400-46ce-aca5-df82887f9fc1.png)

3. Unsuccessful request for a new access token at the same time of previous successful request:

![Screenshot 2022-07-11 at 15 58 28](https://user-images.githubusercontent.com/416652/178281253-71f15599-bc0e-436d-8f4f-452300fc6a8e.png)

4. Started clicking around in my app again. I'm still authorised. Access token seems to be changed.

![Screenshot 2022-07-11 at 15 58 35](https://user-images.githubusercontent.com/416652/178281258-02256098-f01b-44c2-a142-f49b4a2cc94b.png)

5. The `401 unauthorized` messages keep appearing every 5 seconds.

![Screenshot 2022-07-11 at 15 58 40](https://user-images.githubusercontent.com/416652/178281262-ba89fae1-fe5a-4541-9d7f-3eec059e02fc.png)

**Comment by elitan** [comment]
It should be fixed in this pr: https://github.com/nhost/nhost/pull/823

Can you try with the latest version of `@nhost/nextjs`?

If you still experience problems, let me know, and we'll re-open this issue.

**Comment by Rigel772** [comment]
![image](https://user-images.githubusercontent.com/1696243/202924935-5c9b7c96-376c-464c-90a2-1ce1287a56ef.png)
Is it same problem?
It is on React app.

**Comment by Rigel772** [comment]
![image](https://user-images.githubusercontent.com/1696243/202925101-47a132df-75c9-4c1e-a63d-fab8da75440f.png)
Looks very similar... the application works ok.
Nhost on private server from docker-compose.
