### ISSUE TITLE
auth.changePassword not working - message: old_password must be a string

### ISSUE THREAD

**Issue by camillo18tre** [nhost/nhost#82]
Hello there!
I'm trying to change the password as logged In user. I read [docs here](https://docs.nhost.io/auth/api-reference#change-password) 

When I send the request I get this error (even if I'm passing a string):
<img width="669" alt="Schermata 2021-11-30 alle 12 52 19" src="https://user-images.githubusercontent.com/38567269/144043835-3e333653-f948-4b13-a059-528a18480991.png">

Here my code:
<img width="682" alt="Schermata 2021-11-30 alle 12 54 31" src="https://user-images.githubusercontent.com/38567269/144043879-41f51c24-1291-4d5f-8147-714261def059.png">

I hope you can help me.
Thank you

**Comment by elitan** [comment]
Your code looks alright, I think this is a bug in our authentication system.

We have an open PR to remove the `oldPassword` parameter. It's being tracked here: 

https://github.com/nhost/hasura-auth/pull/47

Once that PR is merged and released you don't need to provide the `oldPassword`.

**Comment by camillo18tre** [comment]
@elitan  Looks great! Is that working on local environment?

**Comment by elitan** [comment]
We're working on releasing this in one go (both server and SDK updates). I'll get back here once it's done.

**Comment by elitan** [comment]
Btw @camillo18tre, just to clarify, is this issue related to Nhost or Nhost v2 (currently in private beta)?

**Comment by camillo18tre** [comment]
@elitan 
from my package.json:

"nhost": "^0.4.7",
"nhost-js-sdk": "^3.1.0",

**Comment by elitan** [comment]
This is now fixed in both prod and with the CLI.

Btw @camillo18tre, make sure to use our CLI specified here: https://docs.nhost.io/platform/nhost/local-development

and this npm package: `@nhost/nhost-js`.

The ones you're referring to are old packages for Nhost v1.
