### ISSUE TITLE
React - Upload error when filename contain utf8 chars

### ISSUE THREAD

**Issue by dgoujard** [nhost/nhost#822]
Hi,

When i try to upload in react with the `useMultipleFilesUpload` (it will be the same with `useFileUpload`) the request isn't sent to the storage microservice and this error appear in the Interpretor event: `"Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point."`

Example with special char: https://postimg.cc/SjvWZBCB
Example with normal filename: https://postimg.cc/Sjs6fS2L

It's seems related to axios, here the corresponding issue: https://github.com/axios/axios/issues/4556 (not resolved)

**Comment by szilarddoro** [comment]
Hey @dgoujard!

We have plans to move away from `axios` at some point in the future.

For now, you can use [`encodeUIRComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to encode the file name.

```ts
const { upload } = useFileUpload()

// In your submit handler
await upload({
  file,
  name: encodeURIComponent(file.name),
  // ... other attributes if you want to set the bucketId, etc.
})
```

Please let me know if this fixed your issue.
