### ISSUE TITLE
NHost Cloud GraphQL User Change Throws Error.

### ISSUE THREAD

**Issue by mdp18** [nhost/nhost#826]
When clicking on the 'User: Admin' button within the GraphQL preview page, you are thrown an error of "Cannot read properties of null (reading 'length').
![image](https://user-images.githubusercontent.com/11698527/179244324-46c5a20f-c30b-4a1b-a5e1-c9aba70a45f4.png)

![image](https://user-images.githubusercontent.com/11698527/179244358-ba5c2eb2-f16d-4c25-bab7-035f58186dda.png)

This only happens when clicking on the user change but not with the role.

**Comment by mdp18** [comment]
@guicurcio and I chatted and found out the issue lies with one of my users not having an email address associated with their account due to the implementation of Passwordless SMS.

**Comment by elitan** [comment]
With the new GraphQL playground, this has been solved.
