### ISSUE TITLE
NHost Cloud UI Bug - Status Unverified when User logs in with Passwordless SMS

### ISSUE THREAD

**Issue by mdp18** [nhost/nhost#827]
When one of my users chooses to use passwordless sms as their authentication method they are listed internally as "unverified" within the nhost cloud user panel.

![image](https://user-images.githubusercontent.com/11698527/179243626-ad534d6b-4233-4a9d-b3ea-9993f0b94775.png)

**Comment by szilarddoro** [comment]
Hey @mdp18! This bug was fixed in our latest release. Let us know if you still have problems.
