### ISSUE TITLE
auth.requestPasswordChange not working - message: ""email" must be a string"

### ISSUE THREAD

**Issue by camillo18tre** [nhost/nhost#83]
Hello guys,
I'm trying to work with "auth" and "recovery password" but It's not working correctly.

I get back this:

```
error: "Bad Request"
message: "\"email\" must be a string"
statusCode: 400
```
 
below my code:

```
auth.requestPasswordChange({
   email: values.email,
 })
.then()
.catch()
```

Is there a way to get the ticket? Reading the docs seems that is not possibile and the only way is to send the ticket by email.
I would get back the ticket and then pass It to the  MailGun Api. Do you think is It possible to do It?

thank you.

**Comment by elitan** [comment]
Is this related to Nhost or Nhost v2 (currently in private beta)?

**Comment by camillo18tre** [comment]
@elitan 
from my package.json:

"nhost": "^0.4.7",
"nhost-js-sdk": "^3.1.0",

**Comment by elitan** [comment]
This is now working 👍 

Please make sure to use the new CLI and the new npm packages. All info here: https://docs.nhost.io/get-started
