### ISSUE TITLE
Wildcard Domain 

### ISSUE THREAD

**Issue by sachinvnagane** [nhost/nhost#831]
It would be great to have wildcard domain support for hasura-auth.

**Comment by elitan** [comment]
Wildcard domains have been added (https://github.com/nhost/hasura-auth/pull/282) and released (https://github.com/nhost/hasura-auth/pull/282) but not yet pushed to all projects at Nhost. That will probably happen next week. I'll close this issue once it's available in Nhost Cloud and the CLI.

**Comment by elitan** [comment]
It's now released 🎉
