### ISSUE TITLE
Url is mangled when using vue-router in hash mode

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#832]
So, I'm using latest nhost-vue sdk.
In my app I'm working now with UI for password-reset / email verify / magic link - staff requried redirection.
My app current url looks something like
https://www.mysite.com/v2test/spa2/#/testpage
and this is the url I set in nhost "Client URL" config.
When I'm calling password reset function, I receive email with url, that got redirected to my https://www.mysite.com/v2test/spa2/#/testpage with additional part like
?refreshToken=xxx&type=passwordReset#refreshToken=xxx&type=passwordReset
but resulting url user presented with became rewritten to: 
https://www.mysite.com/#/testpage
I've spent several hours trying to understand why I'm keep getting wrong resulting url (missing "v2test/spa2" part) thinking it was something with my router. But then I tried manually open url with different parameter (like "ZefreshToken=xxx") and everything was working just fine, no sudden url rewrite. I'm 99% sure now - it's somethin nhost SDK does with url rewrite when it's redirected.

**Comment by plmercereau** [comment]
Hello,
Let me know if this solved your issue
https://github.com/nhost/nhost/releases/tag/%40nhost/vue%400.3.7

**Comment by yureckey** [comment]
thanks for quick response!
I tried with resetPassword, after redirect resulting url became:
https://www.mysite.com/v2test/spa2/#%2Ftestpage%3FrefreshToken=79edb4dd-db0d-4a08-9b81-130a3d65ed36
which is better than was before, but still, could it be just
https://www.mysite.com/v2test/spa2/#/testpage  ?

**Comment by plmercereau** [comment]
- what is your vue-router history mode?
- that is the value of the 'redirectTo` option?

**Comment by yureckey** [comment]
my app is Quasar based, with vue-router set to hash.
if by redirectTo you meant "Allowed Redirect URLs", currently it is same as "Client URL" setting (https://www.mysite.com/v2test/spa2/#/testpage)
