### ISSUE TITLE
Client login URLs not taking from the production dashboard

### ISSUE THREAD

**Issue by subhendukundu** [nhost/nhost#84]
Hey folks,

I am trying to change the Client login URL in the production dashboard, but it is still taking the old one after successful redirect.

For example.
I had localhost previously, now I have changed to the prod url, but after login it is still taking the localhost.

Please let me know if you need more info, I am happy to help.

**Comment by nunopato** [comment]
@subhendukundu is this still happening for you? we fixed a bug in the console that might have caused this for you.

**Comment by subhendukundu** [comment]
Yes, seems like it is fixed. Thank you
