### ISSUE TITLE
camelCase entry for environment variables

### ISSUE THREAD

**Issue by ttiras** [nhost/nhost#844]
One of my dependencies variables is camel case and it is only possible to have them with capitals. So it complains that "apiKey value can not be empty". How can we work this around?

**Comment by ttiras** [comment]
oops, this is duplicate of #793

**Comment by ttiras** [comment]
I think we need to enable different formats for environment variables on nhost console.

github page for the package: https://github.com/iyzico/iyzipay-node

**Comment by elitan** [comment]
Yea, I think we should allow lower case letters as environment variables 👍

**Comment by ttiras** [comment]
Closed but still not possible to type lower case variables on nhost console.

**Comment by elitan** [comment]
Sorry, it was closed because we merged a PR in a private repo. It should be live now :)
