### ISSUE TITLE
Packages cause esbuild to fail. Add option to configure esbuild from Nhost? 

### ISSUE THREAD

**Issue by philip-ditgear** [nhost/nhost#846]
Packages like [sharp](https://sharp.pixelplumbing.com/) are very picky with how it is installed. When sharp is imported to a serverless function, esbuild fails to run.

<img width="1216" alt="Screenshot 2022-07-21 at 17 36 31" src="https://user-images.githubusercontent.com/79211932/180258347-76981307-e998-4de5-9d16-57e40966455c.png">

By configuring esbuild to exclude the package and add a script to install with the right architecture/platform seems like the way to move forward. See solution here: https://github.com/lovell/sharp/issues/3126#issuecomment-1132745490

 How can we configure esbuild from Nhost? Would it be possible to add the esbuild configuration to nhost/config.yaml?

**Comment by dbarrosop** [comment]
quick question, what is your use case for sharp? I am asking because `hasura-storage` has support for manipulating images so if you are missing something there or have a different use case it might be interesting to hear.

**Comment by philip-ditgear** [comment]
> quick question, what is your use case for sharp? I am asking because `hasura-storage` has support for manipulating images so if you are missing something there or have a different use case it might be interesting to hear.

In this particular case, perform different image manipulations together with other business logic depending on if the uploaded file is transparent or opaque. I'm creating a separate lambda function for now. The image is uploaded to a bucket before this function runs, the function saves the final image to another bucket and deletes the source image. 

The issue that occurred when trying to run a function with sharp is that esbuild is failing to build with this package, and there is no current way of configuring esbuild from nhost. I don't know if this problem is small or if there are other packages that have the same problem.
