### ISSUE TITLE
Unable to delete project on Nhost v2

### ISSUE THREAD

**Issue by TaylorFacen** [nhost/nhost#85]
When I try to delete a project in v2, this error pops up in the console.

```
_app-4d83c955826672cd.js:1 Uncaught (in promise) 
Error: Foreign key violation. update or delete on table "apps" violates foreign key constraint 
"deployments_app_id_fkey" on table "deployments"
```
<img width="603" alt="Screen Shot 2021-12-09 at 9 30 27 AM" src="https://user-images.githubusercontent.com/44216029/145415234-084ba545-3ea4-4068-8049-10d209e364fc.png">

**Comment by nunopato** [comment]
@TaylorFacen thanks for reporting this. I am closing it since this has been fixed.
