### ISSUE TITLE
RefreshToken output as "TODO" after successful passwordless SMS login

### ISSUE THREAD

**Issue by mdp18** [nhost/nhost#851]
After completing a successful passwordless login via SMS, I see that the results of the sign-in function provides back the session details..
<img width="727" alt="Screen Shot 2022-07-22 at 4 22 39 PM" src="https://user-images.githubusercontent.com/11698527/180580085-8a3dfc07-284b-4c7b-8174-8a7156b11ce0.png">

Is this normal behavior?

**Comment by elitan** [comment]
Definitely a bug.

[Code for reference](https://github.com/nhost/nhost/blob/main/packages/hasura-auth-js/src/utils/helpers.ts#L39)

**Comment by plmercereau** [comment]
Solved. Closing
