### ISSUE TITLE
React Native logout issue - potential root cause

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost#853]
Hi nhost team,

I have been looking into the React Native sporadic logout issue for awhile now and discussing it on Discord. I might have identified the cause, and as suspected it is an edge case BUT it happens frequently enough that it causes user drop off as the UX default is that you log into an app once and you stay logged in for a very long time.

My hypothesis is that due to mobile apps being backgrounded, and they are also killed on a regular basis for OS memory management, this might cause an edge case where a token is not saved to local storage before the app is killed and thus when it returns to foreground after a long period of time (e.g. a day or two) the `nhost-js` SDK tries to use the "one previous" refreshToken to `refreshSession` causing a logout.

I have reproduced it somewhat regularly by simulating a memory leak in a React Native application like so:

1. Add in the below memory leaker code into your app, e.g. in `App.js`
2. Set your nhost client to `refreshIntervalTime: 1` to increase the likelihood you hit the "right moment"
3. Open your app and immediately background it (check your network logger what is the previous & latest refreshToken)
4. Kill the simulator app with `xcrun simctl terminate <SIMULATOR_ID> <BUNDLE_ID>`
5. Re-open the app and look in network logs, with high probability you will see a 401 and an "old" refreshToken being used

As mentioned, this is a working hypothesis and I suggest the next step is to validate it with pulling logs from production when I have a confirmed incident of a logout.

MemoryLeaker simulation function:
```
  const memoryLeakContainer = [];

  const memoryLeaker = () => {
    for (let i = 0; i < 1000000; i++) {
      memoryLeakContainer.push(new Array(100).fill("Hello world!"));
    }
  };
  setTimeout(() => {
    setInterval(() => {
      memoryLeaker();
    });
  }, 1500);
```

**Comment by Svarto** [comment]
Something I noticed, every time an app is closed and reopened, the refreshToken is renewed. Is this intended? It almost acts like an accessToken in that case, in my experience refreshTokens are longer lived and only refreshed every 30-60-90 or even 180+ days. For example, see here: https://stackoverflow.com/questions/8953983/do-google-refresh-tokens-expire

**Comment by elitan** [comment]
@Svarto We've made a few updates both to Auth service and our SDK. Do you still have this issue occurring?
