### ISSUE TITLE
More scopes in Social Sign-In Providers

### ISSUE THREAD

**Issue by heliocaruccio** [nhost/nhost#855]
Hi! How can I add other permissions to the APP? For example with facebook request user_post? Tanks!

**Comment by mdp18** [comment]
I believe this has to be done manually by the team if using the cloud version.

**Comment by elitan** [comment]
Right now, the scopes are hard-coded, like [this](https://github.com/nhost/hasura-auth/blob/main/src/config/providers.ts#L61-L65) for Facebook. 

But we can change them manually, as @mdp18 mentioned. We'll add the UI to make the scopes editable in the Nhost Dashboard.

**Comment by dbarrosop** [comment]
While this isn't possible on the dashboard yet, you can use the `nhost.toml` to set the scopes. Run `nhost config example` and look for "scopes" to find examples.
