### ISSUE TITLE
can't get access to uploaded file

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#858]
I'm confused by public file access.
Either something broke or I'm not using it right.
I remember I tried it couple months ago and it was working (although not sure) back then API call was "getUrl" which is deprecated now.
So, I've uploaded file to specific bucket. Files table have select permission to role public with condition for that bucket.
When I'm executing API call getPublicURL for uploaded id I'm getting https://uurfoleitvxnjiwblkmt.storage.eu-central-1.nhost.run/v1/files/f14bd02e-9805-42ec-a6bf-cb8b6ebfdec0
but when I'm trying open it (just in browser) I only get
{"error":{"message":"you are not authorized"}}

**Comment by szilarddoro** [comment]
I'm glad your problem has been resolved @yureckey. I'll close this issue, do not hesitate to reopen if the issue persists.
