### ISSUE TITLE
nhost.io login not working

### ISSUE THREAD

**Issue by camillo18tre** [nhost/nhost#86]
It's always me!
I've seen that you've changed your look (looks amazing!!), but now I can no longer log in or retrieve my password. 
Before the redesign I used to log in with google, but now I see that this type of access is no longer available.

thanks
C.

<img width="1252" alt="Schermata 2021-12-09 alle 19 31 36" src="https://user-images.githubusercontent.com/38567269/145455582-4e4e7274-4fd8-40fb-ba2e-6f7120933931.png">

**Comment by elitan** [comment]
Thanks.

You can access the old console here: https://console.nhost.io/

**Comment by camillo18tre** [comment]
@elitan  Great! thank you!
