### ISSUE TITLE
Nhost GraphQL console tool doesn't use Permission Variables?

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#866]
I'm running my query in the Nhost GraphQL console tool as specific user, and I see error
 "message": "missing session variable: \"x-hasura-parentid\""
so, I understand, it doesn't use Permission Variables, which (for me) make this tool useless comparing to Hasura built-in graphql.
(the only advantage I saw was ability to quickly choose user to run query for)
Update: 
~~Ah, wait, it seems I just accidentally pushed change to my github, which wasn't synced with live Nhost app, resulting in app rewritten with old github data. After backup restore everything was back to working - with permission variables~~
another update:
I'm looking in the browser dev console, network tab, and I see that request made on behalf of the user only have
X-Hasura-Admin-Secret: XXX
x-hasura-role: user
x-hasura-user-id: XXX
so, is there permission variables or not? Maybe it's added after this request, behind the scene?

**Comment by guicurcio** [comment]
Hey [yureckey](https://github.com/yureckey), only permissions based on `role` and the `user-id` are available through the GraphQL playground. As I see it, the complexity of adding permission variables is low (we just haven't prioritized it for the previous cycles) but we will reconsider after your comment :+1: 

I will keep this issue updated. I do wonder, would having access to a headers editor be useful to your case? You could look up the pertinent variables from a given user and also try different ones.

**Comment by guicurcio** [comment]
Would having access to a headers editor be useful to your case? You could look up the pertinent variables from a given user and also try different ones.

**Comment by yureckey** [comment]
having access to headers editor is better than not having it. It's the question of what features nhost graphql playground have that hasura graphql playground doesn't. Running query "as user" is possible in hasura graphql tool using manual headers entries (with permissions variables in my case). So, if the workflow is same, why would I use nhost graphql tool and not hasura's?

**Comment by guicurcio** [comment]
You are free to use whichever tool you feel is most useful to you. The GraphQL playground in the console will allow us to more neatly integrate with other Nhost services such as hasura-auth and other workflows in the console (such as quickly selecting a user from the database browser or the authentication tab and run queries/mutations on their behalf.)

**Comment by szilarddoro** [comment]
We have added the new version of the GraphiQL Playground to our dashboard recently. It adds support for the header editor and also fixes most of the issues you experienced in the previous version. I'm closing this issue.

**Comment by szilarddoro** [comment]
Reopening based on the discussion with @plmercereau. We'll need to make custom permission variables available through the dashboard, but we are not there yet.

As a workaround, you can send the permission variables manually through the playground using custom headers.
