### ISSUE TITLE
Github repos aren't displaying properly after reconnection

### ISSUE THREAD

**Issue by TaylorFacen** [nhost/nhost#87]
I had to remove and reconnect Nhost from my Github organization. Afterwards, I realized that the list of repos simply get added on instead of just refreshing to only show the current available repos. Here's a pic after I changed my repo's name a few times and connected and reconnected. There should only be two repos displaying, but instead, a new three get added every time I reconnect to my Github org.

<img width="543" alt="Screen Shot 2021-12-11 at 9 24 06 AM" src="https://user-images.githubusercontent.com/44216029/145680103-b13e8b72-02a9-41ac-84d8-4cf6147ec578.png">

**Comment by nunopato** [comment]
@TaylorFacen thank you for reporting this! we have fixed the this issue so am closing it. Feel free to open it again in case you bump into it again.
