### ISSUE TITLE
nhost.storage.upload() incompatible with nhost functions.

### ISSUE THREAD

**Issue by philip-ditgear** [nhost/nhost#876]
Issue:
`nhost.storage.upload()` requires a file of type [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) in [StorageUploadParams](https://github.com/nhost/nhost/blob/main/packages/hasura-storage-js/src/utils/types.ts). [FIle](https://developer.mozilla.org/en-US/docs/Web/API/File) is [not yet introduced in node.js](https://github.com/nodejs/node/issues/39015) making `.upload()` only compatible with browsers. - Can't upload files from a serverless function or other node.js servers. 

Suggestion:
Introduce an alternative to File in StorageUploadParams that is compatible with Node.js, so that `nhost.storage.upload()` can be used from a serverless function or any other Node.js environment. 

Why?
- When you want to generate/modify/check files on the server-side before uploading them to storage.
- Sending large files back to the users' browser, only for uploading is not very efficient.
- This would make `hasura-storage-js` compatible with both the backend and frontend. (Other functions like `nhost.storage.delete` works fine in serverless functions!)

**Comment by elitan** [comment]
It should be fixed in the latest release. You can see how it's done in our tests:

- Local file: https://github.com/nhost/nhost/blob/main/packages/hasura-storage-js/tests/upload.test.ts#L11-L16
- Remote file: https://github.com/nhost/nhost/blob/main/packages/hasura-storage-js/tests/upload.test.ts#L22-L32
