### ISSUE TITLE
Feature: add Expo + React Native example repo

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#877]
Hello Guys,

I've been using Nhost with NextJS for a while and a new upcoming project will be with React Native + Expo and I am currently doing my research how to set it up. Would I follow the basic React + Apollo example at this point? I think a dedicated example would be great for onboarding RN users.

Cheers & keep up the great work

**Comment by elitan** [comment]
We would be thankful if anyone from our community could help us with this.

cc @Svarto? :)

**Comment by Svarto** [comment]
> We would be thankful if anyone from our community could help us with this.
> 
> cc @Svarto? :) 

Really swamped right now, will try over Christmas. If anyone has any questions, feel free to DM me on Discord. Username is same as here
