### ISSUE TITLE
Modifying user roles in the auth section of nhost dashboard doesn't update database

### ISSUE THREAD

**Issue by dlittle1** [nhost/nhost#878]
When I go to `Authentication > Roles and Permissions > Default allowed roles` on the nhost dashboard and add new user roles it doesn't update the database. So I must manually go into `Database > Data Browser > schema.auth > roles` and insert my new user roles into the database.

This isn't ideal, after creating new roles in the auth section the database should update with the new roles and permissions.

**Comment by plmercereau** [comment]
Hello, this will be fixed in the near future, thanks for your patience.

Related: https://github.com/nhost/hasura-auth/pull/271

**Comment by elitan** [comment]
This has now been released in Hasura Auth (https://github.com/nhost/hasura-auth/releases/tag/v0.16.0) but has not yet been released in Nhost Cloud or the CLI. We'll update this issue when it's rolled out completely.

**Comment by plmercereau** [comment]
The cloud already uses hasura-auth version `0.17.0`. I'm closing this issue.
If the problem still occurs, please reopen the issue with some context. Thanks!
