### ISSUE TITLE
Set desired password policy

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#879]
It would be great if the desired password policy could be set up in the backend to be verified for registrations, so that we don't have to do it in the frontend.

Parameters e.g.
- minimum length
- must contain small AND capital letters
- must contain numbers
- must contain at least one special character

**Comment by abhaytaras7** [comment]
Would be great if we add 0auth for extra security

**Comment by hugomn** [comment]
Stronger password requirements are a critical issue for production environments, so this feature will be highly appreciated.
