### ISSUE TITLE
Add support of apple id OAuth-orisation

### ISSUE THREAD

**Issue by conmute** [nhost/nhost#88]
I am developing a react-native application, nhost.io looks very promising and inspiring for me.

But the main audience that my client is focused on is the iOs apps, so I am desperate about having an Apple id.

I see that you have it in the list here <https://github.com/nhost/hasura-auth> and here https://github.com/nhost/hasura-backend-plus but at the same time I see "we don't support Apple id" yet

Do we support it or not? If we do, can I expect to start developing an apple id application and within a month have the apple-id there? Or at least have something to set up apple-id by ourselves? Thank you!

**Comment by nunopato** [comment]
@conmute thanks for the issue, we will be adding support to Apple soon (one month seams very reasonable).

**Comment by Svarto** [comment]
thanks @nunopato for the reply, the sooner the better! Missing Apple specifically is a total showstopper for iOS as the Apple guidelines require it if you want to offer ANY other social login.

**Comment by nunopato** [comment]
@conmute @Svarto this is expected to be released by next week

**Comment by Svarto** [comment]
@nunopato fantastic! Hope you can also have a look at implementing it for mobile / React Native 😊

**Comment by samuelchanx** [comment]
Any updates for this?

**Comment by Svarto** [comment]
@nunopato hi Nuno, any update on this?

**Comment by humleflue** [comment]
If this gets implemented I will switch from Firebase, but I don't see it supported in the docs yet and this issue is still open.

Will it get implemented?

**Comment by elitan** [comment]
It's done! 🎉 🎉 🎉 

![CleanShot 2022-07-07 at 10 51 37@2x](https://user-images.githubusercontent.com/331818/177733082-86ffa53f-0bf4-4971-8c7b-ad502411271a.png)

**Comment by whalemare** [comment]
Thank you, but you also should update your product page about available auth providers
https://nhost.io/product/auth
