### ISSUE TITLE
Gravatar default set have no effect

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#880]
I changed setting of gravatar default to identicon, created new user and I see that saved avatar url still have original "blank" instead of identicon

**Comment by asdsyd** [comment]
Can you elaborate the issue or include a screenshot. Thanks.

**Comment by yureckey** [comment]
ugh, original description is quite self-explanatory but ok, I'll try to elaborate even more:
I was expecting that gravatar settings which I set in the settings->AUTH_GRAVATAR_DEFAULT would result in the avatar_url of the user table be updated (or at least created for new users) with "default=X" where X is what was set in settings. But actually I only see that avatar_url is always ending in "default=blank"
https://s.gravatar.com/avatar/46f50fe400a5c104a1186bb1a15884ff?r=g&default=blank

**Comment by plmercereau** [comment]
Hello @yureckey, thanks for raising this up and for your patience. We found the origin of the bug and will fix it soon.
HYI this is related to our infrastructure, not hasura-auth.

**Comment by Nabinsharma123** [comment]
i set the default Gravatar to "identicon" from the nhost dashboard. but i still get default=blank Gravatar after sign Up a new user.
i also try to turn off the Gravatar from the dashboard but still same
