### ISSUE TITLE
Login with Apple doesn't appear to work for react native in production - crashes server

### ISSUE THREAD

**Issue by jladuval** [nhost/nhost#881]
I have a generic social login component (code can be found in my comment here https://github.com/nhost/nhost/discussions/550) and am currently using both apple and google login. Google login works completely fine but apple login ends up returning a 502 error and takes the whole server out of action for a few minutes. 

The Apple login was definitely working for a time as it went through a testflight build and test phase, it just seemed to stop at some point and never recovered. My settings are all just default nhost settings so I don't think it's anything strange that I've done but I'm happy to do some more testing if it helps track down the reason.

I've done a small debugging session with Nuno so he's somewhat aware of the issue.

**Comment by guicurcio** [comment]
Do you see anything relevant in the authentication section of the logs?
