### ISSUE TITLE
Nhost with Nuxt3 predictableActionArguments 

### ISSUE THREAD

**Issue by haexhub** [nhost/nhost#882]
Hi,

I'm using nhost with nuxt3 and getting following warning:

It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html

I couldn't find anything about it in the docs.

**Comment by plmercereau** [comment]
Hi, thanks for bringing this up.
Please disregard this warning. We will update our code to fix it soon.

**Comment by mikhailcodes** [comment]
Commenting here as I am receiving the same warning using Nhost with Expo/React Native

**Comment by elleryfamilia** [comment]
Getting the same warning on Next.js

**Comment by dohomi** [comment]
Same warning for my environment, using Expo and NextJS in monorepo setup

**Comment by ammarfaris** [comment]
> Commenting here as I am receiving the same warning using Nhost with Expo/React Native

Yup, experiencing the same
