### ISSUE TITLE
user view in nhost dashboard/auth doesn't reload properly

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#885]
if I have opened user, so url is like 
https://app.nhost.io/default-workspace-kimkx/secondwarehousev2/users/bad86bc7-d364-47fe-809b-cfcd25553187
then reloading page gives only "No user..."

**Comment by szilarddoro** [comment]
The fix for this issue has been deployed to production. Let me know if the problem persists. 🤙🏼
