### ISSUE TITLE
getSession return null when use inside next.js getServerSideProps

### ISSUE THREAD

**Issue by eugen2991** [nhost/nhost#886]
Im try to get user session inside getServerSideProps by using - nhost.auth.getSession() but its return null after refreshing the page or route change.
This issue occurs after updating to @nhost/nextjs@1.6.2 or upper.

**Comment by plmercereau** [comment]
`nhost.auth.getSession()` won't work in `getServerSideProps` as it has no access to the execution context.
You could use [getNhostSession](https://docs.nhost.io/reference/nextjs/get-nhost-session) instead, and have a look at the NextJs example, for instance [this page](https://github.com/nhost/nhost/blob/main/examples/nextjs/pages/guarded-ssr.tsx)

**Comment by cj** [comment]
@plmercereau when doing:

```typescript
    const nhost = await createServerSideClient(context)
    let session = nhost.auth.getSession()
```

you are initializing `createServerSideClient` with the context, so shouldn't `nhost.auth.getSession()` have access to the context used to initialize the nhost client? It used to work that was on older versions.

**Comment by altschuler** [comment]
This is still an issue. The cookie is configured like this:

```
Name: nhostRefreshToken
SameSite: None
HttpOnly: false
HostOnly: true
Secure: false
```

I believe it needs to be `Secure: true` since `SameSite: None`? As explained [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite).

Versions in use:

```
"@nhost/nextjs": "^1.7.4",
"@nhost/react": "^0.12.4",
"@nhost/react-apollo": "^4.7.4",
```

**Comment by altschuler** [comment]
@plmercereau This is breaking a lot of functionality when using nextjs, can I help out somehow? If you can give a hint to what you think might be the cause I'd be happy to try to fix.
