### ISSUE TITLE
Passwordless: Resend SMS OTP feature

### ISSUE THREAD

**Issue by mdp18** [nhost/nhost#889]
Is there any feature that allows the user to resend the same OTP code if Twilio fails to deliver the SMS to the device?

**Comment by elitan** [comment]
I think you can simply try to sign in the user again (with a new OTP). Would that work?

**Comment by mdp18** [comment]
@elitan Hmm I think it would.. If I understand correctly.. If I call step 1 of the passwordless capability with the same number 5 times and they all get delivered, I can use any of those OTP's to do step 2 of the sign in process?

**Comment by plmercereau** [comment]
Hello,
Only the last code sent will work.
Closing for now, don't hesitate to ping us if Johan's suggestion didn't solve your problem
