### ISSUE TITLE
How do functions work in detail?

### ISSUE THREAD

**Issue by heygambo** [nhost/nhost#895]
Hey there,

I looked at how functions work last weekend and couldn't understand how to use them.

I looked at the CLI version as well as the [docker file in the examples](https://github.com/nhost/nhost/tree/main/examples/docker-compose)

For docker-compose:
- What's the Hasura host?

For Nhost CLI
- How do I know if functions running?
- What's the host?
- How can I see the logs?

Docs I've read:
- https://docs.nhost.io/platform/serverless-functions
- https://docs.nhost.io/platform/cli

Best,
Christian

**Comment by elitan** [comment]
This is the output of `nhost up`:

```
URLs:
- Postgres:		postgres://postgres:postgres@localhost:5432/postgres
- GraphQL:		http://localhost:1337/v1/graphql
- Auth:			http://localhost:1337/v1/auth
- Storage:		http://localhost:1337/v1/storage
- Functions:		http://localhost:1337/v1/functions

- Hasura console:	http://localhost:9695
- Mailhog:		http://localhost:8025

- subdomain:		localhost
- region:		(empty)
```

> What's the Hasura host?
`http://localhost:9695`

> How do I know if functions running?
You can check the logs using `nhost logs -f functions`.

> What's the host?
`http://localhost:1337/v1/functions`

> How can I see the logs?
`nhost logs -f functions`

Let me know if you want me to expand on any topic.

**Comment by heygambo** [comment]
Where does the functions folder have to go?
I am guessing inside the nhost folder?

It would be cool to have an example dedicated to functions in the examples folder.

**Comment by elitan** [comment]
The `functions/` folder should go in the base folder, so it's a sibling to the `nhost/` folder. We're currently working on standardizing and documenting this.
