### ISSUE TITLE
nhost HELM-Chart available for self-hosting?

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost#896]
Hi there,

is there a HELM-Chart available to make it easier to self-host nhost with Kubernetes?

Many thanks!

**Comment by noverby** [comment]
We are working on it in @aivero, and will open source it as soon as it is finished.

**Comment by plmercereau** [comment]
Hello @MaxSchilling,
We are moving away from Helm to use Kustomize instead. That being said, to open-source yours would be an awesome contribution, @noverby !

**Comment by noverby** [comment]
@plmercereau will you open source your Kustomize work?

**Comment by MaxSchilling** [comment]
@noverby - Are you still planning to open source your helm work?

**Comment by 333miiko** [comment]
Did anyone make any progress on this? Will be super helpful @noverby @plmercereau

**Comment by compiaffe** [comment]
@333miiko @MaxSchilling : @noverby and I will be picking this up again soon. There are still plans to open-source it, but no clear ETA.

**Comment by fpoussin** [comment]
There you go: https://github.com/fpoussin/nhost-helm
I'm still experimenting with nhost so some things might be missing but that should help you get started.
