### ISSUE TITLE
Feature Request - allow nhost-js SDK to use Subscription

### ISSUE THREAD

**Issue by yureckey** [nhost/nhost#897]
Apollo is a bit too advanced for me, I'm fine with nhost-js, but it lacks ability to use Subscription

**Comment by elitan** [comment]
Once we migrate our graphql client to graphql-request (https://github.com/nhost/nhost/issues/1177) we should fix this issue too, because graphql-request has support for subscriptions (https://github.com/prisma-labs/graphql-request/pull/330).

**Comment by elitan** [comment]
We've decided not to take on this for now. There are a lot of other good graphql libraries that handle subscriptions mentioned here: https://docs.nhost.io/graphql#graphql-clients-for-javascript
