### ISSUE TITLE
Feature Request: Enable Streaming Subscriptions

### ISSUE THREAD

**Issue by noverby** [nhost/nhost#899]
In Hasura, a streaming subscription streams the response according to the cursor provided by the user while making the subscription. Streaming subscriptions can be used to subscribe only to the data which has been newly added to the result set. [1]

It is supported in Hasura GraphQL engine versions since `v2.7.0-beta.1, but is disabled as an experimental feature.

[1] https://hasura.io/docs/latest/subscriptions/postgres/streaming/index/

**Comment by OrangeNote** [comment]
Hasura v2.12.0 has been released and it will:
> Enable streaming subscriptions by default in the graphql-engine

Source: https://github.com/hasura/graphql-engine/releases/tag/v2.12.0

🤞

**Comment by plmercereau** [comment]
We will deploy Hasura v2.12 soon, thanks for your patience

**Comment by elitan** [comment]
All projects run Hasura 2.13.0 so streaming subscriptions are available for all Nhost projects.

Docs: https://hasura.io/docs/latest/subscriptions/postgres/streaming/index/
