### ISSUE TITLE
multi-tenancy

### ISSUE THREAD

**Issue by jogri** [nhost/nhost#911]
Currently I'm looking into how to achieve a multi-tenancy architecture (database-per-tenant).
It is relatively easy to use only one hasura instance with different databases (same schema) for each tenant.
Now I try to come up with a good strategy for hasura-storage/hasura-auth.
It is probably a good idea to keep the auth service centralised for all tenants - and the permissions for (and isolations of) each database should be solvable. Right now I don't see a good solution for storage: it would be awesome to run only one hasura-storage instance that uses the respective database and storage location per tenant.
Maybe someone can point me to a solution.

**Comment by pkreipke** [comment]
Have you checked out this example? 

https://github.com/nhost/nhost/tree/main/examples/multi-tenant-one-to-many

I've also noticed some topics that might be related such as attaching an "organization" to each user.

**Comment by elitan** [comment]
Maybe if you provide a database model that you plan to use it's easier to reason about.

This is how I would structure a general multi-tenant system (similar to how we do it at [Nhost](http://nhost.io/) with Users and Workspaces.

```
auth.users (Table that already exists in Nhost)
- id
- display_name
- [and more]

storage.files (Table that already exists in Nhost)
- id
- name
- size
- [and more]

workspaces
- id
- name
- created_by_user_id FK to auth.users.id + Hasura preset using `x-hasura-user-id`
- [and more]

workspace_members
- id
- created_at
- workspace_id FK to workspaces.id
- user_id FK to auth.users.id

workspace_files
- id
- file_id FK to storage.files
- workspace_id
- uploaded_by_user_id FK to auth.users.id + Hasura preset using `x-hasura-user-id`
```

## Upload

1. User is signed in and using a specific (current) workspace
2. Upload file
3. Get `file.id` back
4. Insert a new row to `woskpace_files` with `file_id` and the current `workspace_id`.


## Permissions

## Workspaces

To manage the workspace.

Allow to read/update/delete `if workspace.worksapce_members.user_id = x-hasura-user-id` 

## Workspace Members

To manage workspace members.

Allow to insert/read/update/delete `if workspace_members.workspace.worksapce_members.user_id = x-hasura-user-id` 

## Workspace Files

To manage workspace files.

Allow to insert/read/update/delete `if workspace_files.workspace.worksapce_members.user_id = x-hasura-user-id` 

## Files

Allow to insert: always allow

Allow to read/delete `if workspace_files.workspace.worksapce_members.user_id = x-hasura-user-id`

# Summary

Keep everything in the same database and use Hasura's permissions to allow tenants to only manage their own data.

**Comment by elitan** [comment]
Why would you want to do one database per tenant? I think that will lead to so much extra work for you in keeping the database schema in sync.

Unless you have **really** strong requirements, I recommend that you do anything in your power to **not** use one database per tenant. 

If you do go with one database per tenant, please make sure you fully understand the second-order effects it has in terms of maintenance and complexity for your development team.

> But maybe I should give up on that approach (for now) and try the shared database/storage approach.

I strongly put my vote on this.

**Comment by elitan** [comment]
Yes, it's a complex topic for sure, and there is no general answer that works for everyone.

Hasura Storage uses a single bucket.
