### ISSUE TITLE
Include XState machine diagrams in docs (or wiki)

### ISSUE THREAD

**Issue by pkreipke** [nhost/nhost#913]
If the code in one of your XState machines was rendered through the XState vizualizer and a screenshot of the resulting diagram was available online that could be very helpful in understanding how the Auth flow works and communicates out to via state in React hooks, or the `onAuthChanged` listener.

This machine is probably the most important one to get sense of the Auth package's flow/lifecycle:
https://github.com/nhost/nhost/blob/main/packages/core/src/machines/index.ts 

I tried myself via copy paste of the basic machine code but couldn't get far at all through a succession of errors because of the surrounding code I think.

Thanks for your consideration!

<img width="1440" alt="Screen Shot 2022-09-01 at 2 56 02 AM" src="https://user-images.githubusercontent.com/12683108/187852856-240c9da8-3be9-4b67-9f98-8cd2b2565d7e.png">

**Comment by plmercereau** [comment]
We haven't found a way yet to export state machines to our documentation.
However, you can use the [Xstate inspector](https://xstate.js.org/docs/packages/xstate-inspect/) in your code so you'll be able to get their current state from your browser:
```ts
import { inspect } from '@xstate/inspect'

inspect({
    url: 'https://stately.ai/viz?inspect',
    iframe: false
  })

const nhost = new NhostClient({
  subdomain: '<project subdomain>',
  region: '<project region>',
  devTools: true
})
```
