### ISSUE TITLE
Retry button for deployments

### ISSUE THREAD

**Issue by heygambo** [nhost/nhost#915]
I had trouble with a deployment that I fixed using Hasura migrate in my terminal. Now I would like to retry the current deployment. It seems like the only way is to push a new commit atm. It would be great to have a "retry" button for failed deployments.

![image](https://user-images.githubusercontent.com/449438/188080772-10213aca-bcae-40ef-81af-96fb28392702.png)

**Comment by iangabrielsanchez** [comment]
This would be very helpful. I had to invent unnecessary changes just so it would re-trigger the deployment

**Comment by elitan** [comment]
This is now available.

![Uploading CleanShot 2023-01-27 at 16.08.14.png…]()
