### ISSUE TITLE
Functions filenames fail if they don't match exactly the filename

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost#92]
Might be intentional, but it is a difference between v1 and v2, when calling a function (e.g. functions/hello.js), if the cases are not exactly matching then the function fails. In v1, even if the filename was written in camelCase and the function was called with all lower letters (like a web url) the function was still executed. In v2, it gives a 404 and file not found error.

Reproduce:

1. Following the docs, create a functions/hello.js file, then rename it to helLo.js. 
2. Try calling the function with `const { res, error } = await nhost.functions.call('/hello', { name: 'Johan' })`
3. See the 404 response

Expected outcome:
The function should still be called 

Thoughts:
I would prefer to have the same handling as in v1 here, as I can't think of any time when one needs to separate between two files based on capital letters. V1 also provided more flexibility in naming conventions on the backend (e.g. camelcase was possible)

**Comment by Svarto** [comment]
> If you have a file called helLo.js. (with uppercase letters) does /helLo work?
> 
> I'm also moving this issue to our main repo because it covers both CLI, SDK, and our infra.

Yes, /helLo does work if the file is named helLo.js. the case need to match at the moment (my observation from my testing)

**Comment by elitan** [comment]
This is intentional. URLs and files are case-sensitive. However, I would recommend keeping all function file names to lowercase.

**Comment by Svarto** [comment]
> This is intentional. URLs and files are case-sensitive. However, I would recommend keeping all function file names to lowercase.

Fair enough that it is intentional.

Just a comment, URLs are not case sensitive for the user. Try write in GoOgle.com in your browser and you'll still be directed to google.com. Same with if you try and capitalize a article url on e.g. theverge.com

**Comment by elitan** [comment]
Domains are case insensitive but paths are.

Test this:

http://www.google.com/intl/en/about/corporate/index.html

http://www.google.com/intl/en/ABOUT/corporate/index.html
