### ISSUE TITLE
Missing types on the latest (1.4.11) of @nhost/nhost-js package

### ISSUE THREAD

**Issue by kornect** [nhost/nhost#925]
Hi guys,

I'm getting these errors on the latest version of the javascript client

`TS2724: '"@nhost/core"' has no exported member named 'ChangeEmailResponse'. Did you mean 'ChangeEmailOptions'?
TS2724: '"@nhost/core"' has no exported member named 'DeanonymizeResponse'. Did you mean 'DeanonymizeOptions'?
TS2305: Module '"@nhost/core"' has no exported member 'NhostSessionResponse'.
`

I looked at the type definition in the node_modules and this version is missing all the response types defined in @nhost/core. Downgrading to v1.4.7 fixes the issue

Am I missing something?

I picked this up on an angular project using version 14

**Comment by kornect** [comment]
I upgraded to the latest version and the response issue seems to be solved. This error however remained

```
Error: node_modules/@nhost/hasura-storage-js/dist/utils/types.d.ts:1:8 

import FormData from 'form-data';

node_modules/form-data/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
```

This is pretty self-explanatory, so I added the flag on my tsconfig.json compiler options

`"allowSyntheticDefaultImports": true,`

I can compile and test the app again

**Comment by plmercereau** [comment]
Hello @kornect,
Yes, this is the way to solve this `allowSyntheticDefaultImports` error.

I however tried to reproduce your issue on [this sandbox](https://stackblitz.com/edit/angular-v14-playground-qzufas?file=src%2Fmain.ts) with no success. Regardless of the reproduction, there is not much we can do to avoid this error without setting `allowSyntheticDefaultImports` to `true`.

Don't hesitate to share a reproduction link through.
Thanks!
