### ISSUE TITLE
Downloading storage files in functions as admin should not require giving public permissions to the file

### ISSUE THREAD

**Issue by spakanati** [nhost/nhost#927]
Currently, the recommended way to download a file in a serverless function is to use `getPublicUrl` and then use fetch to request the URL. However, fetch won’t be able to access the URL unless you have given the public role select permissions on your files table. There are a lot of times when you need to be able to access files as admin only but don’t want to allow read access to the files to everyone just for the admin to be able to access the file.

I also tried the presigned url as a workaround, but `getPresignedUrl` generates URLs that look like `http://localhost:1337/v1/storage/files/...` and can’t be accessed from within the serverless functions container (on the other hand, public URLS are generated as `http://traefik:1337/…`).

Ideally, there would be a `downloadFile` method on the JS client that allows a client with an admin secret to download the file without having to otherwise adjust any permissions on the files table.

**Comment by elitan** [comment]
You can download any file in a serverless function by adding the `x-hasura-admin-secret` to the header.

It's also possible to get a pre-signed URL for any file by adding the admin secret to `nhost.storage`.

I've attached an example here:

```js
import { Request, Response } from 'express'
import fetch from 'node-fetch'
import { nhost } from './_utils/nhost'

const handler = async (req: Request, res: Response) => {
  // generate public URL
  const publicUrl = nhost.storage.getPublicUrl({ fileId: 'e6f69adb-c56e-4c90-be91-6bcce2fc9d9e' })

  // get the file using public URL with the admin secret
  const response = await fetch(publicUrl, {
    headers: {
      'x-hasura-admin-secret': process.env.NHOST_ADMIN_SECRET as string
    }
  })

  console.log({ response })

  // set admin secret to storage
  nhost.storage.setAdminSecret(process.env.NHOST_ADMIN_SECRET as string)
  const { presignedUrl } = await nhost.storage.getPresignedUrl({
    fileId: 'e6f69adb-c56e-4c90-be91-6bcce2fc9d9e'
  })

  console.log(presignedUrl)

  res.status(200).send(`ok`)
}

export default handler
```

When I was testing this, I noticed a problem.

The public URL is generated using `traefik:1337,`, but the pre-signed URL is generated using `localhost:3137`. This means:

- Public URL works inside the function, but not outside the function.
- Pre-signed URL doesn't work inside the function, but it works outside the function.

Ideally, URLs should work both inside and outside a function (docker network).
