### ISSUE TITLE
Get client IP address with serverless functions

### ISSUE THREAD

**Issue by barbieessm** [nhost/nhost#929]
I tried to get the client IP with a function like the one below but got 10.128.x.x in return. The 'x-forwarded-for' was not appended with the real client IP.

I also went through the req object but can't see a way to get the correct IP

Is there a way to get the client IP address?

```javascript
export default (req, res) => {

    console.log('<< req.headers >>', req.headers);

    let ipaddress;
    if (req.headers['x-real-ip']) {
        ipaddress = req.headers['x-real-ip'];
    } else {
        ipaddress = req.headers['x-forwarded-for'].split(',')[0];
    }

    res.status(200).json(
        {
            ipaddress,
            timestamp: Date.now()
        }
    );
}
```

**Comment by plmercereau** [comment]
Hello, 
Indeed, both above headers are sending an internal private IP.
@nunopato will be able to say more about it

**Comment by ctrlemo** [comment]
I was about to open an issue, but I see this already existed and described the same thing but in a slightly different way.

const { host, hostname, ip, ips } = req;

Trying to destructure some properties from the req object that is passed into the function.

host and hostname are **undefined**
ip is **empty string**
ips is **empty array**

when running locally they do have values when I console.log them

`request:  {"host":"localhost","hostname":"localhost","ip":"::ffff:172.19.0.8","ips":[] `

I am trying to get the ip address of the source/origin that made the request.

After a fix from @dbarrosop and redeploying my Nhost project,
I am getting this when I console.log
`
{
"host":"{Subdomain}.functions.eu-central-1.nhost.run",
"hostname":"{Subdomain}.functions.eu-central-1.nhost.run",
"ip":"",
"ips":["10.110.10.207"]
}
`
was expecting to see the ip of the computer making the http request as well.

**Comment by dbarrosop** [comment]
Could you verify if this is fixed now? Thanks!

**Comment by ctrlemo** [comment]
Yes now it working. 
👍🏽

**"ips"** comes back with the ip address of the compute making the http request to the nhost function.

but "ip":"" is still empty string (but maybe that is expected behavior)

**Comment by dbarrosop** [comment]
that may be due to some proxy thing on the client side. Can you log the content of `x-forwarded-for`?

**Comment by ctrlemo** [comment]
@dbarrosop 
these are the logs with a single ip address, which is my current ip. so it is correct.
"X-Forwarded-For": "XXX.XX.XX.XXX"

the same ip address also appears in ips as a single entry
"ips":["XXX.XX.XX.XXX"]

but **"ip"** is still **empty string ""**
