### ISSUE TITLE
Nextjs: Nhost client not properly updating user session

### ISSUE THREAD

**Issue by msp-ampcome** [nhost/nhost#930]
I am using nhost with Nextjs. I am trying to use createServerSideClient on a SSR page. but it is not passing the accesstoken when i am making queries with nhost.graphql.request(). I tried to get the session with nhost.auth.getSession(). it is returning null. getNhostSession() is also returning null.

I followed all the steps in the documentation.
i can retrieve the user data once the page is hydrated with useUserData
but i couldn't retrieve any auth related data on getServerSideProps

**Comment by altschuler** [comment]
Same problem as https://github.com/nhost/nhost/issues/886

**Comment by msp-ampcome** [comment]
@altschuler is there any workaround for this? or do we have to wait till they fix it?

**Comment by altschuler** [comment]
I don't think there's much to do about it currently, but someone from nhost would know better :)

**Comment by ejkkan** [comment]
Also seeing this
