### ISSUE TITLE
Custom Apollo client and use nhost only for token management

### ISSUE THREAD

**Issue by heliocaruccio** [nhost/nhost#935]
Friends, then. I'm used to using Apollo and in some cases directly inside class. How could I access the client directly and better: how could I configure a classic Apollo client and only use accessToken.

**Comment by plmercereau** [comment]
Hi,
I'm not 100% sure I understood your question. 
When using React and If you don't use `@nhost/apollo`, you can set Apollo the way it is recommended [in their documentation](https://www.apollographql.com/docs/react/get-started/):

```js
import React from 'react'
import ReactDOM from 'react-dom'
 import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
import App from './App';
import { NhostClient, NhostReactProvider } from '@nhost/react'

const client = new ApolloClient({
  uri: 'https://flyby-gateway.herokuapp.com/',
  cache: new InMemoryCache(),
});

const nhost = new NhostClient({
  subdomain: '<app-subdomain>',
  region: '<app-region>'
})

ReactDOM.render(
  <ApolloProvider client={client}>
      <NhostApolloProvider nhost={nhost}>
        <App />
      </NhostApolloProvider>
  </ApolloProvider>,
);
```

you can then use the access token with `nhost.auth.getAccessToken()` or the `useAccessToken`.

Similar logic for Vue

**Comment by plmercereau** [comment]
Closing for now. If you're still facing the issue please explain it a bit further and we'll reopen.
Thanks!
