### ISSUE TITLE
Dashboard with project metrics e.g. DB size, traffic, etc

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#936]
Following up on a discussion with @L3K0V.
The Nhost cloud could benefit from a Grafana-like dashboard similar to [the image in nhost.io landing page](https://nhost.io/images/chart.png). AppWrite and others 
Possible metrics to expose:
- DB usage
- incoming traffic
- number of GraphQL operations
- number of function calls / total duration
- number of users
- number of active users during the day
- ...

**Comment by dbarrosop** [comment]
fixed
