### ISSUE TITLE
Concurrent deployments on same environment can occur

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#938]
This is a minor issue
If I trigger two commits & push on the same branch, this will trigger 2 deployments quite at the same time.
This may lead to unexpected behaviors :
![image](https://user-images.githubusercontent.com/1137511/191028921-4a31e7b6-3274-453d-af94-09e9b174153a.png)

![image](https://user-images.githubusercontent.com/1137511/191028964-96ca4344-ced6-4402-8c5e-d34d9c8ccb2f.png)

**Comment by elitan** [comment]
Yes, deployments for a project should happen in sequence.

**Comment by dbarrosop** [comment]
this was fixed already some time ago
