### ISSUE TITLE
Define the role table as enum in Hasura

### ISSUE THREAD

**Issue by yannickglt** [nhost/nhost#946]
Having roles as enum allows to generate TypeScript enum when code is generated with graphql-codegen.

**Comment by elitan** [comment]
We had a similar request here: https://github.com/nhost/hasura-storage/issues/136#issuecomment-1322028074

But given that this requires the [metadata to be reloaded](https://hasura.io/docs/latest/schema/postgres/enums/#current-limitations) for enums to be updated, we don't think it's a good idea to have roles to be enums.
