### ISSUE TITLE
remove unnecessary space in graphql website area

### ISSUE THREAD

**Issue by cocodrino** [nhost/nhost#949]
hi guys, the graphql area looks so unnecessary stretch in my screen (and it's even worse when you open the schema panel).

![image](https://user-images.githubusercontent.com/616412/191624137-6240ef3c-ee71-4d0c-968e-c712170b5507.png)

I don't have enough space to write my queries but I've a lot of lose spaces in both sides, checking the css the problem is a max-w-7xl and a nested max-w-8xl, if I remove them this looks much better

![image](https://user-images.githubusercontent.com/616412/191624021-ce3b13be-f42b-4cef-a393-fd55f431bbdf.png)

is possible change that in a future? thanks

**Comment by guicurcio** [comment]
Hey, thanks a lot for opening this issue. We're planning big changes for the GQL editor, stay tuned for the https://nhost.io/blog/launch-week-september-2022
