### ISSUE TITLE
pg_restore failed, ssh connection ended

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#950]
do you have a recommandation to backup / restore a database from one env to another ?
Currently I did not succeed
```
pg_dump -Fc -x -d "postgres://postgres:DG0If&W049zcj8@qimsyaozqntinmrokopq.db.eu-west-2.nhost.run:5432/qimsyaozqntinmrokopq" > dump.tar.gz
pg_restore --clean -d "postgres://postgres:DG0If&W049zcj8@mzoritbducuzqhecsdkg.db.eu-west-2.nhost.run:5432/mzoritbducuzqhecsdkg" dump.tar.gz
```
But after a few minutes of import, the SSL connection is closed without notice, and the hasura console cannot be acceded anymore on the target env.
![image](https://user-images.githubusercontent.com/1137511/191772010-3781fc47-5606-446d-bb3a-09d323d32d44.png)

**Comment by elitan** [comment]
@quentin-decre Do you see anything in the logs in the Nhost Dashboard? You can select to see only Postgres logs.
