### ISSUE TITLE
Support disallowing listing all files and users

### ISSUE THREAD

**Issue by altschuler** [nhost/nhost#951]
I tried disabling listing of all files through metadata, but then found out that's not allowed (as nicely documented [here](https://docs.nhost.io/platform/storage)).

I'd like to disable listing all files for security reasons, instead of making a super complex permission expression. I realize that's just security by obscurity in the sense that attackers will have to guess a file's id, but that's kind of besides the point of the issue :)

The same questions applies to users.

**Comment by elitan** [comment]
I'm not sure I understand the question. 

If you don't apply permissions to `auth.users` or `storage.files`, no one is allowed to list users and files.

**Comment by altschuler** [comment]
But then they're not allowed to load any files at all. I still want them to be loadable through relations, which they won't be if they have no permissions.

I just want to disable the `file_uploads` and `users` root query fields, but keep `file_uploads_by_pk` and `users_by_pk`.

**Comment by plmercereau** [comment]
Maybe this could help:
https://hasura.io/docs/latest/auth/authorization/permission-rules/#disabling-root-fields

**Comment by altschuler** [comment]
Yes, that's what I tried (oddly enough I don't see the option in the console even though it's Hasura v2.10 🤔, but I did it manually by modifying the metadata).

However, that seems to break hasura storage, as you've written in your docs modifying the root query fields is not permitted: https://docs.nhost.io/platform/storage (the first warning box). The file metadata is returned correctly through the graph, but loading the actual file fails.

**Comment by elitan** [comment]
I'm having the same issue. Can't see that option in Hasura Console even if I'm on 2.10.1. Will report back here once I know more.

**Comment by elitan** [comment]
> But then they're not allowed to load any files at all. I still want them to be loadable through relations, which they won't be if they have no permissions.
> 
> I just want to disable the `file_uploads` and `users` root query fields, but keep `file_uploads_by_pk` and `users_by_pk`.

If you set "Limit number of rows" to `0` users won't be able to list all files, but they will still be able to query files via a relation. Would that be enough for your use case?

![CleanShot 2022-11-20 at 09 09 30](https://user-images.githubusercontent.com/331818/202892138-1a5794c0-9675-4fdb-acd7-009de5ff63d6.png)
