### ISSUE TITLE
Nhost docker-compose file not working on local machine - maybe due to database cannot be initiated successfully / postgres connection error 

### ISSUE THREAD

**Issue by ammarfaris** [nhost/nhost#953]
[Title was updated to "Nhost docker-compose file not working on local machine - maybe due to database cannot be initiated correctly" from "Nhost docker-compose file working on local machine, but the same yaml file is not working when running on a VPS (digital ocean)" ]

~~The docker compose file (adjusted from https://github.com/nhost/nhost/tree/main/examples/docker-compose) is working fine when running on my local machine, but is it not working when running on Digital Ocean VPS, do I need to do additional adjustment when running on a VPS? (i tried changing localhost to my VPS public IP address, also not working).~~

Besides traefik dashboard accessible at 9090, only the hasura console is accessible via port 1337, BUT the postgres table inside hasura console only has the public folder and the rest is empty :( 

**[UPDATE]**
After further investigation and after deleting the data folder, I discover that my docker-compose.yml is working on localhost because somehow in one of my trial and error configuration, the  data folder managed to be initiated correctly (but I'm not sure which trial and error managed to set it up correctly)

HOWEVER, when I try to use the docker-compose.yaml directly from https://github.com/nhost/nhost/blob/main/examples/docker-compose/docker-compose.yaml without adjustment, I am receiving the same error ,i.e. issues with connection to auth and storage containers, maybe due to the failure of initial tables setup.

I'm using a macbook M1 laptop, but testing this on a digital ocean AMD and Intel VPS also yield the same error, it seems. 

~~Here is my docker-compose file~~, I RETRIED WITH the [nhost repo](https://github.com/nhost/nhost/blob/main/examples/docker-compose/docker-compose.yaml) directly:

**From "docker compose up":**

![Screenshot 2022-09-27 at 5 17 14 PM](https://user-images.githubusercontent.com/1182205/192489874-1ca6267e-ecbf-43b6-b251-3b47c564f3ad.png)

![Screenshot 2022-09-27 at 5 24 17 PM](https://user-images.githubusercontent.com/1182205/192489791-0ca14e36-cd82-4dc8-8512-ceed5d0f8147.png)

**From "docker compose ps":**
Auth and storage services struggle to run:
![Screenshot 2022-09-27 at 5 12 52 PM](https://user-images.githubusercontent.com/1182205/192490272-60cdf8f8-0cd8-4711-b974-c3bb5ec8ea5b.png)

![Screenshot 2022-09-27 at 5 12 29 PM](https://user-images.githubusercontent.com/1182205/192490300-9f1b21b5-efff-4c63-868d-e9a6581fa67d.png)

When I replaced the data folder with the one which has db initialized successfully, all looks good: 
![Screenshot 2022-09-27 at 5 26 30 PM](https://user-images.githubusercontent.com/1182205/192490594-eb76baa8-e5bc-413a-a23d-ed32353b241a.png)

Thanks in advance for your help!

**Comment by ammarfaris** [comment]
So far to work around the issue, I run the RAW SQL for db initialization (initdb.d) manually inside Hasura Console:

```
-- auth schema
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS storage;
-- https://github.com/hasura/graphql-engine/issues/3657
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
declare _new record;
begin _new := new;
_new."updated_at" = now();
return _new;
end;
$$;
```

and I have to manually add index.js inside functions folder and manually add the email templates inside the emails folder.

Not sure if I'm the only one experiencing this issue with the latest docker compose setup from the nhost examples repo https://github.com/nhost/nhost/blob/main/examples/docker-compose/docker-compose.yaml, or others are experiencing the same.

**Comment by NordlingDev** [comment]
@ammarfaris The reason it never worked from the beginning was that you probably already had a local `dbdata` directory that was created the first time you ran docker compose. However, if there were no SQL scripts (i.e. `0001-create-schema.sql`) inside the directory called `initdb.d` during that initial startup, docker assumes you already have initialized your database (which is true), so therefore no need to run any automated SQL scripts from `initdb.d`.

**Comment by plmercereau** [comment]
Reproduces and solved the issue with @NordlingDev's suggestion - thanks for this!
