### ISSUE TITLE
Nhost Client Doesn't Work on Pipedream

### ISSUE THREAD

**Issue by osseonews** [nhost/nhost#955]
When trying to use the Nhost Client in a server environment on Pipedream, we get the error: "Code Error could not compute configurable props." We have had the staff at Pipedream look into this, and they have confirmed the error. This is the only package out of thousands that will not work on Pipedream. There seems to be some strange dependency in the Nhost client package that breaks on the server. headless browser like Puppeteer? You can see the issue here: https://pipedream.com/community/t/error-code-error-could-not-compute-configurable-props/3299

**Comment by elitan** [comment]
Here's the corresponding error message from Pipedream: https://github.com/PipedreamHQ/pipedream/issues/4321

> There seems to be some strange dependency in the Nhost client package that breaks on the server. headless browser like Puppeteer? 
No, the package should be able to run fine on a server with `node`.

**Comment by osseonews** [comment]
Any chance your team can look into this and connect with the Pipedream team? We use Pipedream for nearly all our webhooks, and if we can't connect to Nhost client there, we can't run anything related to Nhost.
