### ISSUE TITLE
File Upload Vue composables

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#973]
We implemented the [`useFileUpload`](https://docs.nhost.io/reference/react/use-file-upload), [`useMutlipleFilesUpload`](https://docs.nhost.io/reference/react/use-multiple-files-upload) and [`useFileUploadItem'](https://docs.nhost.io/reference/react/use-file-upload-item) React Hooks.

The corresponding Vue 3 composables are missing in the [`@nhost/vue`](https://github.com/nhost/nhost/tree/main/packages/vue/src) package. It would use the same signature, using Vue refs.

**Comment by asdsyd** [comment]
Hey, I would like to work on this issue. But I will require some assistance if needed. Thank you.

**Comment by plmercereau** [comment]
that would be awesome! Yes, we'll be around

**Comment by asdsyd** [comment]
Please assign me the issue. thanks.

**Comment by asdsyd** [comment]
Hey @plmercereau , I have sent a PR on this issue. Please review it. Thanks.

**Comment by asdsyd** [comment]
Sorry it's out of my understanding for now. Complex issue as a beginner. Thank you.

**Comment by plmercereau** [comment]
Done by @chrisli-03
Many thanks!!!
