### ISSUE TITLE
Add description for all Stripe GraphQL Fields

### ISSUE THREAD

**Issue by elitan** [nhost/nhost#975]
Stripe has excellent description for all their fields in their API. We should copy all those descriptions and add them to the Stripe GraphQL API.

Here's an example:

Stripe: 

https://github.com/stripe/stripe-node/blob/master/types/2022-08-01/Customers.d.ts#L12

GraphQL API: 

https://github.com/nhost/nhost/blob/main/packages/stripe-graphql-js/src/schema/customer.ts#L13

That code should be updated to:

```js
id: t.exposeString('id', {
  description: `Unique identifier for the object.`
}),
```

This is to be repeated for all fields in the Stripe GraphQL API.

**Comment by piromsurang** [comment]
hello, could I work on this issue?

**Comment by plmercereau** [comment]
Hello @piromsurang ,
Let us know if you need further details to help you in your PR!

**Comment by piromsurang** [comment]
could you please correct me if I am wrong. Basically, this task is to add all description in `schema/` folder right?

**Comment by elitan** [comment]
That's correct. I recommend starting with one file in the `schema/` folder and creating a PR so we can ensure you're on the right path. Happy hacking! 💪

**Comment by elitan** [comment]
@piromsurang That's perfect!

**Comment by elitan** [comment]
I'm re-opening this issue as there are more fields to add descriptions to.

**Comment by piromsurang** [comment]
I will continue and raise a new PR.

**Comment by piromsurang** [comment]
Please help review.
