### ISSUE TITLE
feature: have createStripeGraphQLServer accept async isAllowed function

### ISSUE THREAD

**Issue by ejkkan** [nhost/nhost#980]
Problem:
Right now we can't  pass an async function according to the TS spec.
This way we can't really fetch more info about a user. 

The example from the stripe [package release page](https://nhost.io/blog/open-source-stripe-graphql-api) could be considered a use-case for it

Solution:
Just adding Promise support for the isAllowed type

```ts
export declare type CreateServerProps = {
    cors?: CORSOptions;
    isAllowed?: (stripeCustomerId: string, context: Context) => boolean | Promise<boolean>;
    graphiql?: boolean;
};
```

**Comment by ejkkan** [comment]
If you're interested. I could make an PR if I could get permissions

**Comment by elitan** [comment]
> If you're interested. I could make an PR if I could get permissions

Yes please

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/nhost/pull/985
