### ISSUE TITLE
How to delete an file from storage without using admin secret in functions

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost#981]
I have a function that is called from my frontend to delete an image from storage by using `admin-secret`, however, I can't figure out how to delete without using `admin-secret`.

Here is my function body:

```ts
const nhost = new NhostClient({
    backendUrl: DOMAIN_URL,
    //adminSecret:"nhost-admin-secret"
});
```

```ts
const {filedId} = req.body;
const {error} = await nhost.storage.delete({fileId: filedId});
```

**Comment by elitan** [comment]
Do you want to make the `nhost.storage.delete` request inside a serverless function, using the same user who called the serverless function?

Something like this:

1. The user calls a serverless function from your app (`nhost.functions.call`).
2. The serverless function should delete certain files using `nhost.storage.delete` as the user who made the initial serverless functions request.

Do I understand your problem correctly?

**Comment by vipafattal** [comment]
Yes, that's it, but also need to call ```nhost.graphql``` to update some linked columns
