### ISSUE TITLE
Unable to add row with a boolean value set to false

### ISSUE THREAD

**Issue by Godefroy** [nhost/nhost#999]
Hi!
I think there is a bug:

![Capture d’écran 2022-10-06 à 21 23 28](https://user-images.githubusercontent.com/148421/194401177-2b7b0cca-1953-4846-bd60-4a93e8541873.png)

**Comment by szilarddoro** [comment]
Hi! Thanks for the bug report, this is indeed a bug. I'm preparing a fix.
